SUMMARY:  More work on Zoltan 3PL options
     BUGS:

     CHECKLIST:

     1)   Did you add any source files? no

     2)   Did you update or change the build system? yes
     2.a) Did you remember to do a bootstrap and do a 'cvs add' on the
          Makefile.am files and the Makefile.in files?  yes
     2.b) [Optional but recommended] Did you blow away the libraries and
          executables and then rebuild?  yes

     3) Did you rerun the test suite on at least the packages that you
        changed?  no

     COMMENTS:

     I added some more 3PL options.  These don't work yet because we need to
have a header file that is #included everywhere to distribute information from
configure.  Although the options don't work, they are not harmful.  I added
some ifdef's to zoltan.h that will #define some things for 3PLs.  These will
not affect the old build system.


(checklist version 2007-06-20)

diff --git a/packages/zoltan/configure b/packages/zoltan/configure
--- a/packages/zoltan/configure
+++ b/packages/zoltan/configure
@@ -705,6 +705,8 @@ BUILD_OCTREEPARTITIONING_TRUE
 BUILD_OCTREEPARTITIONING_FALSE
 BUILD_PARMETIS_TRUE
 BUILD_PARMETIS_FALSE
+BUILD_SCOTCH_TRUE
+BUILD_SCOTCH_FALSE
 BUILD_TESTS_TRUE
 BUILD_TESTS_FALSE
 BUILD_EXAMPLES_TRUE
@@ -1386,6 +1388,19 @@ Optional Packages:
                           /path/to/library
   --with-parmetis-incdir  Specify where the Parmetis header files are located.
                           Ex. /path/to/headers
+  --with-scotch           Enable Scotch support. (default is no)
+  --with-scotch-libdir    Specify where the Scotch library is located. Ex.
+                          /path/to/library
+  --with-scotch-incdir    Specify where the Scotch header files are located.
+                          Ex. /path/to/headers
+  --with-patoh            Enable Patoh support. (default is no)
+  --with-patoh-libdir     Specify where the Patoh library is located. Ex.
+                          /path/to/library
+  --with-patoh-incdir     Specify where the Patoh header files are located.
+                          Ex. /path/to/headers
+  --with-drum             Enable Drum support. Library name as well as library
+                          and include paths must be specified using LDFLAGS
+                          and CPPFLAGS. (default is no)
   --with-libdirs          OBSOLETE use --with-ldflags instead. (ex.
                           --with-ldflags="-L<DIR> -L<DIR2>")
   --with-incdirs          additional directories containing include files:
@@ -5573,6 +5588,7 @@ fi
 
 
 
+
 # Check whether --with-parmetis was given.
 if test "${with_parmetis+set}" = set; then
   withval=$with_parmetis; ac_cv_use_parmetis=$withval
@@ -5616,7 +5632,7 @@ fi
 
 
 if test "X$tac_with_parmetis_libdir" != "Xno"; then
-  LIBS="-L${tac_with_parmetis_libdir} -lparmetis ${LIBS}"
+  LIBS="-L${tac_with_parmetis_libdir} -lparmetis -lmetis ${LIBS}"
 fi
 
 
@@ -5631,6 +5647,165 @@ fi
 if test "X$tac_with_parmetis_incdir" != "Xno"; then
   CPPFLAGS="-I${tac_with_parmetis_incdir}  ${CPPFLAGS}"
 fi
+
+
+
+# Check whether --with-scotch was given.
+if test "${with_scotch+set}" = set; then
+  withval=$with_scotch; ac_cv_use_scotch=$withval
+else
+  ac_cv_use_scotch=no
+fi
+
+
+{ echo "$as_me:$LINENO: checking whether to use scotch" >&5
+echo $ECHO_N "checking whether to use scotch... $ECHO_C" >&6; }
+
+if test "X$ac_cv_use_scotch" != "Xno"; then
+  { echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6; }
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_SCOTCH
+_ACEOF
+
+else
+  { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+fi
+
+ if test "X$ac_cv_use_scotch" != "Xno"; then
+  BUILD_SCOTCH_TRUE=
+  BUILD_SCOTCH_FALSE='#'
+else
+  BUILD_SCOTCH_TRUE='#'
+  BUILD_SCOTCH_FALSE=
+fi
+
+
+
+# Check whether --with-scotch-libdir was given.
+if test "${with_scotch_libdir+set}" = set; then
+  withval=$with_scotch_libdir; tac_with_scotch_libdir=$withval
+else
+  tac_with_scotch_libdir=no
+fi
+
+
+if test "X$tac_with_scotch_libdir" != "Xno"; then
+  LIBS="-L${tac_with_scotch_libdir} -lptscotch -lscotch -lscotcherr ${LIBS}"
+fi
+
+
+# Check whether --with-scotch-incdir was given.
+if test "${with_scotch_incdir+set}" = set; then
+  withval=$with_scotch_incdir; tac_with_scotch_incdir=$withval
+else
+  tac_with_scotch_incdir=no
+fi
+
+
+if test "X$tac_with_scotch_incdir" != "Xno"; then
+  CPPFLAGS="-I${tac_with_scotch_incdir}  ${CPPFLAGS}"
+fi
+
+
+
+# Check whether --with-patoh was given.
+if test "${with_patoh+set}" = set; then
+  withval=$with_patoh; ac_cv_use_patoh=$withval
+else
+  ac_cv_use_patoh=no
+fi
+
+
+{ echo "$as_me:$LINENO: checking whether to use patoh" >&5
+echo $ECHO_N "checking whether to use patoh... $ECHO_C" >&6; }
+
+if test "X$ac_cv_use_patoh" != "Xno"; then
+  { echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6; }
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_PATOH
+_ACEOF
+
+else
+  { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+fi
+
+
+
+# Check whether --with-patoh-libdir was given.
+if test "${with_patoh_libdir+set}" = set; then
+  withval=$with_patoh_libdir; tac_with_patoh_libdir=$withval
+else
+  tac_with_patoh_libdir=no
+fi
+
+
+if test "X$tac_with_patoh_libdir" != "Xno"; then
+  LIBS="-L${tac_with_patoh_libdir} -lpatoh ${LIBS}"
+fi
+
+
+# Check whether --with-patoh-incdir was given.
+if test "${with_patoh_incdir+set}" = set; then
+  withval=$with_patoh_incdir; tac_with_patoh_incdir=$withval
+else
+  tac_with_patoh_incdir=no
+fi
+
+
+if test "X$tac_with_patoh_incdir" != "Xno"; then
+  CPPFLAGS="-I${tac_with_patoh_incdir}  ${CPPFLAGS}"
+fi
+
+
+
+# Check whether --with-drum was given.
+if test "${with_drum+set}" = set; then
+  withval=$with_drum; ac_cv_use_drum=$withval
+else
+  ac_cv_use_drum=no
+fi
+
+
+{ echo "$as_me:$LINENO: checking whether to use drum" >&5
+echo $ECHO_N "checking whether to use drum... $ECHO_C" >&6; }
+
+if test "X$ac_cv_use_drum" != "Xno"; then
+  { echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6; }
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_DRUM
+_ACEOF
+
+else
+  { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+fi
+
+#TAC_ARG_WITH_3PL_SUB(drum, libdir, [Specify where the Drum library is located.  Ex. /path/to/library])
+#if test "X$tac_with_drum_libdir" != "Xno"; then
+#  LIBS="-L${tac_with_drum_libdir} ${LIBS}"
+#fi
+#TAC_ARG_WITH_3PL_SUB(drum, incdir, [Specify where the Drum header files are located.  Ex. /path/to/headers])
+#if test "X$tac_with_drum_incdir" != "Xno"; then
+#  CPPFLAGS="-I${tac_with_drum_incdir}  ${CPPFLAGS}"
+#fi
+
+#TAC_ARG_WITH_PACKAGE(parkway, [Enable Parkway support.], PARKWAY, no)
+#TAC_ARG_WITH_3PL_SUB(parkway, libdir, [Specify where the Parkway library is located.  Ex. /path/to/library])
+#if test "X$tac_with_parkway_libdir" != "Xno"; then
+#  LIBS="-L${tac_with_parkway_libdir} -lparkway -lpmpich++ -lstdc++ ${LIBS}"
+#fi
+#TAC_ARG_WITH_3PL_SUB(parkway, incdir, [Specify where the Parkway header files are located.  Ex. /path/to/headers])
+#if test "X$tac_with_parkway_incdir" != "Xno"; then
+#  CPPFLAGS="-I${tac_with_parkway_incdir}  ${CPPFLAGS}"
+#fi
 
 # ------------------------------------------------------------------------
 # Checks if tests and examples should be built
@@ -6402,6 +6577,13 @@ echo "$as_me: error: conditional \"BUILD_PARMETIS\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
+if test -z "${BUILD_SCOTCH_TRUE}" && test -z "${BUILD_SCOTCH_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"BUILD_SCOTCH\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"BUILD_SCOTCH\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
 if test -z "${BUILD_TESTS_TRUE}" && test -z "${BUILD_TESTS_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"BUILD_TESTS\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
@@ -7137,6 +7319,8 @@ BUILD_OCTREEPARTITIONING_TRUE!$BUILD_OCTREEPARTITIONING_TRUE$ac_delim
 BUILD_OCTREEPARTITIONING_FALSE!$BUILD_OCTREEPARTITIONING_FALSE$ac_delim
 BUILD_PARMETIS_TRUE!$BUILD_PARMETIS_TRUE$ac_delim
 BUILD_PARMETIS_FALSE!$BUILD_PARMETIS_FALSE$ac_delim
+BUILD_SCOTCH_TRUE!$BUILD_SCOTCH_TRUE$ac_delim
+BUILD_SCOTCH_FALSE!$BUILD_SCOTCH_FALSE$ac_delim
 BUILD_TESTS_TRUE!$BUILD_TESTS_TRUE$ac_delim
 BUILD_TESTS_FALSE!$BUILD_TESTS_FALSE$ac_delim
 BUILD_EXAMPLES_TRUE!$BUILD_EXAMPLES_TRUE$ac_delim
@@ -7151,7 +7335,7 @@ LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 41; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 43; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
