SUMMARY:   Merged release branch with main trunk.
     BUGS:      NA

     CHECKLIST:

     1)   Did you add any source files?  no

     2)   Did you update or change the build system? no

     3) Did you rerun the test suite on at least the packages that you
        changed?  yes

     COMMENTS:

Merged release branch with main trunk.  All tests pass except
scotch partitioning:

     Test problem simple with method graph-ptscotch FAILED

This test also fails in the release branch; it looks as if the partition
is identical between the computed answer and the repository answer, but
part numbers one and two are swapped.  If this result is consistent
(at least on octopi), we should update the repository answers.


(checklist version 2007-06-20)

diff --git a/packages/zoltan/configure b/packages/zoltan/configure
--- a/packages/zoltan/configure
+++ b/packages/zoltan/configure
@@ -711,6 +711,8 @@ USING_GNUMAKE_TRUE
 USING_GNUMAKE_FALSE
 BUILD_OCTREEPARTITIONING_TRUE
 BUILD_OCTREEPARTITIONING_FALSE
+BUILD_GZIP_TRUE
+BUILD_GZIP_FALSE
 BUILD_PARMETIS_TRUE
 BUILD_PARMETIS_FALSE
 BUILD_SCOTCH_TRUE
@@ -1345,6 +1347,7 @@ Optional Features:
                           change the paths. (default is yes)
   --enable-octreepartitioning
                           enable octreepartitioning (default is no)
+  --enable-gzip           enable zlib support for driver (default is no)
   --enable-tests          Make tests for all Trilinos packages buildable with
                           'make tests' (default is yes)
 
@@ -5931,6 +5934,43 @@ fi
 
 
 
+# Check whether --enable-gzip was given.
+if test "${enable_gzip+set}" = set; then
+  enableval=$enable_gzip; ac_cv_use_gzip=$enableval
+else
+  ac_cv_use_gzip=no
+fi
+
+
+{ echo "$as_me:$LINENO: checking whether to use gzip" >&5
+echo $ECHO_N "checking whether to use gzip... $ECHO_C" >&6; }
+
+if test "X$ac_cv_use_gzip" != "Xno"; then
+  { echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6; }
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_GZIP 1
+_ACEOF
+
+else
+  { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+fi
+
+if test "X$ac_cv_use_gzip" != "Xno"; then
+   LIBS="-lz ${LIBS}"
+fi
+ if test "X$ac_cv_use_gzip" != "Xno"; then
+  BUILD_GZIP_TRUE=
+  BUILD_GZIP_FALSE='#'
+else
+  BUILD_GZIP_TRUE='#'
+  BUILD_GZIP_FALSE=
+fi
+
+
+
 
 # Check whether --with-parmetis was given.
 if test "${with_parmetis+set}" = set; then
@@ -6968,6 +7008,13 @@ echo "$as_me: error: conditional \"BUILD_OCTREEPARTITIONING\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
+if test -z "${BUILD_GZIP_TRUE}" && test -z "${BUILD_GZIP_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"BUILD_GZIP\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"BUILD_GZIP\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
 if test -z "${BUILD_PARMETIS_TRUE}" && test -z "${BUILD_PARMETIS_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"BUILD_PARMETIS\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
@@ -7726,6 +7773,8 @@ USING_GNUMAKE_TRUE!$USING_GNUMAKE_TRUE$ac_delim
 USING_GNUMAKE_FALSE!$USING_GNUMAKE_FALSE$ac_delim
 BUILD_OCTREEPARTITIONING_TRUE!$BUILD_OCTREEPARTITIONING_TRUE$ac_delim
 BUILD_OCTREEPARTITIONING_FALSE!$BUILD_OCTREEPARTITIONING_FALSE$ac_delim
+BUILD_GZIP_TRUE!$BUILD_GZIP_TRUE$ac_delim
+BUILD_GZIP_FALSE!$BUILD_GZIP_FALSE$ac_delim
 BUILD_PARMETIS_TRUE!$BUILD_PARMETIS_TRUE$ac_delim
 BUILD_PARMETIS_FALSE!$BUILD_PARMETIS_FALSE$ac_delim
 BUILD_SCOTCH_TRUE!$BUILD_SCOTCH_TRUE$ac_delim
@@ -7744,7 +7793,7 @@ LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 51; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 53; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
