Added Dave's tradoptest to the test directory.  Here's what I did: -- Modified configure.ac to check for awk/gawk, added a new configure option to turn on these tests (--enable-sacado-alltests) since they took about 20 minutes to compile on my machine, and added the Makefile and testgen.as to the list of files configure should create.  These tests are disabled by default. -- Added tradoptest to the list of subdirectories in test/Makefile.am -- Added the tradoptest directory with Makfile.{am,in}, tradoptest.c0 and testgen.as.in.  Configure will create testgen.as from testgen.as.in by replacing @AWK@ with the awk program found during configure.  I did not add the compressed traoptest source file since awk is a pretty common program and generating it on the fly shouldn't be a problem.  We can always add it later if necessary.  The Makefile.am is pretty similar to Dave's original makefile.
Also simplified and reorganized example/Makefile.am.

diff --git a/packages/sacado/configure b/packages/sacado/configure
--- a/packages/sacado/configure
+++ b/packages/sacado/configure
@@ -311,7 +311,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot MPI_TEMP_CXX MPI_CXX HAVE_MPI_TRUE HAVE_MPI_FALSE MPI_CXX_EXISTS MPI_CC_EXISTS MPI_F77_EXISTS CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE F77 FFLAGS ac_ct_F77 RANLIB ac_ct_RANLIB USE_ALTERNATE_AR_TRUE USE_ALTERNATE_AR_FALSE ALTERNATE_AR CXXCPP EGREP USING_EXPORT_MAKEFILES_TRUE USING_EXPORT_MAKEFILES_FALSE PERL_EXE HAVE_PERL USING_PERL_TRUE USING_PERL_FALSE USING_GNUMAKE_TRUE USING_GNUMAKE_FALSE BUILD_TESTS_TRUE BUILD_TESTS_FALSE BUILD_EXAMPLES_TRUE BUILD_EXAMPLES_FALSE execincludedir CPPUNIT_CONFIG CPPUNIT_CFLAGS CPPUNIT_LIBS ENABLE_ADOLC_TRUE ENABLE_ADOLC_FALSE ADOLC_INCDIR ADOLC_LIBDIR ADOLC_LIBS TRILINOS_TEMPLATE_OBJS ac_aux_dir LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot MPI_TEMP_CXX MPI_CXX HAVE_MPI_TRUE HAVE_MPI_FALSE MPI_CXX_EXISTS MPI_CC_EXISTS MPI_F77_EXISTS CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE F77 FFLAGS ac_ct_F77 RANLIB ac_ct_RANLIB USE_ALTERNATE_AR_TRUE USE_ALTERNATE_AR_FALSE ALTERNATE_AR CXXCPP EGREP USING_EXPORT_MAKEFILES_TRUE USING_EXPORT_MAKEFILES_FALSE PERL_EXE HAVE_PERL USING_PERL_TRUE USING_PERL_FALSE USING_GNUMAKE_TRUE USING_GNUMAKE_FALSE BUILD_TESTS_TRUE BUILD_TESTS_FALSE BUILD_ALLTESTS_TRUE BUILD_ALLTESTS_FALSE BUILD_EXAMPLES_TRUE BUILD_EXAMPLES_FALSE execincludedir CPPUNIT_CONFIG CPPUNIT_CFLAGS CPPUNIT_LIBS ENABLE_ADOLC_TRUE ENABLE_ADOLC_FALSE ADOLC_INCDIR ADOLC_LIBDIR ADOLC_LIBS TRILINOS_TEMPLATE_OBJS ac_aux_dir LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -887,6 +887,9 @@ Optional Features:
 
   --enable-sacado-tests   Build Sacado tests (default is yes if
                           --disable-tests is not specified)
+  --enable-sacado-alltests
+                          Build all Sacado tests (including very slow ones)
+                          (default is no)
   --enable-examples       Build Sacado examples (default is yes)
   --enable-sacado-examples
                           Build Sacado examples (default is yes if
@@ -3809,7 +3812,7 @@ fi
 
 
 # Provide some information about the compiler.
-echo "$as_me:3812:" \
+echo "$as_me:3815:" \
      "checking for Fortran 77 compiler version" >&5
 ac_compiler=`set X $ac_compile; echo $2`
 { (eval echo "$as_me:$LINENO: \"$ac_compiler --version </dev/null >&5\"") >&5
@@ -4032,6 +4035,46 @@ fi
 else
   RANLIB="$ac_cv_prog_RANLIB"
 fi
+
+for ac_prog in gawk mawk nawk awk
+do
+  # Extract the first word of "$ac_prog", so it can be a program name with args.
+set dummy $ac_prog; ac_word=$2
+echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_prog_AWK+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  if test -n "$AWK"; then
+  ac_cv_prog_AWK="$AWK" # Let the user override the test.
+else
+as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_prog_AWK="$ac_prog"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+
+fi
+fi
+AWK=$ac_cv_prog_AWK
+if test -n "$AWK"; then
+  echo "$as_me:$LINENO: result: $AWK" >&5
+echo "${ECHO_T}$AWK" >&6
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+  test -n "$AWK" && break
+done
 
 
 # ------------------------------------------------------------------------
@@ -6234,6 +6277,42 @@ fi
 
 
 
+# Check whether --enable-sacado-alltests or --disable-sacado-alltests was given.
+if test "${enable_sacado_alltests+set}" = set; then
+  enableval="$enable_sacado_alltests"
+  ac_cv_use_sacado_alltests=$enableval
+else
+  ac_cv_use_sacado_alltests=no
+fi;
+
+echo "$as_me:$LINENO: checking whether to use sacado-alltests" >&5
+echo $ECHO_N "checking whether to use sacado-alltests... $ECHO_C" >&6
+
+if test "X$ac_cv_use_sacado_alltests" != "Xno"; then
+  echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_SACADO_ALLTESTS
+_ACEOF
+
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+
+
+if test "X$ac_cv_use_sacado_alltests" != "Xno"; then
+  BUILD_ALLTESTS_TRUE=
+  BUILD_ALLTESTS_FALSE='#'
+else
+  BUILD_ALLTESTS_TRUE='#'
+  BUILD_ALLTESTS_FALSE=
+fi
+
+
+
 # Check whether --enable-examples or --disable-examples was given.
 if test "${enable_examples+set}" = set; then
   enableval="$enable_examples"
@@ -6943,7 +7022,7 @@ fi
 # ------------------------------------------------------------------------
 # Output files
 # ------------------------------------------------------------------------
-                                                            ac_config_files="$ac_config_files Makefile src/Makefile example/Makefile test/Makefile test/utils/Makefile test/TestSuite/Makefile"
+                                                                                ac_config_files="$ac_config_files Makefile src/Makefile example/Makefile test/Makefile test/utils/Makefile test/TestSuite/Makefile test/tradoptest/Makefile test/tradoptest/testgen.as"
 
 
 cat >confcache <<\_ACEOF
@@ -7111,6 +7190,13 @@ if test -z "${BUILD_TESTS_TRUE}" && test -z "${BUILD_TESTS_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"BUILD_TESTS\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"BUILD_TESTS\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${BUILD_ALLTESTS_TRUE}" && test -z "${BUILD_ALLTESTS_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"BUILD_ALLTESTS\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"BUILD_ALLTESTS\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -7578,6 +7664,8 @@ do
   "test/Makefile" ) CONFIG_FILES="$CONFIG_FILES test/Makefile" ;;
   "test/utils/Makefile" ) CONFIG_FILES="$CONFIG_FILES test/utils/Makefile" ;;
   "test/TestSuite/Makefile" ) CONFIG_FILES="$CONFIG_FILES test/TestSuite/Makefile" ;;
+  "test/tradoptest/Makefile" ) CONFIG_FILES="$CONFIG_FILES test/tradoptest/Makefile" ;;
+  "test/tradoptest/testgen.as" ) CONFIG_FILES="$CONFIG_FILES test/tradoptest/testgen.as" ;;
   "depfiles" ) CONFIG_COMMANDS="$CONFIG_COMMANDS depfiles" ;;
   "src/Sacado_config.h" ) CONFIG_HEADERS="$CONFIG_HEADERS src/Sacado_config.h:src/Sacado_config.h.in" ;;
   *) { { echo "$as_me:$LINENO: error: invalid argument: $ac_config_target" >&5
@@ -7749,6 +7837,8 @@ s,@USING_GNUMAKE_TRUE@,$USING_GNUMAKE_TRUE,;t t
 s,@USING_GNUMAKE_FALSE@,$USING_GNUMAKE_FALSE,;t t
 s,@BUILD_TESTS_TRUE@,$BUILD_TESTS_TRUE,;t t
 s,@BUILD_TESTS_FALSE@,$BUILD_TESTS_FALSE,;t t
+s,@BUILD_ALLTESTS_TRUE@,$BUILD_ALLTESTS_TRUE,;t t
+s,@BUILD_ALLTESTS_FALSE@,$BUILD_ALLTESTS_FALSE,;t t
 s,@BUILD_EXAMPLES_TRUE@,$BUILD_EXAMPLES_TRUE,;t t
 s,@BUILD_EXAMPLES_FALSE@,$BUILD_EXAMPLES_FALSE,;t t
 s,@execincludedir@,$execincludedir,;t t
