SUMMARY:   Adding a PETSc example
     BUGS:      4125

     CHECKLIST:

     1)   Did you add any source files?  yes
     1.a) Did you do a 'cvs add'?  yes
     1.b) Did you add them to a Makefile.am file in some way?  yes
     1.c) Did you do a new bootstrap?  yes

     2)   Did you update or change the build system?  yes
     2.a) Did you remember to do a bootstrap and do a 'cvs add' on the
          Makefile.am files and the Makefile.in files?  yes
     2.b) [Optional but recommended] Did you blow away the libraries and
          executables and then rebuild?  yes

     3) Did you rerun the test suite on at least the packages that you
        changed?  yes

     COMMENTS:

     Added configure support for PETSc.  I borrowed heavily from NOX, but had
     to do a bit more to get the library variable that contains the PETSc
     dependencies.  I'll document all this via Doxygen, but basically, you
     have to tell configure where the PETSc home directory is.

     Added an example that demonstrates how a PETSc application can wrap
     an aij matrix as an Epetra_PETScAIJMatrix and create/apply a Trilinos
     preconditioner.  The example builds a 2D Poisson matrix, wraps the matrix,
     builds an ML preconditioner, and solves the system via AztecOO CG and PETSc
     CG.

     Rebuilt Trilinos with and without PETSc support, and ran all EpetraExt tests.

(checklist version 2007-06-20)

diff --git a/packages/epetraext/configure b/packages/epetraext/configure
--- a/packages/epetraext/configure
+++ b/packages/epetraext/configure
@@ -756,12 +756,18 @@ BUILD_BLOCK_TRUE
 BUILD_BLOCK_FALSE
 BUILD_MODEL_EVALUATOR_TRUE
 BUILD_MODEL_EVALUATOR_FALSE
-BUILD_PETSC_TRUE
-BUILD_PETSC_FALSE
+EPETRAEXT_USING_PETSC_TRUE
+EPETRAEXT_USING_PETSC_FALSE
 BUILD_GRAPH_REORDERINGS_TRUE
 BUILD_GRAPH_REORDERINGS_FALSE
 HAVE_EPETRAEXT_HDF5_TRUE
 HAVE_EPETRAEXT_HDF5_FALSE
+EPETRAEXT_PETSC_INCLUDES
+EPETRAEXT_PETSC_DIR
+EPETRAEXT_PETSC_ARCH
+USER_DEFINED_PETSCLIB
+PETSCLIB_IS_DEFINED_TRUE
+PETSCLIB_IS_DEFINED_FALSE
 BUILD_EPETRAEXT_TRIUTILS_TRUE
 BUILD_EPETRAEXT_TRIUTILS_FALSE
 BUILD_TESTS_TRUE
@@ -1495,6 +1501,7 @@ Optional Packages:
                           with an error if it is not found. (default is no)
   --with-petsc            Enable EpetraExt interface support for PETSc.
                           (default is no)
+  --with-petsc-libdir     specify location of petsc library
   --with-libdirs          OBSOLETE use --with-ldflags instead. (ex.
                           --with-ldflags="-L<DIR> -L<DIR2>")
   --with-incdirs          additional directories containing include files:
@@ -8973,11 +8980,11 @@ echo "${ECHO_T}no" >&6; }
 fi
 
  if test "X$ac_cv_use_petsc" != "Xno"; then
-  BUILD_PETSC_TRUE=
-  BUILD_PETSC_FALSE='#'
+  EPETRAEXT_USING_PETSC_TRUE=
+  EPETRAEXT_USING_PETSC_FALSE='#'
 else
-  BUILD_PETSC_TRUE='#'
-  BUILD_PETSC_FALSE=
+  EPETRAEXT_USING_PETSC_TRUE='#'
+  EPETRAEXT_USING_PETSC_FALSE=
 fi
 
 
@@ -9060,6 +9067,234 @@ else
 fi
 
 fi
+
+# ------------------------------------------------------------------------
+# Check for PETSc (copied from NOX!)
+# ------------------------------------------------------------------------
+
+
+if test X$ac_cv_use_petsc = Xyes; then
+
+
+  { echo "$as_me:$LINENO: checking for petsc include directory" >&5
+echo $ECHO_N "checking for petsc include directory... $ECHO_C" >&6; }
+  if test -n "${petsc_INC}" && test -f ${petsc_INC}/petsc.h; then
+    { echo "$as_me:$LINENO: result: ${petsc_INC}" >&5
+echo "${ECHO_T}${petsc_INC}" >&6; }
+  elif test -f ${PETSC_DIR}/bmake/${PETSC_ARCH}/petsc.h; then
+    petsc_INC=${PETSC_DIR}/bmake/${PETSC_ARCH}
+    { echo "$as_me:$LINENO: result: ${petsc_INC}" >&5
+echo "${ECHO_T}${petsc_INC}" >&6; }
+  elif test -f ${PETSC_DIR}/bmake/common/petsc.h; then
+    petsc_INC=${PETSC_DIR}/bmake/common
+    { echo "$as_me:$LINENO: result: ${petsc_INC}" >&5
+echo "${ECHO_T}${petsc_INC}" >&6; }
+  elif test -f ${PETSC_DIR}/include/petsc.h; then
+    petsc_INC=${PETSC_DIR}/include
+    { echo "$as_me:$LINENO: result: ${petsc_INC}" >&5
+echo "${ECHO_T}${petsc_INC}" >&6; }
+  elif test -f ${PETSC_DIR}/include/mpiuni/petsc.h; then
+    petsc_INC=${PETSC_DIR}/include/mpiuni
+    { echo "$as_me:$LINENO: result: ${petsc_INC}" >&5
+echo "${ECHO_T}${petsc_INC}" >&6; }
+  else
+    { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+    { { echo "$as_me:$LINENO: error: Cannot find petsc include directory containing petsc.h. Make sure PETSC_DIR and PETSC_ARCH are defined." >&5
+echo "$as_me: error: Cannot find petsc include directory containing petsc.h. Make sure PETSC_DIR and PETSC_ARCH are defined." >&2;}
+   { (exit 1); exit 1; }; }
+  fi
+
+
+
+  { echo "$as_me:$LINENO: checking for petsccommon include directory" >&5
+echo $ECHO_N "checking for petsccommon include directory... $ECHO_C" >&6; }
+  if test -n "${petsccommon_INC}" && test -f ${petsccommon_INC}/base; then
+    { echo "$as_me:$LINENO: result: ${petsccommon_INC}" >&5
+echo "${ECHO_T}${petsccommon_INC}" >&6; }
+  elif test -f ${PETSC_DIR}/bmake/${PETSC_ARCH}/base; then
+    petsccommon_INC=${PETSC_DIR}/bmake/${PETSC_ARCH}
+    { echo "$as_me:$LINENO: result: ${petsccommon_INC}" >&5
+echo "${ECHO_T}${petsccommon_INC}" >&6; }
+  elif test -f ${PETSC_DIR}/bmake/common/base; then
+    petsccommon_INC=${PETSC_DIR}/bmake/common
+    { echo "$as_me:$LINENO: result: ${petsccommon_INC}" >&5
+echo "${ECHO_T}${petsccommon_INC}" >&6; }
+  elif test -f ${PETSC_DIR}/include/base; then
+    petsccommon_INC=${PETSC_DIR}/include
+    { echo "$as_me:$LINENO: result: ${petsccommon_INC}" >&5
+echo "${ECHO_T}${petsccommon_INC}" >&6; }
+  elif test -f ${PETSC_DIR}/include/mpiuni/base; then
+    petsccommon_INC=${PETSC_DIR}/include/mpiuni
+    { echo "$as_me:$LINENO: result: ${petsccommon_INC}" >&5
+echo "${ECHO_T}${petsccommon_INC}" >&6; }
+  else
+    { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+    { { echo "$as_me:$LINENO: error: Cannot find petsccommon include directory containing base. Make sure PETSC_DIR and PETSC_ARCH are defined." >&5
+echo "$as_me: error: Cannot find petsccommon include directory containing base. Make sure PETSC_DIR and PETSC_ARCH are defined." >&2;}
+   { (exit 1); exit 1; }; }
+  fi
+
+
+
+  { echo "$as_me:$LINENO: checking for petscbmake include directory" >&5
+echo $ECHO_N "checking for petscbmake include directory... $ECHO_C" >&6; }
+  if test -n "${petscbmake_INC}" && test -f ${petscbmake_INC}/petscconf.h; then
+    { echo "$as_me:$LINENO: result: ${petscbmake_INC}" >&5
+echo "${ECHO_T}${petscbmake_INC}" >&6; }
+  elif test -f ${PETSC_DIR}/bmake/${PETSC_ARCH}/petscconf.h; then
+    petscbmake_INC=${PETSC_DIR}/bmake/${PETSC_ARCH}
+    { echo "$as_me:$LINENO: result: ${petscbmake_INC}" >&5
+echo "${ECHO_T}${petscbmake_INC}" >&6; }
+  elif test -f ${PETSC_DIR}/bmake/common/petscconf.h; then
+    petscbmake_INC=${PETSC_DIR}/bmake/common
+    { echo "$as_me:$LINENO: result: ${petscbmake_INC}" >&5
+echo "${ECHO_T}${petscbmake_INC}" >&6; }
+  elif test -f ${PETSC_DIR}/include/petscconf.h; then
+    petscbmake_INC=${PETSC_DIR}/include
+    { echo "$as_me:$LINENO: result: ${petscbmake_INC}" >&5
+echo "${ECHO_T}${petscbmake_INC}" >&6; }
+  elif test -f ${PETSC_DIR}/include/mpiuni/petscconf.h; then
+    petscbmake_INC=${PETSC_DIR}/include/mpiuni
+    { echo "$as_me:$LINENO: result: ${petscbmake_INC}" >&5
+echo "${ECHO_T}${petscbmake_INC}" >&6; }
+  else
+    { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+    { { echo "$as_me:$LINENO: error: Cannot find petscbmake include directory containing petscconf.h. Make sure PETSC_DIR and PETSC_ARCH are defined." >&5
+echo "$as_me: error: Cannot find petscbmake include directory containing petscconf.h. Make sure PETSC_DIR and PETSC_ARCH are defined." >&2;}
+   { (exit 1); exit 1; }; }
+  fi
+
+
+  if test "X${HAVE_PKG_MPI}" = "Xno"; then
+
+  { echo "$as_me:$LINENO: checking for mpiuni include directory" >&5
+echo $ECHO_N "checking for mpiuni include directory... $ECHO_C" >&6; }
+  if test -n "${mpiuni_INC}" && test -f ${mpiuni_INC}/mpi.h; then
+    { echo "$as_me:$LINENO: result: ${mpiuni_INC}" >&5
+echo "${ECHO_T}${mpiuni_INC}" >&6; }
+  elif test -f ${PETSC_DIR}/bmake/${PETSC_ARCH}/mpi.h; then
+    mpiuni_INC=${PETSC_DIR}/bmake/${PETSC_ARCH}
+    { echo "$as_me:$LINENO: result: ${mpiuni_INC}" >&5
+echo "${ECHO_T}${mpiuni_INC}" >&6; }
+  elif test -f ${PETSC_DIR}/bmake/common/mpi.h; then
+    mpiuni_INC=${PETSC_DIR}/bmake/common
+    { echo "$as_me:$LINENO: result: ${mpiuni_INC}" >&5
+echo "${ECHO_T}${mpiuni_INC}" >&6; }
+  elif test -f ${PETSC_DIR}/include/mpi.h; then
+    mpiuni_INC=${PETSC_DIR}/include
+    { echo "$as_me:$LINENO: result: ${mpiuni_INC}" >&5
+echo "${ECHO_T}${mpiuni_INC}" >&6; }
+  elif test -f ${PETSC_DIR}/include/mpiuni/mpi.h; then
+    mpiuni_INC=${PETSC_DIR}/include/mpiuni
+    { echo "$as_me:$LINENO: result: ${mpiuni_INC}" >&5
+echo "${ECHO_T}${mpiuni_INC}" >&6; }
+  else
+    { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+    { { echo "$as_me:$LINENO: error: Cannot find mpiuni include directory containing mpi.h. Make sure PETSC_DIR and PETSC_ARCH are defined." >&5
+echo "$as_me: error: Cannot find mpiuni include directory containing mpi.h. Make sure PETSC_DIR and PETSC_ARCH are defined." >&2;}
+   { (exit 1); exit 1; }; }
+  fi
+
+
+  fi
+
+  EPETRAEXT_PETSC_INCLUDES="-I${PETSC_DIR} -I${petsc_INC} -I${petsccommon_INC} -I${petscbmake_INC}"
+  if test "X${HAVE_PKG_MPI}" = "Xno"; then
+    EPETRAEXT_PETSC_INCLUDES=" ${EPETRAEXT_PETSC_INCLUDES} -I${mpiuni_INC}"
+  fi
+
+
+  #JJH 8/26/2008
+  # ${PETSC_DIR} and ${PETSC_ARCH} can't be used directly in
+  # Makefile.export.epetraext because not all packages know about them.
+  # EpetraExt does know about them, so I use AC_SUBST to get their values
+  # directly into the export makefile.
+  EPETRAEXT_PETSC_DIR=${PETSC_DIR}
+  EPETRAEXT_PETSC_ARCH=${PETSC_ARCH}
+
+
+
+  { echo "$as_me:$LINENO: checking whether PETSC_LIB is defined" >&5
+echo $ECHO_N "checking whether PETSC_LIB is defined... $ECHO_C" >&6; }
+  if test "X${PETSC_LIB}" = "X"; then
+    #JJH 8/26/2008
+    #The PETSc file "variables" defines PETSC_LIB, which contains all of
+    #PETSc's link dependencies.  Unfortunately, "variables" includes another
+    #file "petscconf" that redefines top_builddir (argh!). But since we need
+    #that other file for PETSC_LIB, I copy both and modify to my liking.  Ugh.
+    { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+    cat ${PETSC_DIR}/bmake/common/variables | sed "s/^include /#include /" > petsc_variables
+    echo "include ${PWD}/petscconf" >> petsc_variables
+    cat ${PETSC_DIR}/bmake/${PETSC_ARCH}/petscconf | sed "s/^top_builddir/#top_builddir/" > petscconf
+  else
+    { echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6; }
+    USER_DEFINED_PETSCLIB=${PETSC_LIB}
+
+  fi
+
+fi #if test X$ac_cv_use_petsc = Xyes; then
+ if test "X${PETSC_LIB}" != "X"; then
+  PETSCLIB_IS_DEFINED_TRUE=
+  PETSCLIB_IS_DEFINED_FALSE='#'
+else
+  PETSCLIB_IS_DEFINED_TRUE='#'
+  PETSCLIB_IS_DEFINED_FALSE=
+fi
+
+
+# ------------------------------------------------------------------------
+# Checks for Petsc libraries
+# ------------------------------------------------------------------------
+
+
+
+# Check for petsc
+
+
+# Check whether --with-petsc-libdir was given.
+if test "${with_petsc_libdir+set}" = set; then
+  withval=$with_petsc_libdir; petsc_LIBDIR=$withval
+fi
+
+
+  { echo "$as_me:$LINENO: checking whether PETSC_DIR is defined" >&5
+echo $ECHO_N "checking whether PETSC_DIR is defined... $ECHO_C" >&6; }
+  if test -n "${PETSC_DIR}"; then
+     { echo "$as_me:$LINENO: result: yes (${PETSC_DIR})" >&5
+echo "${ECHO_T}yes (${PETSC_DIR})" >&6; }
+  else
+     { { echo "$as_me:$LINENO: error: Cannot find PETSC_DIR environment variable. Please define." >&5
+echo "$as_me: error: Cannot find PETSC_DIR environment variable. Please define." >&2;}
+   { (exit 1); exit 1; }; }
+  fi
+
+  { echo "$as_me:$LINENO: checking for petsc" >&5
+echo $ECHO_N "checking for petsc... $ECHO_C" >&6; }
+  if test -n "${petsc_LIBDIR}" && test -f ${petsc_LIBDIR}/libpetsc.a; then
+    LDFLAGS="-L${petsc_LIBDIR} ${LDFLAGS}"
+    { echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6; }
+  elif test -f ${PETSC_DIR}/lib/${PETSC_ARCH}/libpetsc.a; then
+    LDFLAGS="-L${PETSC_DIR}/lib/${PETSC_ARCH} ${LDFLAGS}"
+    { echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6; }
+  else
+    { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+    { { echo "$as_me:$LINENO: error: Cannot find petsc library" >&5
+echo "$as_me: error: Cannot find petsc library" >&2;}
+   { (exit 1); exit 1; }; }
+  fi
+
+  LIBS="-lpetsc ${LIBS}"
+
+
 
 # ------------------------------------------------------------------------
 # Interfaces to other Trilinos packages
@@ -11404,7 +11639,7 @@ ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
 # Output files
 # ------------------------------------------------------------------------
 ##
-ac_config_files="$ac_config_files Makefile Makefile.export.epetraext src/Makefile test/BTF/Makefile test/Composite/Makefile test/Makefile test/MapColoring/Makefile test/Matlab/Makefile test/MatrixMatrix/Makefile test/Overlap/Makefile test/Permutation/Makefile test/SingletonFilter/Makefile test/SymmRCM/Makefile test/Transpose/Makefile test/View/Makefile test/Zoltan/Makefile test/inout/Makefile example/Makefile example/inout/Makefile example/zoltan/Makefile example/matlab/Makefile example/MapColoring/Makefile"
+ac_config_files="$ac_config_files Makefile Makefile.export.epetraext src/Makefile test/BTF/Makefile test/Composite/Makefile test/Makefile test/MapColoring/Makefile test/Matlab/Makefile test/MatrixMatrix/Makefile test/Overlap/Makefile test/Permutation/Makefile test/SingletonFilter/Makefile test/SymmRCM/Makefile test/Transpose/Makefile test/View/Makefile test/Zoltan/Makefile test/inout/Makefile example/Makefile example/inout/Makefile example/zoltan/Makefile example/matlab/Makefile example/MapColoring/Makefile example/petsc/Makefile"
 
 
 cat >confcache <<\_ACEOF
@@ -11650,10 +11885,10 @@ echo "$as_me: error: conditional \"BUILD_MODEL_EVALUATOR\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
-if test -z "${BUILD_PETSC_TRUE}" && test -z "${BUILD_PETSC_FALSE}"; then
-  { { echo "$as_me:$LINENO: error: conditional \"BUILD_PETSC\" was never defined.
+if test -z "${EPETRAEXT_USING_PETSC_TRUE}" && test -z "${EPETRAEXT_USING_PETSC_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"EPETRAEXT_USING_PETSC\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
-echo "$as_me: error: conditional \"BUILD_PETSC\" was never defined.
+echo "$as_me: error: conditional \"EPETRAEXT_USING_PETSC\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -11675,6 +11910,13 @@ if test -z "${HAVE_EPETRAEXT_HDF5_TRUE}" && test -z "${HAVE_EPETRAEXT_HDF5_FALSE
   { { echo "$as_me:$LINENO: error: conditional \"HAVE_EPETRAEXT_HDF5\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"HAVE_EPETRAEXT_HDF5\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${PETSCLIB_IS_DEFINED_TRUE}" && test -z "${PETSCLIB_IS_DEFINED_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"PETSCLIB_IS_DEFINED\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"PETSCLIB_IS_DEFINED\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -12218,6 +12460,7 @@ do
     "example/zoltan/Makefile") CONFIG_FILES="$CONFIG_FILES example/zoltan/Makefile" ;;
     "example/matlab/Makefile") CONFIG_FILES="$CONFIG_FILES example/matlab/Makefile" ;;
     "example/MapColoring/Makefile") CONFIG_FILES="$CONFIG_FILES example/MapColoring/Makefile" ;;
+    "example/petsc/Makefile") CONFIG_FILES="$CONFIG_FILES example/petsc/Makefile" ;;
 
   *) { { echo "$as_me:$LINENO: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
@@ -12462,12 +12705,18 @@ BUILD_BLOCK_TRUE!$BUILD_BLOCK_TRUE$ac_delim
 BUILD_BLOCK_FALSE!$BUILD_BLOCK_FALSE$ac_delim
 BUILD_MODEL_EVALUATOR_TRUE!$BUILD_MODEL_EVALUATOR_TRUE$ac_delim
 BUILD_MODEL_EVALUATOR_FALSE!$BUILD_MODEL_EVALUATOR_FALSE$ac_delim
-BUILD_PETSC_TRUE!$BUILD_PETSC_TRUE$ac_delim
-BUILD_PETSC_FALSE!$BUILD_PETSC_FALSE$ac_delim
+EPETRAEXT_USING_PETSC_TRUE!$EPETRAEXT_USING_PETSC_TRUE$ac_delim
+EPETRAEXT_USING_PETSC_FALSE!$EPETRAEXT_USING_PETSC_FALSE$ac_delim
 BUILD_GRAPH_REORDERINGS_TRUE!$BUILD_GRAPH_REORDERINGS_TRUE$ac_delim
 BUILD_GRAPH_REORDERINGS_FALSE!$BUILD_GRAPH_REORDERINGS_FALSE$ac_delim
 HAVE_EPETRAEXT_HDF5_TRUE!$HAVE_EPETRAEXT_HDF5_TRUE$ac_delim
 HAVE_EPETRAEXT_HDF5_FALSE!$HAVE_EPETRAEXT_HDF5_FALSE$ac_delim
+EPETRAEXT_PETSC_INCLUDES!$EPETRAEXT_PETSC_INCLUDES$ac_delim
+EPETRAEXT_PETSC_DIR!$EPETRAEXT_PETSC_DIR$ac_delim
+EPETRAEXT_PETSC_ARCH!$EPETRAEXT_PETSC_ARCH$ac_delim
+USER_DEFINED_PETSCLIB!$USER_DEFINED_PETSCLIB$ac_delim
+PETSCLIB_IS_DEFINED_TRUE!$PETSCLIB_IS_DEFINED_TRUE$ac_delim
+PETSCLIB_IS_DEFINED_FALSE!$PETSCLIB_IS_DEFINED_FALSE$ac_delim
 BUILD_EPETRAEXT_TRIUTILS_TRUE!$BUILD_EPETRAEXT_TRIUTILS_TRUE$ac_delim
 BUILD_EPETRAEXT_TRIUTILS_FALSE!$BUILD_EPETRAEXT_TRIUTILS_FALSE$ac_delim
 BUILD_TESTS_TRUE!$BUILD_TESTS_TRUE$ac_delim
@@ -12488,7 +12737,7 @@ LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 68; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 74; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
