----------------------------------------------------------------------
 Committing in .

 Modified Files:
 	configure configure.ac src/EpetraExt_ConfigDefs.h
 	src/EpetraExt_config.h.in
 ----------------------------------------------------------------------
Fixes a bug equivalent to 781, but for epetraext instead of teuchos.

diff --git a/packages/epetraext/configure b/packages/epetraext/configure
--- a/packages/epetraext/configure
+++ b/packages/epetraext/configure
@@ -5221,7 +5221,8 @@ done
 
 
 
-for ac_header in string string.h algorithm algorithm.h
+
+for ac_header in string string.h algorithm algo.h algorithm.h
 do
 as_ac_Header=`echo "ac_cv_header_$ac_header" | $as_tr_sh`
 if eval "test \"\${$as_ac_Header+set}\" = set"; then
@@ -5401,9 +5402,9 @@ echo "$as_me: error: Cannot find iostream or iostream.h.  EpetraExt requires at 
    { (exit 1); exit 1; }; }
 fi
 
-if test "X$ac_cv_header_algorithm" != "Xyes" && test "X$ac_cv_header_algorithm_h" != "Xyes"; then
-  { { echo "$as_me:$LINENO: error: Cannot find algorithm or algorithm.h.  EpetraExt requires at least one or the other." >&5
-echo "$as_me: error: Cannot find algorithm or algorithm.h.  EpetraExt requires at least one or the other." >&2;}
+if test "X$ac_cv_header_algorithm" != "Xyes"  && test "X$ac_cv_header_algo_h" != "Xyes" && test "X$ac_cv_header_algorithm_h" != "Xyes"; then
+  { { echo "$as_me:$LINENO: error: Cannot find algorithm, algo.h, or algorithm.h.  EpetraExt requires at least one of these." >&5
+echo "$as_me: error: Cannot find algorithm, algo.h, or algorithm.h.  EpetraExt requires at least one of these." >&2;}
    { (exit 1); exit 1; }; }
 fi
 
@@ -6844,7 +6845,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_verb"
-(eval echo $as_me:6847: \"$ac_link\") >&5
+(eval echo $as_me:6848: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
@@ -6922,7 +6923,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_cv_prog_f77_v"
-(eval echo $as_me:6925: \"$ac_link\") >&5
+(eval echo $as_me:6926: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
@@ -10057,7 +10058,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_verb"
-(eval echo $as_me:10060: \"$ac_link\") >&5
+(eval echo $as_me:10061: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
@@ -10135,7 +10136,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_cv_prog_f77_v"
-(eval echo $as_me:10138: \"$ac_link\") >&5
+(eval echo $as_me:10139: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
