Adding a set of block linear algebra objects.  These are specifically tailored to Andy S.'s needs for the CSRF 4D project.

diff --git a/packages/epetraext/configure b/packages/epetraext/configure
--- a/packages/epetraext/configure
+++ b/packages/epetraext/configure
@@ -311,7 +311,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot MPI_TEMP_CXX MPI_CXX HAVE_MPI_TRUE HAVE_MPI_FALSE MPI_CXX_EXISTS MPI_CC_EXISTS MPI_F77_EXISTS CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE F77 FFLAGS ac_ct_F77 RANLIB ac_ct_RANLIB USE_ALTERNATE_AR_TRUE USE_ALTERNATE_AR_FALSE ALTERNATE_AR CXXCPP EGREP HAVE_THREADS_TRUE HAVE_THREADS_FALSE BUILD_TRANSFORM_TRUE BUILD_TRANSFORM_FALSE BUILD_INOUT_TRUE BUILD_INOUT_FALSE BUILD_COLORING_TRUE BUILD_COLORING_FALSE BUILD_ZOLTAN_TRUE BUILD_ZOLTAN_FALSE BUILD_BTF_TRUE BUILD_BTF_FALSE BUILD_MATLAB_TRUE BUILD_MATLAB_FALSE BUILD_TESTS_TRUE BUILD_TESTS_FALSE BUILD_EXAMPLES_TRUE BUILD_EXAMPLES_FALSE BUILD_EXPERIMENTAL_TRUE BUILD_EXPERIMENTAL_FALSE FLIBS BLAS_LIBS LAPACK_LIBS TRILINOS_TEMPLATE_OBJS XTRALDADD ac_aux_dir LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot MPI_TEMP_CXX MPI_CXX HAVE_MPI_TRUE HAVE_MPI_FALSE MPI_CXX_EXISTS MPI_CC_EXISTS MPI_F77_EXISTS CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE F77 FFLAGS ac_ct_F77 RANLIB ac_ct_RANLIB USE_ALTERNATE_AR_TRUE USE_ALTERNATE_AR_FALSE ALTERNATE_AR CXXCPP EGREP HAVE_THREADS_TRUE HAVE_THREADS_FALSE BUILD_TRANSFORM_TRUE BUILD_TRANSFORM_FALSE BUILD_INOUT_TRUE BUILD_INOUT_FALSE BUILD_COLORING_TRUE BUILD_COLORING_FALSE BUILD_ZOLTAN_TRUE BUILD_ZOLTAN_FALSE BUILD_BTF_TRUE BUILD_BTF_FALSE BUILD_MATLAB_TRUE BUILD_MATLAB_FALSE BUILD_BLOCK_TRUE BUILD_BLOCK_FALSE BUILD_TESTS_TRUE BUILD_TESTS_FALSE BUILD_EXAMPLES_TRUE BUILD_EXAMPLES_FALSE BUILD_EXPERIMENTAL_TRUE BUILD_EXPERIMENTAL_FALSE FLIBS BLAS_LIBS LAPACK_LIBS TRILINOS_TEMPLATE_OBJS XTRALDADD ac_aux_dir LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -895,6 +895,8 @@ Optional Features:
   --enable-epetraext-btf  Enable EpetraExt BTF subpkg (default is no)
   --enable-epetraext-matlab
                           Enable EpetraExt Matlab subpkg (default is no)
+  --enable-epetraext-block
+                          Enable EpetraExt Block subpkg (default is yes)
   --enable-tests          Build tests for all Trilinos packages (not all
                           packages are sensitive to this option) (default is
                           yes)
@@ -4203,7 +4205,7 @@ fi
 
 
 # Provide some information about the compiler.
-echo "$as_me:4206:" \
+echo "$as_me:4208:" \
      "checking for Fortran 77 compiler version" >&5
 ac_compiler=`set X $ac_compile; echo $2`
 { (eval echo "$as_me:$LINENO: \"$ac_compiler --version </dev/null >&5\"") >&5
@@ -7737,6 +7739,42 @@ else
 fi
 
 
+
+# Check whether --enable-epetraext-block or --disable-epetraext-block was given.
+if test "${enable_epetraext_block+set}" = set; then
+  enableval="$enable_epetraext_block"
+  ac_cv_use_epetraext_block=$enableval
+else
+  ac_cv_use_epetraext_block=yes
+fi;
+
+echo "$as_me:$LINENO: checking whether to use epetraext-block" >&5
+echo $ECHO_N "checking whether to use epetraext-block... $ECHO_C" >&6
+
+if test "X$ac_cv_use_epetraext_block" != "Xno"; then
+  echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_BLOCK
+_ACEOF
+
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+
+
+if test "X$ac_cv_use_epetraext_block" != "Xno"; then
+  BUILD_BLOCK_TRUE=
+  BUILD_BLOCK_FALSE='#'
+else
+  BUILD_BLOCK_TRUE='#'
+  BUILD_BLOCK_FALSE=
+fi
+
+
 # ------------------------------------------------------------------------
 # Checks if tests should be built
 # ------------------------------------------------------------------------
@@ -8074,7 +8112,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_verb"
-(eval echo $as_me:8077: \"$ac_link\") >&5
+(eval echo $as_me:8115: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
@@ -8152,7 +8190,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_cv_prog_f77_v"
-(eval echo $as_me:8155: \"$ac_link\") >&5
+(eval echo $as_me:8193: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
@@ -11643,7 +11681,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_verb"
-(eval echo $as_me:11646: \"$ac_link\") >&5
+(eval echo $as_me:11684: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
@@ -11721,7 +11759,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_cv_prog_f77_v"
-(eval echo $as_me:11724: \"$ac_link\") >&5
+(eval echo $as_me:11762: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
@@ -12114,6 +12152,13 @@ if test -z "${BUILD_MATLAB_TRUE}" && test -z "${BUILD_MATLAB_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"BUILD_MATLAB\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"BUILD_MATLAB\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${BUILD_BLOCK_TRUE}" && test -z "${BUILD_BLOCK_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"BUILD_BLOCK\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"BUILD_BLOCK\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -12792,6 +12837,8 @@ s,@BUILD_BTF_TRUE@,$BUILD_BTF_TRUE,;t t
 s,@BUILD_BTF_FALSE@,$BUILD_BTF_FALSE,;t t
 s,@BUILD_MATLAB_TRUE@,$BUILD_MATLAB_TRUE,;t t
 s,@BUILD_MATLAB_FALSE@,$BUILD_MATLAB_FALSE,;t t
+s,@BUILD_BLOCK_TRUE@,$BUILD_BLOCK_TRUE,;t t
+s,@BUILD_BLOCK_FALSE@,$BUILD_BLOCK_FALSE,;t t
 s,@BUILD_TESTS_TRUE@,$BUILD_TESTS_TRUE,;t t
 s,@BUILD_TESTS_FALSE@,$BUILD_TESTS_FALSE,;t t
 s,@BUILD_EXAMPLES_TRUE@,$BUILD_EXAMPLES_TRUE,;t t
