bootstrap'd after adding new files. Hope everything is fine!

diff --git a/packages/epetraext/configure b/packages/epetraext/configure
--- a/packages/epetraext/configure
+++ b/packages/epetraext/configure
@@ -311,7 +311,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot MPI_TEMP_CXX MPI_CXX HAVE_MPI_TRUE HAVE_MPI_FALSE MPI_CXX_EXISTS MPI_CC_EXISTS MPI_F77_EXISTS CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE F77 FFLAGS ac_ct_F77 RANLIB ac_ct_RANLIB USE_ALTERNATE_AR_TRUE USE_ALTERNATE_AR_FALSE ALTERNATE_AR CXXCPP USING_EXPORT_MAKEFILES_TRUE USING_EXPORT_MAKEFILES_FALSE PERL_EXE HAVE_PERL USING_PERL_TRUE USING_PERL_FALSE USING_GNUMAKE_TRUE USING_GNUMAKE_FALSE EGREP HAVE_THREADS_TRUE HAVE_THREADS_FALSE BUILD_TRANSFORM_TRUE BUILD_TRANSFORM_FALSE BUILD_INOUT_TRUE BUILD_INOUT_FALSE BUILD_COLORING_TRUE BUILD_COLORING_FALSE BUILD_ZOLTAN_TRUE BUILD_ZOLTAN_FALSE BUILD_BTF_TRUE BUILD_BTF_FALSE BUILD_MATLAB_TRUE BUILD_MATLAB_FALSE BUILD_BLOCK_TRUE BUILD_BLOCK_FALSE BUILD_MODEL_EVALUATOR_TRUE BUILD_MODEL_EVALUATOR_FALSE BUILD_TRIUTILS_TRUE BUILD_TRIUTILS_FALSE ENABLE_EPETRAEXT_THYRA_TRUE ENABLE_EPETRAEXT_THYRA_FALSE ENABLE_EPETRA_THYRA_TRUE ENABLE_EPETRA_THYRA_FALSE ENABLE_AMESOS_THYRA_TRUE ENABLE_AMESOS_THYRA_FALSE BUILD_TESTS_TRUE BUILD_TESTS_FALSE BUILD_EXAMPLES_TRUE BUILD_EXAMPLES_FALSE BUILD_EXPERIMENTAL_TRUE BUILD_EXPERIMENTAL_FALSE BUILD_EPETRAEXT_PYTHON_TRUE BUILD_EPETRAEXT_PYTHON_FALSE PYTHON_USE_TRUE PYTHON_USE_FALSE PYTHON PYTHON_PREFIX PYTHON_EXECPREFIX BUILD_PYTHON_TRUE BUILD_PYTHON_FALSE PYTHON_CSPEC PYTHON_LSPEC WITH_SWIG SWIG SWIG_LIB SWIG_PYTHON_OPT SWIG_PYTHON_CPPFLAGS HAVE_SWIG_TRUE HAVE_SWIG_FALSE GNU_HAVE_SWIG FLIBS BLAS_LIBS LAPACK_LIBS TRILINOS_TEMPLATE_OBJS XTRALDADD ac_aux_dir LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot MPI_TEMP_CXX MPI_CXX HAVE_MPI_TRUE HAVE_MPI_FALSE MPI_CXX_EXISTS MPI_CC_EXISTS MPI_F77_EXISTS CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE F77 FFLAGS ac_ct_F77 RANLIB ac_ct_RANLIB USE_ALTERNATE_AR_TRUE USE_ALTERNATE_AR_FALSE ALTERNATE_AR CXXCPP USING_EXPORT_MAKEFILES_TRUE USING_EXPORT_MAKEFILES_FALSE PERL_EXE HAVE_PERL USING_PERL_TRUE USING_PERL_FALSE USING_GNUMAKE_TRUE USING_GNUMAKE_FALSE EGREP HAVE_THREADS_TRUE HAVE_THREADS_FALSE BUILD_TRANSFORM_TRUE BUILD_TRANSFORM_FALSE BUILD_INOUT_TRUE BUILD_INOUT_FALSE BUILD_COLORING_TRUE BUILD_COLORING_FALSE BUILD_ZOLTAN_TRUE BUILD_ZOLTAN_FALSE BUILD_BTF_TRUE BUILD_BTF_FALSE BUILD_MATLAB_TRUE BUILD_MATLAB_FALSE BUILD_BLOCK_TRUE BUILD_BLOCK_FALSE BUILD_MODEL_EVALUATOR_TRUE BUILD_MODEL_EVALUATOR_FALSE HAVE_EPETRAEXT_HDF5_TRUE HAVE_EPETRAEXT_HDF5_FALSE BUILD_TEUCHOS_TRUE BUILD_TEUCHOS_FALSE HAVE_EPETRAEXT_TEUCHOS_TRUE HAVE_EPETRAEXT_TEUCHOS_FALSE BUILD_TRIUTILS_TRUE BUILD_TRIUTILS_FALSE ENABLE_EPETRAEXT_THYRA_TRUE ENABLE_EPETRAEXT_THYRA_FALSE ENABLE_EPETRA_THYRA_TRUE ENABLE_EPETRA_THYRA_FALSE ENABLE_AMESOS_THYRA_TRUE ENABLE_AMESOS_THYRA_FALSE BUILD_TESTS_TRUE BUILD_TESTS_FALSE BUILD_EXAMPLES_TRUE BUILD_EXAMPLES_FALSE BUILD_EXPERIMENTAL_TRUE BUILD_EXPERIMENTAL_FALSE BUILD_EPETRAEXT_PYTHON_TRUE BUILD_EPETRAEXT_PYTHON_FALSE PYTHON_USE_TRUE PYTHON_USE_FALSE PYTHON PYTHON_PREFIX PYTHON_EXECPREFIX BUILD_PYTHON_TRUE BUILD_PYTHON_FALSE PYTHON_CSPEC PYTHON_LSPEC WITH_SWIG SWIG SWIG_LIB SWIG_PYTHON_OPT SWIG_PYTHON_CPPFLAGS HAVE_SWIG_TRUE HAVE_SWIG_FALSE GNU_HAVE_SWIG FLIBS BLAS_LIBS LAPACK_LIBS TRILINOS_TEMPLATE_OBJS XTRALDADD ac_aux_dir LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -912,6 +912,17 @@ Optional Features:
   --enable-epetraext-modelevaluator
                           Enable EpetraExt Model Evaluator subpkg (default is
                           yes)
+  --enable-epetraext-hdf5 Enable EpetraExt interface support for HDF5. This
+                          interface requires an already installed HDF5
+                          library; the include, the library path and the
+                          library name must be specified using --with-incdirs,
+                          --with-ldflags and --with-libs, respectively.
+                          (default is no)
+  --enable-teuchos        Build teuchos support in epetraext. Can be
+                          overridden with --disable-epetraext-teuchos.
+  --enable-epetraext-teuchos
+                          Build teuchos support in epetraext, which is
+                          required in some examples.
   --enable-triutils       Build triutils support in epetraext. Can be
                           overridden with --disable-epetraext-triutils.
   --enable-epetraext-triutils
@@ -4253,7 +4264,7 @@ fi
 
 
 # Provide some information about the compiler.
-echo "$as_me:4256:" \
+echo "$as_me:4267:" \
      "checking for Fortran 77 compiler version" >&5
 ac_compiler=`set X $ac_compile; echo $2`
 { (eval echo "$as_me:$LINENO: \"$ac_compiler --version </dev/null >&5\"") >&5
@@ -8063,9 +8074,122 @@ else
 fi
 
 
+
+# Check whether --enable-epetraext-hdf5 or --disable-epetraext-hdf5 was given.
+if test "${enable_epetraext_hdf5+set}" = set; then
+  enableval="$enable_epetraext_hdf5"
+  ac_cv_use_epetraext_hdf5=$enableval
+else
+  ac_cv_use_epetraext_hdf5=no
+fi;
+
+echo "$as_me:$LINENO: checking whether to use epetraext-hdf5" >&5
+echo $ECHO_N "checking whether to use epetraext-hdf5... $ECHO_C" >&6
+
+if test "X$ac_cv_use_epetraext_hdf5" != "Xno"; then
+  echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_EPETRAEXT_HDF5
+_ACEOF
+
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+
+if test "X$ac_cv_use_epetraext_hdf5" != "Xno" ; then
+
+
+if true ; then
+  HAVE_EPETRAEXT_HDF5_TRUE=
+  HAVE_EPETRAEXT_HDF5_FALSE='#'
+else
+  HAVE_EPETRAEXT_HDF5_TRUE='#'
+  HAVE_EPETRAEXT_HDF5_FALSE=
+fi
+
+else
+
+
+if false ; then
+  HAVE_EPETRAEXT_HDF5_TRUE=
+  HAVE_EPETRAEXT_HDF5_FALSE='#'
+else
+  HAVE_EPETRAEXT_HDF5_TRUE='#'
+  HAVE_EPETRAEXT_HDF5_FALSE=
+fi
+
+fi
+
 # ------------------------------------------------------------------------
 # Interfaces to other Trilinos packages
 # ------------------------------------------------------------------------
+
+
+
+# Check whether --enable-teuchos or --disable-teuchos was given.
+if test "${enable_teuchos+set}" = set; then
+  enableval="$enable_teuchos"
+  ac_cv_implicit_use_teuchos=$enableval
+else
+  ac_cv_implicit_use_teuchos=no
+fi;
+
+if test "Xyes" != "Xno"; then
+  ac_cv_epetraext_using_teuchos_default=$ac_cv_implicit_use_teuchos
+else
+  ac_cv_epetraext_using_teuchos_default=no
+fi
+
+# Check whether --enable-epetraext-teuchos or --disable-epetraext-teuchos was given.
+if test "${enable_epetraext_teuchos+set}" = set; then
+  enableval="$enable_epetraext_teuchos"
+  ac_cv_use_teuchos=$enableval
+else
+  ac_cv_use_teuchos=$ac_cv_epetraext_using_teuchos_default
+fi;
+
+echo "$as_me:$LINENO: checking whether to build optional teuchos dependent code in epetraext" >&5
+echo $ECHO_N "checking whether to build optional teuchos dependent code in epetraext... $ECHO_C" >&6
+
+if test "X$ac_cv_use_teuchos" != "Xno"; then
+  echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_EPETRAEXT_TEUCHOS 1
+_ACEOF
+
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+
+
+if test "X$ac_cv_use_teuchos" = "Xyes"; then
+  BUILD_TEUCHOS_TRUE=
+  BUILD_TEUCHOS_FALSE='#'
+else
+  BUILD_TEUCHOS_TRUE='#'
+  BUILD_TEUCHOS_FALSE=
+fi
+
+
+
+
+
+if test "X$ac_cv_use_epetraext_teuchos" != "Xyes"; then
+  HAVE_EPETRAEXT_TEUCHOS_TRUE=
+  HAVE_EPETRAEXT_TEUCHOS_FALSE='#'
+else
+  HAVE_EPETRAEXT_TEUCHOS_TRUE='#'
+  HAVE_EPETRAEXT_TEUCHOS_FALSE=
+fi
+
 
 
 
@@ -9579,7 +9703,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_verb"
-(eval echo $as_me:9582: \"$ac_link\") >&5
+(eval echo $as_me:9706: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
@@ -9657,7 +9781,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_cv_prog_f77_v"
-(eval echo $as_me:9660: \"$ac_link\") >&5
+(eval echo $as_me:9784: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
@@ -13148,7 +13272,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_verb"
-(eval echo $as_me:13151: \"$ac_link\") >&5
+(eval echo $as_me:13275: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
@@ -13226,7 +13350,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_cv_prog_f77_v"
-(eval echo $as_me:13229: \"$ac_link\") >&5
+(eval echo $as_me:13353: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
@@ -13654,6 +13778,34 @@ if test -z "${BUILD_MODEL_EVALUATOR_TRUE}" && test -z "${BUILD_MODEL_EVALUATOR_F
   { { echo "$as_me:$LINENO: error: conditional \"BUILD_MODEL_EVALUATOR\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"BUILD_MODEL_EVALUATOR\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${HAVE_EPETRAEXT_HDF5_TRUE}" && test -z "${HAVE_EPETRAEXT_HDF5_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"HAVE_EPETRAEXT_HDF5\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"HAVE_EPETRAEXT_HDF5\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${HAVE_EPETRAEXT_HDF5_TRUE}" && test -z "${HAVE_EPETRAEXT_HDF5_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"HAVE_EPETRAEXT_HDF5\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"HAVE_EPETRAEXT_HDF5\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${BUILD_TEUCHOS_TRUE}" && test -z "${BUILD_TEUCHOS_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"BUILD_TEUCHOS\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"BUILD_TEUCHOS\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${HAVE_EPETRAEXT_TEUCHOS_TRUE}" && test -z "${HAVE_EPETRAEXT_TEUCHOS_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"HAVE_EPETRAEXT_TEUCHOS\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"HAVE_EPETRAEXT_TEUCHOS\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -14475,6 +14627,12 @@ s,@BUILD_BLOCK_TRUE@,$BUILD_BLOCK_TRUE,;t t
 s,@BUILD_BLOCK_FALSE@,$BUILD_BLOCK_FALSE,;t t
 s,@BUILD_MODEL_EVALUATOR_TRUE@,$BUILD_MODEL_EVALUATOR_TRUE,;t t
 s,@BUILD_MODEL_EVALUATOR_FALSE@,$BUILD_MODEL_EVALUATOR_FALSE,;t t
+s,@HAVE_EPETRAEXT_HDF5_TRUE@,$HAVE_EPETRAEXT_HDF5_TRUE,;t t
+s,@HAVE_EPETRAEXT_HDF5_FALSE@,$HAVE_EPETRAEXT_HDF5_FALSE,;t t
+s,@BUILD_TEUCHOS_TRUE@,$BUILD_TEUCHOS_TRUE,;t t
+s,@BUILD_TEUCHOS_FALSE@,$BUILD_TEUCHOS_FALSE,;t t
+s,@HAVE_EPETRAEXT_TEUCHOS_TRUE@,$HAVE_EPETRAEXT_TEUCHOS_TRUE,;t t
+s,@HAVE_EPETRAEXT_TEUCHOS_FALSE@,$HAVE_EPETRAEXT_TEUCHOS_FALSE,;t t
 s,@BUILD_TRIUTILS_TRUE@,$BUILD_TRIUTILS_TRUE,;t t
 s,@BUILD_TRIUTILS_FALSE@,$BUILD_TRIUTILS_FALSE,;t t
 s,@ENABLE_EPETRAEXT_THYRA_TRUE@,$ENABLE_EPETRAEXT_THYRA_TRUE,;t t
