Removed amesos dependence on epetraext - changing it to a can-use relationship

diff --git a/packages/amesos/configure b/packages/amesos/configure
--- a/packages/amesos/configure
+++ b/packages/amesos/configure
@@ -311,7 +311,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot MPI_TEMP_CXX MPI_CXX HAVE_MPI_TRUE HAVE_MPI_FALSE MPI_CXX_EXISTS MPI_CC_EXISTS MPI_F77_EXISTS CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE F77 FFLAGS ac_ct_F77 RANLIB ac_ct_RANLIB USE_ALTERNATE_AR_TRUE USE_ALTERNATE_AR_FALSE ALTERNATE_AR CXXCPP EGREP BUILD_TESTS_TRUE BUILD_TESTS_FALSE BUILD_EXAMPLES_TRUE BUILD_EXAMPLES_FALSE HAVE_VALGRIND_TRUE HAVE_VALGRIND_FALSE FLIBS HAVE_AMESOS_TRIUTILS_TRUE HAVE_AMESOS_TRIUTILS_FALSE BLAS_LIBS LAPACK_LIBS HAVE_AMESOS_LAPACK_TRUE HAVE_AMESOS_LAPACK_FALSE NEED_PARAMETER_LIST_TRUE NEED_PARAMETER_LIST_FALSE HAVE_AMESOS_KLU_TRUE HAVE_AMESOS_KLU_FALSE CPP HAVE_AMESOS_UMFPACK_TRUE HAVE_AMESOS_UMFPACK_FALSE HAVE_AMESOS_SUPERLU_TRUE HAVE_AMESOS_SUPERLU_FALSE HAVE_AMESOS_SUPERLUDIST_TRUE HAVE_AMESOS_SUPERLUDIST_FALSE HAVE_AMESOS_DSCPACK_TRUE HAVE_AMESOS_DSCPACK_FALSE HAVE_AMESOS_MUMPS_TRUE HAVE_AMESOS_MUMPS_FALSE HAVE_AMESOS_SMUMPS_TRUE HAVE_AMESOS_SMUMPS_FALSE HAVE_AMESOS_MERIKOS_TRUE HAVE_AMESOS_MERIKOS_FALSE HAVE_AMESOS_KUNDERT_TRUE HAVE_AMESOS_KUNDERT_FALSE TRILINOS_TEMPLATE_OBJS XTRALDADD ac_aux_dir LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot MPI_TEMP_CXX MPI_CXX HAVE_MPI_TRUE HAVE_MPI_FALSE MPI_CXX_EXISTS MPI_CC_EXISTS MPI_F77_EXISTS CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE F77 FFLAGS ac_ct_F77 RANLIB ac_ct_RANLIB USE_ALTERNATE_AR_TRUE USE_ALTERNATE_AR_FALSE ALTERNATE_AR CXXCPP EGREP BUILD_TESTS_TRUE BUILD_TESTS_FALSE BUILD_EXAMPLES_TRUE BUILD_EXAMPLES_FALSE HAVE_VALGRIND_TRUE HAVE_VALGRIND_FALSE HAVE_AMESOS_EPETRAEXT_TRUE HAVE_AMESOS_EPETRAEXT_FALSE HAVE_AMESOS_TRIUTILS_TRUE HAVE_AMESOS_TRIUTILS_FALSE FLIBS BLAS_LIBS LAPACK_LIBS HAVE_AMESOS_LAPACK_TRUE HAVE_AMESOS_LAPACK_FALSE NEED_PARAMETER_LIST_TRUE NEED_PARAMETER_LIST_FALSE HAVE_AMESOS_KLU_TRUE HAVE_AMESOS_KLU_FALSE CPP HAVE_AMESOS_UMFPACK_TRUE HAVE_AMESOS_UMFPACK_FALSE HAVE_AMESOS_SUPERLU_TRUE HAVE_AMESOS_SUPERLU_FALSE HAVE_AMESOS_SUPERLUDIST_TRUE HAVE_AMESOS_SUPERLUDIST_FALSE HAVE_AMESOS_DSCPACK_TRUE HAVE_AMESOS_DSCPACK_FALSE HAVE_AMESOS_MUMPS_TRUE HAVE_AMESOS_MUMPS_FALSE HAVE_AMESOS_SMUMPS_TRUE HAVE_AMESOS_SMUMPS_FALSE HAVE_AMESOS_MERIKOS_TRUE HAVE_AMESOS_MERIKOS_FALSE HAVE_AMESOS_KUNDERT_TRUE HAVE_AMESOS_KUNDERT_FALSE TRILINOS_TEMPLATE_OBJS XTRALDADD ac_aux_dir LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -894,12 +894,15 @@ Optional Features:
   --enable-valgrind       Use valgrind to perform memory checks and detect
                           leaks (not all packages are sensitive to this
                           option) (default is no)
+  --enable-epetraext      Allow Amesos tests and examples to use Epetraext to
+                          build matrices. Default is no. Requires Epetraext
+                          package.
+  --enable-triutils       Allow Amesos tests and examples to use Triutils to
+                          build matrices. Default is no. Requires Triutils
+                          package.
   --enable-libcheck       Check for some third-party libraries including BLAS
                           and LAPACK. (Cannot be disabled unless tests and
                           examples are also disabled.) (default is yes)
-  --enable-triutils       Enable TRIUTILS support. Triutils, a Trilinos
-                          package, is used by some Amesos examples to
-                          construct the linear system
   --enable-amesos-lapack  Enable Amesos interface support for LAPACK (default
                           is yes)
   --enable-amesos-superludist
@@ -3844,7 +3847,7 @@ fi
 
 
 # Provide some information about the compiler.
-echo "$as_me:3847:" \
+echo "$as_me:3850:" \
      "checking for Fortran 77 compiler version" >&5
 ac_compiler=`set X $ac_compile; echo $2`
 { (eval echo "$as_me:$LINENO: \"$ac_compiler --version </dev/null >&5\"") >&5
@@ -7246,6 +7249,79 @@ fi
 
 
 
+# Check whether --enable-epetraext or --disable-epetraext was given.
+if test "${enable_epetraext+set}" = set; then
+  enableval="$enable_epetraext"
+  ac_cv_use_epetraext=$enableval
+else
+  ac_cv_use_epetraext=no
+fi;
+
+echo "$as_me:$LINENO: checking whether to use epetraext" >&5
+echo $ECHO_N "checking whether to use epetraext... $ECHO_C" >&6
+
+if test "X$ac_cv_use_epetraext" != "Xno"; then
+  echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_AMESOS_EPETRAEXT
+_ACEOF
+
+else
+ echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+
+
+if test "X$ac_cv_use_epetraext" != "Xno"; then
+  HAVE_AMESOS_EPETRAEXT_TRUE=
+  HAVE_AMESOS_EPETRAEXT_FALSE='#'
+else
+  HAVE_AMESOS_EPETRAEXT_TRUE='#'
+  HAVE_AMESOS_EPETRAEXT_FALSE=
+fi
+
+
+
+
+# Check whether --enable-triutils or --disable-triutils was given.
+if test "${enable_triutils+set}" = set; then
+  enableval="$enable_triutils"
+  ac_cv_use_triutils=$enableval
+else
+  ac_cv_use_triutils=no
+fi;
+
+echo "$as_me:$LINENO: checking whether to use triutils" >&5
+echo $ECHO_N "checking whether to use triutils... $ECHO_C" >&6
+
+if test "X$ac_cv_use_triutils" != "Xno"; then
+  echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_AMESOS_TRIUTILS
+_ACEOF
+
+else
+ echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+
+
+if test "X$ac_cv_use_triutils" != "Xno"; then
+  HAVE_AMESOS_TRIUTILS_TRUE=
+  HAVE_AMESOS_TRIUTILS_FALSE='#'
+else
+  HAVE_AMESOS_TRIUTILS_TRUE='#'
+  HAVE_AMESOS_TRIUTILS_FALSE=
+fi
+
+
+
 # Check whether --enable-libcheck or --disable-libcheck was given.
 if test "${enable_libcheck+set}" = set; then
   enableval="$enable_libcheck"
@@ -7367,7 +7443,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_verb"
-(eval echo $as_me:7370: \"$ac_link\") >&5
+(eval echo $as_me:7446: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
@@ -7445,7 +7521,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_cv_prog_f77_v"
-(eval echo $as_me:7448: \"$ac_link\") >&5
+(eval echo $as_me:7524: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
@@ -8137,41 +8213,11 @@ ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
 # Interfaces to other Trilinos packages
 # ------------------------------------------------------------------------
 
-
-# Check whether --enable-triutils or --disable-triutils was given.
-if test "${enable_triutils+set}" = set; then
-  enableval="$enable_triutils"
-  ac_cv_use_triutils=$enableval
-else
-  ac_cv_use_triutils=no
-fi;
-
-echo "$as_me:$LINENO: checking whether to build optional triutils dependent code" >&5
-echo $ECHO_N "checking whether to build optional triutils dependent code... $ECHO_C" >&6
-
-if test "X$ac_cv_use_triutils" != "Xno"; then
-  echo "$as_me:$LINENO: result: yes" >&5
-echo "${ECHO_T}yes" >&6
-
-cat >>confdefs.h <<\_ACEOF
-#define HAVE_AMESOS_TRIUTILS 1
-_ACEOF
-
-else
-  echo "$as_me:$LINENO: result: no" >&5
-echo "${ECHO_T}no" >&6
-fi
-
-
-
-if test "X$ac_cv_use_triutils" = "Xyes"; then
-  HAVE_AMESOS_TRIUTILS_TRUE=
-  HAVE_AMESOS_TRIUTILS_FALSE='#'
-else
-  HAVE_AMESOS_TRIUTILS_TRUE='#'
-  HAVE_AMESOS_TRIUTILS_FALSE=
-fi
-
+# TAC_ARG_ENABLE_CAN_USE_PACKAGE(triutils, [Enable TRIUTILS support.
+# 				 Triutils, a Trilinos package, is used by
+# 				 some Amesos examples to construct the
+# 				 linear system], AMESOS_TRIUTILS)
+# AM_CONDITIONAL(HAVE_TRIUTILS, test "X$ac_cv_use_triutils" = "Xyes")
 
 # ------------------------------------------------------------------------
 # Checks for libraries
@@ -12592,7 +12638,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_verb"
-(eval echo $as_me:12595: \"$ac_link\") >&5
+(eval echo $as_me:12641: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
@@ -12670,7 +12716,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_cv_prog_f77_v"
-(eval echo $as_me:12673: \"$ac_link\") >&5
+(eval echo $as_me:12719: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
@@ -13052,6 +13098,13 @@ if test -z "${HAVE_VALGRIND_TRUE}" && test -z "${HAVE_VALGRIND_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"HAVE_VALGRIND\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"HAVE_VALGRIND\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${HAVE_AMESOS_EPETRAEXT_TRUE}" && test -z "${HAVE_AMESOS_EPETRAEXT_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"HAVE_AMESOS_EPETRAEXT\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"HAVE_AMESOS_EPETRAEXT\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -13891,9 +13944,11 @@ s,@BUILD_EXAMPLES_TRUE@,$BUILD_EXAMPLES_TRUE,;t t
 s,@BUILD_EXAMPLES_FALSE@,$BUILD_EXAMPLES_FALSE,;t t
 s,@HAVE_VALGRIND_TRUE@,$HAVE_VALGRIND_TRUE,;t t
 s,@HAVE_VALGRIND_FALSE@,$HAVE_VALGRIND_FALSE,;t t
-s,@FLIBS@,$FLIBS,;t t
+s,@HAVE_AMESOS_EPETRAEXT_TRUE@,$HAVE_AMESOS_EPETRAEXT_TRUE,;t t
+s,@HAVE_AMESOS_EPETRAEXT_FALSE@,$HAVE_AMESOS_EPETRAEXT_FALSE,;t t
 s,@HAVE_AMESOS_TRIUTILS_TRUE@,$HAVE_AMESOS_TRIUTILS_TRUE,;t t
 s,@HAVE_AMESOS_TRIUTILS_FALSE@,$HAVE_AMESOS_TRIUTILS_FALSE,;t t
+s,@FLIBS@,$FLIBS,;t t
 s,@BLAS_LIBS@,$BLAS_LIBS,;t t
 s,@LAPACK_LIBS@,$LAPACK_LIBS,;t t
 s,@HAVE_AMESOS_LAPACK_TRUE@,$HAVE_AMESOS_LAPACK_TRUE,;t t
