Added --enable-amesos-python.  Now, if amesos/python fails, then amesos can still attempt to build after inserting --disable-amesos-python.

diff --git a/packages/amesos/configure b/packages/amesos/configure
--- a/packages/amesos/configure
+++ b/packages/amesos/configure
@@ -311,7 +311,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot MPI_TEMP_CXX MPI_CXX HAVE_MPI_TRUE HAVE_MPI_FALSE MPI_CXX_EXISTS MPI_CC_EXISTS MPI_F77_EXISTS CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE F77 FFLAGS ac_ct_F77 RANLIB ac_ct_RANLIB USE_ALTERNATE_AR_TRUE USE_ALTERNATE_AR_FALSE ALTERNATE_AR CXXCPP USING_EXPORT_MAKEFILES_TRUE USING_EXPORT_MAKEFILES_FALSE PERL_EXE HAVE_PERL USING_PERL_TRUE USING_PERL_FALSE USING_GNUMAKE_TRUE USING_GNUMAKE_FALSE EGREP BUILD_TESTS_TRUE BUILD_TESTS_FALSE BUILD_EXAMPLES_TRUE BUILD_EXAMPLES_FALSE HAVE_PERFORMANCE_TRUE HAVE_PERFORMANCE_FALSE HAVE_VALGRIND_TRUE HAVE_VALGRIND_FALSE HAVE_COVERAGE_TRUE HAVE_COVERAGE_FALSE HAVE_AMESOS_EPETRAEXT_TRUE HAVE_AMESOS_EPETRAEXT_FALSE HAVE_AMESOS_TRIUTILS_TRUE HAVE_AMESOS_TRIUTILS_FALSE HAVE_AMESOS_GALERI_TRUE HAVE_AMESOS_GALERI_FALSE PYTHON_USE_TRUE PYTHON_USE_FALSE PYTHON PYTHON_PREFIX PYTHON_EXECPREFIX BUILD_PYTHON_TRUE BUILD_PYTHON_FALSE PYTHON_CSPEC PYTHON_LSPEC WITH_SWIG SWIG SWIG_LIB SWIG_PYTHON_OPT SWIG_PYTHON_CPPFLAGS HAVE_SWIG_TRUE HAVE_SWIG_FALSE GNU_HAVE_SWIG FLIBS ENABLE_AMESOS_THYRA_TRUE ENABLE_AMESOS_THYRA_FALSE BLAS_LIBS LAPACK_LIBS tac_with_trilinosdatadir HAVE_AMESOS_LAPACK_TRUE HAVE_AMESOS_LAPACK_FALSE NEED_PARAMETER_LIST_TRUE NEED_PARAMETER_LIST_FALSE HAVE_AMESOS_KLU_TRUE HAVE_AMESOS_KLU_FALSE CPP HAVE_AMESOS_UMFPACK_TRUE HAVE_AMESOS_UMFPACK_FALSE HAVE_AMESOS_SUPERLU_TRUE HAVE_AMESOS_SUPERLU_FALSE HAVE_AMESOS_SUPERLUDIST_TRUE HAVE_AMESOS_SUPERLUDIST_FALSE HAVE_AMESOS_DSCPACK_TRUE HAVE_AMESOS_DSCPACK_FALSE HAVE_AMESOS_SCALAPACK_TRUE HAVE_AMESOS_SCALAPACK_FALSE HAVE_AMESOS_MUMPS_TRUE HAVE_AMESOS_MUMPS_FALSE HAVE_AMESOS_PARDISO_TRUE HAVE_AMESOS_PARDISO_FALSE HAVE_AMESOS_PASTIX_TRUE HAVE_AMESOS_PASTIX_FALSE HAVE_AMESOS_PARAKLETE_TRUE HAVE_AMESOS_PARAKLETE_FALSE HAVE_AMESOS_TAUCS_TRUE HAVE_AMESOS_TAUCS_FALSE HAVE_AMESOS_MERIKOS_TRUE HAVE_AMESOS_MERIKOS_FALSE HAVE_AMESOS_MC64_TRUE HAVE_AMESOS_MC64_FALSE HAVE_AMESOS_KUNDERT_TRUE HAVE_AMESOS_KUNDERT_FALSE TRILINOS_TEMPLATE_OBJS XTRALDADD ac_aux_dir LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot MPI_TEMP_CXX MPI_CXX HAVE_MPI_TRUE HAVE_MPI_FALSE MPI_CXX_EXISTS MPI_CC_EXISTS MPI_F77_EXISTS CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE F77 FFLAGS ac_ct_F77 RANLIB ac_ct_RANLIB USE_ALTERNATE_AR_TRUE USE_ALTERNATE_AR_FALSE ALTERNATE_AR CXXCPP USING_EXPORT_MAKEFILES_TRUE USING_EXPORT_MAKEFILES_FALSE PERL_EXE HAVE_PERL USING_PERL_TRUE USING_PERL_FALSE USING_GNUMAKE_TRUE USING_GNUMAKE_FALSE EGREP BUILD_TESTS_TRUE BUILD_TESTS_FALSE BUILD_EXAMPLES_TRUE BUILD_EXAMPLES_FALSE HAVE_PERFORMANCE_TRUE HAVE_PERFORMANCE_FALSE HAVE_VALGRIND_TRUE HAVE_VALGRIND_FALSE HAVE_COVERAGE_TRUE HAVE_COVERAGE_FALSE HAVE_AMESOS_EPETRAEXT_TRUE HAVE_AMESOS_EPETRAEXT_FALSE HAVE_AMESOS_TRIUTILS_TRUE HAVE_AMESOS_TRIUTILS_FALSE HAVE_AMESOS_GALERI_TRUE HAVE_AMESOS_GALERI_FALSE BUILD_AMESOS_PYTHON_TRUE BUILD_AMESOS_PYTHON_FALSE PYTHON_USE_TRUE PYTHON_USE_FALSE PYTHON PYTHON_PREFIX PYTHON_EXECPREFIX BUILD_PYTHON_TRUE BUILD_PYTHON_FALSE PYTHON_CSPEC PYTHON_LSPEC WITH_SWIG SWIG SWIG_LIB SWIG_PYTHON_OPT SWIG_PYTHON_CPPFLAGS HAVE_SWIG_TRUE HAVE_SWIG_FALSE GNU_HAVE_SWIG FLIBS ENABLE_AMESOS_THYRA_TRUE ENABLE_AMESOS_THYRA_FALSE BLAS_LIBS LAPACK_LIBS tac_with_trilinosdatadir HAVE_AMESOS_LAPACK_TRUE HAVE_AMESOS_LAPACK_FALSE NEED_PARAMETER_LIST_TRUE NEED_PARAMETER_LIST_FALSE HAVE_AMESOS_KLU_TRUE HAVE_AMESOS_KLU_FALSE CPP HAVE_AMESOS_UMFPACK_TRUE HAVE_AMESOS_UMFPACK_FALSE HAVE_AMESOS_SUPERLU_TRUE HAVE_AMESOS_SUPERLU_FALSE HAVE_AMESOS_SUPERLUDIST_TRUE HAVE_AMESOS_SUPERLUDIST_FALSE HAVE_AMESOS_DSCPACK_TRUE HAVE_AMESOS_DSCPACK_FALSE HAVE_AMESOS_SCALAPACK_TRUE HAVE_AMESOS_SCALAPACK_FALSE HAVE_AMESOS_MUMPS_TRUE HAVE_AMESOS_MUMPS_FALSE HAVE_AMESOS_PARDISO_TRUE HAVE_AMESOS_PARDISO_FALSE HAVE_AMESOS_PASTIX_TRUE HAVE_AMESOS_PASTIX_FALSE HAVE_AMESOS_PARAKLETE_TRUE HAVE_AMESOS_PARAKLETE_FALSE HAVE_AMESOS_TAUCS_TRUE HAVE_AMESOS_TAUCS_FALSE HAVE_AMESOS_MERIKOS_TRUE HAVE_AMESOS_MERIKOS_FALSE HAVE_AMESOS_MC64_TRUE HAVE_AMESOS_MC64_FALSE HAVE_AMESOS_KUNDERT_TRUE HAVE_AMESOS_KUNDERT_FALSE TRILINOS_TEMPLATE_OBJS XTRALDADD ac_aux_dir LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -927,6 +927,9 @@ Optional Features:
   --enable-libcheck       Check for some third-party libraries including BLAS
                           and LAPACK. (Cannot be disabled unless tests and
                           examples are also disabled.) (default is yes)
+  --enable-amesos-python  Build Amesos Python wrappers (requires
+                          --enable-python, which is NOT set by default)
+                          (default is yes)
   --enable-python[=PYTHON]
                           absolute path name of Python executable
   --enable-thyra          Build the Thyra operator/vector adapater support in
@@ -3897,7 +3900,7 @@ fi
 
 
 # Provide some information about the compiler.
-echo "$as_me:3900:" \
+echo "$as_me:3903:" \
      "checking for Fortran 77 compiler version" >&5
 ac_compiler=`set X $ac_compile; echo $2`
 { (eval echo "$as_me:$LINENO: \"$ac_compiler --version </dev/null >&5\"") >&5
@@ -7737,6 +7740,41 @@ fi
 # Enable optional python wrappers
 # ------------------------------------------------------------------------
 
+# Check whether --enable-amesos-python or --disable-amesos-python was given.
+if test "${enable_amesos_python+set}" = set; then
+  enableval="$enable_amesos_python"
+  ac_cv_use_amesos_python=$enableval
+else
+  ac_cv_use_amesos_python=yes
+fi;
+
+echo "$as_me:$LINENO: checking whether to use amesos-python" >&5
+echo $ECHO_N "checking whether to use amesos-python... $ECHO_C" >&6
+
+if test "X$ac_cv_use_amesos_python" != "Xno"; then
+  echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_AMESOS_PYTHON
+_ACEOF
+
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+
+
+if test "X$ac_cv_use_amesos_python" != "Xno"; then
+  BUILD_AMESOS_PYTHON_TRUE=
+  BUILD_AMESOS_PYTHON_FALSE='#'
+else
+  BUILD_AMESOS_PYTHON_TRUE='#'
+  BUILD_AMESOS_PYTHON_FALSE=
+fi
+
+
 
     az_python_use=false
 
@@ -8757,7 +8795,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_verb"
-(eval echo $as_me:8760: \"$ac_link\") >&5
+(eval echo $as_me:8798: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
@@ -8835,7 +8873,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_cv_prog_f77_v"
-(eval echo $as_me:8838: \"$ac_link\") >&5
+(eval echo $as_me:8876: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
@@ -14312,7 +14350,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_verb"
-(eval echo $as_me:14315: \"$ac_link\") >&5
+(eval echo $as_me:14353: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
@@ -14390,7 +14428,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_cv_prog_f77_v"
-(eval echo $as_me:14393: \"$ac_link\") >&5
+(eval echo $as_me:14431: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
@@ -14828,6 +14866,13 @@ if test -z "${HAVE_AMESOS_GALERI_TRUE}" && test -z "${HAVE_AMESOS_GALERI_FALSE}"
   { { echo "$as_me:$LINENO: error: conditional \"HAVE_AMESOS_GALERI\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"HAVE_AMESOS_GALERI\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${BUILD_AMESOS_PYTHON_TRUE}" && test -z "${BUILD_AMESOS_PYTHON_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"BUILD_AMESOS_PYTHON\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"BUILD_AMESOS_PYTHON\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -15875,6 +15920,8 @@ s,@HAVE_AMESOS_TRIUTILS_TRUE@,$HAVE_AMESOS_TRIUTILS_TRUE,;t t
 s,@HAVE_AMESOS_TRIUTILS_FALSE@,$HAVE_AMESOS_TRIUTILS_FALSE,;t t
 s,@HAVE_AMESOS_GALERI_TRUE@,$HAVE_AMESOS_GALERI_TRUE,;t t
 s,@HAVE_AMESOS_GALERI_FALSE@,$HAVE_AMESOS_GALERI_FALSE,;t t
+s,@BUILD_AMESOS_PYTHON_TRUE@,$BUILD_AMESOS_PYTHON_TRUE,;t t
+s,@BUILD_AMESOS_PYTHON_FALSE@,$BUILD_AMESOS_PYTHON_FALSE,;t t
 s,@PYTHON_USE_TRUE@,$PYTHON_USE_TRUE,;t t
 s,@PYTHON_USE_FALSE@,$PYTHON_USE_FALSE,;t t
 s,@PYTHON@,$PYTHON,;t t
