Merging back changes from the release branch.  There is now a configure time check for mpi when Paraklete is enabled.  Paraklete cannot build without mpi, so now the configure will fail if a users tries to do that.

diff --git a/packages/amesos/configure b/packages/amesos/configure
--- a/packages/amesos/configure
+++ b/packages/amesos/configure
@@ -3142,7 +3142,6 @@ echo "$as_me: error: MPI Fortran 77 compiler (${MPI_F77}) not found." >&2;}
 fi
 
 
-
 # ------------------------------------------------------------------------
 # Checks for programs
 # ------------------------------------------------------------------------
@@ -13700,6 +13699,13 @@ fi
 #  =========  #
 
 if test "X$ac_cv_use_amesos_paraklete" != "Xno"; then
+
+  # paraklete cannot be enabled if mpi is not enabled.
+  if test "X${HAVE_PKG_MPI}" != "Xyes"; then
+    { { echo "$as_me:$LINENO: error: Paraklete CANNOT be built because MPI is required!" >&5
+echo "$as_me: error: Paraklete CANNOT be built because MPI is required!" >&2;}
+   { (exit 1); exit 1; }; }
+  fi
 
   if test "X$ac_cv_use_amesos_tests" != "Xno" || test "X$ac_cv_use_amesos_examples" != "Xno" || test "X$ac_cv_use_libcheck" != "Xno"; then
 
