Amesos/SuperludistOO 1.0 now works on Atlantis from ./configure

diff --git a/packages/amesos/configure b/packages/amesos/configure
--- a/packages/amesos/configure
+++ b/packages/amesos/configure
@@ -2103,6 +2103,7 @@ echo "$as_me: error: MPI Fortran 77 compiler (${MPI_F77}) not found." >&2;}
 fi
 
 
+
 # ------------------------------------------------------------------------
 # Checks for programs
 # ------------------------------------------------------------------------
@@ -3242,7 +3243,7 @@ fi
 
 
 # Provide some information about the compiler.
-echo "$as_me:3245:" \
+echo "$as_me:3246:" \
      "checking for Fortran 77 compiler version" >&5
 ac_compiler=`set X $ac_compile; echo $2`
 { (eval echo "$as_me:$LINENO: \"$ac_compiler --version </dev/null >&5\"") >&5
@@ -5524,7 +5525,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_verb"
-(eval echo $as_me:5527: \"$ac_link\") >&5
+(eval echo $as_me:5528: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
@@ -5603,7 +5604,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_cv_prog_f77_v"
-(eval echo $as_me:5606: \"$ac_link\") >&5
+(eval echo $as_me:5607: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
@@ -6246,6 +6247,12 @@ ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $
 ac_compiler_gnu=$ac_cv_c_compiler_gnu
 
 
+  if test "X${HAVE_PKG_MPI}" != "Xyes"; then
+    { { echo "$as_me:$LINENO: error: Amesos/SuperludistOO requires MPI." >&5
+echo "$as_me: error: Amesos/SuperludistOO requires MPI." >&2;}
+   { (exit 1); exit 1; }; }
+  fi
+
 
 
 # Check whether --with-amesos-sluddir or --without-amesos-sluddir was given.
@@ -6396,7 +6403,7 @@ fi
 
     SAVE_LIBS="${LIBS}"
     LIBS="${tac_with_amesos_sludlib} ${LIBS}"
-    cat >conftest.$ac_ext <<_ACEOF
+     cat >conftest.$ac_ext <<_ACEOF
 #line $LINENO "configure"
 #include "confdefs.h"
 
@@ -8011,7 +8018,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_verb"
-(eval echo $as_me:8014: \"$ac_link\") >&5
+(eval echo $as_me:8021: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
@@ -8090,7 +8097,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_cv_prog_f77_v"
-(eval echo $as_me:8093: \"$ac_link\") >&5
+(eval echo $as_me:8100: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
