bootstrap for new configure.ac

diff --git a/packages/amesos/configure b/packages/amesos/configure
--- a/packages/amesos/configure
+++ b/packages/amesos/configure
@@ -311,7 +311,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot MPI_TEMP_CXX MPI_CXX HAVE_MPI_TRUE HAVE_MPI_FALSE MPI_CXX_EXISTS MPI_CC_EXISTS MPI_F77_EXISTS CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE F77 FFLAGS ac_ct_F77 RANLIB ac_ct_RANLIB USE_ALTERNATE_AR_TRUE USE_ALTERNATE_AR_FALSE ALTERNATE_AR CXXCPP EGREP BUILD_TESTS_TRUE BUILD_TESTS_FALSE BUILD_EXAMPLES_TRUE BUILD_EXAMPLES_FALSE HAVE_VALGRIND_TRUE HAVE_VALGRIND_FALSE FLIBS BLAS_LIBS LAPACK_LIBS NEED_PARAMETER_LIST_TRUE NEED_PARAMETER_LIST_FALSE HAVE_AMESOS_KLU_TRUE HAVE_AMESOS_KLU_FALSE CPP HAVE_AMESOS_UMFPACK_TRUE HAVE_AMESOS_UMFPACK_FALSE HAVE_AMESOS_SUPERLU_TRUE HAVE_AMESOS_SUPERLU_FALSE HAVE_AMESOS_SUPERLUDIST_TRUE HAVE_AMESOS_SUPERLUDIST_FALSE HAVE_AMESOS_DSCPACK_TRUE HAVE_AMESOS_DSCPACK_FALSE HAVE_AMESOS_SCALAPACK_TRUE HAVE_AMESOS_SCALAPACK_FALSE HAVE_AMESOS_MUMPS_TRUE HAVE_AMESOS_MUMPS_FALSE HAVE_AMESOS_SMUMPS_TRUE HAVE_AMESOS_SMUMPS_FALSE HAVE_AMESOS_MERIKOS_TRUE HAVE_AMESOS_MERIKOS_FALSE HAVE_AMESOS_KUNDERT_TRUE HAVE_AMESOS_KUNDERT_FALSE TRILINOS_TEMPLATE_OBJS XTRALDADD ac_aux_dir LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot MPI_TEMP_CXX MPI_CXX HAVE_MPI_TRUE HAVE_MPI_FALSE MPI_CXX_EXISTS MPI_CC_EXISTS MPI_F77_EXISTS CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE F77 FFLAGS ac_ct_F77 RANLIB ac_ct_RANLIB USE_ALTERNATE_AR_TRUE USE_ALTERNATE_AR_FALSE ALTERNATE_AR CXXCPP EGREP BUILD_TESTS_TRUE BUILD_TESTS_FALSE BUILD_EXAMPLES_TRUE BUILD_EXAMPLES_FALSE HAVE_VALGRIND_TRUE HAVE_VALGRIND_FALSE FLIBS HAVE_AMESOS_TRIUTILS_TRUE HAVE_AMESOS_TRIUTILS_FALSE BLAS_LIBS LAPACK_LIBS HAVE_AMESOS_LAPACK_TRUE HAVE_AMESOS_LAPACK_FALSE NEED_PARAMETER_LIST_TRUE NEED_PARAMETER_LIST_FALSE HAVE_AMESOS_KLU_TRUE HAVE_AMESOS_KLU_FALSE CPP HAVE_AMESOS_UMFPACK_TRUE HAVE_AMESOS_UMFPACK_FALSE HAVE_AMESOS_SUPERLU_TRUE HAVE_AMESOS_SUPERLU_FALSE HAVE_AMESOS_SUPERLUDIST_TRUE HAVE_AMESOS_SUPERLUDIST_FALSE HAVE_AMESOS_DSCPACK_TRUE HAVE_AMESOS_DSCPACK_FALSE HAVE_AMESOS_SCALAPACK_TRUE HAVE_AMESOS_SCALAPACK_FALSE HAVE_AMESOS_MUMPS_TRUE HAVE_AMESOS_MUMPS_FALSE HAVE_AMESOS_SMUMPS_TRUE HAVE_AMESOS_SMUMPS_FALSE HAVE_AMESOS_MERIKOS_TRUE HAVE_AMESOS_MERIKOS_FALSE HAVE_AMESOS_KUNDERT_TRUE HAVE_AMESOS_KUNDERT_FALSE TRILINOS_TEMPLATE_OBJS XTRALDADD ac_aux_dir LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -897,6 +897,17 @@ Optional Features:
   --enable-libcheck       Check for some third-party libraries including BLAS
                           and LAPACK. (Cannot be disabled unless tests and
                           examples are also disabled.) (default is yes)
+  --enable-default-packages
+                          Build all default packages unless explicitly
+                          disabled. When this option is disabled, only
+                          packages explicitly enabled and packages needed to
+                          satisfy the dependencies of enabled packages will be
+                          built (default is yes)
+  --enable-triutils       Enable TRIUTILS support. Triutils, a Trilinos
+                          package, is used if some Amesos examples to
+                          construct the linear system (default is no)
+  --enable-amesos-lapack  Enable Amesos interface support for LAPACK (default
+                          is yes)
   --enable-amesos-superludist
                           Enable Amesos interface support for SuperLU Dist
                           (default is no)
@@ -3846,7 +3857,7 @@ fi
 
 
 # Provide some information about the compiler.
-echo "$as_me:3849:" \
+echo "$as_me:3860:" \
      "checking for Fortran 77 compiler version" >&5
 ac_compiler=`set X $ac_compile; echo $2`
 { (eval echo "$as_me:$LINENO: \"$ac_compiler --version </dev/null >&5\"") >&5
@@ -7369,7 +7380,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_verb"
-(eval echo $as_me:7372: \"$ac_link\") >&5
+(eval echo $as_me:7383: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
@@ -7447,7 +7458,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_cv_prog_f77_v"
-(eval echo $as_me:7450: \"$ac_link\") >&5
+(eval echo $as_me:7461: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
@@ -8133,6 +8144,72 @@ ac_cpp='$CXXCPP $CPPFLAGS'
 ac_compile='$CXX -c $CXXFLAGS $CPPFLAGS conftest.$ac_ext >&5'
 ac_link='$CXX -o conftest$ac_exeext $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
 ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
+
+
+# ------------------------------------------------------------------------
+# Interfaces to other Trilinos packages
+# ------------------------------------------------------------------------
+
+
+# Check whether --enable-default-packages or --disable-default-packages was given.
+if test "${enable_default_packages+set}" = set; then
+  enableval="$enable_default_packages"
+  ac_cv_use_default_packages=$enableval
+else
+  ac_cv_use_default_packages=yes
+fi;
+
+echo "$as_me:$LINENO: checking whether to use default-packages" >&5
+echo $ECHO_N "checking whether to use default-packages... $ECHO_C" >&6
+
+if test "X$ac_cv_use_default_packages" != "Xno"; then
+  echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_DEFAULT_PACKAGES
+_ACEOF
+
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+
+
+# Check whether --enable-triutils or --disable-triutils was given.
+if test "${enable_triutils+set}" = set; then
+  enableval="$enable_triutils"
+  ac_cv_use_triutils=$enableval
+else
+  ac_cv_use_triutils=no
+fi;
+
+echo "$as_me:$LINENO: checking whether to use triutils" >&5
+echo $ECHO_N "checking whether to use triutils... $ECHO_C" >&6
+
+if test "X$ac_cv_use_triutils" != "Xno"; then
+  echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_AMESOS_TRIUTILS 1
+_ACEOF
+
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+
+
+if test "X$ac_cv_use_triutils" = "Xyes"; then
+  HAVE_AMESOS_TRIUTILS_TRUE=
+  HAVE_AMESOS_TRIUTILS_FALSE='#'
+else
+  HAVE_AMESOS_TRIUTILS_TRUE='#'
+  HAVE_AMESOS_TRIUTILS_FALSE=
+fi
 
 
 # ------------------------------------------------------------------------
@@ -9970,6 +10047,42 @@ fi
 # ------------------------------------------------------------------------
 # Checks for addons
 # ------------------------------------------------------------------------
+
+
+# Check whether --enable-amesos-lapack or --disable-amesos-lapack was given.
+if test "${enable_amesos_lapack+set}" = set; then
+  enableval="$enable_amesos_lapack"
+  ac_cv_use_amesos_lapack=$enableval
+else
+  ac_cv_use_amesos_lapack=yes
+fi;
+
+echo "$as_me:$LINENO: checking whether to use amesos-lapack" >&5
+echo $ECHO_N "checking whether to use amesos-lapack... $ECHO_C" >&6
+
+if test "X$ac_cv_use_amesos_lapack" != "Xno"; then
+  echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_AMESOS_LAPACK
+_ACEOF
+
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+
+
+if true ; then
+  HAVE_AMESOS_LAPACK_TRUE=
+  HAVE_AMESOS_LAPACK_FALSE='#'
+else
+  HAVE_AMESOS_LAPACK_TRUE='#'
+  HAVE_AMESOS_LAPACK_FALSE=
+fi
+
 
 
 # Check whether --enable-amesos-superludist or --disable-amesos-superludist was given.
@@ -12619,7 +12732,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_verb"
-(eval echo $as_me:12622: \"$ac_link\") >&5
+(eval echo $as_me:12735: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
@@ -12697,7 +12810,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_cv_prog_f77_v"
-(eval echo $as_me:12700: \"$ac_link\") >&5
+(eval echo $as_me:12813: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
@@ -12918,7 +13031,7 @@ fi
 # ------------------------------------------------------------------------
 ##
 #
-                                                                                                                                  ac_config_files="$ac_config_files Makefile src/Makefile test/Makefile example/Makefile example/AmesosDscpack/Makefile example/AmesosFactory/Makefile example/AmesosSuperludist/Makefile test/TestOptions/Makefile test/TestWithTriutils/Makefile test/scripts/Makefile test/scripts/daily/Makefile test/scripts/daily/mpi/Makefile test/scripts/daily/serial/Makefile"
+                                                                                                                                                                                                        ac_config_files="$ac_config_files Makefile src/Makefile test/Makefile example/Makefile test/Test_Epetra_RowMatrix/Makefile test/Test_Epetra_CrsMatrix/Makefile test/Test_Epetra_VbrMatrix/Makefile test/Test_MultipleSolves/Makefile test/Test_Detailed/Makefile test/Test_LAPACK/Makefile test/Test_KLU/Makefile test/Test_UMFPACK/Makefile test/Test_MUMPS/Makefile test/Test_SuperLU/Makefile test/Test_SuperLU_DIST/Makefile test/Test_DSCPACK/Makefile test/scripts/Makefile test/scripts/daily/Makefile test/scripts/daily/mpi/Makefile test/scripts/daily/serial/Makefile"
 
 
 cat >confcache <<\_ACEOF
@@ -13079,6 +13192,20 @@ if test -z "${HAVE_VALGRIND_TRUE}" && test -z "${HAVE_VALGRIND_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"HAVE_VALGRIND\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"HAVE_VALGRIND\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${HAVE_AMESOS_TRIUTILS_TRUE}" && test -z "${HAVE_AMESOS_TRIUTILS_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"HAVE_AMESOS_TRIUTILS\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"HAVE_AMESOS_TRIUTILS\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${HAVE_AMESOS_LAPACK_TRUE}" && test -z "${HAVE_AMESOS_LAPACK_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"HAVE_AMESOS_LAPACK\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"HAVE_AMESOS_LAPACK\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -13740,11 +13867,18 @@ do
   "src/Makefile" ) CONFIG_FILES="$CONFIG_FILES src/Makefile" ;;
   "test/Makefile" ) CONFIG_FILES="$CONFIG_FILES test/Makefile" ;;
   "example/Makefile" ) CONFIG_FILES="$CONFIG_FILES example/Makefile" ;;
-  "example/AmesosDscpack/Makefile" ) CONFIG_FILES="$CONFIG_FILES example/AmesosDscpack/Makefile" ;;
-  "example/AmesosFactory/Makefile" ) CONFIG_FILES="$CONFIG_FILES example/AmesosFactory/Makefile" ;;
-  "example/AmesosSuperludist/Makefile" ) CONFIG_FILES="$CONFIG_FILES example/AmesosSuperludist/Makefile" ;;
-  "test/TestOptions/Makefile" ) CONFIG_FILES="$CONFIG_FILES test/TestOptions/Makefile" ;;
-  "test/TestWithTriutils/Makefile" ) CONFIG_FILES="$CONFIG_FILES test/TestWithTriutils/Makefile" ;;
+  "test/Test_Epetra_RowMatrix/Makefile" ) CONFIG_FILES="$CONFIG_FILES test/Test_Epetra_RowMatrix/Makefile" ;;
+  "test/Test_Epetra_CrsMatrix/Makefile" ) CONFIG_FILES="$CONFIG_FILES test/Test_Epetra_CrsMatrix/Makefile" ;;
+  "test/Test_Epetra_VbrMatrix/Makefile" ) CONFIG_FILES="$CONFIG_FILES test/Test_Epetra_VbrMatrix/Makefile" ;;
+  "test/Test_MultipleSolves/Makefile" ) CONFIG_FILES="$CONFIG_FILES test/Test_MultipleSolves/Makefile" ;;
+  "test/Test_Detailed/Makefile" ) CONFIG_FILES="$CONFIG_FILES test/Test_Detailed/Makefile" ;;
+  "test/Test_LAPACK/Makefile" ) CONFIG_FILES="$CONFIG_FILES test/Test_LAPACK/Makefile" ;;
+  "test/Test_KLU/Makefile" ) CONFIG_FILES="$CONFIG_FILES test/Test_KLU/Makefile" ;;
+  "test/Test_UMFPACK/Makefile" ) CONFIG_FILES="$CONFIG_FILES test/Test_UMFPACK/Makefile" ;;
+  "test/Test_MUMPS/Makefile" ) CONFIG_FILES="$CONFIG_FILES test/Test_MUMPS/Makefile" ;;
+  "test/Test_SuperLU/Makefile" ) CONFIG_FILES="$CONFIG_FILES test/Test_SuperLU/Makefile" ;;
+  "test/Test_SuperLU_DIST/Makefile" ) CONFIG_FILES="$CONFIG_FILES test/Test_SuperLU_DIST/Makefile" ;;
+  "test/Test_DSCPACK/Makefile" ) CONFIG_FILES="$CONFIG_FILES test/Test_DSCPACK/Makefile" ;;
   "test/scripts/Makefile" ) CONFIG_FILES="$CONFIG_FILES test/scripts/Makefile" ;;
   "test/scripts/daily/Makefile" ) CONFIG_FILES="$CONFIG_FILES test/scripts/daily/Makefile" ;;
   "test/scripts/daily/mpi/Makefile" ) CONFIG_FILES="$CONFIG_FILES test/scripts/daily/mpi/Makefile" ;;
@@ -13917,8 +14051,12 @@ s,@BUILD_EXAMPLES_FALSE@,$BUILD_EXAMPLES_FALSE,;t t
 s,@HAVE_VALGRIND_TRUE@,$HAVE_VALGRIND_TRUE,;t t
 s,@HAVE_VALGRIND_FALSE@,$HAVE_VALGRIND_FALSE,;t t
 s,@FLIBS@,$FLIBS,;t t
+s,@HAVE_AMESOS_TRIUTILS_TRUE@,$HAVE_AMESOS_TRIUTILS_TRUE,;t t
+s,@HAVE_AMESOS_TRIUTILS_FALSE@,$HAVE_AMESOS_TRIUTILS_FALSE,;t t
 s,@BLAS_LIBS@,$BLAS_LIBS,;t t
 s,@LAPACK_LIBS@,$LAPACK_LIBS,;t t
+s,@HAVE_AMESOS_LAPACK_TRUE@,$HAVE_AMESOS_LAPACK_TRUE,;t t
+s,@HAVE_AMESOS_LAPACK_FALSE@,$HAVE_AMESOS_LAPACK_FALSE,;t t
 s,@NEED_PARAMETER_LIST_TRUE@,$NEED_PARAMETER_LIST_TRUE,;t t
 s,@NEED_PARAMETER_LIST_FALSE@,$NEED_PARAMETER_LIST_FALSE,;t t
 s,@HAVE_AMESOS_KLU_TRUE@,$HAVE_AMESOS_KLU_TRUE,;t t
