----------------------------------------------------------------------  Modified Files:  	Trilinos_config.h.in configure configure.ac  	packages/Makefile.am packages/Makefile.in  ----------------------------------------------------------------------
Integrating the Tpetra package into the Trilinos autoconf/automake system. Tpetra is disabled by default.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -290,7 +290,8 @@ ac_subdirs_all="$ac_subdirs_all packages/meros"
 ac_subdirs_all="$ac_subdirs_all packages/nox"
 ac_subdirs_all="$ac_subdirs_all packages/ml"
 ac_subdirs_all="$ac_subdirs_all packages/new_package"
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM AWK SET_MAKE BUILD_AMESOS_TRUE BUILD_AMESOS_FALSE BUILD_NOX_TRUE BUILD_NOX_FALSE BUILD_MEROS_TRUE BUILD_MEROS_FALSE BUILD_TSF_TRUE BUILD_TSF_FALSE BUILD_TSFCORE_TRUE BUILD_TSFCORE_FALSE BUILD_TSFCOREUTILS_TRUE BUILD_TSFCOREUTILS_FALSE BUILD_KOMPLEX_TRUE BUILD_KOMPLEX_FALSE BUILD_AZTECOO_TRUE BUILD_AZTECOO_FALSE BUILD_BELOS_TRUE BUILD_BELOS_FALSE BUILD_ANASAZI_TRUE BUILD_ANASAZI_FALSE BUILD_IFPACK_TRUE BUILD_IFPACK_FALSE BUILD_TRIUTILS_TRUE BUILD_TRIUTILS_FALSE BUILD_EPETRAEXT_TRUE BUILD_EPETRAEXT_FALSE BUILD_TEUCHOS_TRUE BUILD_TEUCHOS_FALSE BUILD_ML_TRUE BUILD_ML_FALSE BUILD_NEW_PACKAGE_TRUE BUILD_NEW_PACKAGE_FALSE subdirs BUILD_EPETRA_TRUE BUILD_EPETRA_FALSE LIBOBJS LTLIBOBJS'
+ac_subdirs_all="$ac_subdirs_all packages/tpetra"
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM AWK SET_MAKE BUILD_AMESOS_TRUE BUILD_AMESOS_FALSE BUILD_NOX_TRUE BUILD_NOX_FALSE BUILD_MEROS_TRUE BUILD_MEROS_FALSE BUILD_TSF_TRUE BUILD_TSF_FALSE BUILD_TSFCORE_TRUE BUILD_TSFCORE_FALSE BUILD_TSFCOREUTILS_TRUE BUILD_TSFCOREUTILS_FALSE BUILD_KOMPLEX_TRUE BUILD_KOMPLEX_FALSE BUILD_AZTECOO_TRUE BUILD_AZTECOO_FALSE BUILD_BELOS_TRUE BUILD_BELOS_FALSE BUILD_ANASAZI_TRUE BUILD_ANASAZI_FALSE BUILD_IFPACK_TRUE BUILD_IFPACK_FALSE BUILD_TRIUTILS_TRUE BUILD_TRIUTILS_FALSE BUILD_EPETRAEXT_TRUE BUILD_EPETRAEXT_FALSE BUILD_TPETRA_TRUE BUILD_TPETRA_FALSE BUILD_TEUCHOS_TRUE BUILD_TEUCHOS_FALSE BUILD_ML_TRUE BUILD_ML_FALSE BUILD_NEW_PACKAGE_TRUE BUILD_NEW_PACKAGE_FALSE subdirs BUILD_EPETRA_TRUE BUILD_EPETRA_FALSE LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -823,6 +824,7 @@ Optional Features:
   --enable-ifpack         Build ifpack (default is yes)
   --enable-triutils       Build triutils (default is no)
   --enable-epetraext      Build epetraext (default is yes)
+  --enable-tpetra         Build tpetra (default is no)
   --enable-teuchos        Build teuchos (default is no)
   --enable-ml             Build ml (default is yes)
   --enable-new_package    Build new_package (default is yes)
@@ -2188,6 +2190,42 @@ fi
 
 
 
+# Check whether --enable-tpetra or --disable-tpetra was given.
+if test "${enable_tpetra+set}" = set; then
+  enableval="$enable_tpetra"
+  ac_cv_use_tpetra=$enableval
+else
+  ac_cv_use_tpetra=no
+fi;
+
+echo "$as_me:$LINENO: checking whether to use tpetra" >&5
+echo $ECHO_N "checking whether to use tpetra... $ECHO_C" >&6
+
+if test "X$ac_cv_use_tpetra" != "Xno"; then
+  echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_TPETRA
+_ACEOF
+
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+
+
+if test "X$ac_cv_use_tpetra" != "Xno"; then
+  BUILD_TPETRA_TRUE=
+  BUILD_TPETRA_FALSE='#'
+else
+  BUILD_TPETRA_TRUE='#'
+  BUILD_TPETRA_FALSE=
+fi
+
+
+
 # Check whether --enable-teuchos or --disable-teuchos was given.
 if test "${enable_teuchos+set}" = set; then
   enableval="$enable_teuchos"
@@ -2215,6 +2253,7 @@ fi
 
 
 if test "X$ac_cv_use_teuchos" != "Xno" ||
+	test "X$ac_cv_use_tpetra" != "Xno" ||
 	test "X$ac_cv_use_belos" != "Xno" ||
 	test "X$ac_cv_use_anasazi" != "Xno"; then
   BUILD_TEUCHOS_TRUE=
@@ -2299,8 +2338,8 @@ fi
 
 
 
-
 if test "X$ac_cv_use_teuchos" != "Xno" ||
+	test "X$ac_cv_use_tpetra" != "Xno" ||
 	test "X$ac_cv_use_anasazi" != "Xno" ||
 	test "X$ac_cv_use_belos" != "Xno"; then
 
@@ -2486,6 +2525,13 @@ if test "X$ac_cv_use_new_package" != "Xno"; then
 
 
 subdirs="$subdirs packages/new_package"
+
+fi
+
+if test "X$ac_cv_use_tpetra" != "Xno"; then
+
+
+subdirs="$subdirs packages/tpetra"
 
 fi
 
@@ -2682,6 +2728,13 @@ if test -z "${BUILD_EPETRAEXT_TRUE}" && test -z "${BUILD_EPETRAEXT_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"BUILD_EPETRAEXT\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"BUILD_EPETRAEXT\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${BUILD_TPETRA_TRUE}" && test -z "${BUILD_TPETRA_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"BUILD_TPETRA\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"BUILD_TPETRA\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -3279,6 +3332,8 @@ s,@BUILD_TRIUTILS_TRUE@,$BUILD_TRIUTILS_TRUE,;t t
 s,@BUILD_TRIUTILS_FALSE@,$BUILD_TRIUTILS_FALSE,;t t
 s,@BUILD_EPETRAEXT_TRUE@,$BUILD_EPETRAEXT_TRUE,;t t
 s,@BUILD_EPETRAEXT_FALSE@,$BUILD_EPETRAEXT_FALSE,;t t
+s,@BUILD_TPETRA_TRUE@,$BUILD_TPETRA_TRUE,;t t
+s,@BUILD_TPETRA_FALSE@,$BUILD_TPETRA_FALSE,;t t
 s,@BUILD_TEUCHOS_TRUE@,$BUILD_TEUCHOS_TRUE,;t t
 s,@BUILD_TEUCHOS_FALSE@,$BUILD_TEUCHOS_FALSE,;t t
 s,@BUILD_ML_TRUE@,$BUILD_ML_TRUE,;t t
