Added Zoltan to the top level build system and the tarball creation test script.  I verified that I could build Zoltan from the top level.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -716,6 +716,8 @@ BUILD_DIDASKO_TRUE
 BUILD_DIDASKO_FALSE
 BUILD_WEBTRILINOS_TRUE
 BUILD_WEBTRILINOS_FALSE
+BUILD_ZOLTAN_TRUE
+BUILD_ZOLTAN_FALSE
 BUILD_FORTRILINOS_TRUE
 BUILD_FORTRILINOS_FALSE
 BUILD_EXTERNAL_TRUE
@@ -765,6 +767,7 @@ packages/tpetra
 packages/trilinoscouplings
 packages/didasko
 packages/WebTrilinos
+packages/zoltan
 packages/ForTrilinos
 packages/external
 packages/moocho'
@@ -1437,6 +1440,8 @@ Optional Features:
   --enable-galeri         Build galeri, a gallery package (default is no)
   --enable-webtrilinos    Build WebTrilinos, a web interface package (default
                           is no)
+  --enable-zoltan         Build zoltan, a partitioning and load balancing
+                          package (default is no)
   --enable-shared         Build shared libraries in addition to static
                           libraries (default is no)
   --enable-aztecoo-teuchos
@@ -3683,6 +3688,34 @@ fi
 
 
 
+# Check whether --enable-zoltan was given.
+if test "${enable_zoltan+set}" = set; then
+  enableval=$enable_zoltan; ac_cv_use_zoltan=$enableval
+ac_cv_use_zoltan_explicit=$enableval
+else
+  ac_cv_use_zoltan=no
+ac_cv_use_zoltan_explicit=no
+fi
+
+
+{ echo "$as_me:$LINENO: checking whether to use zoltan" >&5
+echo $ECHO_N "checking whether to use zoltan... $ECHO_C" >&6; }
+
+if test "X$ac_cv_use_zoltan" != "Xno"; then
+  { echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6; }
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_ZOLTAN
+_ACEOF
+
+else
+  { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+fi
+
+
+
 # Check whether --enable-shared was given.
 if test "${enable_shared+set}" = set; then
   enableval=$enable_shared; ac_cv_use_shared=$enableval
@@ -4515,6 +4548,25 @@ else
 fi
 
 
+if test "X$ac_cv_use_zoltan" != "Xno"; then
+  subdirs="$subdirs packages/zoltan"
+
+  BUILD_ZOLTAN=yes
+  if test "X$ac_cv_use_zoltan_explicit" != "Xyes"; then
+    ac_configure_args="$ac_configure_args --enable-zoltan"
+  fi
+else
+  BUILD_ZOLTAN=no
+fi
+ if test "X$BUILD_ZOLTAN" != "Xno"; then
+  BUILD_ZOLTAN_TRUE=
+  BUILD_ZOLTAN_FALSE='#'
+else
+  BUILD_ZOLTAN_TRUE='#'
+  BUILD_ZOLTAN_FALSE=
+fi
+
+
 if test "X$ac_cv_use_fortrilinos" != "Xno"; then
   subdirs="$subdirs packages/ForTrilinos"
 
@@ -4938,6 +4990,13 @@ if test -z "${BUILD_WEBTRILINOS_TRUE}" && test -z "${BUILD_WEBTRILINOS_FALSE}"; 
   { { echo "$as_me:$LINENO: error: conditional \"BUILD_WEBTRILINOS\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"BUILD_WEBTRILINOS\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${BUILD_ZOLTAN_TRUE}" && test -z "${BUILD_ZOLTAN_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"BUILD_ZOLTAN\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"BUILD_ZOLTAN\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -5663,6 +5722,8 @@ BUILD_DIDASKO_TRUE!$BUILD_DIDASKO_TRUE$ac_delim
 BUILD_DIDASKO_FALSE!$BUILD_DIDASKO_FALSE$ac_delim
 BUILD_WEBTRILINOS_TRUE!$BUILD_WEBTRILINOS_TRUE$ac_delim
 BUILD_WEBTRILINOS_FALSE!$BUILD_WEBTRILINOS_FALSE$ac_delim
+BUILD_ZOLTAN_TRUE!$BUILD_ZOLTAN_TRUE$ac_delim
+BUILD_ZOLTAN_FALSE!$BUILD_ZOLTAN_FALSE$ac_delim
 BUILD_FORTRILINOS_TRUE!$BUILD_FORTRILINOS_TRUE$ac_delim
 BUILD_FORTRILINOS_FALSE!$BUILD_FORTRILINOS_FALSE$ac_delim
 BUILD_EXTERNAL_TRUE!$BUILD_EXTERNAL_TRUE$ac_delim
@@ -5673,7 +5734,7 @@ LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 48; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 50; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
