Added --enable-galeri to the top level configure. This should fix some of the IFPACK's failures in the test harness.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -280,6 +280,7 @@ ac_subdirs_all="$ac_subdirs_all packages/kokkos"
 ac_subdirs_all="$ac_subdirs_all packages/epetra"
 ac_subdirs_all="$ac_subdirs_all packages/pliris"
 ac_subdirs_all="$ac_subdirs_all packages/triutils"
+ac_subdirs_all="$ac_subdirs_all packages/galeri"
 ac_subdirs_all="$ac_subdirs_all packages/ifpack"
 ac_subdirs_all="$ac_subdirs_all packages/aztecoo"
 ac_subdirs_all="$ac_subdirs_all packages/claps"
@@ -301,7 +302,7 @@ ac_subdirs_all="$ac_subdirs_all packages/PyTrilinos"
 ac_subdirs_all="$ac_subdirs_all packages/rythmos"
 ac_subdirs_all="$ac_subdirs_all packages/tpetra"
 ac_subdirs_all="$ac_subdirs_all packages/didasko"
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot subdirs BUILD_TEUCHOS_TRUE BUILD_TEUCHOS_FALSE BUILD_THYRA_TRUE BUILD_THYRA_FALSE BUILD_KOKKOS_TRUE BUILD_KOKKOS_FALSE BUILD_EPETRA_TRUE BUILD_EPETRA_FALSE BUILD_PLIRIS_TRUE BUILD_PLIRIS_FALSE BUILD_TRIUTILS_TRUE BUILD_TRIUTILS_FALSE BUILD_IFPACK_TRUE BUILD_IFPACK_FALSE BUILD_AZTECOO_TRUE BUILD_AZTECOO_FALSE BUILD_CLAPS_TRUE BUILD_CLAPS_FALSE BUILD_KOMPLEX_TRUE BUILD_KOMPLEX_FALSE BUILD_TSF_TRUE BUILD_TSF_FALSE BUILD_TSFCORE_TRUE BUILD_TSFCORE_FALSE BUILD_TSFEXTENDED_TRUE BUILD_TSFEXTENDED_FALSE BUILD_TSFCOREUTILS_TRUE BUILD_TSFCOREUTILS_FALSE BUILD_AMESOS_TRUE BUILD_AMESOS_FALSE BUILD_EPETRAEXT_TRUE BUILD_EPETRAEXT_FALSE BUILD_BELOS_TRUE BUILD_BELOS_FALSE BUILD_ANASAZI_TRUE BUILD_ANASAZI_FALSE BUILD_MEROS_TRUE BUILD_MEROS_FALSE BUILD_ML_TRUE BUILD_ML_FALSE BUILD_NOX_TRUE BUILD_NOX_FALSE BUILD_NEW_PACKAGE_TRUE BUILD_NEW_PACKAGE_FALSE BUILD_CAPO_TRUE BUILD_CAPO_FALSE BUILD_PYTRILINOS_TRUE BUILD_PYTRILINOS_FALSE BUILD_RYTHMOS_TRUE BUILD_RYTHMOS_FALSE BUILD_TPETRA_TRUE BUILD_TPETRA_FALSE BUILD_DIDASKO_TRUE BUILD_DIDASKO_FALSE LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot subdirs BUILD_TEUCHOS_TRUE BUILD_TEUCHOS_FALSE BUILD_THYRA_TRUE BUILD_THYRA_FALSE BUILD_KOKKOS_TRUE BUILD_KOKKOS_FALSE BUILD_EPETRA_TRUE BUILD_EPETRA_FALSE BUILD_PLIRIS_TRUE BUILD_PLIRIS_FALSE BUILD_TRIUTILS_TRUE BUILD_TRIUTILS_FALSE BUILD_GALERI_TRUE BUILD_GALERI_FALSE BUILD_IFPACK_TRUE BUILD_IFPACK_FALSE BUILD_AZTECOO_TRUE BUILD_AZTECOO_FALSE BUILD_CLAPS_TRUE BUILD_CLAPS_FALSE BUILD_KOMPLEX_TRUE BUILD_KOMPLEX_FALSE BUILD_TSF_TRUE BUILD_TSF_FALSE BUILD_TSFCORE_TRUE BUILD_TSFCORE_FALSE BUILD_TSFEXTENDED_TRUE BUILD_TSFEXTENDED_FALSE BUILD_TSFCOREUTILS_TRUE BUILD_TSFCOREUTILS_FALSE BUILD_AMESOS_TRUE BUILD_AMESOS_FALSE BUILD_EPETRAEXT_TRUE BUILD_EPETRAEXT_FALSE BUILD_BELOS_TRUE BUILD_BELOS_FALSE BUILD_ANASAZI_TRUE BUILD_ANASAZI_FALSE BUILD_MEROS_TRUE BUILD_MEROS_FALSE BUILD_ML_TRUE BUILD_ML_FALSE BUILD_NOX_TRUE BUILD_NOX_FALSE BUILD_NEW_PACKAGE_TRUE BUILD_NEW_PACKAGE_FALSE BUILD_CAPO_TRUE BUILD_CAPO_FALSE BUILD_PYTRILINOS_TRUE BUILD_PYTRILINOS_FALSE BUILD_RYTHMOS_TRUE BUILD_RYTHMOS_FALSE BUILD_TPETRA_TRUE BUILD_TPETRA_FALSE BUILD_DIDASKO_TRUE BUILD_DIDASKO_FALSE LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -861,6 +862,7 @@ Optional Features:
   --enable-thyra          Build thyra (default is no)
   --enable-tpetra         Build tpetra (default is no)
   --enable-triutils       Build triutils (default is no)
+  --enable-galeri         Build galeri (default is no)
   --enable-tsf            Build TSF (default is no)
   --enable-tsfcore        Build TSFCore (default is no)
   --enable-tsfcoreutils   Build TSFCoreUtils (default is no)
@@ -2601,6 +2603,34 @@ fi
 
 
 
+# Check whether --enable-galeri or --disable-galeri was given.
+if test "${enable_galeri+set}" = set; then
+  enableval="$enable_galeri"
+  ac_cv_use_galeri=$enableval
+ac_cv_use_galeri_explicit=$enableval
+else
+  ac_cv_use_galeri=no
+ac_cv_use_galeri_explicit=no
+fi;
+
+echo "$as_me:$LINENO: checking whether to use galeri" >&5
+echo $ECHO_N "checking whether to use galeri... $ECHO_C" >&6
+
+if test "X$ac_cv_use_galeri" != "Xno"; then
+  echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_GALERI
+_ACEOF
+
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+
+
 # Check whether --enable-tsf or --disable-tsf was given.
 if test "${enable_tsf+set}" = set; then
   enableval="$enable_tsf"
@@ -2727,6 +2757,7 @@ if test "X$ac_cv_use_teuchos" != "Xno" ||
  	test "X$ac_cv_use_tsfcore" != "Xno" ||
 	test "X$ac_cv_use_tsfcoreutils" != "Xno" ||
         test "X$ac_cv_use_loca" != "Xno" ||
+	test "X$ac_cv_use_galeri" != "Xno" ||
 	test "X$ac_cv_use_amesos" != "Xno" ||
  	test "X$ac_cv_use_anasazi" != "Xno" ||
 	test "X$ac_cv_use_aztecoo_teuchos" != "Xno" ||
@@ -2806,6 +2837,7 @@ fi
 
 if test "X$ac_cv_use_epetra" != "Xno" || test "X$ac_cv_use_ifpack" != "Xno" ||
 	test "X$ac_cv_use_triutils" != "Xno" ||
+	test "X$ac_cv_use_galeri" != "Xno" ||
 	test "X$ac_cv_use_tsf" != "Xno" ||
         test "X$ac_cv_use_tsfextended" != "Xno" ||
  	test "X$ac_cv_use_amesos" != "Xno" ||
@@ -2878,13 +2910,35 @@ else
 fi
 
 
-
 if test "X$BUILD_TRIUTILS" != "Xno"; then
   BUILD_TRIUTILS_TRUE=
   BUILD_TRIUTILS_FALSE='#'
 else
   BUILD_TRIUTILS_TRUE='#'
   BUILD_TRIUTILS_FALSE=
+fi
+
+
+if test "X$ac_cv_use_galeri" != "Xno"; then
+
+
+subdirs="$subdirs packages/galeri"
+
+  BUILD_GALERI=yes
+  if test "X$ac_cv_use_galeri_explicit" != "Xyes"; then
+    ac_configure_args="$ac_configure_args --enable-galeri"
+  fi
+else
+  BUILD_GALERI=no
+fi
+
+
+if test "X$BUILD_GALERI" != "Xno"; then
+  BUILD_GALERI_TRUE=
+  BUILD_GALERI_FALSE='#'
+else
+  BUILD_GALERI_TRUE='#'
+  BUILD_GALERI_FALSE=
 fi
 
 
@@ -3525,6 +3579,13 @@ if test -z "${BUILD_TRIUTILS_TRUE}" && test -z "${BUILD_TRIUTILS_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"BUILD_TRIUTILS\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"BUILD_TRIUTILS\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${BUILD_GALERI_TRUE}" && test -z "${BUILD_GALERI_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"BUILD_GALERI\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"BUILD_GALERI\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -4233,6 +4294,8 @@ s,@BUILD_PLIRIS_TRUE@,$BUILD_PLIRIS_TRUE,;t t
 s,@BUILD_PLIRIS_FALSE@,$BUILD_PLIRIS_FALSE,;t t
 s,@BUILD_TRIUTILS_TRUE@,$BUILD_TRIUTILS_TRUE,;t t
 s,@BUILD_TRIUTILS_FALSE@,$BUILD_TRIUTILS_FALSE,;t t
+s,@BUILD_GALERI_TRUE@,$BUILD_GALERI_TRUE,;t t
+s,@BUILD_GALERI_FALSE@,$BUILD_GALERI_FALSE,;t t
 s,@BUILD_IFPACK_TRUE@,$BUILD_IFPACK_TRUE,;t t
 s,@BUILD_IFPACK_FALSE@,$BUILD_IFPACK_FALSE,;t t
 s,@BUILD_AZTECOO_TRUE@,$BUILD_AZTECOO_TRUE,;t t
