Adding Trilinos infrastructure to build Sacado.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -301,11 +301,12 @@ ac_subdirs_all="$ac_subdirs_all packages/moertel"
 ac_subdirs_all="$ac_subdirs_all packages/PyTrilinos"
 ac_subdirs_all="$ac_subdirs_all packages/rythmos"
 ac_subdirs_all="$ac_subdirs_all packages/tpetra"
+ac_subdirs_all="$ac_subdirs_all packages/sacado"
 ac_subdirs_all="$ac_subdirs_all packages/didasko"
 ac_subdirs_all="$ac_subdirs_all packages/WebTrilinos"
 ac_subdirs_all="$ac_subdirs_all packages/external"
 ac_subdirs_all="$ac_subdirs_all packages/moocho"
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot subdirs BUILD_TEUCHOS_TRUE BUILD_TEUCHOS_FALSE BUILD_RTOP_TRUE BUILD_RTOP_FALSE BUILD_THYRA_TRUE BUILD_THYRA_FALSE BUILD_STRATIMIKOS_TRUE BUILD_STRATIMIKOS_FALSE BUILD_KOKKOS_TRUE BUILD_KOKKOS_FALSE BUILD_EPETRA_TRUE BUILD_EPETRA_FALSE BUILD_PLIRIS_TRUE BUILD_PLIRIS_FALSE BUILD_TRIUTILS_TRUE BUILD_TRIUTILS_FALSE BUILD_GALERI_TRUE BUILD_GALERI_FALSE BUILD_IFPACK_TRUE BUILD_IFPACK_FALSE BUILD_AZTECOO_TRUE BUILD_AZTECOO_FALSE BUILD_CLAPS_TRUE BUILD_CLAPS_FALSE BUILD_KOMPLEX_TRUE BUILD_KOMPLEX_FALSE BUILD_AMESOS_TRUE BUILD_AMESOS_FALSE BUILD_EPETRAEXT_TRUE BUILD_EPETRAEXT_FALSE BUILD_BELOS_TRUE BUILD_BELOS_FALSE BUILD_ANASAZI_TRUE BUILD_ANASAZI_FALSE BUILD_MEROS_TRUE BUILD_MEROS_FALSE BUILD_ML_TRUE BUILD_ML_FALSE BUILD_NOX_TRUE BUILD_NOX_FALSE BUILD_ISORROPIA_TRUE BUILD_ISORROPIA_FALSE BUILD_NEW_PACKAGE_TRUE BUILD_NEW_PACKAGE_FALSE BUILD_CAPO_TRUE BUILD_CAPO_FALSE BUILD_MOERTEL_TRUE BUILD_MOERTEL_FALSE BUILD_PYTRILINOS_TRUE BUILD_PYTRILINOS_FALSE BUILD_RYTHMOS_TRUE BUILD_RYTHMOS_FALSE BUILD_TPETRA_TRUE BUILD_TPETRA_FALSE BUILD_DIDASKO_TRUE BUILD_DIDASKO_FALSE BUILD_WEBTRILINOS_TRUE BUILD_WEBTRILINOS_FALSE BUILD_EXTERNAL_TRUE BUILD_EXTERNAL_FALSE BUILD_MOOCHO_TRUE BUILD_MOOCHO_FALSE LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot subdirs BUILD_TEUCHOS_TRUE BUILD_TEUCHOS_FALSE BUILD_RTOP_TRUE BUILD_RTOP_FALSE BUILD_THYRA_TRUE BUILD_THYRA_FALSE BUILD_STRATIMIKOS_TRUE BUILD_STRATIMIKOS_FALSE BUILD_KOKKOS_TRUE BUILD_KOKKOS_FALSE BUILD_EPETRA_TRUE BUILD_EPETRA_FALSE BUILD_PLIRIS_TRUE BUILD_PLIRIS_FALSE BUILD_TRIUTILS_TRUE BUILD_TRIUTILS_FALSE BUILD_GALERI_TRUE BUILD_GALERI_FALSE BUILD_IFPACK_TRUE BUILD_IFPACK_FALSE BUILD_AZTECOO_TRUE BUILD_AZTECOO_FALSE BUILD_CLAPS_TRUE BUILD_CLAPS_FALSE BUILD_KOMPLEX_TRUE BUILD_KOMPLEX_FALSE BUILD_AMESOS_TRUE BUILD_AMESOS_FALSE BUILD_EPETRAEXT_TRUE BUILD_EPETRAEXT_FALSE BUILD_BELOS_TRUE BUILD_BELOS_FALSE BUILD_ANASAZI_TRUE BUILD_ANASAZI_FALSE BUILD_MEROS_TRUE BUILD_MEROS_FALSE BUILD_ML_TRUE BUILD_ML_FALSE BUILD_NOX_TRUE BUILD_NOX_FALSE BUILD_ISORROPIA_TRUE BUILD_ISORROPIA_FALSE BUILD_NEW_PACKAGE_TRUE BUILD_NEW_PACKAGE_FALSE BUILD_CAPO_TRUE BUILD_CAPO_FALSE BUILD_MOERTEL_TRUE BUILD_MOERTEL_FALSE BUILD_PYTRILINOS_TRUE BUILD_PYTRILINOS_FALSE BUILD_RYTHMOS_TRUE BUILD_RYTHMOS_FALSE BUILD_TPETRA_TRUE BUILD_TPETRA_FALSE BUILD_SACADO_TRUE BUILD_SACADO_FALSE BUILD_DIDASKO_TRUE BUILD_DIDASKO_FALSE BUILD_WEBTRILINOS_TRUE BUILD_WEBTRILINOS_FALSE BUILD_EXTERNAL_TRUE BUILD_EXTERNAL_FALSE BUILD_MOOCHO_TRUE BUILD_MOOCHO_FALSE LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -865,6 +866,7 @@ Optional Features:
   --enable-pytrilinos     Build PyTrilinos (default is no)
   --enable-python         Build PyTrilinos (default is no)
   --enable-rythmos        Build rythmos (default is no)
+  --enable-sacado         Build sacado (default is no)
   --enable-teuchos        Build teuchos (default is no)
   --enable-rtop           Build RTOP (default is no)
   --enable-thyra          Build thyra (default is no)
@@ -2584,6 +2586,34 @@ fi
 
 
 
+# Check whether --enable-sacado or --disable-sacado was given.
+if test "${enable_sacado+set}" = set; then
+  enableval="$enable_sacado"
+  ac_cv_use_sacado=$enableval
+ac_cv_use_sacado_explicit=$enableval
+else
+  ac_cv_use_sacado=no
+ac_cv_use_sacado_explicit=no
+fi;
+
+echo "$as_me:$LINENO: checking whether to use sacado" >&5
+echo $ECHO_N "checking whether to use sacado... $ECHO_C" >&6
+
+if test "X$ac_cv_use_sacado" != "Xno"; then
+  echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_SACADO
+_ACEOF
+
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+
+
 # Check whether --enable-teuchos or --disable-teuchos was given.
 if test "${enable_teuchos+set}" = set; then
   enableval="$enable_teuchos"
@@ -3531,6 +3561,29 @@ else
 fi
 
 
+if test "X$ac_cv_use_sacado" != "Xno"; then
+
+
+subdirs="$subdirs packages/sacado"
+
+  BUILD_SACADO=yes
+  if test "X$ac_cv_use_sacado_explicit" != "Xyes"; then
+    ac_configure_args="$ac_configure_args --enable-sacado"
+  fi
+else
+  BUILD_SACADO=no
+fi
+
+
+if test "X$BUILD_SACADO" != "Xno"; then
+  BUILD_SACADO_TRUE=
+  BUILD_SACADO_FALSE='#'
+else
+  BUILD_SACADO_TRUE='#'
+  BUILD_SACADO_FALSE=
+fi
+
+
 if test "X$ac_cv_use_didasko" != "Xno"; then
 
 
@@ -3914,6 +3967,13 @@ if test -z "${BUILD_TPETRA_TRUE}" && test -z "${BUILD_TPETRA_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"BUILD_TPETRA\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"BUILD_TPETRA\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${BUILD_SACADO_TRUE}" && test -z "${BUILD_SACADO_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"BUILD_SACADO\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"BUILD_SACADO\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -4545,6 +4605,8 @@ s,@BUILD_RYTHMOS_TRUE@,$BUILD_RYTHMOS_TRUE,;t t
 s,@BUILD_RYTHMOS_FALSE@,$BUILD_RYTHMOS_FALSE,;t t
 s,@BUILD_TPETRA_TRUE@,$BUILD_TPETRA_TRUE,;t t
 s,@BUILD_TPETRA_FALSE@,$BUILD_TPETRA_FALSE,;t t
+s,@BUILD_SACADO_TRUE@,$BUILD_SACADO_TRUE,;t t
+s,@BUILD_SACADO_FALSE@,$BUILD_SACADO_FALSE,;t t
 s,@BUILD_DIDASKO_TRUE@,$BUILD_DIDASKO_TRUE,;t t
 s,@BUILD_DIDASKO_FALSE@,$BUILD_DIDASKO_FALSE,;t t
 s,@BUILD_WEBTRILINOS_TRUE@,$BUILD_WEBTRILINOS_TRUE,;t t
