Modify top-level Trilinos configure.ac to add '--enable-fei', and add lines to have configure configure the packages/fei subdirectory.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -654,6 +654,8 @@ BUILD_KOKKOS_TRUE
 BUILD_KOKKOS_FALSE
 BUILD_EPETRA_TRUE
 BUILD_EPETRA_FALSE
+BUILD_FEI_TRUE
+BUILD_FEI_FALSE
 BUILD_PLIRIS_TRUE
 BUILD_PLIRIS_FALSE
 BUILD_TRIUTILS_TRUE
@@ -726,6 +728,7 @@ packages/thyra
 packages/stratimikos
 packages/kokkos
 packages/epetra
+packages/fei
 packages/pliris
 packages/triutils
 packages/galeri
@@ -1364,6 +1367,9 @@ Optional Features:
   --enable-external       Build external package in packages/external (default
                           is no)
   --enable-ifpack         Build ifpack, an algebraic preconditioner package
+                          (default is yes unless the
+                          --disable-default-packages option is used)
+  --enable-fei            Build fei, a sparse linear-system assembly package
                           (default is yes unless the
                           --disable-default-packages option is used)
   --enable-intrepid       Build intrepid, a discretization package (default is
@@ -2849,6 +2855,34 @@ fi
 
 
 
+# Check whether --enable-fei was given.
+if test "${enable_fei+set}" = set; then
+  enableval=$enable_fei; ac_cv_use_fei=$enableval
+ac_cv_use_fei_explicit=$enableval
+else
+  ac_cv_use_fei=$ac_cv_use_default_packages
+ac_cv_use_fei_explicit=no
+fi
+
+
+{ echo "$as_me:$LINENO: checking whether to use fei" >&5
+echo $ECHO_N "checking whether to use fei... $ECHO_C" >&6; }
+
+if test "X$ac_cv_use_fei" != "Xno"; then
+  { echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6; }
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_FEI
+_ACEOF
+
+else
+  { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+fi
+
+
+
 # Check whether --enable-intrepid was given.
 if test "${enable_intrepid+set}" = set; then
   enableval=$enable_intrepid; ac_cv_use_intrepid=$enableval
@@ -3749,6 +3783,22 @@ else
 fi
 
 
+if test "X$ac_cv_use_fei" != "Xno"; then
+  subdirs="$subdirs packages/fei"
+
+  BUILD_FEI=yes
+else
+  BUILD_FEI=no
+fi
+ if test "X$BUILD_FEI" != "Xno"; then
+  BUILD_FEI_TRUE=
+  BUILD_FEI_FALSE='#'
+else
+  BUILD_FEI_TRUE='#'
+  BUILD_FEI_FALSE=
+fi
+
+
 if test "X$ac_cv_use_pliris" != "Xno"; then
   subdirs="$subdirs packages/pliris"
 
@@ -4497,6 +4547,13 @@ if test -z "${BUILD_EPETRA_TRUE}" && test -z "${BUILD_EPETRA_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"BUILD_EPETRA\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"BUILD_EPETRA\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${BUILD_FEI_TRUE}" && test -z "${BUILD_FEI_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"BUILD_FEI\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"BUILD_FEI\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -5308,6 +5365,8 @@ BUILD_KOKKOS_TRUE!$BUILD_KOKKOS_TRUE$ac_delim
 BUILD_KOKKOS_FALSE!$BUILD_KOKKOS_FALSE$ac_delim
 BUILD_EPETRA_TRUE!$BUILD_EPETRA_TRUE$ac_delim
 BUILD_EPETRA_FALSE!$BUILD_EPETRA_FALSE$ac_delim
+BUILD_FEI_TRUE!$BUILD_FEI_TRUE$ac_delim
+BUILD_FEI_FALSE!$BUILD_FEI_FALSE$ac_delim
 BUILD_PLIRIS_TRUE!$BUILD_PLIRIS_TRUE$ac_delim
 BUILD_PLIRIS_FALSE!$BUILD_PLIRIS_FALSE$ac_delim
 BUILD_TRIUTILS_TRUE!$BUILD_TRIUTILS_TRUE$ac_delim
@@ -5328,8 +5387,6 @@ BUILD_EPETRAEXT_TRUE!$BUILD_EPETRAEXT_TRUE$ac_delim
 BUILD_EPETRAEXT_FALSE!$BUILD_EPETRAEXT_FALSE$ac_delim
 BUILD_BELOS_TRUE!$BUILD_BELOS_TRUE$ac_delim
 BUILD_BELOS_FALSE!$BUILD_BELOS_FALSE$ac_delim
-BUILD_ANASAZI_TRUE!$BUILD_ANASAZI_TRUE$ac_delim
-BUILD_ANASAZI_FALSE!$BUILD_ANASAZI_FALSE$ac_delim
 _ACEOF
 
   if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 97; then
@@ -5371,6 +5428,8 @@ _ACEOF
 ac_delim='%!_!# '
 for ac_last_try in false false false false false :; do
   cat >conf$$subs.sed <<_ACEOF
+BUILD_ANASAZI_TRUE!$BUILD_ANASAZI_TRUE$ac_delim
+BUILD_ANASAZI_FALSE!$BUILD_ANASAZI_FALSE$ac_delim
 BUILD_RBGEN_TRUE!$BUILD_RBGEN_TRUE$ac_delim
 BUILD_RBGEN_FALSE!$BUILD_RBGEN_FALSE$ac_delim
 BUILD_ARISTOS_TRUE!$BUILD_ARISTOS_TRUE$ac_delim
@@ -5413,7 +5472,7 @@ LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 40; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 42; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
