SUMMARY: Adding new TriKota package, some RTOp refactorings, and some playing with Teuchos::Comm
BUGS: None filed

CHECKLIST:

1) Did you add any source or other files needed for building, testing,
   or documentation? Yes
1.a) Did you do a 'cvs add'? Yes
1.b) Did you add them to a Makefile.am file in some way (either as
     a header or soruce file or to EXTRA_DIST)? Yes
1.c) Did you do a new bootstrap? Yes

2) Did you update or change the build system (other than just adding
   source files)? Yes
2.a) Did you remember to do a bootstrap and do a 'cvs add' on any
     Makefile.am files and Makefile.in files you created? Yes

3) Did you do a cvs update *very* recently before rebuilding and
   retesting? Yes

4) If justified, did you type 'make partial-clean' and then rebuild all
   libraries and executables with 'make everything'? yes, both serial debug
   and mpi optimized

5) Did you rerun the test suite on at least the packages that you
   changed (rerunning the entire Trlinos test suite on all affected
   packages is *strongly* recommended)? Yes, all 876 serial debug and
   735 mpi optimized tests run passed.

COMMENTS:

The main thing that I did here is to add the new Trilinos package TriKota for
Dakota/Trilinos integration.  This is only in prototype mode for now so no-one
should try to enable it.  The main thing is that when you enable trikota (with
--enable-trikota), several of the examples and tests in other packages don't
link.  The problem is that the Dakota library has its own incompatible version
of Epetra which is found first.  Therefore, Dakota needs to be able to be
configured for library mode where it does *not* try to build its own versions
of any TPL software and instead can be pointed to another set of header files
(that live in Trilinos of course).

However, if you disable trikota and remove the -L paths to the bad Dakota
Trilinos libraries, everything else works just fine.

Here are some other changes that I am checking in:

(*) packages/teuchos/src/Teuchos_DefaultMpiComm.hpp: Some minor reformating.

(*) packages/teuchos/src/Teuchos_TestingHelpers.hpp: Fixing
TEUCHOS_TEST_FLOATING_EQUALITY(...) to pass out correctly.

(*) packages/teuchos/test/Comm/Comm_test.cpp: Mostly just reformating to see
what is going on.

(*) packages/teuchos/test/Comm/ReduceAllAndScatter_test.cpp: Added test case
using miss-match of data type and reduction operator.

(*) sampleScripts/linux-gabriel-gcc-3.3.4-serial-debug: Removed
--enable-intrepid since it is just taking too long.

(*) packages/rtop: All of the changes made here are in prepairation for
removing use of raw pointers and cleaning up how RTOp subclasses are defined.
This should make it easier for users to create their own RTOps.  I still have
a lot of work to do to even just clean up the interfaces and the
implementations before moving on to thyra.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -712,6 +712,8 @@ BUILD_RYTHMOS_TRUE
 BUILD_RYTHMOS_FALSE
 BUILD_TPETRA_TRUE
 BUILD_TPETRA_FALSE
+BUILD_TRIKOTA_TRUE
+BUILD_TRIKOTA_FALSE
 BUILD_TRILINOSCOUPLINGS_TRUE
 BUILD_TRILINOSCOUPLINGS_FALSE
 BUILD_DIDASKO_TRUE
@@ -769,6 +771,7 @@ packages/moertel
 packages/PyTrilinos
 packages/rythmos
 packages/tpetra
+packages/TriKota
 packages/trilinoscouplings
 packages/didasko
 packages/WebTrilinos
@@ -1443,6 +1446,8 @@ Optional Features:
                           no)
   --enable-tpetra         Build tpetra, a templated linear algebra package
                           (default is no)
+  --enable-trikota        Build TriKota, a package providing Trilinos/Dakota
+                          interoperability (default is no)
   --enable-trilinoscouplings
                           Build trilinoscouplings, a package of interfaces
                           between Trilinos packages (default is no)
@@ -3642,6 +3647,34 @@ fi
 
 
 
+# Check whether --enable-trikota was given.
+if test "${enable_trikota+set}" = set; then
+  enableval=$enable_trikota; ac_cv_use_trikota=$enableval
+ac_cv_use_trikota_explicit=$enableval
+else
+  ac_cv_use_trikota=no
+ac_cv_use_trikota_explicit=no
+fi
+
+
+{ echo "$as_me:$LINENO: checking whether to use trikota" >&5
+echo $ECHO_N "checking whether to use trikota... $ECHO_C" >&6; }
+
+if test "X$ac_cv_use_trikota" != "Xno"; then
+  { echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6; }
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_TRIKOTA
+_ACEOF
+
+else
+  { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+fi
+
+
+
 # Check whether --enable-trilinoscouplings was given.
 if test "${enable_trilinoscouplings+set}" = set; then
   enableval=$enable_trilinoscouplings; ac_cv_use_trilinoscouplings=$enableval
@@ -4577,6 +4610,25 @@ else
 fi
 
 
+if test "X$ac_cv_use_trikota" != "Xno"; then
+  subdirs="$subdirs packages/TriKota"
+
+  BUILD_TRIKOTA=yes
+  if test "X$ac_cv_use_trikota_explicit" != "Xyes"; then
+    ac_configure_args="$ac_configure_args --enable-trikota"
+  fi
+else
+  BUILD_TRIKOTA=no
+fi
+ if test "X$BUILD_TRIKOTA" != "Xno"; then
+  BUILD_TRIKOTA_TRUE=
+  BUILD_TRIKOTA_FALSE='#'
+else
+  BUILD_TRIKOTA_TRUE='#'
+  BUILD_TRIKOTA_FALSE=
+fi
+
+
 if test "X$ac_cv_use_trilinoscouplings" != "Xno"; then
   subdirs="$subdirs packages/trilinoscouplings"
 
@@ -5081,6 +5133,13 @@ if test -z "${BUILD_TPETRA_TRUE}" && test -z "${BUILD_TPETRA_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"BUILD_TPETRA\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"BUILD_TPETRA\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${BUILD_TRIKOTA_TRUE}" && test -z "${BUILD_TRIKOTA_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"BUILD_TRIKOTA\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"BUILD_TRIKOTA\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -5837,6 +5896,8 @@ BUILD_RYTHMOS_TRUE!$BUILD_RYTHMOS_TRUE$ac_delim
 BUILD_RYTHMOS_FALSE!$BUILD_RYTHMOS_FALSE$ac_delim
 BUILD_TPETRA_TRUE!$BUILD_TPETRA_TRUE$ac_delim
 BUILD_TPETRA_FALSE!$BUILD_TPETRA_FALSE$ac_delim
+BUILD_TRIKOTA_TRUE!$BUILD_TRIKOTA_TRUE$ac_delim
+BUILD_TRIKOTA_FALSE!$BUILD_TRIKOTA_FALSE$ac_delim
 BUILD_TRILINOSCOUPLINGS_TRUE!$BUILD_TRILINOSCOUPLINGS_TRUE$ac_delim
 BUILD_TRILINOSCOUPLINGS_FALSE!$BUILD_TRILINOSCOUPLINGS_FALSE$ac_delim
 BUILD_DIDASKO_TRUE!$BUILD_DIDASKO_TRUE$ac_delim
@@ -5857,7 +5918,7 @@ LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 54; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 56; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
