Initial commit of Aristos. Aristos is an optimization package based on full-space sequential quadratic programming (SQP) algorithms.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -292,6 +292,7 @@ ac_subdirs_all="$ac_subdirs_all packages/epetraext"
 ac_subdirs_all="$ac_subdirs_all packages/belos"
 ac_subdirs_all="$ac_subdirs_all packages/anasazi"
 ac_subdirs_all="$ac_subdirs_all packages/rbgen"
+ac_subdirs_all="$ac_subdirs_all packages/aristos"
 ac_subdirs_all="$ac_subdirs_all packages/meros"
 ac_subdirs_all="$ac_subdirs_all packages/ml"
 ac_subdirs_all="$ac_subdirs_all packages/nox"
@@ -307,7 +308,7 @@ ac_subdirs_all="$ac_subdirs_all packages/didasko"
 ac_subdirs_all="$ac_subdirs_all packages/WebTrilinos"
 ac_subdirs_all="$ac_subdirs_all packages/external"
 ac_subdirs_all="$ac_subdirs_all packages/moocho"
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot subdirs BUILD_TEUCHOS_TRUE BUILD_TEUCHOS_FALSE BUILD_RTOP_TRUE BUILD_RTOP_FALSE BUILD_THYRA_TRUE BUILD_THYRA_FALSE BUILD_STRATIMIKOS_TRUE BUILD_STRATIMIKOS_FALSE BUILD_KOKKOS_TRUE BUILD_KOKKOS_FALSE BUILD_EPETRA_TRUE BUILD_EPETRA_FALSE BUILD_PLIRIS_TRUE BUILD_PLIRIS_FALSE BUILD_TRIUTILS_TRUE BUILD_TRIUTILS_FALSE BUILD_GALERI_TRUE BUILD_GALERI_FALSE BUILD_IFPACK_TRUE BUILD_IFPACK_FALSE BUILD_AZTECOO_TRUE BUILD_AZTECOO_FALSE BUILD_CLAPS_TRUE BUILD_CLAPS_FALSE BUILD_KOMPLEX_TRUE BUILD_KOMPLEX_FALSE BUILD_AMESOS_TRUE BUILD_AMESOS_FALSE BUILD_EPETRAEXT_TRUE BUILD_EPETRAEXT_FALSE BUILD_BELOS_TRUE BUILD_BELOS_FALSE BUILD_ANASAZI_TRUE BUILD_ANASAZI_FALSE BUILD_RBGEN_TRUE BUILD_RBGEN_FALSE BUILD_MEROS_TRUE BUILD_MEROS_FALSE BUILD_ML_TRUE BUILD_ML_FALSE BUILD_NOX_TRUE BUILD_NOX_FALSE BUILD_ISORROPIA_TRUE BUILD_ISORROPIA_FALSE BUILD_NEW_PACKAGE_TRUE BUILD_NEW_PACKAGE_FALSE BUILD_CAPO_TRUE BUILD_CAPO_FALSE BUILD_MOERTEL_TRUE BUILD_MOERTEL_FALSE BUILD_PYTRILINOS_TRUE BUILD_PYTRILINOS_FALSE BUILD_RYTHMOS_TRUE BUILD_RYTHMOS_FALSE BUILD_TPETRA_TRUE BUILD_TPETRA_FALSE BUILD_SACADO_TRUE BUILD_SACADO_FALSE BUILD_DIDASKO_TRUE BUILD_DIDASKO_FALSE BUILD_WEBTRILINOS_TRUE BUILD_WEBTRILINOS_FALSE BUILD_EXTERNAL_TRUE BUILD_EXTERNAL_FALSE BUILD_MOOCHO_TRUE BUILD_MOOCHO_FALSE LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot subdirs BUILD_TEUCHOS_TRUE BUILD_TEUCHOS_FALSE BUILD_RTOP_TRUE BUILD_RTOP_FALSE BUILD_THYRA_TRUE BUILD_THYRA_FALSE BUILD_STRATIMIKOS_TRUE BUILD_STRATIMIKOS_FALSE BUILD_KOKKOS_TRUE BUILD_KOKKOS_FALSE BUILD_EPETRA_TRUE BUILD_EPETRA_FALSE BUILD_PLIRIS_TRUE BUILD_PLIRIS_FALSE BUILD_TRIUTILS_TRUE BUILD_TRIUTILS_FALSE BUILD_GALERI_TRUE BUILD_GALERI_FALSE BUILD_IFPACK_TRUE BUILD_IFPACK_FALSE BUILD_AZTECOO_TRUE BUILD_AZTECOO_FALSE BUILD_CLAPS_TRUE BUILD_CLAPS_FALSE BUILD_KOMPLEX_TRUE BUILD_KOMPLEX_FALSE BUILD_AMESOS_TRUE BUILD_AMESOS_FALSE BUILD_EPETRAEXT_TRUE BUILD_EPETRAEXT_FALSE BUILD_BELOS_TRUE BUILD_BELOS_FALSE BUILD_ANASAZI_TRUE BUILD_ANASAZI_FALSE BUILD_RBGEN_TRUE BUILD_RBGEN_FALSE BUILD_ARISTOS_TRUE BUILD_ARISTOS_FALSE BUILD_MEROS_TRUE BUILD_MEROS_FALSE BUILD_ML_TRUE BUILD_ML_FALSE BUILD_NOX_TRUE BUILD_NOX_FALSE BUILD_ISORROPIA_TRUE BUILD_ISORROPIA_FALSE BUILD_NEW_PACKAGE_TRUE BUILD_NEW_PACKAGE_FALSE BUILD_CAPO_TRUE BUILD_CAPO_FALSE BUILD_MOERTEL_TRUE BUILD_MOERTEL_FALSE BUILD_PYTRILINOS_TRUE BUILD_PYTRILINOS_FALSE BUILD_RYTHMOS_TRUE BUILD_RYTHMOS_FALSE BUILD_TPETRA_TRUE BUILD_TPETRA_FALSE BUILD_SACADO_TRUE BUILD_SACADO_FALSE BUILD_DIDASKO_TRUE BUILD_DIDASKO_FALSE BUILD_WEBTRILINOS_TRUE BUILD_WEBTRILINOS_FALSE BUILD_EXTERNAL_TRUE BUILD_EXTERNAL_FALSE BUILD_MOOCHO_TRUE BUILD_MOOCHO_FALSE LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -835,6 +836,7 @@ Optional Features:
                           built (default is yes)
   --enable-amesos         Build amesos (default is no)
   --enable-anasazi        Build anasazi (default is no)
+  --enable-aristos        Build aristos (default is no)
   --enable-aztecoo        Build aztecoo (default is yes unless the
                           --disable-default-packages option is used
   --enable-belos          Build belos (default is no)
@@ -1927,6 +1929,34 @@ fi
 
 
 
+# Check whether --enable-aristos or --disable-aristos was given.
+if test "${enable_aristos+set}" = set; then
+  enableval="$enable_aristos"
+  ac_cv_use_aristos=$enableval
+ac_cv_use_aristos_explicit=$enableval
+else
+  ac_cv_use_aristos=no
+ac_cv_use_aristos_explicit=no
+fi;
+
+echo "$as_me:$LINENO: checking whether to use aristos" >&5
+echo $ECHO_N "checking whether to use aristos... $ECHO_C" >&6
+
+if test "X$ac_cv_use_aristos" != "Xno"; then
+  echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_ARISTOS
+_ACEOF
+
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+
+
 # Check whether --enable-aztecoo or --disable-aztecoo was given.
 if test "${enable_aztecoo+set}" = set; then
   enableval="$enable_aztecoo"
@@ -2911,6 +2941,7 @@ if test "X$ac_cv_use_teuchos" != "Xno" ||
 	test "X$ac_cv_use_galeri" != "Xno" ||
 	test "X$ac_cv_use_amesos" != "Xno" ||
  	test "X$ac_cv_use_anasazi" != "Xno" ||
+ 	test "X$ac_cv_use_aristos" != "Xno" ||
 	test "X$ac_cv_use_aztecoo_teuchos" != "Xno" ||
 	test "X$ac_cv_use_capo" != "Xno" ||
 	test "X$ac_cv_use_epetraext" != "Xno" ||
@@ -3059,6 +3090,7 @@ if test "X$ac_cv_use_epetra" != "Xno" || test "X$ac_cv_use_ifpack" != "Xno" ||
         test "X$ac_cv_use_epetraext" != "Xno" ||
 	test "X$ac_cv_use_belos" != "Xno" ||
 	test "X$ac_cv_use_anasazi" != "Xno" ||
+	test "X$ac_cv_use_aristos" != "Xno" ||
         test "X$ac_cv_use_claps" != "Xno" ||
 	test "X$ac_cv_use_meros" != "Xno" ||
         test "X$ac_cv_use_moertel" != "Xno" ||
@@ -3375,6 +3407,29 @@ if test "X$BUILD_RBGEN" != "Xno"; then
 else
   BUILD_RBGEN_TRUE='#'
   BUILD_RBGEN_FALSE=
+fi
+
+
+if test "X$ac_cv_use_aristos" != "Xno"; then
+
+
+subdirs="$subdirs packages/aristos"
+
+  BUILD_ARISTOS=yes
+  if test "X$ac_cv_use_aristos_explicit" != "Xyes"; then
+    ac_configure_args="$ac_configure_args --enable-aristos"
+  fi
+else
+  BUILD_ARISTOS=no
+fi
+
+
+if test "X$BUILD_ARISTOS" != "Xno"; then
+  BUILD_ARISTOS_TRUE=
+  BUILD_ARISTOS_FALSE='#'
+else
+  BUILD_ARISTOS_TRUE='#'
+  BUILD_ARISTOS_FALSE=
 fi
 
 
@@ -3958,6 +4013,13 @@ if test -z "${BUILD_RBGEN_TRUE}" && test -z "${BUILD_RBGEN_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"BUILD_RBGEN\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"BUILD_RBGEN\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${BUILD_ARISTOS_TRUE}" && test -z "${BUILD_ARISTOS_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"BUILD_ARISTOS\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"BUILD_ARISTOS\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -4648,6 +4710,8 @@ s,@BUILD_ANASAZI_TRUE@,$BUILD_ANASAZI_TRUE,;t t
 s,@BUILD_ANASAZI_FALSE@,$BUILD_ANASAZI_FALSE,;t t
 s,@BUILD_RBGEN_TRUE@,$BUILD_RBGEN_TRUE,;t t
 s,@BUILD_RBGEN_FALSE@,$BUILD_RBGEN_FALSE,;t t
+s,@BUILD_ARISTOS_TRUE@,$BUILD_ARISTOS_TRUE,;t t
+s,@BUILD_ARISTOS_FALSE@,$BUILD_ARISTOS_FALSE,;t t
 s,@BUILD_MEROS_TRUE@,$BUILD_MEROS_TRUE,;t t
 s,@BUILD_MEROS_FALSE@,$BUILD_MEROS_FALSE,;t t
 s,@BUILD_ML_TRUE@,$BUILD_ML_TRUE,;t t
