Initial checkin of TSFExtended

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -281,6 +281,7 @@ ac_subdirs_all="$ac_subdirs_all packages/aztecoo"
 ac_subdirs_all="$ac_subdirs_all packages/komplex"
 ac_subdirs_all="$ac_subdirs_all packages/TSF"
 ac_subdirs_all="$ac_subdirs_all packages/TSFCore"
+ac_subdirs_all="$ac_subdirs_all packages/TSFExtended"
 ac_subdirs_all="$ac_subdirs_all packages/TSFCoreUtils"
 ac_subdirs_all="$ac_subdirs_all packages/amesos"
 ac_subdirs_all="$ac_subdirs_all packages/epetraext"
@@ -291,7 +292,7 @@ ac_subdirs_all="$ac_subdirs_all packages/nox"
 ac_subdirs_all="$ac_subdirs_all packages/ml"
 ac_subdirs_all="$ac_subdirs_all packages/new_package"
 ac_subdirs_all="$ac_subdirs_all packages/tpetra"
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM AWK SET_MAKE BUILD_AMESOS_TRUE BUILD_AMESOS_FALSE BUILD_NOX_TRUE BUILD_NOX_FALSE BUILD_MEROS_TRUE BUILD_MEROS_FALSE BUILD_TSF_TRUE BUILD_TSF_FALSE BUILD_TSFCORE_TRUE BUILD_TSFCORE_FALSE BUILD_TSFCOREUTILS_TRUE BUILD_TSFCOREUTILS_FALSE BUILD_KOMPLEX_TRUE BUILD_KOMPLEX_FALSE BUILD_AZTECOO_TRUE BUILD_AZTECOO_FALSE BUILD_BELOS_TRUE BUILD_BELOS_FALSE BUILD_ANASAZI_TRUE BUILD_ANASAZI_FALSE BUILD_IFPACK_TRUE BUILD_IFPACK_FALSE BUILD_TRIUTILS_TRUE BUILD_TRIUTILS_FALSE BUILD_EPETRAEXT_TRUE BUILD_EPETRAEXT_FALSE BUILD_TPETRA_TRUE BUILD_TPETRA_FALSE BUILD_TEUCHOS_TRUE BUILD_TEUCHOS_FALSE BUILD_ML_TRUE BUILD_ML_FALSE BUILD_NEW_PACKAGE_TRUE BUILD_NEW_PACKAGE_FALSE subdirs BUILD_EPETRA_TRUE BUILD_EPETRA_FALSE LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM AWK SET_MAKE BUILD_AMESOS_TRUE BUILD_AMESOS_FALSE BUILD_NOX_TRUE BUILD_NOX_FALSE BUILD_MEROS_TRUE BUILD_MEROS_FALSE BUILD_TSF_TRUE BUILD_TSF_FALSE BUILD_TSFCORE_TRUE BUILD_TSFCORE_FALSE BUILD_TSFCOREUTILS_TRUE BUILD_TSFCOREUTILS_FALSE BUILD_TSFEXTENDED_TRUE BUILD_TSFEXTENDED_FALSE BUILD_KOMPLEX_TRUE BUILD_KOMPLEX_FALSE BUILD_AZTECOO_TRUE BUILD_AZTECOO_FALSE BUILD_BELOS_TRUE BUILD_BELOS_FALSE BUILD_ANASAZI_TRUE BUILD_ANASAZI_FALSE BUILD_IFPACK_TRUE BUILD_IFPACK_FALSE BUILD_TRIUTILS_TRUE BUILD_TRIUTILS_FALSE BUILD_EPETRAEXT_TRUE BUILD_EPETRAEXT_FALSE BUILD_TPETRA_TRUE BUILD_TPETRA_FALSE BUILD_TEUCHOS_TRUE BUILD_TEUCHOS_FALSE BUILD_ML_TRUE BUILD_ML_FALSE BUILD_NEW_PACKAGE_TRUE BUILD_NEW_PACKAGE_FALSE subdirs BUILD_EPETRA_TRUE BUILD_EPETRA_FALSE LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -817,6 +818,7 @@ Optional Features:
   --enable-tsf            Build TSF (default is no)
   --enable-tsfcore        Build TSFCore (default is no)
   --enable-tsfcoreutils   Build TSFCoreUtils (default is no)
+  --enable-tsfextended    Build TSFExtended (default is no)
   --enable-komplex        Build komplex (default is no)
   --enable-aztecoo        Build aztecoo (default is yes)
   --enable-belos          Build belos (default is no)
@@ -1886,7 +1888,8 @@ fi
 
 
 
-if test "X$ac_cv_use_tsfcore" != "Xno"; then
+if test "X$ac_cv_use_tsfcore" != "Xno" ||
+  test "X$ac_cv_use_tsfextended" != "Xno"; then
   BUILD_TSFCORE_TRUE=
   BUILD_TSFCORE_FALSE='#'
 else
@@ -1923,12 +1926,49 @@ fi
 
 
 if test "X$ac_cv_use_tsfcoreutils" != "Xno" ||
-	test "X$ac_cv_use_tsfcore" != "Xno"; then
+	test "X$ac_cv_use_tsfcore" != "Xno" ||
+  test "X$ac_cv_use_tsfextended" != "Xno"; then
   BUILD_TSFCOREUTILS_TRUE=
   BUILD_TSFCOREUTILS_FALSE='#'
 else
   BUILD_TSFCOREUTILS_TRUE='#'
   BUILD_TSFCOREUTILS_FALSE=
+fi
+
+
+
+# Check whether --enable-tsfextended or --disable-tsfextended was given.
+if test "${enable_tsfextended+set}" = set; then
+  enableval="$enable_tsfextended"
+  ac_cv_use_tsfextended=$enableval
+else
+  ac_cv_use_tsfextended=no
+fi;
+
+echo "$as_me:$LINENO: checking whether to use tsfextended" >&5
+echo $ECHO_N "checking whether to use tsfextended... $ECHO_C" >&6
+
+if test "X$ac_cv_use_tsfextended" != "Xno"; then
+  echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_TSFEXTENDED
+_ACEOF
+
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+
+
+if test "X$ac_cv_use_tsfextended" != "Xno"; then
+  BUILD_TSFEXTENDED_TRUE=
+  BUILD_TSFEXTENDED_FALSE='#'
+else
+  BUILD_TSFEXTENDED_TRUE='#'
+  BUILD_TSFEXTENDED_FALSE=
 fi
 
 
@@ -2256,6 +2296,7 @@ if test "X$ac_cv_use_teuchos" != "Xno" ||
 	test "X$ac_cv_use_tpetra" != "Xno" ||
 	test "X$ac_cv_use_tsfcore" != "Xno" ||
 	test "X$ac_cv_use_tsfcoreutils" != "Xno" ||
+	test "X$ac_cv_use_tsfextended" != "Xno" ||
 	test "X$ac_cv_use_belos" != "Xno" ||
 	test "X$ac_cv_use_anasazi" != "Xno"; then
   BUILD_TEUCHOS_TRUE=
@@ -2385,6 +2426,7 @@ fi
 if test "X$ac_cv_use_epetra" != "Xno" ||
 	test "X$ac_cv_use_ifpack" != "Xno" ||
 	test "X$ac_cv_use_tsf" != "Xno" ||
+	test "X$ac_cv_use_tsfextended" != "Xno" ||
 	test "X$ac_cv_use_amesos" != "Xno" ||
 	test "X$ac_cv_use_triutils" != "Xno" ||
 	test "X$ac_cv_use_aztecoo" != "Xno" ||
@@ -2464,6 +2506,13 @@ if test "X$ac_cv_use_tsfcore" != "Xno"; then
 
 
 subdirs="$subdirs packages/TSFCore"
+
+fi
+
+if test "X$ac_cv_use_tsfextended" != "Xno"; then
+
+
+subdirs="$subdirs packages/TSFExtended"
 
 fi
 
@@ -2683,6 +2732,13 @@ if test -z "${BUILD_TSFCOREUTILS_TRUE}" && test -z "${BUILD_TSFCOREUTILS_FALSE}"
   { { echo "$as_me:$LINENO: error: conditional \"BUILD_TSFCOREUTILS\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"BUILD_TSFCOREUTILS\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${BUILD_TSFEXTENDED_TRUE}" && test -z "${BUILD_TSFEXTENDED_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"BUILD_TSFEXTENDED\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"BUILD_TSFEXTENDED\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -3322,6 +3378,8 @@ s,@BUILD_TSFCORE_TRUE@,$BUILD_TSFCORE_TRUE,;t t
 s,@BUILD_TSFCORE_FALSE@,$BUILD_TSFCORE_FALSE,;t t
 s,@BUILD_TSFCOREUTILS_TRUE@,$BUILD_TSFCOREUTILS_TRUE,;t t
 s,@BUILD_TSFCOREUTILS_FALSE@,$BUILD_TSFCOREUTILS_FALSE,;t t
+s,@BUILD_TSFEXTENDED_TRUE@,$BUILD_TSFEXTENDED_TRUE,;t t
+s,@BUILD_TSFEXTENDED_FALSE@,$BUILD_TSFEXTENDED_FALSE,;t t
 s,@BUILD_KOMPLEX_TRUE@,$BUILD_KOMPLEX_TRUE,;t t
 s,@BUILD_KOMPLEX_FALSE@,$BUILD_KOMPLEX_FALSE,;t t
 s,@BUILD_AZTECOO_TRUE@,$BUILD_AZTECOO_TRUE,;t t
