Updating the top level autotools setup to recognize ForTrilinos.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -712,6 +712,8 @@ BUILD_DIDASKO_TRUE
 BUILD_DIDASKO_FALSE
 BUILD_WEBTRILINOS_TRUE
 BUILD_WEBTRILINOS_FALSE
+BUILD_FORTRILINOS_TRUE
+BUILD_FORTRILINOS_FALSE
 BUILD_EXTERNAL_TRUE
 BUILD_EXTERNAL_FALSE
 BUILD_MOOCHO_TRUE
@@ -757,6 +759,7 @@ packages/tpetra
 packages/trilinoscouplings
 packages/didasko
 packages/WebTrilinos
+packages/ForTrilinos
 packages/external
 packages/moocho'
 
@@ -1369,6 +1372,9 @@ Optional Features:
                           --disable-default-packages option is used)
   --enable-fei            Build fei, a sparse linear-system assembly package
                           (default is no)
+  --enable-fortrilinos    Build ForTrilinos, a package providing Fortran
+                          wrappers for other Trilinos packages (default is
+                          no)
   --enable-intrepid       Build intrepid, a discretization package (default is
                           no)
   --enable-isorropia      Build isorropia, a repartitioning/rebalancing
@@ -2845,6 +2851,34 @@ echo "${ECHO_T}yes" >&6; }
 
 cat >>confdefs.h <<\_ACEOF
 #define HAVE_FEI
+_ACEOF
+
+else
+  { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+fi
+
+
+
+# Check whether --enable-fortrilinos was given.
+if test "${enable_fortrilinos+set}" = set; then
+  enableval=$enable_fortrilinos; ac_cv_use_fortrilinos=$enableval
+ac_cv_use_fortrilinos_explicit=$enableval
+else
+  ac_cv_use_fortrilinos=no
+ac_cv_use_fortrilinos_explicit=no
+fi
+
+
+{ echo "$as_me:$LINENO: checking whether to use fortrilinos" >&5
+echo $ECHO_N "checking whether to use fortrilinos... $ECHO_C" >&6; }
+
+if test "X$ac_cv_use_fortrilinos" != "Xno"; then
+  { echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6; }
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_FORTRILINOS
 _ACEOF
 
 else
@@ -4361,6 +4395,25 @@ else
 fi
 
 
+if test "X$ac_cv_use_fortrilinos" != "Xno"; then
+  subdirs="$subdirs packages/ForTrilinos"
+
+  BUILD_FORTRILINOS=yes
+  if test "X$ac_cv_use_fortrilinos_explicit" != "Xyes"; then
+    ac_configure_args="$ac_configure_args --enable-fortrilinos"
+  fi
+else
+  BUILD_FORTRILINOS=no
+fi
+ if test "X$BUILD_FORTRILINOS" != "Xno"; then
+  BUILD_FORTRILINOS_TRUE=
+  BUILD_FORTRILINOS_FALSE='#'
+else
+  BUILD_FORTRILINOS_TRUE='#'
+  BUILD_FORTRILINOS_FALSE=
+fi
+
+
 if test "X$ac_cv_use_external" != "Xno"; then
   subdirs="$subdirs packages/external"
 
@@ -4751,6 +4804,13 @@ if test -z "${BUILD_WEBTRILINOS_TRUE}" && test -z "${BUILD_WEBTRILINOS_FALSE}"; 
   { { echo "$as_me:$LINENO: error: conditional \"BUILD_WEBTRILINOS\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"BUILD_WEBTRILINOS\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${BUILD_FORTRILINOS_TRUE}" && test -z "${BUILD_FORTRILINOS_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"BUILD_FORTRILINOS\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"BUILD_FORTRILINOS\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -5465,6 +5525,8 @@ BUILD_DIDASKO_TRUE!$BUILD_DIDASKO_TRUE$ac_delim
 BUILD_DIDASKO_FALSE!$BUILD_DIDASKO_FALSE$ac_delim
 BUILD_WEBTRILINOS_TRUE!$BUILD_WEBTRILINOS_TRUE$ac_delim
 BUILD_WEBTRILINOS_FALSE!$BUILD_WEBTRILINOS_FALSE$ac_delim
+BUILD_FORTRILINOS_TRUE!$BUILD_FORTRILINOS_TRUE$ac_delim
+BUILD_FORTRILINOS_FALSE!$BUILD_FORTRILINOS_FALSE$ac_delim
 BUILD_EXTERNAL_TRUE!$BUILD_EXTERNAL_TRUE$ac_delim
 BUILD_EXTERNAL_FALSE!$BUILD_EXTERNAL_FALSE$ac_delim
 BUILD_MOOCHO_TRUE!$BUILD_MOOCHO_TRUE$ac_delim
@@ -5473,7 +5535,7 @@ LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 42; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 44; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
