Updated toplevel autoconf/automake files for new stokhos package.  Currently stokhos requires teuchos, and sacado can use stokhos.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -688,6 +688,8 @@ BUILD_MEROS_TRUE
 BUILD_MEROS_FALSE
 BUILD_ML_TRUE
 BUILD_ML_FALSE
+BUILD_STOKHOS_TRUE
+BUILD_STOKHOS_FALSE
 BUILD_SACADO_TRUE
 BUILD_SACADO_FALSE
 BUILD_NOX_TRUE
@@ -743,6 +745,7 @@ packages/aristos
 packages/intrepid
 packages/meros
 packages/ml
+packages/stokhos
 packages/sacado
 packages/nox
 packages/isorropia
@@ -1399,6 +1402,8 @@ Optional Features:
                           (default is no)
   --enable-sacado         Build sacado, an automatic differentation package
                           (default is no)
+  --enable-stokhos        Build stokhos, an intrusive stochastic Galerkin
+                          package (default is no)
   --enable-teuchos        Build teuchos, a tools package (default is no)
   --enable-rtop           Build RTOp, a vector reduction/transformation
                           operator package (default is no)
@@ -3271,6 +3276,34 @@ fi
 
 
 
+# Check whether --enable-stokhos was given.
+if test "${enable_stokhos+set}" = set; then
+  enableval=$enable_stokhos; ac_cv_use_stokhos=$enableval
+ac_cv_use_stokhos_explicit=$enableval
+else
+  ac_cv_use_stokhos=no
+ac_cv_use_stokhos_explicit=no
+fi
+
+
+{ echo "$as_me:$LINENO: checking whether to use stokhos" >&5
+echo $ECHO_N "checking whether to use stokhos... $ECHO_C" >&6; }
+
+if test "X$ac_cv_use_stokhos" != "Xno"; then
+  { echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6; }
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_STOKHOS
+_ACEOF
+
+else
+  { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+fi
+
+
+
 # Check whether --enable-teuchos was given.
 if test "${enable_teuchos+set}" = set; then
   enableval=$enable_teuchos; ac_cv_use_teuchos=$enableval
@@ -3605,6 +3638,7 @@ if test "X$ac_cv_use_teuchos" != "Xno" ||
 	test "X$ac_cv_use_rtop" != "Xno" ||
 	test "X$ac_cv_use_rythmos" != "Xno" ||
 	test "X$ac_cv_use_sacado" != "Xno" ||
+	test "X$ac_cv_use_stokhos" != "Xno" ||
 	test "X$ac_cv_use_isorropia" != "Xno" ||
 	test "X$ac_cv_use_moertel" != "Xno" ||
 	test "X$ac_cv_use_webtrilinos" != "Xno" ||
@@ -4083,6 +4117,25 @@ fi
 else
   BUILD_ML_TRUE='#'
   BUILD_ML_FALSE=
+fi
+
+
+if test "X$ac_cv_use_stokhos" != "Xno"; then
+  subdirs="$subdirs packages/stokhos"
+
+  BUILD_STOKHOS=yes
+  if test "X$ac_cv_use_stokhos_explicit" != "Xyes"; then
+    ac_configure_args="$ac_configure_args --enable-stokhos"
+  fi
+else
+  BUILD_STOKHOS=no
+fi
+ if test "X$BUILD_STOKHOS" != "Xno"; then
+  BUILD_STOKHOS_TRUE=
+  BUILD_STOKHOS_FALSE='#'
+else
+  BUILD_STOKHOS_TRUE='#'
+  BUILD_STOKHOS_FALSE=
 fi
 
 
@@ -4614,6 +4667,13 @@ if test -z "${BUILD_ML_TRUE}" && test -z "${BUILD_ML_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"BUILD_ML\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"BUILD_ML\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${BUILD_STOKHOS_TRUE}" && test -z "${BUILD_STOKHOS_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"BUILD_STOKHOS\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"BUILD_STOKHOS\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -5381,6 +5441,8 @@ BUILD_MEROS_TRUE!$BUILD_MEROS_TRUE$ac_delim
 BUILD_MEROS_FALSE!$BUILD_MEROS_FALSE$ac_delim
 BUILD_ML_TRUE!$BUILD_ML_TRUE$ac_delim
 BUILD_ML_FALSE!$BUILD_ML_FALSE$ac_delim
+BUILD_STOKHOS_TRUE!$BUILD_STOKHOS_TRUE$ac_delim
+BUILD_STOKHOS_FALSE!$BUILD_STOKHOS_FALSE$ac_delim
 BUILD_SACADO_TRUE!$BUILD_SACADO_TRUE$ac_delim
 BUILD_SACADO_FALSE!$BUILD_SACADO_FALSE$ac_delim
 BUILD_NOX_TRUE!$BUILD_NOX_TRUE$ac_delim
@@ -5411,7 +5473,7 @@ LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 40; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 42; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
