----------------------------------------------------------------------
 Committing in .

 Modified Files:
 	Makefile.in Trilinos_config.h.in configure configure.ac
 ----------------------------------------------------------------------
The rest of the files to add Didasko to the top level.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -295,7 +295,8 @@ ac_subdirs_all="$ac_subdirs_all packages/ml"
 ac_subdirs_all="$ac_subdirs_all packages/nox"
 ac_subdirs_all="$ac_subdirs_all packages/new_package"
 ac_subdirs_all="$ac_subdirs_all packages/tpetra"
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot subdirs BUILD_TEUCHOS_TRUE BUILD_TEUCHOS_FALSE BUILD_KOKKOS_TRUE BUILD_KOKKOS_FALSE BUILD_EPETRA_TRUE BUILD_EPETRA_FALSE BUILD_TRIUTILS_TRUE BUILD_TRIUTILS_FALSE BUILD_IFPACK_TRUE BUILD_IFPACK_FALSE BUILD_AZTECOO_TRUE BUILD_AZTECOO_FALSE BUILD_CLAPS_TRUE BUILD_CLAPS_FALSE BUILD_KOMPLEX_TRUE BUILD_KOMPLEX_FALSE BUILD_TSF_TRUE BUILD_TSF_FALSE BUILD_TSFCORE_TRUE BUILD_TSFCORE_FALSE BUILD_TSFEXTENDED_TRUE BUILD_TSFEXTENDED_FALSE BUILD_TSFCOREUTILS_TRUE BUILD_TSFCOREUTILS_FALSE BUILD_AMESOS_TRUE BUILD_AMESOS_FALSE BUILD_EPETRAEXT_TRUE BUILD_EPETRAEXT_FALSE BUILD_BELOS_TRUE BUILD_BELOS_FALSE BUILD_ANASAZI_TRUE BUILD_ANASAZI_FALSE BUILD_MEROS_TRUE BUILD_MEROS_FALSE BUILD_ML_TRUE BUILD_ML_FALSE BUILD_NOX_TRUE BUILD_NOX_FALSE BUILD_NEW_PACKAGE_TRUE BUILD_NEW_PACKAGE_FALSE BUILD_TPETRA_TRUE BUILD_TPETRA_FALSE LIBOBJS LTLIBOBJS'
+ac_subdirs_all="$ac_subdirs_all packages/didasko"
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot subdirs BUILD_TEUCHOS_TRUE BUILD_TEUCHOS_FALSE BUILD_KOKKOS_TRUE BUILD_KOKKOS_FALSE BUILD_EPETRA_TRUE BUILD_EPETRA_FALSE BUILD_TRIUTILS_TRUE BUILD_TRIUTILS_FALSE BUILD_IFPACK_TRUE BUILD_IFPACK_FALSE BUILD_AZTECOO_TRUE BUILD_AZTECOO_FALSE BUILD_CLAPS_TRUE BUILD_CLAPS_FALSE BUILD_KOMPLEX_TRUE BUILD_KOMPLEX_FALSE BUILD_TSF_TRUE BUILD_TSF_FALSE BUILD_TSFCORE_TRUE BUILD_TSFCORE_FALSE BUILD_TSFEXTENDED_TRUE BUILD_TSFEXTENDED_FALSE BUILD_TSFCOREUTILS_TRUE BUILD_TSFCOREUTILS_FALSE BUILD_AMESOS_TRUE BUILD_AMESOS_FALSE BUILD_EPETRAEXT_TRUE BUILD_EPETRAEXT_FALSE BUILD_BELOS_TRUE BUILD_BELOS_FALSE BUILD_ANASAZI_TRUE BUILD_ANASAZI_FALSE BUILD_MEROS_TRUE BUILD_MEROS_FALSE BUILD_ML_TRUE BUILD_ML_FALSE BUILD_NOX_TRUE BUILD_NOX_FALSE BUILD_NEW_PACKAGE_TRUE BUILD_NEW_PACKAGE_FALSE BUILD_TPETRA_TRUE BUILD_TPETRA_FALSE BUILD_DIDASKO_TRUE BUILD_DIDASKO_FALSE LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -827,6 +828,8 @@ Optional Features:
                           --disable-default-packages option is used
   --enable-belos          Build belos (default is no)
   --enable-claps          Build claps (default is no)
+  --enable-didasko        Build didasko (a Trilinos tutorial) (default is
+                          no)
   --enable-epetra         Build epetra (default is yes unless the
                           --disable-default-packages option is used
   --enable-epetraext      Build epetraext (default is yes unless the
@@ -1979,6 +1982,34 @@ fi
 
 
 
+# Check whether --enable-didasko or --disable-didasko was given.
+if test "${enable_didasko+set}" = set; then
+  enableval="$enable_didasko"
+  ac_cv_use_didasko=$enableval
+ac_cv_use_didasko_explicit=$enableval
+else
+  ac_cv_use_didasko=no
+ac_cv_use_didasko_explicit=no
+fi;
+
+echo "$as_me:$LINENO: checking whether to use didasko" >&5
+echo $ECHO_N "checking whether to use didasko... $ECHO_C" >&6
+
+if test "X$ac_cv_use_didasko" != "Xno"; then
+  echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_DIDASKO
+_ACEOF
+
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+
+
 # Check whether --enable-epetra or --disable-epetra was given.
 if test "${enable_epetra+set}" = set; then
   enableval="$enable_epetra"
@@ -2980,6 +3011,29 @@ else
 fi
 
 
+if test "X$ac_cv_use_didasko" != "Xno"; then
+
+
+subdirs="$subdirs packages/didasko"
+
+  BUILD_DIDASKO=yes
+  if test "X$ac_cv_use_didasko_explicit" == "Xno"; then
+    ac_configure_args="$ac_configure_args --enable-didasko"
+  fi
+else
+  BUILD_DIDASKO=no
+fi
+
+
+if test "X$BUILD_DIDASKO" != "Xno"; then
+  BUILD_DIDASKO_TRUE=
+  BUILD_DIDASKO_FALSE='#'
+else
+  BUILD_DIDASKO_TRUE='#'
+  BUILD_DIDASKO_FALSE=
+fi
+
+
 # Check whether --enable- or --disable- was given.
 if test "${enable_+set}" = set; then
   enableval="$enable_"
@@ -3229,6 +3283,13 @@ if test -z "${BUILD_TPETRA_TRUE}" && test -z "${BUILD_TPETRA_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"BUILD_TPETRA\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"BUILD_TPETRA\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${BUILD_DIDASKO_TRUE}" && test -z "${BUILD_DIDASKO_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"BUILD_DIDASKO\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"BUILD_DIDASKO\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -3819,6 +3880,8 @@ s,@BUILD_NEW_PACKAGE_TRUE@,$BUILD_NEW_PACKAGE_TRUE,;t t
 s,@BUILD_NEW_PACKAGE_FALSE@,$BUILD_NEW_PACKAGE_FALSE,;t t
 s,@BUILD_TPETRA_TRUE@,$BUILD_TPETRA_TRUE,;t t
 s,@BUILD_TPETRA_FALSE@,$BUILD_TPETRA_FALSE,;t t
+s,@BUILD_DIDASKO_TRUE@,$BUILD_DIDASKO_TRUE,;t t
+s,@BUILD_DIDASKO_FALSE@,$BUILD_DIDASKO_FALSE,;t t
 s,@LIBOBJS@,$LIBOBJS,;t t
 s,@LTLIBOBJS@,$LTLIBOBJS,;t t
 CEOF
