----------------------------------------------------------------------
 Committing in .

 Modified Files:
 	Makefile.in Trilinos_config.h.in aclocal.m4 configure
 	configure.ac packages/Makefile.am packages/Makefile.in
 ----------------------------------------------------------------------
Adding the experimental package "external" to the top level build process.
This package will allow us to tie other packages into a Trilinos build.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -302,7 +302,8 @@ ac_subdirs_all="$ac_subdirs_all packages/PyTrilinos"
 ac_subdirs_all="$ac_subdirs_all packages/rythmos"
 ac_subdirs_all="$ac_subdirs_all packages/tpetra"
 ac_subdirs_all="$ac_subdirs_all packages/didasko"
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot subdirs BUILD_TEUCHOS_TRUE BUILD_TEUCHOS_FALSE BUILD_THYRA_TRUE BUILD_THYRA_FALSE BUILD_KOKKOS_TRUE BUILD_KOKKOS_FALSE BUILD_EPETRA_TRUE BUILD_EPETRA_FALSE BUILD_PLIRIS_TRUE BUILD_PLIRIS_FALSE BUILD_TRIUTILS_TRUE BUILD_TRIUTILS_FALSE BUILD_GALERI_TRUE BUILD_GALERI_FALSE BUILD_IFPACK_TRUE BUILD_IFPACK_FALSE BUILD_AZTECOO_TRUE BUILD_AZTECOO_FALSE BUILD_CLAPS_TRUE BUILD_CLAPS_FALSE BUILD_KOMPLEX_TRUE BUILD_KOMPLEX_FALSE BUILD_TSF_TRUE BUILD_TSF_FALSE BUILD_TSFCORE_TRUE BUILD_TSFCORE_FALSE BUILD_TSFEXTENDED_TRUE BUILD_TSFEXTENDED_FALSE BUILD_TSFCOREUTILS_TRUE BUILD_TSFCOREUTILS_FALSE BUILD_AMESOS_TRUE BUILD_AMESOS_FALSE BUILD_EPETRAEXT_TRUE BUILD_EPETRAEXT_FALSE BUILD_BELOS_TRUE BUILD_BELOS_FALSE BUILD_ANASAZI_TRUE BUILD_ANASAZI_FALSE BUILD_MEROS_TRUE BUILD_MEROS_FALSE BUILD_ML_TRUE BUILD_ML_FALSE BUILD_NOX_TRUE BUILD_NOX_FALSE BUILD_NEW_PACKAGE_TRUE BUILD_NEW_PACKAGE_FALSE BUILD_CAPO_TRUE BUILD_CAPO_FALSE BUILD_PYTRILINOS_TRUE BUILD_PYTRILINOS_FALSE BUILD_RYTHMOS_TRUE BUILD_RYTHMOS_FALSE BUILD_TPETRA_TRUE BUILD_TPETRA_FALSE BUILD_DIDASKO_TRUE BUILD_DIDASKO_FALSE LIBOBJS LTLIBOBJS'
+ac_subdirs_all="$ac_subdirs_all packages/external"
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot subdirs BUILD_TEUCHOS_TRUE BUILD_TEUCHOS_FALSE BUILD_THYRA_TRUE BUILD_THYRA_FALSE BUILD_KOKKOS_TRUE BUILD_KOKKOS_FALSE BUILD_EPETRA_TRUE BUILD_EPETRA_FALSE BUILD_PLIRIS_TRUE BUILD_PLIRIS_FALSE BUILD_TRIUTILS_TRUE BUILD_TRIUTILS_FALSE BUILD_GALERI_TRUE BUILD_GALERI_FALSE BUILD_IFPACK_TRUE BUILD_IFPACK_FALSE BUILD_AZTECOO_TRUE BUILD_AZTECOO_FALSE BUILD_CLAPS_TRUE BUILD_CLAPS_FALSE BUILD_KOMPLEX_TRUE BUILD_KOMPLEX_FALSE BUILD_TSF_TRUE BUILD_TSF_FALSE BUILD_TSFCORE_TRUE BUILD_TSFCORE_FALSE BUILD_TSFEXTENDED_TRUE BUILD_TSFEXTENDED_FALSE BUILD_TSFCOREUTILS_TRUE BUILD_TSFCOREUTILS_FALSE BUILD_AMESOS_TRUE BUILD_AMESOS_FALSE BUILD_EPETRAEXT_TRUE BUILD_EPETRAEXT_FALSE BUILD_BELOS_TRUE BUILD_BELOS_FALSE BUILD_ANASAZI_TRUE BUILD_ANASAZI_FALSE BUILD_MEROS_TRUE BUILD_MEROS_FALSE BUILD_ML_TRUE BUILD_ML_FALSE BUILD_NOX_TRUE BUILD_NOX_FALSE BUILD_NEW_PACKAGE_TRUE BUILD_NEW_PACKAGE_FALSE BUILD_CAPO_TRUE BUILD_CAPO_FALSE BUILD_PYTRILINOS_TRUE BUILD_PYTRILINOS_FALSE BUILD_RYTHMOS_TRUE BUILD_RYTHMOS_FALSE BUILD_TPETRA_TRUE BUILD_TPETRA_FALSE BUILD_DIDASKO_TRUE BUILD_DIDASKO_FALSE BUILD_EXTERNAL_TRUE BUILD_EXTERNAL_FALSE LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -841,6 +842,8 @@ Optional Features:
                           --disable-default-packages option is used
   --enable-epetraext      Build epetraext (default is yes unless the
                           --disable-default-packages option is used
+  --enable-external       Build external package in packages/external (default
+                          is no)
   --enable-ifpack         Build ifpack (default is yes unless the
                           --disable-default-packages option is used
   --enable-kokkos         Build kokkos (default is no)
@@ -1568,7 +1571,7 @@ else
 echo "$as_me: WARNING: \`missing' script is too old or missing" >&2;}
 fi
 
-if mkdir -p --version . >/dev/null 2>&1 && test ! -d ./--version; then
+if mkdir -p -- . 2>/dev/null; then
   # Keeping the `.' argument allows $(mkdir_p) to be used without
   # argument.  Indeed, we sometimes output rules like
   #   $(mkdir_p) $(somedir)
@@ -1581,7 +1584,7 @@ else
   # recognize any option.  It will interpret all options as
   # directories to create, and then abort because `.' already
   # exists.
-  for d in ./-p ./--version;
+  for d in ./-p ./--;
   do
     test -d $d && rmdir $d
   done
@@ -2103,6 +2106,36 @@ echo "${ECHO_T}yes" >&6
 
 cat >>confdefs.h <<\_ACEOF
 #define HAVE_EPETRAEXT
+_ACEOF
+
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+
+#The external package is a mechanism for adding external packages to the Trilinos
+#build process.
+
+# Check whether --enable-external or --disable-external was given.
+if test "${enable_external+set}" = set; then
+  enableval="$enable_external"
+  ac_cv_use_external=$enableval
+ac_cv_use_external_explicit=$enableval
+else
+  ac_cv_use_external=no
+ac_cv_use_external_explicit=no
+fi;
+
+echo "$as_me:$LINENO: checking whether to use external" >&5
+echo $ECHO_N "checking whether to use external... $ECHO_C" >&6
+
+if test "X$ac_cv_use_external" != "Xno"; then
+  echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_EXTERNAL
 _ACEOF
 
 else
@@ -3435,6 +3468,29 @@ else
 fi
 
 
+if test "X$ac_cv_use_external" != "Xno"; then
+
+
+subdirs="$subdirs packages/external"
+
+  BUILD_EXTERNAL=yes
+  if test "X$ac_cv_use_external_explicit" != "Xyes"; then
+    ac_configure_args="$ac_configure_args --enable-external"
+  fi
+else
+  BUILD_EXTERNAL=no
+fi
+
+
+if test "X$BUILD_EXTERNAL" != "Xno"; then
+  BUILD_EXTERNAL_TRUE=
+  BUILD_EXTERNAL_FALSE='#'
+else
+  BUILD_EXTERNAL_TRUE='#'
+  BUILD_EXTERNAL_FALSE=
+fi
+
+
 # Check whether --enable- or --disable- was given.
 if test "${enable_+set}" = set; then
   enableval="$enable_"
@@ -3733,6 +3789,13 @@ if test -z "${BUILD_DIDASKO_TRUE}" && test -z "${BUILD_DIDASKO_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"BUILD_DIDASKO\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"BUILD_DIDASKO\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${BUILD_EXTERNAL_TRUE}" && test -z "${BUILD_EXTERNAL_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"BUILD_EXTERNAL\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"BUILD_EXTERNAL\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -4338,6 +4401,8 @@ s,@BUILD_TPETRA_TRUE@,$BUILD_TPETRA_TRUE,;t t
 s,@BUILD_TPETRA_FALSE@,$BUILD_TPETRA_FALSE,;t t
 s,@BUILD_DIDASKO_TRUE@,$BUILD_DIDASKO_TRUE,;t t
 s,@BUILD_DIDASKO_FALSE@,$BUILD_DIDASKO_FALSE,;t t
+s,@BUILD_EXTERNAL_TRUE@,$BUILD_EXTERNAL_TRUE,;t t
+s,@BUILD_EXTERNAL_FALSE@,$BUILD_EXTERNAL_FALSE,;t t
 s,@LIBOBJS@,$LIBOBJS,;t t
 s,@LTLIBOBJS@,$LTLIBOBJS,;t t
 CEOF
