----------------------------------------------------------------------
 Committing in .

 Modified Files:
 	Makefile.in Trilinos_config.h.in configure configure.ac
 	packages/Makefile.am packages/Makefile.in
 ----------------------------------------------------------------------
Adding Moertel to the top level build system.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -298,13 +298,14 @@ ac_subdirs_all="$ac_subdirs_all packages/ml"
 ac_subdirs_all="$ac_subdirs_all packages/nox"
 ac_subdirs_all="$ac_subdirs_all packages/new_package"
 ac_subdirs_all="$ac_subdirs_all packages/capo"
+ac_subdirs_all="$ac_subdirs_all packages/moertel"
 ac_subdirs_all="$ac_subdirs_all packages/PyTrilinos"
 ac_subdirs_all="$ac_subdirs_all packages/rythmos"
 ac_subdirs_all="$ac_subdirs_all packages/tpetra"
 ac_subdirs_all="$ac_subdirs_all packages/didasko"
 ac_subdirs_all="$ac_subdirs_all packages/external"
 ac_subdirs_all="$ac_subdirs_all packages/moocho"
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot subdirs BUILD_TEUCHOS_TRUE BUILD_TEUCHOS_FALSE BUILD_THYRA_TRUE BUILD_THYRA_FALSE BUILD_KOKKOS_TRUE BUILD_KOKKOS_FALSE BUILD_EPETRA_TRUE BUILD_EPETRA_FALSE BUILD_PLIRIS_TRUE BUILD_PLIRIS_FALSE BUILD_TRIUTILS_TRUE BUILD_TRIUTILS_FALSE BUILD_GALERI_TRUE BUILD_GALERI_FALSE BUILD_IFPACK_TRUE BUILD_IFPACK_FALSE BUILD_AZTECOO_TRUE BUILD_AZTECOO_FALSE BUILD_CLAPS_TRUE BUILD_CLAPS_FALSE BUILD_KOMPLEX_TRUE BUILD_KOMPLEX_FALSE BUILD_TSF_TRUE BUILD_TSF_FALSE BUILD_TSFCORE_TRUE BUILD_TSFCORE_FALSE BUILD_TSFEXTENDED_TRUE BUILD_TSFEXTENDED_FALSE BUILD_TSFCOREUTILS_TRUE BUILD_TSFCOREUTILS_FALSE BUILD_AMESOS_TRUE BUILD_AMESOS_FALSE BUILD_EPETRAEXT_TRUE BUILD_EPETRAEXT_FALSE BUILD_BELOS_TRUE BUILD_BELOS_FALSE BUILD_ANASAZI_TRUE BUILD_ANASAZI_FALSE BUILD_MEROS_TRUE BUILD_MEROS_FALSE BUILD_ML_TRUE BUILD_ML_FALSE BUILD_NOX_TRUE BUILD_NOX_FALSE BUILD_NEW_PACKAGE_TRUE BUILD_NEW_PACKAGE_FALSE BUILD_CAPO_TRUE BUILD_CAPO_FALSE BUILD_PYTRILINOS_TRUE BUILD_PYTRILINOS_FALSE BUILD_RYTHMOS_TRUE BUILD_RYTHMOS_FALSE BUILD_TPETRA_TRUE BUILD_TPETRA_FALSE BUILD_DIDASKO_TRUE BUILD_DIDASKO_FALSE BUILD_EXTERNAL_TRUE BUILD_EXTERNAL_FALSE BUILD_MOOCHO_TRUE BUILD_MOOCHO_FALSE LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot subdirs BUILD_TEUCHOS_TRUE BUILD_TEUCHOS_FALSE BUILD_THYRA_TRUE BUILD_THYRA_FALSE BUILD_KOKKOS_TRUE BUILD_KOKKOS_FALSE BUILD_EPETRA_TRUE BUILD_EPETRA_FALSE BUILD_PLIRIS_TRUE BUILD_PLIRIS_FALSE BUILD_TRIUTILS_TRUE BUILD_TRIUTILS_FALSE BUILD_GALERI_TRUE BUILD_GALERI_FALSE BUILD_IFPACK_TRUE BUILD_IFPACK_FALSE BUILD_AZTECOO_TRUE BUILD_AZTECOO_FALSE BUILD_CLAPS_TRUE BUILD_CLAPS_FALSE BUILD_KOMPLEX_TRUE BUILD_KOMPLEX_FALSE BUILD_TSF_TRUE BUILD_TSF_FALSE BUILD_TSFCORE_TRUE BUILD_TSFCORE_FALSE BUILD_TSFEXTENDED_TRUE BUILD_TSFEXTENDED_FALSE BUILD_TSFCOREUTILS_TRUE BUILD_TSFCOREUTILS_FALSE BUILD_AMESOS_TRUE BUILD_AMESOS_FALSE BUILD_EPETRAEXT_TRUE BUILD_EPETRAEXT_FALSE BUILD_BELOS_TRUE BUILD_BELOS_FALSE BUILD_ANASAZI_TRUE BUILD_ANASAZI_FALSE BUILD_MEROS_TRUE BUILD_MEROS_FALSE BUILD_ML_TRUE BUILD_ML_FALSE BUILD_NOX_TRUE BUILD_NOX_FALSE BUILD_NEW_PACKAGE_TRUE BUILD_NEW_PACKAGE_FALSE BUILD_CAPO_TRUE BUILD_CAPO_FALSE BUILD_MOERTEL_TRUE BUILD_MOERTEL_FALSE BUILD_PYTRILINOS_TRUE BUILD_PYTRILINOS_FALSE BUILD_RYTHMOS_TRUE BUILD_RYTHMOS_FALSE BUILD_TPETRA_TRUE BUILD_TPETRA_FALSE BUILD_DIDASKO_TRUE BUILD_DIDASKO_FALSE BUILD_EXTERNAL_TRUE BUILD_EXTERNAL_FALSE BUILD_MOOCHO_TRUE BUILD_MOOCHO_FALSE LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -852,6 +853,7 @@ Optional Features:
   --enable-loca           Build loca (default is yes unless the
                           --disable-default-packages option is used
   --enable-meros          Build meros (default is no)
+  --enable-moertel        Build moertel (default is no)
   --enable-ml             Build ml (default is yes unless the
                           --disable-default-packages option is used
   --enable-new_package    Build new_package (default is yes unless the
@@ -2287,6 +2289,34 @@ fi
 
 
 
+# Check whether --enable-moertel or --disable-moertel was given.
+if test "${enable_moertel+set}" = set; then
+  enableval="$enable_moertel"
+  ac_cv_use_moertel=$enableval
+ac_cv_use_moertel_explicit=$enableval
+else
+  ac_cv_use_moertel=no
+ac_cv_use_moertel_explicit=no
+fi;
+
+echo "$as_me:$LINENO: checking whether to use moertel" >&5
+echo $ECHO_N "checking whether to use moertel... $ECHO_C" >&6
+
+if test "X$ac_cv_use_moertel" != "Xno"; then
+  echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_MOERTEL
+_ACEOF
+
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+
+
 # Check whether --enable-ml or --disable-ml was given.
 if test "${enable_ml+set}" = set; then
   enableval="$enable_ml"
@@ -2826,6 +2856,7 @@ if test "X$ac_cv_use_teuchos" != "Xno" ||
 	test "X$ac_cv_use_aztecoo_teuchos" != "Xno" ||
 	test "X$ac_cv_use_capo" != "Xno" ||
 	test "X$ac_cv_use_rythmos" != "Xno" ||
+	test "X$ac_cv_use_moertel" != "Xno" ||
 	test "X$ac_cv_use_belos" != "Xno"; then
 
 
@@ -2911,6 +2942,7 @@ if test "X$ac_cv_use_epetra" != "Xno" || test "X$ac_cv_use_ifpack" != "Xno" ||
 	test "X$ac_cv_use_belos" != "Xno" ||
 	test "X$ac_cv_use_anasazi" != "Xno" ||
         test "X$ac_cv_use_claps" != "Xno" ||
+        test "X$ac_cv_use_moertel" != "Xno" ||
 	test "X$ac_cv_use_komplex" != "Xno"; then
 
 
@@ -3192,7 +3224,8 @@ else
 fi
 
 
-if test "X$ac_cv_use_amesos" != "Xno"; then
+if test "X$ac_cv_use_amesos" != "Xno" ||
+        test "X$ac_cv_use_moertel" != "Xno"; then
 
 
 subdirs="$subdirs packages/amesos"
@@ -3216,6 +3249,7 @@ fi
 
 
 if test "X$ac_cv_use_epetraext" != "Xno" ||
+        test "X$ac_cv_use_moertel" != "Xno" ||
 	( test "X$ac_cv_use_thyra" != "Xno" && test "X$ac_cv_use_aztecoo" != "Xno" ); then
 
 
@@ -3308,7 +3342,8 @@ else
 fi
 
 
-if test "X$ac_cv_use_ml" != "Xno"; then
+if test "X$ac_cv_use_ml" != "Xno" ||
+        test "X$ac_cv_use_moertel" != "Xno"; then
 
 
 subdirs="$subdirs packages/ml"
@@ -3402,7 +3437,27 @@ else
 fi
 
 
+if test "X$ac_cv_use_moertel" != "Xno"; then
 
+
+subdirs="$subdirs packages/moertel"
+
+  BUILD_MOERTEL=yes
+  if test "X$ac_cv_use_moertel_explicit" != "Xyes"; then
+    ac_configure_args="$ac_configure_args --enable-moertel"
+  fi
+else
+  BUILD_MOERTEL=no
+fi
+
+
+if test "X$BUILD_MOERTEL" != "Xno"; then
+  BUILD_MOERTEL_TRUE=
+  BUILD_MOERTEL_FALSE='#'
+else
+  BUILD_MOERTEL_TRUE='#'
+  BUILD_MOERTEL_FALSE=
+fi
 
 
 if test "X$ac_cv_use_pytrilinos" != "Xno" ||
@@ -3814,6 +3869,13 @@ if test -z "${BUILD_CAPO_TRUE}" && test -z "${BUILD_CAPO_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"BUILD_CAPO\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"BUILD_CAPO\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${BUILD_MOERTEL_TRUE}" && test -z "${BUILD_MOERTEL_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"BUILD_MOERTEL\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"BUILD_MOERTEL\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -4453,6 +4515,8 @@ s,@BUILD_NEW_PACKAGE_TRUE@,$BUILD_NEW_PACKAGE_TRUE,;t t
 s,@BUILD_NEW_PACKAGE_FALSE@,$BUILD_NEW_PACKAGE_FALSE,;t t
 s,@BUILD_CAPO_TRUE@,$BUILD_CAPO_TRUE,;t t
 s,@BUILD_CAPO_FALSE@,$BUILD_CAPO_FALSE,;t t
+s,@BUILD_MOERTEL_TRUE@,$BUILD_MOERTEL_TRUE,;t t
+s,@BUILD_MOERTEL_FALSE@,$BUILD_MOERTEL_FALSE,;t t
 s,@BUILD_PYTRILINOS_TRUE@,$BUILD_PYTRILINOS_TRUE,;t t
 s,@BUILD_PYTRILINOS_FALSE@,$BUILD_PYTRILINOS_FALSE,;t t
 s,@BUILD_RYTHMOS_TRUE@,$BUILD_RYTHMOS_TRUE,;t t
