Adding WebTrilinos to the top level configure/build system.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -306,9 +306,10 @@ ac_subdirs_all="$ac_subdirs_all packages/PyTrilinos"
 ac_subdirs_all="$ac_subdirs_all packages/rythmos"
 ac_subdirs_all="$ac_subdirs_all packages/tpetra"
 ac_subdirs_all="$ac_subdirs_all packages/didasko"
+ac_subdirs_all="$ac_subdirs_all packages/WebTrilinos"
 ac_subdirs_all="$ac_subdirs_all packages/external"
 ac_subdirs_all="$ac_subdirs_all packages/moocho"
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot subdirs BUILD_TEUCHOS_TRUE BUILD_TEUCHOS_FALSE BUILD_RTOP_TRUE BUILD_RTOP_FALSE BUILD_THYRA_TRUE BUILD_THYRA_FALSE BUILD_STRATIMIKOS_TRUE BUILD_STRATIMIKOS_FALSE BUILD_KOKKOS_TRUE BUILD_KOKKOS_FALSE BUILD_EPETRA_TRUE BUILD_EPETRA_FALSE BUILD_PLIRIS_TRUE BUILD_PLIRIS_FALSE BUILD_TRIUTILS_TRUE BUILD_TRIUTILS_FALSE BUILD_GALERI_TRUE BUILD_GALERI_FALSE BUILD_IFPACK_TRUE BUILD_IFPACK_FALSE BUILD_AZTECOO_TRUE BUILD_AZTECOO_FALSE BUILD_CLAPS_TRUE BUILD_CLAPS_FALSE BUILD_KOMPLEX_TRUE BUILD_KOMPLEX_FALSE BUILD_TSF_TRUE BUILD_TSF_FALSE BUILD_TSFCORE_TRUE BUILD_TSFCORE_FALSE BUILD_TSFEXTENDED_TRUE BUILD_TSFEXTENDED_FALSE BUILD_TSFCOREUTILS_TRUE BUILD_TSFCOREUTILS_FALSE BUILD_AMESOS_TRUE BUILD_AMESOS_FALSE BUILD_EPETRAEXT_TRUE BUILD_EPETRAEXT_FALSE BUILD_BELOS_TRUE BUILD_BELOS_FALSE BUILD_ANASAZI_TRUE BUILD_ANASAZI_FALSE BUILD_MEROS_TRUE BUILD_MEROS_FALSE BUILD_ML_TRUE BUILD_ML_FALSE BUILD_NOX_TRUE BUILD_NOX_FALSE BUILD_ISORROPIA_TRUE BUILD_ISORROPIA_FALSE BUILD_NEW_PACKAGE_TRUE BUILD_NEW_PACKAGE_FALSE BUILD_CAPO_TRUE BUILD_CAPO_FALSE BUILD_MOERTEL_TRUE BUILD_MOERTEL_FALSE BUILD_PYTRILINOS_TRUE BUILD_PYTRILINOS_FALSE BUILD_RYTHMOS_TRUE BUILD_RYTHMOS_FALSE BUILD_TPETRA_TRUE BUILD_TPETRA_FALSE BUILD_DIDASKO_TRUE BUILD_DIDASKO_FALSE BUILD_EXTERNAL_TRUE BUILD_EXTERNAL_FALSE BUILD_MOOCHO_TRUE BUILD_MOOCHO_FALSE LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot subdirs BUILD_TEUCHOS_TRUE BUILD_TEUCHOS_FALSE BUILD_RTOP_TRUE BUILD_RTOP_FALSE BUILD_THYRA_TRUE BUILD_THYRA_FALSE BUILD_STRATIMIKOS_TRUE BUILD_STRATIMIKOS_FALSE BUILD_KOKKOS_TRUE BUILD_KOKKOS_FALSE BUILD_EPETRA_TRUE BUILD_EPETRA_FALSE BUILD_PLIRIS_TRUE BUILD_PLIRIS_FALSE BUILD_TRIUTILS_TRUE BUILD_TRIUTILS_FALSE BUILD_GALERI_TRUE BUILD_GALERI_FALSE BUILD_IFPACK_TRUE BUILD_IFPACK_FALSE BUILD_AZTECOO_TRUE BUILD_AZTECOO_FALSE BUILD_CLAPS_TRUE BUILD_CLAPS_FALSE BUILD_KOMPLEX_TRUE BUILD_KOMPLEX_FALSE BUILD_TSF_TRUE BUILD_TSF_FALSE BUILD_TSFCORE_TRUE BUILD_TSFCORE_FALSE BUILD_TSFEXTENDED_TRUE BUILD_TSFEXTENDED_FALSE BUILD_TSFCOREUTILS_TRUE BUILD_TSFCOREUTILS_FALSE BUILD_AMESOS_TRUE BUILD_AMESOS_FALSE BUILD_EPETRAEXT_TRUE BUILD_EPETRAEXT_FALSE BUILD_BELOS_TRUE BUILD_BELOS_FALSE BUILD_ANASAZI_TRUE BUILD_ANASAZI_FALSE BUILD_MEROS_TRUE BUILD_MEROS_FALSE BUILD_ML_TRUE BUILD_ML_FALSE BUILD_NOX_TRUE BUILD_NOX_FALSE BUILD_ISORROPIA_TRUE BUILD_ISORROPIA_FALSE BUILD_NEW_PACKAGE_TRUE BUILD_NEW_PACKAGE_FALSE BUILD_CAPO_TRUE BUILD_CAPO_FALSE BUILD_MOERTEL_TRUE BUILD_MOERTEL_FALSE BUILD_PYTRILINOS_TRUE BUILD_PYTRILINOS_FALSE BUILD_RYTHMOS_TRUE BUILD_RYTHMOS_FALSE BUILD_TPETRA_TRUE BUILD_TPETRA_FALSE BUILD_DIDASKO_TRUE BUILD_DIDASKO_FALSE BUILD_WEBTRILINOS_TRUE BUILD_WEBTRILINOS_FALSE BUILD_EXTERNAL_TRUE BUILD_EXTERNAL_FALSE BUILD_MOOCHO_TRUE BUILD_MOOCHO_FALSE LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -880,6 +881,7 @@ Optional Features:
   --enable-tsfcore        Build TSFCore (default is no)
   --enable-tsfcoreutils   Build TSFCoreUtils (default is no)
   --enable-tsfextended    Build TSFExtended (default is no)
+  --enable-webtrilinos    Build WebTrilinos (default is no)
   --enable-aztecoo-teuchos
                           Enable AztecOO Teuchos::ParameterList interface.
                           Default is no. Requires Teuchos package.
@@ -1581,7 +1583,7 @@ else
 echo "$as_me: WARNING: \`missing' script is too old or missing" >&2;}
 fi
 
-if mkdir -p --version . >/dev/null 2>&1 && test ! -d ./--version; then
+if mkdir -p -- . 2>/dev/null; then
   # Keeping the `.' argument allows $(mkdir_p) to be used without
   # argument.  Indeed, we sometimes output rules like
   #   $(mkdir_p) $(somedir)
@@ -1594,7 +1596,7 @@ else
   # recognize any option.  It will interpret all options as
   # directories to create, and then abort because `.' already
   # exists.
-  for d in ./-p ./--version;
+  for d in ./-p ./--;
   do
     test -d $d && rmdir $d
   done
@@ -2925,6 +2927,34 @@ echo "${ECHO_T}no" >&6
 fi
 
 
+
+# Check whether --enable-webtrilinos or --disable-webtrilinos was given.
+if test "${enable_webtrilinos+set}" = set; then
+  enableval="$enable_webtrilinos"
+  ac_cv_use_webtrilinos=$enableval
+ac_cv_use_webtrilinos_explicit=$enableval
+else
+  ac_cv_use_webtrilinos=no
+ac_cv_use_webtrilinos_explicit=no
+fi;
+
+echo "$as_me:$LINENO: checking whether to use webtrilinos" >&5
+echo $ECHO_N "checking whether to use webtrilinos... $ECHO_C" >&6
+
+if test "X$ac_cv_use_webtrilinos" != "Xno"; then
+  echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_WEBTRILINOS
+_ACEOF
+
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+
 # Check whether --enable-aztecoo-teuchos or --disable-aztecoo-teuchos was given.
 if test "${enable_aztecoo_teuchos+set}" = set; then
   enableval="$enable_aztecoo_teuchos"
@@ -2952,6 +2982,7 @@ if test "X$ac_cv_use_teuchos" != "Xno" ||
 	test "X$ac_cv_use_rythmos" != "Xno" ||
 	test "X$ac_cv_use_isorropia" != "Xno" ||
 	test "X$ac_cv_use_moertel" != "Xno" ||
+	test "X$ac_cv_use_webtrilinos" != "Xno" ||
 	test "X$ac_cv_use_belos" != "Xno"; then
 
 
@@ -3087,6 +3118,7 @@ if test "X$ac_cv_use_epetra" != "Xno" || test "X$ac_cv_use_ifpack" != "Xno" ||
 	test "X$ac_cv_use_anasazi" != "Xno" ||
         test "X$ac_cv_use_claps" != "Xno" ||
         test "X$ac_cv_use_moertel" != "Xno" ||
+	test "X$ac_cv_use_webtrilinos" != "Xno" ||
 	test "X$ac_cv_use_komplex" != "Xno"; then
 
 
@@ -3159,7 +3191,8 @@ else
 fi
 
 
-if test "X$ac_cv_use_galeri" != "Xno"; then
+if test "X$ac_cv_use_galeri" != "Xno" ||
+	test "X$ac_cv_use_webtrilinos" != "Xno"; then
 
 
 subdirs="$subdirs packages/galeri"
@@ -3182,7 +3215,8 @@ else
 fi
 
 
-if test "X$ac_cv_use_ifpack" != "Xno"; then
+if test "X$ac_cv_use_ifpack" != "Xno" ||
+	test "X$ac_cv_use_webtrilinos" != "Xno"; then
 
 
 subdirs="$subdirs packages/ifpack"
@@ -3207,6 +3241,7 @@ fi
 
 if test "X$ac_cv_use_aztecoo" != "Xno" ||
 	test "X$ac_cv_use_moertel" != "Xno" ||
+	test "X$ac_cv_use_webtrilinos" != "Xno" ||
 	test "X$ac_cv_use_komplex" != "Xno"; then
 
 
@@ -3371,6 +3406,7 @@ fi
 
 
 if test "X$ac_cv_use_amesos" != "Xno" ||
+	test "X$ac_cv_use_webtrilinos" != "Xno" ||
         test "X$ac_cv_use_moertel" != "Xno"; then
 
 
@@ -3396,6 +3432,7 @@ fi
 
 if test "X$ac_cv_use_epetraext" != "Xno" ||
         test "X$ac_cv_use_moertel" != "Xno" ||
+	test "X$ac_cv_use_webtrilinos" != "Xno" ||
 	( test "X$ac_cv_use_thyra" != "Xno" && test "X$ac_cv_use_aztecoo" != "Xno" ); then
 
 
@@ -3489,6 +3526,7 @@ fi
 
 
 if test "X$ac_cv_use_ml" != "Xno" ||
+	test "X$ac_cv_use_webtrilinos" != "Xno" ||
         test "X$ac_cv_use_moertel" != "Xno"; then
 
 
@@ -3630,6 +3668,7 @@ fi
 
 
 if test "X$ac_cv_use_pytrilinos" != "Xno" ||
+	test "X$ac_cv_use_webtrilinos" != "Xno" ||
 	test "X$ac_cv_use_python" != "Xno"; then
 
 
@@ -3719,6 +3758,29 @@ if test "X$BUILD_DIDASKO" != "Xno"; then
 else
   BUILD_DIDASKO_TRUE='#'
   BUILD_DIDASKO_FALSE=
+fi
+
+
+if test "X$ac_cv_use_webtrilinos" != "Xno"; then
+
+
+subdirs="$subdirs packages/WebTrilinos"
+
+  BUILD_WEBTRILINOS=yes
+  if test "X$ac_cv_use_webtrilinos_explicit" != "Xyes"; then
+    ac_configure_args="$ac_configure_args --enable-webtrilinos"
+  fi
+else
+  BUILD_WEBTRILINOS=no
+fi
+
+
+if test "X$BUILD_WEBTRILINOS" != "Xno"; then
+  BUILD_WEBTRILINOS_TRUE=
+  BUILD_WEBTRILINOS_FALSE='#'
+else
+  BUILD_WEBTRILINOS_TRUE='#'
+  BUILD_WEBTRILINOS_FALSE=
 fi
 
 
@@ -4094,6 +4156,13 @@ if test -z "${BUILD_DIDASKO_TRUE}" && test -z "${BUILD_DIDASKO_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"BUILD_DIDASKO\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"BUILD_DIDASKO\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${BUILD_WEBTRILINOS_TRUE}" && test -z "${BUILD_WEBTRILINOS_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"BUILD_WEBTRILINOS\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"BUILD_WEBTRILINOS\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -4721,6 +4790,8 @@ s,@BUILD_TPETRA_TRUE@,$BUILD_TPETRA_TRUE,;t t
 s,@BUILD_TPETRA_FALSE@,$BUILD_TPETRA_FALSE,;t t
 s,@BUILD_DIDASKO_TRUE@,$BUILD_DIDASKO_TRUE,;t t
 s,@BUILD_DIDASKO_FALSE@,$BUILD_DIDASKO_FALSE,;t t
+s,@BUILD_WEBTRILINOS_TRUE@,$BUILD_WEBTRILINOS_TRUE,;t t
+s,@BUILD_WEBTRILINOS_FALSE@,$BUILD_WEBTRILINOS_FALSE,;t t
 s,@BUILD_EXTERNAL_TRUE@,$BUILD_EXTERNAL_TRUE,;t t
 s,@BUILD_EXTERNAL_FALSE@,$BUILD_EXTERNAL_FALSE,;t t
 s,@BUILD_MOOCHO_TRUE@,$BUILD_MOOCHO_TRUE,;t t
