Added Intrepid to Trilinos make system.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -680,6 +680,8 @@ BUILD_RBGEN_TRUE
 BUILD_RBGEN_FALSE
 BUILD_ARISTOS_TRUE
 BUILD_ARISTOS_FALSE
+BUILD_INTREPID_TRUE
+BUILD_INTREPID_FALSE
 BUILD_MEROS_TRUE
 BUILD_MEROS_FALSE
 BUILD_ML_TRUE
@@ -737,6 +739,7 @@ packages/belos
 packages/anasazi
 packages/rbgen
 packages/aristos
+packages/intrepid
 packages/meros
 packages/ml
 packages/sacado
@@ -1363,6 +1366,8 @@ Optional Features:
   --enable-ifpack         Build ifpack, an algebraic preconditioner package
                           (default is yes unless the
                           --disable-default-packages option is used)
+  --enable-intrepid       Build intrepid, a discretization package (default is
+                          no)
   --enable-isorropia      Build isorropia, a repartitioning/rebalancing
                           package (default is no)
   --enable-kokkos         Build kokkos, a sparse kernels package (default is
@@ -2842,6 +2847,34 @@ fi
 
 
 
+# Check whether --enable-intrepid was given.
+if test "${enable_intrepid+set}" = set; then
+  enableval=$enable_intrepid; ac_cv_use_intrepid=$enableval
+ac_cv_use_intrepid_explicit=$enableval
+else
+  ac_cv_use_intrepid=no
+ac_cv_use_intrepid_explicit=no
+fi
+
+
+{ echo "$as_me:$LINENO: checking whether to use intrepid" >&5
+echo $ECHO_N "checking whether to use intrepid... $ECHO_C" >&6; }
+
+if test "X$ac_cv_use_intrepid" != "Xno"; then
+  { echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6; }
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_INTREPID
+_ACEOF
+
+else
+  { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+fi
+
+
+
 # Check whether --enable-isorropia was given.
 if test "${enable_isorropia+set}" = set; then
   enableval=$enable_isorropia; ac_cv_use_isorropia=$enableval
@@ -3949,6 +3982,25 @@ else
 fi
 
 
+if test "X$ac_cv_use_intrepid" != "Xno"; then
+  subdirs="$subdirs packages/intrepid"
+
+  BUILD_INTREPID=yes
+  if test "X$ac_cv_use_intrepid_explicit" != "Xyes"; then
+    ac_configure_args="$ac_configure_args --enable-intrepid"
+  fi
+else
+  BUILD_INTREPID=no
+fi
+ if test "X$BUILD_INTREPID" != "Xno"; then
+  BUILD_INTREPID_TRUE=
+  BUILD_INTREPID_FALSE='#'
+else
+  BUILD_INTREPID_TRUE='#'
+  BUILD_INTREPID_FALSE=
+fi
+
+
 if test "X$ac_cv_use_meros" != "Xno"; then
   subdirs="$subdirs packages/meros"
 
@@ -4499,6 +4551,13 @@ if test -z "${BUILD_ARISTOS_TRUE}" && test -z "${BUILD_ARISTOS_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"BUILD_ARISTOS\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"BUILD_ARISTOS\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${BUILD_INTREPID_TRUE}" && test -z "${BUILD_INTREPID_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"BUILD_INTREPID\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"BUILD_INTREPID\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -5279,6 +5338,8 @@ BUILD_RBGEN_TRUE!$BUILD_RBGEN_TRUE$ac_delim
 BUILD_RBGEN_FALSE!$BUILD_RBGEN_FALSE$ac_delim
 BUILD_ARISTOS_TRUE!$BUILD_ARISTOS_TRUE$ac_delim
 BUILD_ARISTOS_FALSE!$BUILD_ARISTOS_FALSE$ac_delim
+BUILD_INTREPID_TRUE!$BUILD_INTREPID_TRUE$ac_delim
+BUILD_INTREPID_FALSE!$BUILD_INTREPID_FALSE$ac_delim
 BUILD_MEROS_TRUE!$BUILD_MEROS_TRUE$ac_delim
 BUILD_MEROS_FALSE!$BUILD_MEROS_FALSE$ac_delim
 BUILD_ML_TRUE!$BUILD_ML_TRUE$ac_delim
@@ -5315,7 +5376,7 @@ LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 38; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 40; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
