----------------------------------------------------------------------
 Committing in .

 Modified Files:
 	Makefile.in Trilinos_config.h.in configure configure.ac
 	packages/Makefile.in
 ----------------------------------------------------------------------
Added Claps to the top level configure build process.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -280,6 +280,7 @@ ac_subdirs_all="$ac_subdirs_all packages/epetra"
 ac_subdirs_all="$ac_subdirs_all packages/triutils"
 ac_subdirs_all="$ac_subdirs_all packages/ifpack"
 ac_subdirs_all="$ac_subdirs_all packages/aztecoo"
+ac_subdirs_all="$ac_subdirs_all packages/claps"
 ac_subdirs_all="$ac_subdirs_all packages/komplex"
 ac_subdirs_all="$ac_subdirs_all packages/TSF"
 ac_subdirs_all="$ac_subdirs_all packages/TSFCore"
@@ -294,7 +295,7 @@ ac_subdirs_all="$ac_subdirs_all packages/ml"
 ac_subdirs_all="$ac_subdirs_all packages/nox"
 ac_subdirs_all="$ac_subdirs_all packages/new_package"
 ac_subdirs_all="$ac_subdirs_all packages/tpetra"
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot BUILD_AMESOS_TRUE BUILD_AMESOS_FALSE BUILD_NOX_TRUE BUILD_NOX_FALSE BUILD_MEROS_TRUE BUILD_MEROS_FALSE BUILD_TSF_TRUE BUILD_TSF_FALSE BUILD_TSFEXTENDED_TRUE BUILD_TSFEXTENDED_FALSE BUILD_TSFCORE_TRUE BUILD_TSFCORE_FALSE BUILD_TSFCOREUTILS_TRUE BUILD_TSFCOREUTILS_FALSE BUILD_KOMPLEX_TRUE BUILD_KOMPLEX_FALSE BUILD_AZTECOO_TRUE BUILD_AZTECOO_FALSE BUILD_BELOS_TRUE BUILD_BELOS_FALSE BUILD_ANASAZI_TRUE BUILD_ANASAZI_FALSE BUILD_IFPACK_TRUE BUILD_IFPACK_FALSE BUILD_TRIUTILS_TRUE BUILD_TRIUTILS_FALSE BUILD_EPETRAEXT_TRUE BUILD_EPETRAEXT_FALSE BUILD_TPETRA_TRUE BUILD_TPETRA_FALSE BUILD_TEUCHOS_TRUE BUILD_TEUCHOS_FALSE BUILD_ML_TRUE BUILD_ML_FALSE BUILD_NEW_PACKAGE_TRUE BUILD_NEW_PACKAGE_FALSE subdirs BUILD_EPETRA_TRUE BUILD_EPETRA_FALSE BUILD_KOKKOS_TRUE BUILD_KOKKOS_FALSE LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot BUILD_AMESOS_TRUE BUILD_AMESOS_FALSE BUILD_NOX_TRUE BUILD_NOX_FALSE BUILD_MEROS_TRUE BUILD_MEROS_FALSE BUILD_TSF_TRUE BUILD_TSF_FALSE BUILD_TSFEXTENDED_TRUE BUILD_TSFEXTENDED_FALSE BUILD_TSFCORE_TRUE BUILD_TSFCORE_FALSE BUILD_TSFCOREUTILS_TRUE BUILD_TSFCOREUTILS_FALSE BUILD_KOMPLEX_TRUE BUILD_KOMPLEX_FALSE BUILD_AZTECOO_TRUE BUILD_AZTECOO_FALSE BUILD_CLAPS_TRUE BUILD_CLAPS_FALSE BUILD_BELOS_TRUE BUILD_BELOS_FALSE BUILD_ANASAZI_TRUE BUILD_ANASAZI_FALSE BUILD_IFPACK_TRUE BUILD_IFPACK_FALSE BUILD_TRIUTILS_TRUE BUILD_TRIUTILS_FALSE BUILD_EPETRAEXT_TRUE BUILD_EPETRAEXT_FALSE BUILD_TPETRA_TRUE BUILD_TPETRA_FALSE BUILD_TEUCHOS_TRUE BUILD_TEUCHOS_FALSE BUILD_ML_TRUE BUILD_ML_FALSE BUILD_NEW_PACKAGE_TRUE BUILD_NEW_PACKAGE_FALSE subdirs BUILD_EPETRA_TRUE BUILD_EPETRA_FALSE BUILD_KOKKOS_TRUE BUILD_KOKKOS_FALSE LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -836,6 +837,7 @@ Optional Features:
   --enable-aztecoo-teuchos
                           Enable AztecOO Teuchos::ParameterList interface.
                           Default is no. Requires Teuchos package.
+  --enable-claps          Build claps (default is no)
   --enable-belos          Build belos (default is no)
   --enable-anasazi        Build anasazi (default is no)
   --enable-ifpack         Build ifpack (default is yes unless the
@@ -2204,6 +2206,41 @@ else
 fi;
 
 
+# Check whether --enable-claps or --disable-claps was given.
+if test "${enable_claps+set}" = set; then
+  enableval="$enable_claps"
+  ac_cv_use_claps=$enableval
+else
+  ac_cv_use_claps=no
+fi;
+
+echo "$as_me:$LINENO: checking whether to use claps" >&5
+echo $ECHO_N "checking whether to use claps... $ECHO_C" >&6
+
+if test "X$ac_cv_use_claps" != "Xno"; then
+  echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_CLAPS
+_ACEOF
+
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+
+
+if test "X$ac_cv_use_claps" != "Xno"; then
+  BUILD_CLAPS_TRUE=
+  BUILD_CLAPS_FALSE='#'
+else
+  BUILD_CLAPS_TRUE='#'
+  BUILD_CLAPS_FALSE=
+fi
+
+
 
 # Check whether --enable-belos or --disable-belos was given.
 if test "${enable_belos+set}" = set; then
@@ -2601,6 +2638,7 @@ if test "X$ac_cv_use_epetra" != "Xno" ||
 	test "X$ac_cv_use_anasazi" != "Xno" ||
 	test "X$ac_cv_use_new_package" != "Xno" ||
         test "X$ac_cv_use_epetraext" != "Xno"  ||
+        test "X$ac_cv_use_claps" != "Xno"  ||
         test "X$ac_cv_use_meros" != "Xno"; then
   BUILD_EPETRA_TRUE=
   BUILD_EPETRA_FALSE='#'
@@ -2666,6 +2704,7 @@ if test "X$ac_cv_use_epetra" != "Xno" || test "X$ac_cv_use_ifpack" != "Xno" ||
         test "X$ac_cv_use_epetraext" != "Xno" ||
 	test "X$ac_cv_use_belos" != "Xno" ||
 	test "X$ac_cv_use_anasazi" != "Xno" ||
+        test "X$ac_cv_use_claps" != "Xno" ||
 	test "X$ac_cv_use_komplex" != "Xno"; then
 
 
@@ -2696,6 +2735,13 @@ if test "X$ac_cv_use_aztecoo" != "Xno" ||
 
 
 subdirs="$subdirs packages/aztecoo"
+
+fi
+
+if test "X$ac_cv_use_claps" != "Xno"; then
+
+
+subdirs="$subdirs packages/claps"
 
 fi
 
@@ -2968,6 +3014,13 @@ if test -z "${BUILD_AZTECOO_TRUE}" && test -z "${BUILD_AZTECOO_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"BUILD_AZTECOO\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"BUILD_AZTECOO\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${BUILD_CLAPS_TRUE}" && test -z "${BUILD_CLAPS_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"BUILD_CLAPS\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"BUILD_CLAPS\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -3610,6 +3663,8 @@ s,@BUILD_KOMPLEX_TRUE@,$BUILD_KOMPLEX_TRUE,;t t
 s,@BUILD_KOMPLEX_FALSE@,$BUILD_KOMPLEX_FALSE,;t t
 s,@BUILD_AZTECOO_TRUE@,$BUILD_AZTECOO_TRUE,;t t
 s,@BUILD_AZTECOO_FALSE@,$BUILD_AZTECOO_FALSE,;t t
+s,@BUILD_CLAPS_TRUE@,$BUILD_CLAPS_TRUE,;t t
+s,@BUILD_CLAPS_FALSE@,$BUILD_CLAPS_FALSE,;t t
 s,@BUILD_BELOS_TRUE@,$BUILD_BELOS_TRUE,;t t
 s,@BUILD_BELOS_FALSE@,$BUILD_BELOS_FALSE,;t t
 s,@BUILD_ANASAZI_TRUE@,$BUILD_ANASAZI_TRUE,;t t
