Stratimikos is born.  There is still a lot more work to do on testing and documentation but the basics of the class are finished.  I added a new extended Operator/Solve interface called Thyra::LinearSolverBuilderBase that the default implementation in Stratimikos derives from.  Again, there is lots of more work to do but the basics are finished.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -277,6 +277,7 @@ ac_unique_file="packages/epetra/src/Epetra_Object.h"
 ac_subdirs_all="$ac_subdirs_all packages/teuchos"
 ac_subdirs_all="$ac_subdirs_all packages/rtop"
 ac_subdirs_all="$ac_subdirs_all packages/thyra"
+ac_subdirs_all="$ac_subdirs_all packages/stratimikos"
 ac_subdirs_all="$ac_subdirs_all packages/kokkos"
 ac_subdirs_all="$ac_subdirs_all packages/epetra"
 ac_subdirs_all="$ac_subdirs_all packages/pliris"
@@ -307,7 +308,7 @@ ac_subdirs_all="$ac_subdirs_all packages/tpetra"
 ac_subdirs_all="$ac_subdirs_all packages/didasko"
 ac_subdirs_all="$ac_subdirs_all packages/external"
 ac_subdirs_all="$ac_subdirs_all packages/moocho"
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot subdirs BUILD_TEUCHOS_TRUE BUILD_TEUCHOS_FALSE BUILD_RTOP_TRUE BUILD_RTOP_FALSE BUILD_THYRA_TRUE BUILD_THYRA_FALSE BUILD_KOKKOS_TRUE BUILD_KOKKOS_FALSE BUILD_EPETRA_TRUE BUILD_EPETRA_FALSE BUILD_PLIRIS_TRUE BUILD_PLIRIS_FALSE BUILD_TRIUTILS_TRUE BUILD_TRIUTILS_FALSE BUILD_GALERI_TRUE BUILD_GALERI_FALSE BUILD_IFPACK_TRUE BUILD_IFPACK_FALSE BUILD_AZTECOO_TRUE BUILD_AZTECOO_FALSE BUILD_CLAPS_TRUE BUILD_CLAPS_FALSE BUILD_KOMPLEX_TRUE BUILD_KOMPLEX_FALSE BUILD_TSF_TRUE BUILD_TSF_FALSE BUILD_TSFCORE_TRUE BUILD_TSFCORE_FALSE BUILD_TSFEXTENDED_TRUE BUILD_TSFEXTENDED_FALSE BUILD_TSFCOREUTILS_TRUE BUILD_TSFCOREUTILS_FALSE BUILD_AMESOS_TRUE BUILD_AMESOS_FALSE BUILD_EPETRAEXT_TRUE BUILD_EPETRAEXT_FALSE BUILD_BELOS_TRUE BUILD_BELOS_FALSE BUILD_ANASAZI_TRUE BUILD_ANASAZI_FALSE BUILD_MEROS_TRUE BUILD_MEROS_FALSE BUILD_ML_TRUE BUILD_ML_FALSE BUILD_NOX_TRUE BUILD_NOX_FALSE BUILD_ISORROPIA_TRUE BUILD_ISORROPIA_FALSE BUILD_NEW_PACKAGE_TRUE BUILD_NEW_PACKAGE_FALSE BUILD_CAPO_TRUE BUILD_CAPO_FALSE BUILD_MOERTEL_TRUE BUILD_MOERTEL_FALSE BUILD_PYTRILINOS_TRUE BUILD_PYTRILINOS_FALSE BUILD_RYTHMOS_TRUE BUILD_RYTHMOS_FALSE BUILD_TPETRA_TRUE BUILD_TPETRA_FALSE BUILD_DIDASKO_TRUE BUILD_DIDASKO_FALSE BUILD_EXTERNAL_TRUE BUILD_EXTERNAL_FALSE BUILD_MOOCHO_TRUE BUILD_MOOCHO_FALSE LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot subdirs BUILD_TEUCHOS_TRUE BUILD_TEUCHOS_FALSE BUILD_RTOP_TRUE BUILD_RTOP_FALSE BUILD_THYRA_TRUE BUILD_THYRA_FALSE BUILD_STRATIMIKOS_TRUE BUILD_STRATIMIKOS_FALSE BUILD_KOKKOS_TRUE BUILD_KOKKOS_FALSE BUILD_EPETRA_TRUE BUILD_EPETRA_FALSE BUILD_PLIRIS_TRUE BUILD_PLIRIS_FALSE BUILD_TRIUTILS_TRUE BUILD_TRIUTILS_FALSE BUILD_GALERI_TRUE BUILD_GALERI_FALSE BUILD_IFPACK_TRUE BUILD_IFPACK_FALSE BUILD_AZTECOO_TRUE BUILD_AZTECOO_FALSE BUILD_CLAPS_TRUE BUILD_CLAPS_FALSE BUILD_KOMPLEX_TRUE BUILD_KOMPLEX_FALSE BUILD_TSF_TRUE BUILD_TSF_FALSE BUILD_TSFCORE_TRUE BUILD_TSFCORE_FALSE BUILD_TSFEXTENDED_TRUE BUILD_TSFEXTENDED_FALSE BUILD_TSFCOREUTILS_TRUE BUILD_TSFCOREUTILS_FALSE BUILD_AMESOS_TRUE BUILD_AMESOS_FALSE BUILD_EPETRAEXT_TRUE BUILD_EPETRAEXT_FALSE BUILD_BELOS_TRUE BUILD_BELOS_FALSE BUILD_ANASAZI_TRUE BUILD_ANASAZI_FALSE BUILD_MEROS_TRUE BUILD_MEROS_FALSE BUILD_ML_TRUE BUILD_ML_FALSE BUILD_NOX_TRUE BUILD_NOX_FALSE BUILD_ISORROPIA_TRUE BUILD_ISORROPIA_FALSE BUILD_NEW_PACKAGE_TRUE BUILD_NEW_PACKAGE_FALSE BUILD_CAPO_TRUE BUILD_CAPO_FALSE BUILD_MOERTEL_TRUE BUILD_MOERTEL_FALSE BUILD_PYTRILINOS_TRUE BUILD_PYTRILINOS_FALSE BUILD_RYTHMOS_TRUE BUILD_RYTHMOS_FALSE BUILD_TPETRA_TRUE BUILD_TPETRA_FALSE BUILD_DIDASKO_TRUE BUILD_DIDASKO_FALSE BUILD_EXTERNAL_TRUE BUILD_EXTERNAL_FALSE BUILD_MOOCHO_TRUE BUILD_MOOCHO_FALSE LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -870,6 +871,7 @@ Optional Features:
   --enable-teuchos        Build teuchos (default is no)
   --enable-rtop           Build RTOP (default is no)
   --enable-thyra          Build thyra (default is no)
+  --enable-stratimikos    Build stratimikos (default is no)
   --enable-moocho         Build moocho (default is no)
   --enable-tpetra         Build tpetra (default is no)
   --enable-triutils       Build triutils (default is no)
@@ -2672,6 +2674,34 @@ fi
 
 
 
+# Check whether --enable-stratimikos or --disable-stratimikos was given.
+if test "${enable_stratimikos+set}" = set; then
+  enableval="$enable_stratimikos"
+  ac_cv_use_stratimikos=$enableval
+ac_cv_use_stratimikos_explicit=$enableval
+else
+  ac_cv_use_stratimikos=no
+ac_cv_use_stratimikos_explicit=no
+fi;
+
+echo "$as_me:$LINENO: checking whether to use stratimikos" >&5
+echo $ECHO_N "checking whether to use stratimikos... $ECHO_C" >&6
+
+if test "X$ac_cv_use_stratimikos" != "Xno"; then
+  echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_STRATIMIKOS
+_ACEOF
+
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+
+
 # Check whether --enable-moocho or --disable-moocho was given.
 if test "${enable_moocho+set}" = set; then
   enableval="$enable_moocho"
@@ -2905,6 +2935,7 @@ fi;
 
 if test "X$ac_cv_use_teuchos" != "Xno" ||
 	test "X$ac_cv_use_thyra" != "Xno" ||
+	test "X$ac_cv_use_stratimikos" != "Xno" ||
 	test "X$ac_cv_use_tpetra" != "Xno" ||
         test "X$ac_cv_use_tsfextended" != "Xno" ||
  	test "X$ac_cv_use_tsfcore" != "Xno" ||
@@ -2971,7 +3002,8 @@ fi
 
 if test "X$ac_cv_use_thyra" != "Xno" ||
 	test "X$ac_cv_use_capo" != "Xno" ||
-	test "X$ac_cv_use_rythmos" != "Xno"; then
+	test "X$ac_cv_use_rythmos" != "Xno" ||
+	test "X$ac_cv_use_stratimikos" != "Xno"; then
 
 
 subdirs="$subdirs packages/thyra"
@@ -2991,6 +3023,29 @@ if test "X$BUILD_THYRA" != "Xno"; then
 else
   BUILD_THYRA_TRUE='#'
   BUILD_THYRA_FALSE=
+fi
+
+
+if test "X$ac_cv_use_stratimikos" != "Xno"; then
+
+
+subdirs="$subdirs packages/stratimikos"
+
+  BUILD_STRATIMIKOS=yes
+  if test "X$ac_cv_use_stratimikos_explicit" != "Xyes"; then
+    ac_configure_args="$ac_configure_args --enable-stratimikos"
+  fi
+else
+  BUILD_STRATIMIKOS=no
+fi
+
+
+if test "X$BUILD_STRATIMIKOS" != "Xno"; then
+  BUILD_STRATIMIKOS_TRUE=
+  BUILD_STRATIMIKOS_FALSE='#'
+else
+  BUILD_STRATIMIKOS_TRUE='#'
+  BUILD_STRATIMIKOS_FALSE=
 fi
 
 
@@ -3839,6 +3894,13 @@ echo "$as_me: error: conditional \"BUILD_THYRA\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
+if test -z "${BUILD_STRATIMIKOS_TRUE}" && test -z "${BUILD_STRATIMIKOS_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"BUILD_STRATIMIKOS\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"BUILD_STRATIMIKOS\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
 if test -z "${BUILD_KOKKOS_TRUE}" && test -z "${BUILD_KOKKOS_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"BUILD_KOKKOS\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
@@ -4601,6 +4663,8 @@ s,@BUILD_RTOP_TRUE@,$BUILD_RTOP_TRUE,;t t
 s,@BUILD_RTOP_FALSE@,$BUILD_RTOP_FALSE,;t t
 s,@BUILD_THYRA_TRUE@,$BUILD_THYRA_TRUE,;t t
 s,@BUILD_THYRA_FALSE@,$BUILD_THYRA_FALSE,;t t
+s,@BUILD_STRATIMIKOS_TRUE@,$BUILD_STRATIMIKOS_TRUE,;t t
+s,@BUILD_STRATIMIKOS_FALSE@,$BUILD_STRATIMIKOS_FALSE,;t t
 s,@BUILD_KOKKOS_TRUE@,$BUILD_KOKKOS_TRUE,;t t
 s,@BUILD_KOKKOS_FALSE@,$BUILD_KOKKOS_FALSE,;t t
 s,@BUILD_EPETRA_TRUE@,$BUILD_EPETRA_TRUE,;t t
