----------------------------------------------------------------------
 Committing in .

 Modified Files:
 	Makefile.in Trilinos_config.h.in configure configure.ac
 	packages/Makefile.am packages/Makefile.in
 ----------------------------------------------------------------------
These changes allow Pliris to be built from the top level.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -277,6 +277,7 @@ ac_unique_file="packages/epetra/src/Epetra_Object.h"
 ac_subdirs_all="$ac_subdirs_all packages/teuchos"
 ac_subdirs_all="$ac_subdirs_all packages/kokkos"
 ac_subdirs_all="$ac_subdirs_all packages/epetra"
+ac_subdirs_all="$ac_subdirs_all packages/pliris"
 ac_subdirs_all="$ac_subdirs_all packages/triutils"
 ac_subdirs_all="$ac_subdirs_all packages/ifpack"
 ac_subdirs_all="$ac_subdirs_all packages/aztecoo"
@@ -297,7 +298,7 @@ ac_subdirs_all="$ac_subdirs_all packages/new_package"
 ac_subdirs_all="$ac_subdirs_all packages/PyTrilinos"
 ac_subdirs_all="$ac_subdirs_all packages/tpetra"
 ac_subdirs_all="$ac_subdirs_all packages/didasko"
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot subdirs BUILD_TEUCHOS_TRUE BUILD_TEUCHOS_FALSE BUILD_KOKKOS_TRUE BUILD_KOKKOS_FALSE BUILD_EPETRA_TRUE BUILD_EPETRA_FALSE BUILD_TRIUTILS_TRUE BUILD_TRIUTILS_FALSE BUILD_IFPACK_TRUE BUILD_IFPACK_FALSE BUILD_AZTECOO_TRUE BUILD_AZTECOO_FALSE BUILD_CLAPS_TRUE BUILD_CLAPS_FALSE BUILD_KOMPLEX_TRUE BUILD_KOMPLEX_FALSE BUILD_TSF_TRUE BUILD_TSF_FALSE BUILD_TSFCORE_TRUE BUILD_TSFCORE_FALSE BUILD_TSFEXTENDED_TRUE BUILD_TSFEXTENDED_FALSE BUILD_TSFCOREUTILS_TRUE BUILD_TSFCOREUTILS_FALSE BUILD_AMESOS_TRUE BUILD_AMESOS_FALSE BUILD_EPETRAEXT_TRUE BUILD_EPETRAEXT_FALSE BUILD_BELOS_TRUE BUILD_BELOS_FALSE BUILD_ANASAZI_TRUE BUILD_ANASAZI_FALSE BUILD_MEROS_TRUE BUILD_MEROS_FALSE BUILD_ML_TRUE BUILD_ML_FALSE BUILD_NOX_TRUE BUILD_NOX_FALSE BUILD_NEW_PACKAGE_TRUE BUILD_NEW_PACKAGE_FALSE BUILD_PYTRILINOS_TRUE BUILD_PYTRILINOS_FALSE BUILD_TPETRA_TRUE BUILD_TPETRA_FALSE BUILD_DIDASKO_TRUE BUILD_DIDASKO_FALSE LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot subdirs BUILD_TEUCHOS_TRUE BUILD_TEUCHOS_FALSE BUILD_KOKKOS_TRUE BUILD_KOKKOS_FALSE BUILD_EPETRA_TRUE BUILD_EPETRA_FALSE BUILD_PLIRIS_TRUE BUILD_PLIRIS_FALSE BUILD_TRIUTILS_TRUE BUILD_TRIUTILS_FALSE BUILD_IFPACK_TRUE BUILD_IFPACK_FALSE BUILD_AZTECOO_TRUE BUILD_AZTECOO_FALSE BUILD_CLAPS_TRUE BUILD_CLAPS_FALSE BUILD_KOMPLEX_TRUE BUILD_KOMPLEX_FALSE BUILD_TSF_TRUE BUILD_TSF_FALSE BUILD_TSFCORE_TRUE BUILD_TSFCORE_FALSE BUILD_TSFEXTENDED_TRUE BUILD_TSFEXTENDED_FALSE BUILD_TSFCOREUTILS_TRUE BUILD_TSFCOREUTILS_FALSE BUILD_AMESOS_TRUE BUILD_AMESOS_FALSE BUILD_EPETRAEXT_TRUE BUILD_EPETRAEXT_FALSE BUILD_BELOS_TRUE BUILD_BELOS_FALSE BUILD_ANASAZI_TRUE BUILD_ANASAZI_FALSE BUILD_MEROS_TRUE BUILD_MEROS_FALSE BUILD_ML_TRUE BUILD_ML_FALSE BUILD_NOX_TRUE BUILD_NOX_FALSE BUILD_NEW_PACKAGE_TRUE BUILD_NEW_PACKAGE_FALSE BUILD_PYTRILINOS_TRUE BUILD_PYTRILINOS_FALSE BUILD_TPETRA_TRUE BUILD_TPETRA_FALSE BUILD_DIDASKO_TRUE BUILD_DIDASKO_FALSE LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -848,6 +849,7 @@ Optional Features:
                           --disable-default-packages option is used
   --enable-nox            Build nox (default is yes unless the
                           --disable-default-packages option is used
+  --enable-pliris         Build pliris (default is no)
   --enable-pytrilinos     Build PyTrilinos (default is no)
   --enable-teuchos        Build teuchos (default is no)
   --enable-tpetra         Build tpetra (default is no)
@@ -2294,6 +2296,34 @@ fi
 
 
 
+# Check whether --enable-pliris or --disable-pliris was given.
+if test "${enable_pliris+set}" = set; then
+  enableval="$enable_pliris"
+  ac_cv_use_pliris=$enableval
+ac_cv_use_pliris_explicit=$enableval
+else
+  ac_cv_use_pliris=no
+ac_cv_use_pliris_explicit=no
+fi;
+
+echo "$as_me:$LINENO: checking whether to use pliris" >&5
+echo $ECHO_N "checking whether to use pliris... $ECHO_C" >&6
+
+if test "X$ac_cv_use_pliris" != "Xno"; then
+  echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_PLIRIS
+_ACEOF
+
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+
+
 # Check whether --enable-pytrilinos or --disable-pytrilinos was given.
 if test "${enable_pytrilinos+set}" = set; then
   enableval="$enable_pytrilinos"
@@ -2616,6 +2646,29 @@ else
 fi
 
 
+if test "X$ac_cv_use_pliris" != "Xno"; then
+
+
+subdirs="$subdirs packages/pliris"
+
+  BUILD_PLIRIS=yes
+  if test "X$ac_cv_use_pliris_explicit" != "Xyes"; then
+    ac_configure_args="$ac_configure_args --enable-pliris"
+  fi
+else
+  BUILD_PLIRIS=no
+fi
+
+
+if test "X$BUILD_PLIRIS" != "Xno"; then
+  BUILD_PLIRIS_TRUE=
+  BUILD_PLIRIS_FALSE='#'
+else
+  BUILD_PLIRIS_TRUE='#'
+  BUILD_PLIRIS_FALSE=
+fi
+
+
 if test "X$ac_cv_use_triutils" != "Xno" ||
 	test "X$ac_cv_use_aztecoo" != "Xno" ||
 	test "X$ac_cv_use_anasazi" != "Xno" ||
@@ -2632,6 +2685,7 @@ subdirs="$subdirs packages/triutils"
 else
   BUILD_TRIUTILS=no
 fi
+
 
 
 if test "X$BUILD_TRIUTILS" != "Xno"; then
@@ -3210,6 +3264,13 @@ if test -z "${BUILD_EPETRA_TRUE}" && test -z "${BUILD_EPETRA_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"BUILD_EPETRA\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"BUILD_EPETRA\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${BUILD_PLIRIS_TRUE}" && test -z "${BUILD_PLIRIS_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"BUILD_PLIRIS\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"BUILD_PLIRIS\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -3904,6 +3965,8 @@ s,@BUILD_KOKKOS_TRUE@,$BUILD_KOKKOS_TRUE,;t t
 s,@BUILD_KOKKOS_FALSE@,$BUILD_KOKKOS_FALSE,;t t
 s,@BUILD_EPETRA_TRUE@,$BUILD_EPETRA_TRUE,;t t
 s,@BUILD_EPETRA_FALSE@,$BUILD_EPETRA_FALSE,;t t
+s,@BUILD_PLIRIS_TRUE@,$BUILD_PLIRIS_TRUE,;t t
+s,@BUILD_PLIRIS_FALSE@,$BUILD_PLIRIS_FALSE,;t t
 s,@BUILD_TRIUTILS_TRUE@,$BUILD_TRIUTILS_TRUE,;t t
 s,@BUILD_TRIUTILS_FALSE@,$BUILD_TRIUTILS_FALSE,;t t
 s,@BUILD_IFPACK_TRUE@,$BUILD_IFPACK_TRUE,;t t
