Adding the trilinoscouplings package to the top level build process.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -702,6 +702,8 @@ BUILD_RYTHMOS_TRUE
 BUILD_RYTHMOS_FALSE
 BUILD_TPETRA_TRUE
 BUILD_TPETRA_FALSE
+BUILD_TRILINOSCOUPLINGS_TRUE
+BUILD_TRILINOSCOUPLINGS_FALSE
 BUILD_DIDASKO_TRUE
 BUILD_DIDASKO_FALSE
 BUILD_WEBTRILINOS_TRUE
@@ -746,6 +748,7 @@ packages/moertel
 packages/PyTrilinos
 packages/rythmos
 packages/tpetra
+packages/trilinoscouplings
 packages/didasko
 packages/WebTrilinos
 packages/external
@@ -1402,6 +1405,9 @@ Optional Features:
                           no)
   --enable-tpetra         Build tpetra, a templated linear algebra package
                           (default is no)
+  --enable-trilinoscouplings
+                          Build trilinoscouplings, a package of interfaces
+                          between Trilinos packages (default is no)
   --enable-triutils       Build triutils, a utility package (default is no)
   --enable-galeri         Build galeri, a gallery package (default is no)
   --enable-webtrilinos    Build WebTrilinos, a web interface package (default
@@ -3404,6 +3410,34 @@ fi
 
 
 
+# Check whether --enable-trilinoscouplings was given.
+if test "${enable_trilinoscouplings+set}" = set; then
+  enableval=$enable_trilinoscouplings; ac_cv_use_trilinoscouplings=$enableval
+ac_cv_use_trilinoscouplings_explicit=$enableval
+else
+  ac_cv_use_trilinoscouplings=no
+ac_cv_use_trilinoscouplings_explicit=no
+fi
+
+
+{ echo "$as_me:$LINENO: checking whether to use trilinoscouplings" >&5
+echo $ECHO_N "checking whether to use trilinoscouplings... $ECHO_C" >&6; }
+
+if test "X$ac_cv_use_trilinoscouplings" != "Xno"; then
+  { echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6; }
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_TRILINOSCOUPLINGS
+_ACEOF
+
+else
+  { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+fi
+
+
+
 # Check whether --enable-triutils was given.
 if test "${enable_triutils+set}" = set; then
   enableval=$enable_triutils; ac_cv_use_triutils=$enableval
@@ -4136,6 +4170,25 @@ else
 fi
 
 
+if test "X$ac_cv_use_trilinoscouplings" != "Xno"; then
+  subdirs="$subdirs packages/trilinoscouplings"
+
+  BUILD_TRILINOSCOUPLINGS=yes
+  if test "X$ac_cv_use_trilinoscouplings_explicit" != "Xyes"; then
+    ac_configure_args="$ac_configure_args --enable-trilinoscouplings"
+  fi
+else
+  BUILD_TRILINOSCOUPLINGS=no
+fi
+ if test "X$BUILD_TRILINOSCOUPLINGS" != "Xno"; then
+  BUILD_TRILINOSCOUPLINGS_TRUE=
+  BUILD_TRILINOSCOUPLINGS_FALSE='#'
+else
+  BUILD_TRILINOSCOUPLINGS_TRUE='#'
+  BUILD_TRILINOSCOUPLINGS_FALSE=
+fi
+
+
 if test "X$ac_cv_use_didasko" != "Xno"; then
   subdirs="$subdirs packages/didasko"
 
@@ -4529,6 +4582,13 @@ if test -z "${BUILD_TPETRA_TRUE}" && test -z "${BUILD_TPETRA_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"BUILD_TPETRA\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"BUILD_TPETRA\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${BUILD_TRILINOSCOUPLINGS_TRUE}" && test -z "${BUILD_TRILINOSCOUPLINGS_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"BUILD_TRILINOSCOUPLINGS\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"BUILD_TRILINOSCOUPLINGS\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -5247,6 +5307,8 @@ BUILD_RYTHMOS_TRUE!$BUILD_RYTHMOS_TRUE$ac_delim
 BUILD_RYTHMOS_FALSE!$BUILD_RYTHMOS_FALSE$ac_delim
 BUILD_TPETRA_TRUE!$BUILD_TPETRA_TRUE$ac_delim
 BUILD_TPETRA_FALSE!$BUILD_TPETRA_FALSE$ac_delim
+BUILD_TRILINOSCOUPLINGS_TRUE!$BUILD_TRILINOSCOUPLINGS_TRUE$ac_delim
+BUILD_TRILINOSCOUPLINGS_FALSE!$BUILD_TRILINOSCOUPLINGS_FALSE$ac_delim
 BUILD_DIDASKO_TRUE!$BUILD_DIDASKO_TRUE$ac_delim
 BUILD_DIDASKO_FALSE!$BUILD_DIDASKO_FALSE$ac_delim
 BUILD_WEBTRILINOS_TRUE!$BUILD_WEBTRILINOS_TRUE$ac_delim
@@ -5259,7 +5321,7 @@ LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 36; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 38; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
