Changing the way we build Trilinos so that "make" simply builds the libraries. Tests and examples will be built with "make tests" and "make examples", respectively.  I will send a note with more details to the developer list after I am done making these changes.

diff --git a/packages/komplex/configure b/packages/komplex/configure
--- a/packages/komplex/configure
+++ b/packages/komplex/configure
@@ -737,6 +737,10 @@ USING_PERL_TRUE
 USING_PERL_FALSE
 USING_GNUMAKE_TRUE
 USING_GNUMAKE_FALSE
+BUILD_EXAMPLES_TRUE
+BUILD_EXAMPLES_FALSE
+SUB_EXAMPLE_TRUE
+SUB_EXAMPLE_FALSE
 FLIBS
 XTRALDADD
 ac_aux_dir
@@ -1349,6 +1353,13 @@ Optional Features:
                           always created and used in the build directory, but
                           will not be installable without this option to
                           change the paths. (default is yes)
+  --enable-examples       Make examples for all Trilinos packages buildable
+                          with 'make examples' (default is yes)
+
+  --enable-komplex-examples
+                          Make Komplex examples buildable with 'make examples'
+                          (default is yes if --disable-examples is not
+                          specified)
 
 Optional Packages:
   --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
@@ -5292,25 +5303,6 @@ fi
 
 
 # ------------------------------------------------------------------------
-# Special check for case of running on TFLOP
-# ------------------------------------------------------------------------
-
-{ echo "$as_me:$LINENO: checking if host is TFLOP (and therefore needs special TFLOP define statement)" >&5
-echo $ECHO_N "checking if host is TFLOP (and therefore needs special TFLOP define statement)... $ECHO_C" >&6; }
-if test "X${host}" = "Xtflop"; then
-  { echo "$as_me:$LINENO: result: yes" >&5
-echo "${ECHO_T}yes" >&6; }
-
-cat >>confdefs.h <<\_ACEOF
-#define TFLOP
-_ACEOF
-
-else
-  { echo "$as_me:$LINENO: result: no" >&5
-echo "${ECHO_T}no" >&6; }
-fi
-
-# ------------------------------------------------------------------------
 # Checks for header files
 # ------------------------------------------------------------------------
 
@@ -7653,8 +7645,90 @@ fi
 
 
 # ------------------------------------------------------------------------
-# Checks for special package flags
+# Checks if tests and examples should be built
 # ------------------------------------------------------------------------
+
+
+# Check whether --enable-examples was given.
+if test "${enable_examples+set}" = set; then
+  enableval=$enable_examples; ac_cv_use_examples=$enableval
+else
+  ac_cv_use_examples=yes
+fi
+
+
+{ echo "$as_me:$LINENO: checking whether to use examples" >&5
+echo $ECHO_N "checking whether to use examples... $ECHO_C" >&6; }
+
+if test "X$ac_cv_use_examples" != "Xno"; then
+  { echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6; }
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_EXAMPLES
+_ACEOF
+
+else
+  { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+fi
+
+
+# Check whether --enable-examples was given.
+if test "${enable_examples+set}" = set; then
+  enableval=$enable_examples; ac_cv_use_examples=$enableval
+else
+  ac_cv_use_examples=yes
+fi
+
+
+# Check whether --enable-komplex-examples was given.
+if test "${enable_komplex_examples+set}" = set; then
+  enableval=$enable_komplex_examples; ac_cv_use_komplex_examples=$enableval
+else
+  ac_cv_use_komplex_examples=${ac_cv_use_examples}
+fi
+
+
+{ echo "$as_me:$LINENO: checking whether to use komplex-examples" >&5
+echo $ECHO_N "checking whether to use komplex-examples... $ECHO_C" >&6; }
+
+if test "X$ac_cv_use_komplex_examples" != "Xno"; then
+  { echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6; }
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_KOMPLEX_EXAMPLES
+_ACEOF
+
+else
+  { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+fi
+
+ if test "X$ac_cv_use_komplex_examples" != "Xno"; then
+  BUILD_EXAMPLES_TRUE=
+  BUILD_EXAMPLES_FALSE='#'
+else
+  BUILD_EXAMPLES_TRUE='#'
+  BUILD_EXAMPLES_FALSE=
+fi
+
+
+#We now build tests and examples through separate make targets, rather than
+#during "make".  We still need to conditionally include the test and example
+#in SUBDIRS, even though SUB_TEST and SUB_EXAMPLE will never be
+#defined, so that the tests and examples are included in the distribution
+#tarball.
+#AM_CONDITIONAL(SUB_TEST, test "X$ac_cv_use_sub_test" = "Xyes")
+ if test "X$ac_cv_use_sub_example" = "Xyes"; then
+  SUB_EXAMPLE_TRUE=
+  SUB_EXAMPLE_FALSE='#'
+else
+  SUB_EXAMPLE_TRUE='#'
+  SUB_EXAMPLE_FALSE=
+fi
+
 
 # ------------------------------------------------------------------------
 # Specify other directories
@@ -9229,6 +9303,20 @@ echo "$as_me: error: conditional \"USING_GNUMAKE\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
+if test -z "${BUILD_EXAMPLES_TRUE}" && test -z "${BUILD_EXAMPLES_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"BUILD_EXAMPLES\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"BUILD_EXAMPLES\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${SUB_EXAMPLE_TRUE}" && test -z "${SUB_EXAMPLE_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"SUB_EXAMPLE\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"SUB_EXAMPLE\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
 
 : ${CONFIG_STATUS=./config.status}
 ac_clean_files_save=$ac_clean_files
@@ -9927,13 +10015,17 @@ USING_PERL_TRUE!$USING_PERL_TRUE$ac_delim
 USING_PERL_FALSE!$USING_PERL_FALSE$ac_delim
 USING_GNUMAKE_TRUE!$USING_GNUMAKE_TRUE$ac_delim
 USING_GNUMAKE_FALSE!$USING_GNUMAKE_FALSE$ac_delim
+BUILD_EXAMPLES_TRUE!$BUILD_EXAMPLES_TRUE$ac_delim
+BUILD_EXAMPLES_FALSE!$BUILD_EXAMPLES_FALSE$ac_delim
+SUB_EXAMPLE_TRUE!$SUB_EXAMPLE_TRUE$ac_delim
+SUB_EXAMPLE_FALSE!$SUB_EXAMPLE_FALSE$ac_delim
 FLIBS!$FLIBS$ac_delim
 XTRALDADD!$XTRALDADD$ac_delim
 ac_aux_dir!$ac_aux_dir$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 29; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 33; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
