SUMMARY: Few small RTOp refactorings, support for g++ checked STL, etc.
BUGS: None filed

CHECKLIST:

1) Did you add any source or other files needed for building, testing,
   or documentation? Yes
1.a) Did you do a 'cvs add'? Yes
1.b) Did you add them to a Makefile.am file in some way (either as
     a header or soruce file or to EXTRA_DIST)? Yes
1.c) Did you do a new bootstrap? Yes

2) Did you update or change the build system (other than just adding
   source files)? Yes
2.a) Did you remember to do a bootstrap and do a 'cvs add' on any
     Makefile.am files and Makefile.in files you created? Yes

3) Did you do a cvs update *very* recently before rebuilding and
   retesting? Yes

4) If justified, did you type 'make partial-clean' and then rebuild all
   libraries and executables with 'make everything'? [???]

5) Did you rerun the test suite on at least the packages that you
   changed (rerunning the entire Trlinos test suite on all affected
   packages is *strongly* recommended)? Yes, all 879 tests run passed.

COMMENTS:

Specific changes:

(*) packages/ifpack/src/Ifpack_ConfigDefs.h : Just added vertical space

(*) packages/rtop/src/interfaces/RTOpPack_RTOpT[Decl].hpp: Removed the '_new'
from apply_op and reduce_reduct_obj functions.  This will smooth refactoring
(I think).

(*) packages/rtop/src/ops_lib/RTOpPack_ROpDotProd.hpp,
packages/rtop/src/ops_lib/RTOpPack_ROpNorm1.hpp,
packages/rtop/src/ops_lib/RTOpPack_ROpNorm2.hpp,
packages/rtop/src/ops_lib/RTOpPack_ROpNormInf.hpp,
packages/rtop/src/ops_lib/RTOpPack_ROpSum.hpp: Rewrote using new helper macros

(*) packages/rtop/src/support/RTOpPack_RTOpTHelpers.hpp: Added some new macros
to make it easier to define new RTOps.  So far just a few cases are supported
but more will come.

(*) packages/rtop/test/ops_lib/Makefile.[am,in]: New unit tests added

(*) packages/rtop/test/ops_lib/ROpDotProd_UnitTests.cpp,
packages/rtop/test/ops_lib/ROpNorm1_UnitTests.cpp,
packages/rtop/test/ops_lib/ROpNorm2_UnitTests.cpp,
packages/rtop/test/ops_lib/ROpNormInf_UnitTests.cpp,
packages/rtop/test/ops_lib/ROpSum_UnitTests.cpp,
packages/rtop/test/ops_lib/opsUnitTests.cpp,
packages/rtop/test/ops_lib/opsUnitTestsHelpers.cpp,
packages/rtop/test/ops_lib/opsUnitTestsHelpers.hpp: Broke the unit tests up
into separate files for faster rebuild/retest cycles.

(*) packages/teuchos/configure[.ac], packages/teuchos/src/Teuchos_config.h.in
packages/teuchos/src/Teuchos_ConfigDefs.hpp,
packages/teuchos/test/MemoryManagement/GCC_CheckedSTL_UnitTests.cpp,
packages/teuchos/test/MemoryManagement/Makefile.[am,in],
packages/teuchos/test/definition: Added --enable-gcc-checkedstl to support
_GXXLIB_DEBUG define that turns on the checked STL in g++.  I also added a
unit test for this.  This currently does not work for all of Trilinos because
some packages (e.g. ml and ifpack) don't include Teuchos_config.h correctly
before they include their standard C++ headers.  I have not tested this but I
suspect that if you define CPPFLAGS=-D_GXXLIB_DEBUG and
--enable-gcc-checkedstl that all of Trilinos will compile (but may not run if
everyone is not using the STL correctly).

(*) packages/teuchos/src/Teuchos_ParameterList.hpp: Minor reformat

(*) packages/teuchos/src/Teuchos_UnitTestHelpers.hpp,
packages/teuchos/test/UnitTest/vector_UnitTests.cpp: Added macro to simplify
static initailizations in unit tests.

(*) packages/teuchos/src/Teuchos_UnitTestRepository.cpp: Added --no-op
command-line argument to allow you to just see what tests would run without
actually running them.

(*) packages/teuchos/test/MemoryManagement/Array_UnitTests.cpp: Starting to
add true unit-test versions for testing Teuchos::Array.  This is not finished
yet.

(*) sampleScripts/linux-gabriel-gcc-3.3.4-serial-debug: Added testing for
boost and rbgen.

diff --git a/packages/teuchos/configure b/packages/teuchos/configure
--- a/packages/teuchos/configure
+++ b/packages/teuchos/configure
@@ -740,6 +740,8 @@ SUB_TEST_TRUE
 SUB_TEST_FALSE
 SUB_EXAMPLE_TRUE
 SUB_EXAMPLE_FALSE
+HAVE_GCC_CHECKEDSTL_TRUE
+HAVE_GCC_CHECKEDSTL_FALSE
 HAVE_TEUCHOS_COMPLEX_TRUE
 HAVE_TEUCHOS_COMPLEX_FALSE
 HAVE_TEUCHOS_EXTENDED_TRUE
@@ -1382,6 +1384,8 @@ Optional Features:
                           examples are also disabled. Cannot be disabled when
                           fortran is disabled. (default is yes)
   --enable-teuchos-abc    Enable array bounds checking (default is no)
+  --enable-gcc-checkedstl Enable the checked STL for compatible gcc compilers
+                          (default is no)
   --enable-teuchos-complex
                           Enable Teuchos complex code (default is yes)
   --enable-teuchos-extended
@@ -7485,6 +7489,43 @@ else
 echo "${ECHO_T}no" >&6; }
 fi
 
+
+#
+#  --enable-gcc-checkedstl
+#
+
+
+# Check whether --enable-gcc-checkedstl was given.
+if test "${enable_gcc_checkedstl+set}" = set; then
+  enableval=$enable_gcc_checkedstl; ac_cv_use_gcc_checkedstl=$enableval
+else
+  ac_cv_use_gcc_checkedstl=no
+fi
+
+
+{ echo "$as_me:$LINENO: checking whether to use gcc-checkedstl" >&5
+echo $ECHO_N "checking whether to use gcc-checkedstl... $ECHO_C" >&6; }
+
+if test "X$ac_cv_use_gcc_checkedstl" != "Xno"; then
+  { echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6; }
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_GCC_CHECKEDSTL
+_ACEOF
+
+else
+  { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+fi
+
+ if test "X$ac_cv_use_gcc_checkedstl" != "Xno"; then
+  HAVE_GCC_CHECKEDSTL_TRUE=
+  HAVE_GCC_CHECKEDSTL_FALSE='#'
+else
+  HAVE_GCC_CHECKEDSTL_TRUE='#'
+  HAVE_GCC_CHECKEDSTL_FALSE=
+fi
 
 
 # ------------------------------------------------------------------------
@@ -16650,6 +16691,13 @@ echo "$as_me: error: conditional \"SUB_EXAMPLE\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
+if test -z "${HAVE_GCC_CHECKEDSTL_TRUE}" && test -z "${HAVE_GCC_CHECKEDSTL_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"HAVE_GCC_CHECKEDSTL\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"HAVE_GCC_CHECKEDSTL\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
 if test -z "${HAVE_TEUCHOS_COMPLEX_TRUE}" && test -z "${HAVE_TEUCHOS_COMPLEX_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"HAVE_TEUCHOS_COMPLEX\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
@@ -17433,6 +17481,8 @@ SUB_TEST_TRUE!$SUB_TEST_TRUE$ac_delim
 SUB_TEST_FALSE!$SUB_TEST_FALSE$ac_delim
 SUB_EXAMPLE_TRUE!$SUB_EXAMPLE_TRUE$ac_delim
 SUB_EXAMPLE_FALSE!$SUB_EXAMPLE_FALSE$ac_delim
+HAVE_GCC_CHECKEDSTL_TRUE!$HAVE_GCC_CHECKEDSTL_TRUE$ac_delim
+HAVE_GCC_CHECKEDSTL_FALSE!$HAVE_GCC_CHECKEDSTL_FALSE$ac_delim
 HAVE_TEUCHOS_COMPLEX_TRUE!$HAVE_TEUCHOS_COMPLEX_TRUE$ac_delim
 HAVE_TEUCHOS_COMPLEX_FALSE!$HAVE_TEUCHOS_COMPLEX_FALSE$ac_delim
 HAVE_TEUCHOS_EXTENDED_TRUE!$HAVE_TEUCHOS_EXTENDED_TRUE$ac_delim
@@ -17460,7 +17510,7 @@ LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 53; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 55; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
