SUMMARY: Changing long long and MPI logic with explicit --enable-teuchos-long_long
BUGS: 3999

CHECKLIST:

1) Did you add any source or other files needed for building, testing,
   or documentation? No

2) Did you update or change the build system (other than just adding
   source files)? Yes
2.a) Did you remember to do a bootstrap and do a 'cvs add' on any
     Makefile.am files and Makefile.in files you created? Yes

3) Did you do a cvs update *very* recently before rebuilding and
   retesting? Yes

4) If justified, did you type 'make partial-clean' and then rebuild all
   libraries and executables with 'make everything'? No, just rebuilt
   teuchos serial debug without long long and mpi optimized with long long
   (and without -pedantic).  This has only been in Trilinos 1 day so little
   chance this extends outside of teuchos yet.

5) Did you rerun the test suite on at least the packages that you
   changed (rerunning the entire Trlinos test suite on all affected
   packages is *strongly* recommended)? No, just the teuchos test suite
   for serial debug and mpi optimized (with long long).  All passed.

COMMENTS:

(*) teuchos/configure.ac, Teuchos_config.h.in: Added
--enable-teuchos-long_long and HAVE_TEUCHOS_LONG_LONG_INT (off by defaut)

(*) Teuchos_ConfigDefs.hpp: Removed bad logic that set
HAVE_TEUCHOS_LONG_LONG_INT based on HAVE_MPI.

(*) Teuchos_OrdinalTraits.hpp, DefaultMpiComm_UnitTests.cpp: Fixed misspelling
of HAVE_TEUCHOS_LONG_LONG_INT

(*) commonTools/test/harness/invoke-configures/linux-gabriel-gcc_3.4.6-mpi:
Added --enable-teuchos-long_long

(*) linux-gabriel-gcc-3.3.4-serial-debug: Minor reformatting.

(*) linux-gabriel-gcc-3.3.4-mpi-opt: Added the configure scirpt I actally use
on gabriel.sandia.gov.  I keep a soft link to this file so you can be sure
that it is up to date.

(*) Teuchos_ParameterListAcceptorDefaultBase.hpp: Fixed documentation typo.

diff --git a/packages/teuchos/configure b/packages/teuchos/configure
--- a/packages/teuchos/configure
+++ b/packages/teuchos/configure
@@ -744,6 +744,8 @@ HAVE_GCC_CHECKEDSTL_TRUE
 HAVE_GCC_CHECKEDSTL_FALSE
 HAVE_TEUCHOS_COMPLEX_TRUE
 HAVE_TEUCHOS_COMPLEX_FALSE
+HAVE_TEUCHOS_LONG_LONG_INT_TRUE
+HAVE_TEUCHOS_LONG_LONG_INT_FALSE
 HAVE_TEUCHOS_EXTENDED_TRUE
 HAVE_TEUCHOS_EXTENDED_FALSE
 HAVE_TEUCHOS_BLASFLOAT_TRUE
@@ -1388,6 +1390,9 @@ Optional Features:
                           (default is no)
   --enable-teuchos-complex
                           Enable Teuchos complex code (default is yes)
+  --enable-teuchos-long_long
+                          Enable long long int support in Teuchos (default is
+                          no)
   --enable-teuchos-extended
                           Enable Teuchos extended code (default is yes)
   --enable-teuchos-arprec Enable Teuchos interface support for the ARbitrary
@@ -7567,6 +7572,44 @@ fi
 else
   HAVE_TEUCHOS_COMPLEX_TRUE='#'
   HAVE_TEUCHOS_COMPLEX_FALSE=
+fi
+
+
+#
+#  --enable-teuchos-long-long
+#
+
+
+# Check whether --enable-teuchos-long_long was given.
+if test "${enable_teuchos_long_long+set}" = set; then
+  enableval=$enable_teuchos_long_long; ac_cv_use_teuchos_long_long=$enableval
+else
+  ac_cv_use_teuchos_long_long=no
+fi
+
+
+{ echo "$as_me:$LINENO: checking whether to use teuchos-long_long" >&5
+echo $ECHO_N "checking whether to use teuchos-long_long... $ECHO_C" >&6; }
+
+if test "X$ac_cv_use_teuchos_long_long" != "Xno"; then
+  { echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6; }
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_TEUCHOS_LONG_LONG_INT
+_ACEOF
+
+else
+  { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+fi
+
+ if test "X$ac_cv_use_teuchos_long_long_int" != "Xno"; then
+  HAVE_TEUCHOS_LONG_LONG_INT_TRUE=
+  HAVE_TEUCHOS_LONG_LONG_INT_FALSE='#'
+else
+  HAVE_TEUCHOS_LONG_LONG_INT_TRUE='#'
+  HAVE_TEUCHOS_LONG_LONG_INT_FALSE=
 fi
 
 
@@ -16897,6 +16940,13 @@ echo "$as_me: error: conditional \"HAVE_TEUCHOS_COMPLEX\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
+if test -z "${HAVE_TEUCHOS_LONG_LONG_INT_TRUE}" && test -z "${HAVE_TEUCHOS_LONG_LONG_INT_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"HAVE_TEUCHOS_LONG_LONG_INT\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"HAVE_TEUCHOS_LONG_LONG_INT\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
 if test -z "${HAVE_TEUCHOS_EXTENDED_TRUE}" && test -z "${HAVE_TEUCHOS_EXTENDED_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"HAVE_TEUCHOS_EXTENDED\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
@@ -17677,6 +17727,8 @@ HAVE_GCC_CHECKEDSTL_TRUE!$HAVE_GCC_CHECKEDSTL_TRUE$ac_delim
 HAVE_GCC_CHECKEDSTL_FALSE!$HAVE_GCC_CHECKEDSTL_FALSE$ac_delim
 HAVE_TEUCHOS_COMPLEX_TRUE!$HAVE_TEUCHOS_COMPLEX_TRUE$ac_delim
 HAVE_TEUCHOS_COMPLEX_FALSE!$HAVE_TEUCHOS_COMPLEX_FALSE$ac_delim
+HAVE_TEUCHOS_LONG_LONG_INT_TRUE!$HAVE_TEUCHOS_LONG_LONG_INT_TRUE$ac_delim
+HAVE_TEUCHOS_LONG_LONG_INT_FALSE!$HAVE_TEUCHOS_LONG_LONG_INT_FALSE$ac_delim
 HAVE_TEUCHOS_EXTENDED_TRUE!$HAVE_TEUCHOS_EXTENDED_TRUE$ac_delim
 HAVE_TEUCHOS_EXTENDED_FALSE!$HAVE_TEUCHOS_EXTENDED_FALSE$ac_delim
 HAVE_TEUCHOS_BLASFLOAT_TRUE!$HAVE_TEUCHOS_BLASFLOAT_TRUE$ac_delim
@@ -17702,7 +17754,7 @@ LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 55; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 57; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
