I updated scalar traits some.
One of the major changes I made was to add a configure-time test for <limits> and std::numeric_limits<>.  I then put in an #ifdef so that Teuchos::ScalarTraits can use this standard class for the definition of certain constants instead of the LAPACK routine.  Not only is this faster but my version of LAPACK that configure found did not have this routine.  When std::numeric_limits<> is available this should be used.

For now I only updated the eps() function but I can also update some of the other functions too.

Another change was to add support of generating NaN (the new nan() function) and a test for NAN or Inf (the new isnaninf() function).  I took the test for NaN/Inf from NOX and this seems to be a really good and portable test.  This test only requires that the hardward support the IEEE standard, not the C++ compiler (which has been a problem with checking x!=x as a test for NaN since most compilers are too smart and just return true at compile time).

I have run the test suite for both debug and optimized versions and they check out.

diff --git a/packages/teuchos/configure b/packages/teuchos/configure
--- a/packages/teuchos/configure
+++ b/packages/teuchos/configure
@@ -4501,10 +4501,8 @@ fi
 
 
 #  #np# - Customize the checks for headers needed in package being added.
-#NOTE: This section still needs to be updated for new_package, it is still
-# code from Epetra
 # ------------------------------------------------------------------------
-# Checks for header files - used in Epetra_ConfigDefs.h
+# Checks for header files - used in Teuchos_ConfigDefs.h
 # ------------------------------------------------------------------------
 
 echo "$as_me:$LINENO: checking for egrep" >&5
@@ -6111,7 +6109,7 @@ esac
 
 
 # ------------------------------------------------------------------------
-# Checks for compiler characteristics - Epetra_ConfigDefs.h uses these,
+# Checks for compiler characteristics - Teuchos_ConfigDefs.h uses these,
 # so it makes sense to leave them in - see PORTABILITY in this directory
 # ------------------------------------------------------------------------
 echo "$as_me:$LINENO: checking whether the compiler implements namespaces" >&5
@@ -6429,6 +6427,84 @@ if test "$ac_cv_cxx_mutable" = yes; then
 
 cat >>confdefs.h <<\_ACEOF
 #define HAVE_MUTABLE
+_ACEOF
+
+fi
+
+echo "$as_me:$LINENO: checking whether the compiler supports std::numeric_limits<>" >&5
+echo $ECHO_N "checking whether the compiler supports std::numeric_limits<>... $ECHO_C" >&6
+if test "${ac_cv_cxx_numeric_limits+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+
+
+ ac_ext=cc
+ac_cpp='$CXXCPP $CPPFLAGS'
+ac_compile='$CXX -c $CXXFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CXX -o conftest$ac_exeext $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
+
+ cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <limits>
+
+int
+main ()
+{
+
+double eps = std::numeric_limits<double>::epsilon();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_cxx_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_cxx_numeric_limits=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_cxx_numeric_limits=no
+fi
+rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
+ ac_ext=cc
+ac_cpp='$CXXCPP $CPPFLAGS'
+ac_compile='$CXX -c $CXXFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CXX -o conftest$ac_exeext $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
+
+
+fi
+echo "$as_me:$LINENO: result: $ac_cv_cxx_numeric_limits" >&5
+echo "${ECHO_T}$ac_cv_cxx_numeric_limits" >&6
+if test "$ac_cv_cxx_numeric_limits" = yes; then
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_NUMERIC_LIMITS
 _ACEOF
 
 fi
@@ -7510,7 +7586,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_verb"
-(eval echo $as_me:7513: \"$ac_link\") >&5
+(eval echo $as_me:7589: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
@@ -7588,7 +7664,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_cv_prog_f77_v"
-(eval echo $as_me:7591: \"$ac_link\") >&5
+(eval echo $as_me:7667: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
@@ -10118,7 +10194,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_verb"
-(eval echo $as_me:10121: \"$ac_link\") >&5
+(eval echo $as_me:10197: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
@@ -10196,7 +10272,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_cv_prog_f77_v"
-(eval echo $as_me:10199: \"$ac_link\") >&5
+(eval echo $as_me:10275: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
