----------------------------------------------------------------------
 Committing in .

 Modified Files:
 	configure configure.ac
 ----------------------------------------------------------------------
Bug 1415.

Modified the math library error message because when configure dies
looking for pow, it is almost always because of a problem not related
to the math library.  The message now reads:

configure: error: Error encountered when checking for math library.  ***Almost
always this error is caused by a typo in the list of configure arguments
that is not related to the math library.  Look especially for missing
quotes or hyphens in any value related to compiler flags or libraries.
For an error message that may assist in finding the problem grep for
"checking for library containing pow" in the file
packages/teuchos/config.log and read the next several lines.

Mike Heroux suggested that this change be made to Teuchos only because
Teuchos is required for almost every other Trilinos package.

Bug 1906.

Made minor modifications to the compiler selection lists.  Removed
gcc from the c++ list (unsure why it was there).  Also added gfortran,
the replacement for g77, and f95 to the fortran list.

I tested these changed on my local Linux box.

diff --git a/packages/teuchos/configure b/packages/teuchos/configure
--- a/packages/teuchos/configure
+++ b/packages/teuchos/configure
@@ -3294,7 +3294,7 @@ ac_compile='$CXX -c $CXXFLAGS $CPPFLAGS conftest.$ac_ext >&5'
 ac_link='$CXX -o conftest$ac_exeext $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
 ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
 if test -n "$ac_tool_prefix"; then
-  for ac_prog in $CCC CC g++ gcc c++ cxx
+  for ac_prog in $CCC CC g++ c++ cxx
   do
     # Extract the first word of "$ac_tool_prefix$ac_prog", so it can be a program name with args.
 set dummy $ac_tool_prefix$ac_prog; ac_word=$2
@@ -3336,7 +3336,7 @@ fi
 fi
 if test -z "$CXX"; then
   ac_ct_CXX=$CXX
-  for ac_prog in $CCC CC g++ gcc c++ cxx
+  for ac_prog in $CCC CC g++ c++ cxx
 do
   # Extract the first word of "$ac_prog", so it can be a program name with args.
 set dummy $ac_prog; ac_word=$2
@@ -3750,7 +3750,7 @@ ac_compile='$F77 -c $FFLAGS conftest.$ac_ext >&5'
 ac_link='$F77 -o conftest$ac_exeext $FFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
 ac_compiler_gnu=$ac_cv_f77_compiler_gnu
 if test -n "$ac_tool_prefix"; then
-  for ac_prog in f77 g77 f90 xlf90
+  for ac_prog in f77 g77 gfortran f90 xlf90 f95
   do
     # Extract the first word of "$ac_tool_prefix$ac_prog", so it can be a program name with args.
 set dummy $ac_tool_prefix$ac_prog; ac_word=$2
@@ -3792,7 +3792,7 @@ fi
 fi
 if test -z "$F77"; then
   ac_ct_F77=$F77
-  for ac_prog in f77 g77 f90 xlf90
+  for ac_prog in f77 g77 gfortran f90 xlf90 f95
 do
   # Extract the first word of "$ac_prog", so it can be a program name with args.
 set dummy $ac_prog; ac_word=$2
@@ -10788,8 +10788,20 @@ if test "$ac_cv_search_pow" != no; then
   test "$ac_cv_search_pow" = "none required" || LIBS="$ac_cv_search_pow $LIBS"
 
 else
-  { { echo "$as_me:$LINENO: error: Cannot find math library" >&5
-echo "$as_me: error: Cannot find math library" >&2;}
+  { { echo "$as_me:$LINENO: error: Error encountered when checking for math library.  ***Almost
+always this error is caused by a typo in the list of configure arguments
+that is not related to the math library.  Look especially for missing
+quotes or hyphens in any value related to compiler flags or libraries.
+For an error message that may assist in finding the problem grep for
+\"checking for library containing pow\" in the file
+packages/teuchos/config.log and read the next several lines." >&5
+echo "$as_me: error: Error encountered when checking for math library.  ***Almost
+always this error is caused by a typo in the list of configure arguments
+that is not related to the math library.  Look especially for missing
+quotes or hyphens in any value related to compiler flags or libraries.
+For an error message that may assist in finding the problem grep for
+\"checking for library containing pow\" in the file
+packages/teuchos/config.log and read the next several lines." >&2;}
    { (exit 1); exit 1; }; }
 fi
 
@@ -12973,7 +12985,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_verb"
-(eval echo $as_me:12976: \"$ac_link\") >&5
+(eval echo $as_me:12988: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
@@ -13051,7 +13063,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_cv_prog_f77_v"
-(eval echo $as_me:13054: \"$ac_link\") >&5
+(eval echo $as_me:13066: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
