SUMMARY:   added configure-time test of BLAS complex dot products, solution
     BUGS:      4261

     CHECKLIST:

     1)   Did you add any source files?  no

     2)   Did you update or change the build system?  yes
     2.a) Did you remember to do a bootstrap and do a 'cvs add' on the
          Makefile.am files and the Makefile.in files?  yes
     2.b) [Optional but recommended] Did you blow away the libraries and
          executables and then rebuild?  yes

     3) Did you rerun the test suite on at least the packages that you
        changed?  yes

     COMMENTS:

The way that Fortran-compiled BLAS routines return a complex number was causing problems when called from C/C++.
I added a configure-time test to determine
a) whether this was a problem
b) if so, whether it could be addressed.
These tests are currently disabled, requiring --enable-teuchos-dotcheck to be enabled. If so, the wrapper for the
third-party BLAS routines CDOTC and ZDOTC by Teuchos::BLAS::DOT() are modified.

Currently, only Tpetra stresses this "bug".

(checklist version 2007-06-20)

diff --git a/packages/teuchos/configure b/packages/teuchos/configure
--- a/packages/teuchos/configure
+++ b/packages/teuchos/configure
@@ -1416,7 +1416,7 @@ Optional Features:
   --enable-teuchos-comm_timers
                           Enable timers for Teuchos::Comm related software
                           (default is yes, )
-  --enable-teuchos-debug  Enable optional extra debugging checkes (default is
+  --enable-teuchos-debug  Enable optional extra debugging checks (default is
                           no, )
   --enable-teuchos-demangle
                           Name demangling for types (g++ only). By default,
@@ -1425,6 +1425,9 @@ Optional Features:
                           every platoform. Use --disable-teuchos-demangle to
                           turn this off and avoid problems (default is
                           yes, )
+  --enable-teuchos-dotcheck
+                          Enable checking on complex BLAS dot routines
+                          (default is no, )
   --enable-export-makefiles
                           Creates export makefiles in the install (prefix)
                           directory. This option requires perl to be set in
@@ -16182,6 +16185,229 @@ echo "$as_me: error: Cannot determine BLAS and LAPACK name mangling using the va
   fi
 
 fi
+
+# check whether C/C++ has problems calling cdotc and zdotc and whether we know how to fix it
+
+# Check whether --enable-teuchos-dotcheck was given.
+if test "${enable_teuchos_dotcheck+set}" = set; then
+  enableval=$enable_teuchos_dotcheck; ac_cv_use_teuchos_dotcheck=$enableval
+else
+  ac_cv_use_teuchos_dotcheck=no
+fi
+
+
+{ echo "$as_me:$LINENO: checking whether to use teuchos-dotcheck" >&5
+echo $ECHO_N "checking whether to use teuchos-dotcheck... $ECHO_C" >&6; }
+
+if test "X$ac_cv_use_teuchos_dotcheck" != "Xno"; then
+  { echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6; }
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_TEUCHOS_DOTCHECK
+_ACEOF
+
+else
+  { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+fi
+
+if test "X$ac_cv_use_teuchos_dotcheck" != "Xno"; then
+        { echo "$as_me:$LINENO: checking whether CDOTC and ZDOTC have problems with C/C++" >&5
+echo $ECHO_N "checking whether CDOTC and ZDOTC have problems with C/C++... $ECHO_C" >&6; }
+if test "${ac_cv_cxx_complex_blas_problem+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+
+ ac_ext=cpp
+ac_cpp='$CXXCPP $CPPFLAGS'
+ac_compile='$CXX -c $CXXFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CXX -o conftest$ac_exeext $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
+
+ save_LIBS="$LIBS"; LIBS="$LAPACK_LIBS $BLAS_LIBS $LIBS $FLIBS"
+ if test "$cross_compiling" = yes; then
+  { { echo "$as_me:$LINENO: error: cannot run test program while cross compiling
+See \`config.log' for more details." >&5
+echo "$as_me: error: cannot run test program while cross compiling
+See \`config.log' for more details." >&2;}
+   { (exit 1); exit 1; }; }
+else
+  cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+#include  <complex>
+extern "C" {
+std::complex<float> F77_BLAS_MANGLE(cdotc,CDOTC)(const int* n, const  std::complex<float> x[], const int* incx, const std::complex<float> y[], const int* incy);
+}
+int main() {
+ const int NUM=2;
+ const int INC=1;
+ std::complex<float> f[NUM];
+ const std::complex<float> ONE = std::complex<float>(1.0,0.0),
+                           TWO = std::complex<float>(2.0,0.0);
+ f[0] =  ONE; f[1] =  ONE;
+ std::complex<float> ret = F77_BLAS_MANGLE(cdotc,CDOTC)(&NUM,f,&INC,f,&INC);
+ return (ret == TWO ? 0 : 1);
+}
+
+_ACEOF
+rm -f conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && { ac_try='./conftest$ac_exeext'
+  { (case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_try") 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_cxx_complex_blas_problem=no
+else
+  echo "$as_me: program exited with status $ac_status" >&5
+echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+( exit $ac_status )
+ac_cv_cxx_complex_blas_problem=yes
+fi
+rm -f core *.core core.conftest.* gmon.out bb.out conftest$ac_exeext conftest.$ac_objext conftest.$ac_ext
+fi
+
+
+ac_ext=cpp
+ac_cpp='$CXXCPP $CPPFLAGS'
+ac_compile='$CXX -c $CXXFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CXX -o conftest$ac_exeext $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
+
+LIBS="$save_LIBS"
+
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_cxx_complex_blas_problem" >&5
+echo "${ECHO_T}$ac_cv_cxx_complex_blas_problem" >&6; }
+if test "$ac_cv_cxx_complex_blas_problem" = yes; then
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_COMPLEX_BLAS_PROBLEM
+_ACEOF
+
+fi
+
+        if test "X$ac_cv_cxx_complex_blas_problem" == "Xyes"; then
+                { echo "$as_me:$LINENO: checking whether CDOTC and ZDOTC problems can be fixed" >&5
+echo $ECHO_N "checking whether CDOTC and ZDOTC problems can be fixed... $ECHO_C" >&6; }
+if test "${ac_cv_cxx_complex_blas_problem_fixed+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+
+ ac_ext=cpp
+ac_cpp='$CXXCPP $CPPFLAGS'
+ac_compile='$CXX -c $CXXFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CXX -o conftest$ac_exeext $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
+
+ save_LIBS="$LIBS"; LIBS="$LAPACK_LIBS $BLAS_LIBS $LIBS $FLIBS"
+ if test "$cross_compiling" = yes; then
+  { { echo "$as_me:$LINENO: error: cannot run test program while cross compiling
+See \`config.log' for more details." >&5
+echo "$as_me: error: cannot run test program while cross compiling
+See \`config.log' for more details." >&2;}
+   { (exit 1); exit 1; }; }
+else
+  cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+#include  <complex>
+extern "C" {
+std::complex<float> F77_BLAS_MANGLE(cdotc,CDOTC)(std::complex<float> x[], const int* n, const  std::complex<float> x[], const int* incx, const std::complex<float> y[], const int* incy);
+}
+int main() {
+ const int NUM=2;
+ const int INC=1;
+ std::complex<float> f[NUM];
+ const std::complex<float> ONE = std::complex<float>(1.0,0.0),
+                           TWO = std::complex<float>(2.0,0.0);
+ f[0] =  ONE; f[1] =  ONE;
+ std::complex<float> ret(0.0,0.0);
+ F77_BLAS_MANGLE(cdotc,CDOTC)(&ret,&NUM,f,&INC,f,&INC);
+ return (ret == TWO ? 0 : 1);
+}
+
+_ACEOF
+rm -f conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && { ac_try='./conftest$ac_exeext'
+  { (case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_try") 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_cxx_complex_blas_problem_fixed=yes
+else
+  echo "$as_me: program exited with status $ac_status" >&5
+echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+( exit $ac_status )
+ac_cv_cxx_complex_blas_problem_fixed=no
+fi
+rm -f core *.core core.conftest.* gmon.out bb.out conftest$ac_exeext conftest.$ac_objext conftest.$ac_ext
+fi
+
+
+ac_ext=cpp
+ac_cpp='$CXXCPP $CPPFLAGS'
+ac_compile='$CXX -c $CXXFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CXX -o conftest$ac_exeext $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
+
+LIBS="$save_LIBS"
+
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_cxx_complex_blas_problem_fixed" >&5
+echo "${ECHO_T}$ac_cv_cxx_complex_blas_problem_fixed" >&6; }
+if test "$ac_cv_cxx_complex_blas_problem_fixed" = yes; then
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_FIXABLE_COMPLEX_BLAS_PROBLEM
+_ACEOF
+
+fi
+
+        fi
+fi
+
 # end of the list of libraries that don't need to be checked for if
 # tests and examples are disabled.
 
