----------------------------------------------------------------------
 Committing in .

 Modified Files:
 	Makefile.in aclocal.m4 configure configure.ac src/Makefile.am
 	src/Makefile.in src/Teuchos_ConfigDefs.hpp
 	src/Teuchos_config.h.in test/Makefile.am test/Makefile.in
 	test/BLAS/Makefile.in test/Containers/Makefile.in
 	test/DenseMatrix/Makefile.in test/LAPACK/Makefile.in
 	test/ParameterList/Makefile.in test/RefCountPtr/Makefile.in
 	test/Time/Makefile.in test/XML/Makefile.in
 	test/scripts/Makefile.in test/scripts/daily/Makefile.in
 	test/scripts/daily/serial/Makefile.in
 ----------------------------------------------------------------------

 Changed standard build to include: BLAS/LAPACK wrappers, SerialDenseMatrix/Vector class,
 Flop counters, Timers, RefCountPtr, and Parameter List.  The tests for these classes were
 moved to the standard (--enable-teuchos) build if they weren't there already.

 The rest has been put in a EXTENDED build which can be obtained through enabling Teuchos
 with "--enable-teuchos-extended".  The MPI communicators, XML parsing, HashTables, etc.
 will then be built as well as their tests.

 Furthermore, I put in a check for the "list/list.h" header, which is needed for the Teuchos
 map (on Janus).  This check precipitated a changed in the Teuchos_ConfigDefs.hpp header for
 HAVE_LIST.

 This all passes in serial and parallel on my Dell/Linux machine

diff --git a/packages/teuchos/configure b/packages/teuchos/configure
--- a/packages/teuchos/configure
+++ b/packages/teuchos/configure
@@ -310,7 +310,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM AWK SET_MAKE CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE CXX CXXFLAGS ac_ct_CXX CXXDEPMODE F77 FFLAGS ac_ct_F77 RANLIB ac_ct_RANLIB MPI_CXX HAVE_MPI_TRUE HAVE_MPI_FALSE MPI_CXX_EXISTS MPI_CC_EXISTS MPI_F77_EXISTS USE_ALTERNATE_AR_TRUE USE_ALTERNATE_AR_FALSE ALTERNATE_AR CXXCPP EGREP BUILD_TESTS_TRUE BUILD_TESTS_FALSE HAVE_TEUCHOS_COMPLEX_TRUE HAVE_TEUCHOS_COMPLEX_FALSE HAVE_TEUCHOS_EXPERIMENTAL_TRUE HAVE_TEUCHOS_EXPERIMENTAL_FALSE FLIBS BLAS_LIBS LAPACK_LIBS TRILINOS_TEMPLATE_OBJS EXPAT_LIBS EXPAT_INC HAVE_EXPAT_TRUE HAVE_EXPAT_FALSE ac_aux_dir LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM AWK SET_MAKE CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE CXX CXXFLAGS ac_ct_CXX CXXDEPMODE F77 FFLAGS ac_ct_F77 RANLIB ac_ct_RANLIB MPI_CXX HAVE_MPI_TRUE HAVE_MPI_FALSE MPI_CXX_EXISTS MPI_CC_EXISTS MPI_F77_EXISTS USE_ALTERNATE_AR_TRUE USE_ALTERNATE_AR_FALSE ALTERNATE_AR CXXCPP EGREP BUILD_TESTS_TRUE BUILD_TESTS_FALSE HAVE_TEUCHOS_COMPLEX_TRUE HAVE_TEUCHOS_COMPLEX_FALSE HAVE_TEUCHOS_EXTENDED_TRUE HAVE_TEUCHOS_EXTENDED_FALSE FLIBS BLAS_LIBS LAPACK_LIBS TRILINOS_TEMPLATE_OBJS EXPAT_LIBS EXPAT_INC HAVE_EXPAT_TRUE HAVE_EXPAT_FALSE ac_aux_dir LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -880,8 +880,8 @@ Optional Features:
   --enable-teuchos-abc    Enable array bounds checking (default is no)
   --enable-teuchos-complex
                           enable Teuchos complex code (default is no)
-  --enable-teuchos-experimental
-                          enable Teuchos experimental code (default is no)
+  --enable-teuchos-extended
+                          enable Teuchos extended code (default is no)
   --enable-teuchos-arprec Enable Teuchos interface support for the ARbitrary
                           PRECision Library (default is no)
   --enable-expat          enable expat XML parser
@@ -4904,7 +4904,9 @@ done
 
 
 
-for ac_header in map map.h vector vector.h
+
+
+for ac_header in map map.h list list.h vector vector.h
 do
 as_ac_Header=`echo "ac_cv_header_$ac_header" | $as_tr_sh`
 if eval "test \"\${$as_ac_Header+set}\" = set"; then
@@ -5529,6 +5531,12 @@ fi
 if test "X$ac_cv_header_map" != "Xyes" && test "X$ac_cv_header_map_h" != "Xyes"; then
   { { echo "$as_me:$LINENO: error: Cannot find map or map.h.  Teuchos requires at least one or the other." >&5
 echo "$as_me: error: Cannot find map or map.h.  Teuchos requires at least one or the other." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+
+if test "X$ac_cv_header_list" != "Xyes" && test "X$ac_cv_header_list_h" != "Xyes"; then
+  { { echo "$as_me:$LINENO: error: Cannot find list or list.h.  Teuchos requires at least one or the other." >&5
+echo "$as_me: error: Cannot find list or list.h.  Teuchos requires at least one or the other." >&2;}
    { (exit 1); exit 1; }; }
 fi
 
@@ -6499,27 +6507,27 @@ fi
 
 
 #
-#  --enable-teuchos-experimental
+#  --enable-teuchos-extended
 #
 
 
-# Check whether --enable-teuchos-experimental or --disable-teuchos-experimental was given.
-if test "${enable_teuchos_experimental+set}" = set; then
-  enableval="$enable_teuchos_experimental"
-  ac_cv_use_teuchos_experimental=$enableval
+# Check whether --enable-teuchos-extended or --disable-teuchos-extended was given.
+if test "${enable_teuchos_extended+set}" = set; then
+  enableval="$enable_teuchos_extended"
+  ac_cv_use_teuchos_extended=$enableval
 else
-  ac_cv_use_teuchos_experimental=no
+  ac_cv_use_teuchos_extended=no
 fi;
 
-echo "$as_me:$LINENO: checking whether to use teuchos-experimental" >&5
-echo $ECHO_N "checking whether to use teuchos-experimental... $ECHO_C" >&6
+echo "$as_me:$LINENO: checking whether to use teuchos-extended" >&5
+echo $ECHO_N "checking whether to use teuchos-extended... $ECHO_C" >&6
 
-if test "X$ac_cv_use_teuchos_experimental" != "Xno"; then
+if test "X$ac_cv_use_teuchos_extended" != "Xno"; then
   echo "$as_me:$LINENO: result: yes" >&5
 echo "${ECHO_T}yes" >&6
 
 cat >>confdefs.h <<\_ACEOF
-#define HAVE_TEUCHOS_EXPERIMENTAL
+#define HAVE_TEUCHOS_EXTENDED
 _ACEOF
 
 else
@@ -6529,12 +6537,12 @@ fi
 
 
 
-if test "X$ac_cv_use_teuchos_experimental" != "Xno"; then
-  HAVE_TEUCHOS_EXPERIMENTAL_TRUE=
-  HAVE_TEUCHOS_EXPERIMENTAL_FALSE='#'
+if test "X$ac_cv_use_teuchos_extended" != "Xno"; then
+  HAVE_TEUCHOS_EXTENDED_TRUE=
+  HAVE_TEUCHOS_EXTENDED_FALSE='#'
 else
-  HAVE_TEUCHOS_EXPERIMENTAL_TRUE='#'
-  HAVE_TEUCHOS_EXPERIMENTAL_FALSE=
+  HAVE_TEUCHOS_EXTENDED_TRUE='#'
+  HAVE_TEUCHOS_EXTENDED_FALSE=
 fi
 
 
@@ -6916,7 +6924,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_verb"
-(eval echo $as_me:6919: \"$ac_link\") >&5
+(eval echo $as_me:6927: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
@@ -6996,7 +7004,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_cv_prog_f77_v"
-(eval echo $as_me:6999: \"$ac_link\") >&5
+(eval echo $as_me:7007: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
@@ -9137,7 +9145,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_verb"
-(eval echo $as_me:9140: \"$ac_link\") >&5
+(eval echo $as_me:9148: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
@@ -9217,7 +9225,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_cv_prog_f77_v"
-(eval echo $as_me:9220: \"$ac_link\") >&5
+(eval echo $as_me:9228: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
@@ -9688,10 +9696,10 @@ echo "$as_me: error: conditional \"HAVE_TEUCHOS_COMPLEX\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
-if test -z "${HAVE_TEUCHOS_EXPERIMENTAL_TRUE}" && test -z "${HAVE_TEUCHOS_EXPERIMENTAL_FALSE}"; then
-  { { echo "$as_me:$LINENO: error: conditional \"HAVE_TEUCHOS_EXPERIMENTAL\" was never defined.
+if test -z "${HAVE_TEUCHOS_EXTENDED_TRUE}" && test -z "${HAVE_TEUCHOS_EXTENDED_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"HAVE_TEUCHOS_EXTENDED\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
-echo "$as_me: error: conditional \"HAVE_TEUCHOS_EXPERIMENTAL\" was never defined.
+echo "$as_me: error: conditional \"HAVE_TEUCHOS_EXTENDED\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -10316,8 +10324,8 @@ s,@BUILD_TESTS_TRUE@,$BUILD_TESTS_TRUE,;t t
 s,@BUILD_TESTS_FALSE@,$BUILD_TESTS_FALSE,;t t
 s,@HAVE_TEUCHOS_COMPLEX_TRUE@,$HAVE_TEUCHOS_COMPLEX_TRUE,;t t
 s,@HAVE_TEUCHOS_COMPLEX_FALSE@,$HAVE_TEUCHOS_COMPLEX_FALSE,;t t
-s,@HAVE_TEUCHOS_EXPERIMENTAL_TRUE@,$HAVE_TEUCHOS_EXPERIMENTAL_TRUE,;t t
-s,@HAVE_TEUCHOS_EXPERIMENTAL_FALSE@,$HAVE_TEUCHOS_EXPERIMENTAL_FALSE,;t t
+s,@HAVE_TEUCHOS_EXTENDED_TRUE@,$HAVE_TEUCHOS_EXTENDED_TRUE,;t t
+s,@HAVE_TEUCHOS_EXTENDED_FALSE@,$HAVE_TEUCHOS_EXTENDED_FALSE,;t t
 s,@FLIBS@,$FLIBS,;t t
 s,@BLAS_LIBS@,$BLAS_LIBS,;t t
 s,@LAPACK_LIBS@,$LAPACK_LIBS,;t t
