Summary: More progress on OptiPack and disables for float support
1) Finished the OptiPack:::DiagonalQuadraticResponseOnlyModelEvaluator
implementation and added decent unit tests.

2) Implemented optional support for float and tested.  I did a not of work to
get support for float to be optional.  The main reason that I did this was to
avoid longer compile times so I could just test with only double during the
development cycle.


Specific changes:
-----------------



(*) teuchos/CMakeLists.txt, teuchos/cmake/Teuchos_config.h.in: Added
Teuchos_ENABLE_FLOAT with the macro HAVE_TEUCHOS_FLOAT.

(*) Teuchos_ExplicitInstantiationHelpers.hpp: Added conditional support for
float added new macros
TEUCHOS_[MACRO,Class]_TEMPLATE_INSTANT_REAL_SCALAR_TYPES(...) to only
instaniate real types.

(*) Teuchos_UnitTestHelpers.hpp: Added conditional logic for float support

(*) teuchos/test/CMakeLists.txt, teuchos/test/UnitTest/CMakeLists.txt: Moved
'UnitTests' into their own directory and modifed passing result for disabling
complex and float.

(*) teuchos/configure[.ac], teuchos/src/Teuchos_config.h.in: Added
--enable-teuchos-float (which is on by default) which puts in
HAVE_TEUCHOS_FLOAT to match the CMake system


(*) rtop/*: Updated for optional support for float and complex.


(*) Thyra_ModelEvaluatorHelpers.hpp: Provided a pointer-free version of
eval_g(...) and provided a new eval_g_DgDp(...) helper function (only being
tested in OptiPack right now).

(*) Thyra_DetachedSpmdVectorView.hpp,
thyra/test/operator_vector/DetachedSpmdVectorView_UnitTests.cpp: Added the
non-const version DetachedSpmdVectorView with unit tests.

(*) sampleScripts/linux-gabriel-gcc-3.3.4-dbg-cmake: Changed from
Teuchos_ENABLE_EXPLICIT_INSTANTIATION:BOOL=ON to
Thyra_ENABLE_EXPLICIT_INSTANTIATION:BOOL=ON


(*) OptiPack_Types.hpp: Common types for OptiPack (usings, etc.)

(*) optipack/test/NonlinearCG/NonlinearCG_UnitTests.cpp: Moved out the unit
tests for OptiPack::DiagonalQuadraticResponseOnlyModelEvaluator

(*) OptiPack_DiagonalQuadraticResponseOnlyModelEvaluator[_decl,_def].hpp:
Finished implementation

(*) optipack/test/models/CMakeLists.txt,
optipack/test/models/UnitTests/CMakeLists.txt,
optipack/test/models/UnitTests/DiagonalQuadraticResponseOnlyModelEvaluator_UnitTests.cpp:
Added specific unit test for
OptiPack::DiagonalQuadraticResponseOnlyModelEvaluator



Tests run on gabriel.sandia.gov:
--------------------------------

(*) CMake serial debug rebuild (all 296 tests ran passed)

(*) CMake mpi release rebuild (all 269 tests ran passed)

(*) Autotools serial debug rebuild (all 911 tests ran passed)

diff --git a/packages/teuchos/configure b/packages/teuchos/configure
--- a/packages/teuchos/configure
+++ b/packages/teuchos/configure
@@ -744,6 +744,8 @@ HAVE_GCC_CHECKEDSTL_TRUE
 HAVE_GCC_CHECKEDSTL_FALSE
 HAVE_TEUCHOS_EXPLICIT_INSTANTIATION_TRUE
 HAVE_TEUCHOS_EXPLICIT_INSTANTIATION_FALSE
+HAVE_TEUCHOS_FLOAT_TRUE
+HAVE_TEUCHOS_FLOAT_FALSE
 HAVE_TEUCHOS_COMPLEX_TRUE
 HAVE_TEUCHOS_COMPLEX_FALSE
 HAVE_TEUCHOS_LONG_LONG_INT_TRUE
@@ -1393,6 +1395,7 @@ Optional Features:
   --enable-teuchos-explicit_instantiation
                           Enable explicit template instantiation for selected
                           types (default is no)
+  --enable-teuchos-float  Enable Teuchos float code (default is yes)
   --enable-teuchos-complex
                           Enable Teuchos complex code (default is yes)
   --enable-teuchos-long_long
@@ -7587,6 +7590,44 @@ fi
 else
   HAVE_TEUCHOS_EXPLICIT_INSTANTIATION_TRUE='#'
   HAVE_TEUCHOS_EXPLICIT_INSTANTIATION_FALSE=
+fi
+
+
+#
+#  --enable-teuchos-float
+#
+
+
+# Check whether --enable-teuchos-float was given.
+if test "${enable_teuchos_float+set}" = set; then
+  enableval=$enable_teuchos_float; ac_cv_use_teuchos_float=$enableval
+else
+  ac_cv_use_teuchos_float=yes
+fi
+
+
+{ echo "$as_me:$LINENO: checking whether to use teuchos-float" >&5
+echo $ECHO_N "checking whether to use teuchos-float... $ECHO_C" >&6; }
+
+if test "X$ac_cv_use_teuchos_float" != "Xno"; then
+  { echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6; }
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_TEUCHOS_FLOAT
+_ACEOF
+
+else
+  { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+fi
+
+ if test "X$ac_cv_use_teuchos_float" != "Xno"; then
+  HAVE_TEUCHOS_FLOAT_TRUE=
+  HAVE_TEUCHOS_FLOAT_FALSE='#'
+else
+  HAVE_TEUCHOS_FLOAT_TRUE='#'
+  HAVE_TEUCHOS_FLOAT_FALSE=
 fi
 
 
@@ -17399,6 +17440,13 @@ echo "$as_me: error: conditional \"HAVE_TEUCHOS_EXPLICIT_INSTANTIATION\" was nev
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
+if test -z "${HAVE_TEUCHOS_FLOAT_TRUE}" && test -z "${HAVE_TEUCHOS_FLOAT_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"HAVE_TEUCHOS_FLOAT\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"HAVE_TEUCHOS_FLOAT\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
 if test -z "${HAVE_TEUCHOS_COMPLEX_TRUE}" && test -z "${HAVE_TEUCHOS_COMPLEX_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"HAVE_TEUCHOS_COMPLEX\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
@@ -18194,6 +18242,8 @@ HAVE_GCC_CHECKEDSTL_TRUE!$HAVE_GCC_CHECKEDSTL_TRUE$ac_delim
 HAVE_GCC_CHECKEDSTL_FALSE!$HAVE_GCC_CHECKEDSTL_FALSE$ac_delim
 HAVE_TEUCHOS_EXPLICIT_INSTANTIATION_TRUE!$HAVE_TEUCHOS_EXPLICIT_INSTANTIATION_TRUE$ac_delim
 HAVE_TEUCHOS_EXPLICIT_INSTANTIATION_FALSE!$HAVE_TEUCHOS_EXPLICIT_INSTANTIATION_FALSE$ac_delim
+HAVE_TEUCHOS_FLOAT_TRUE!$HAVE_TEUCHOS_FLOAT_TRUE$ac_delim
+HAVE_TEUCHOS_FLOAT_FALSE!$HAVE_TEUCHOS_FLOAT_FALSE$ac_delim
 HAVE_TEUCHOS_COMPLEX_TRUE!$HAVE_TEUCHOS_COMPLEX_TRUE$ac_delim
 HAVE_TEUCHOS_COMPLEX_FALSE!$HAVE_TEUCHOS_COMPLEX_FALSE$ac_delim
 HAVE_TEUCHOS_LONG_LONG_INT_TRUE!$HAVE_TEUCHOS_LONG_LONG_INT_TRUE$ac_delim
@@ -18223,7 +18273,7 @@ LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 59; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 61; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
