But 2887
I have finally figured out how to get demangled names from typeid(Type or
object).name() on GCC compilers.  The way to do this is to include the header
<cxxabi.h> and to use the the C function abi::__cxa_demangle(...).  This
function will get called automatically by the non-member function
Teuchos::typeName<T>(t) and the default traits class function
Teuchos::TypeNameTraits<T>::name().

I have put in a configure-time test that will only use this code in place of
typeid(T or t).name() if a test program that uses this compiles, runs, and does
the demangling correctly.

To update your code, include the header Teuchos_TypeNameTraits.hpp and,
replace:

  typeid(TypeName).name()

with

  Teuchos::TypeNameTraits<TypeName>::name()

and replace:

  typeid(object).name()

with

  Teuchos::typeName(object)

I have inject the names Teuchos::typeName and Teuchos::TypeNameTraits into the
Thyra namespace so you can leave the Teuchos:: off of your uses in this
namespace.  I have updated all of Thyra (and adpaters) and MOOCHO to use the
demangled names.  Now all error messages and informative print statements
will show demangled names automatically.

There is also a script
Trilinos/packages/teuchos/refactoring/replace-typeid-name-with-typeName-20061112.sh
that you can run on files to replace the object use of typeid(object).name()
with typeName(object).  This script is not perfect but it can help in refactoring
your code (if you use std::typeinfo::name()).

diff --git a/packages/teuchos/configure b/packages/teuchos/configure
--- a/packages/teuchos/configure
+++ b/packages/teuchos/configure
@@ -8166,6 +8166,96 @@ _ACEOF
 
 fi
 
+echo "$as_me:$LINENO: checking whether the compiler supports abi::__cxa_demangle(...)" >&5
+echo $ECHO_N "checking whether the compiler supports abi::__cxa_demangle(...)... $ECHO_C" >&6
+if test "${ac_cv_cxx_abi_demangle+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+
+
+ ac_ext=cc
+ac_cpp='$CXXCPP $CPPFLAGS'
+ac_compile='$CXX -c $CXXFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CXX -o conftest$ac_exeext $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
+
+ cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <cxxabi.h>
+#include <string>
+namespace MyNamespace {
+class MyClass {};
+}
+
+int
+main ()
+{
+
+const std::string
+  mangledName = typeid(MyNamespace::MyClass).name();
+int status;
+char
+  *_demangledName = abi::__cxa_demangle(mangledName.c_str(),0,0,&status);
+const std::string demangledName(_demangledName);
+free(_demangledName);
+return ( demangledName == "MyNamespace::MyClass" ? 0 : 1 );
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_cxx_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_cxx_abi_demangle=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_cxx_abi_demangle=no
+fi
+rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
+ac_ext=cc
+ac_cpp='$CXXCPP $CPPFLAGS'
+ac_compile='$CXX -c $CXXFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CXX -o conftest$ac_exeext $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
+
+
+fi
+echo "$as_me:$LINENO: result: $ac_cv_cxx_abi_demangle" >&5
+echo "${ECHO_T}$ac_cv_cxx_abi_demangle" >&6
+if test "$ac_cv_cxx_abi_demangle" = yes; then
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_GCC_ABI_DEMANGLE
+_ACEOF
+
+fi
+
 # ---------------------------------------------------------------------
 # These are pretty obscure
 # ---------------------------------------------------------------------
@@ -10891,7 +10981,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_verb"
-(eval echo $as_me:10894: \"$ac_link\") >&5
+(eval echo $as_me:10984: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
@@ -10969,7 +11059,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_cv_prog_f77_v"
-(eval echo $as_me:10972: \"$ac_link\") >&5
+(eval echo $as_me:11062: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
@@ -14004,7 +14094,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_verb"
-(eval echo $as_me:14007: \"$ac_link\") >&5
+(eval echo $as_me:14097: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
@@ -14082,7 +14172,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_cv_prog_f77_v"
-(eval echo $as_me:14085: \"$ac_link\") >&5
+(eval echo $as_me:14175: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
