Added two new typedefs to ScalarTraits: doublePrecision and halfPrecision Filled these out for non-ordinal type traits Tested in ScalarTraits unit test.
Added support to ScalarTraits for QD (double-double and quad-double) library.
Added optional (default: no) configure flag to promote double to dd_real (double-double)
Added test of QD functionality to ScalarTraits test.

Updated ARPREC, GNU MP support in ScalarTraits to latest versions for these packages (directory, header changes).

diff --git a/packages/teuchos/configure b/packages/teuchos/configure
--- a/packages/teuchos/configure
+++ b/packages/teuchos/configure
@@ -1407,6 +1407,11 @@ Optional Features:
                           is yes)
   --enable-teuchos-gmp    Enable Teuchos interface support for the GNU MP
                           Library (default is no)
+  --enable-teuchos-qd     Enable Teuchos interface support for the QD library
+                          (default is no)
+  --enable-teuchos-double-to-dd
+                          Instruct Teuchos ScalarTraits to promote double to
+                          dd_real (default is no)
   --enable-teuchos-expat  Enable Teuchos interface support for the Expat XML
                           Library (default is no)
   --enable-teuchos-libxml2
@@ -7893,7 +7898,7 @@ ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
 fi
 
 #
-#  --enable-teuchos-arprec
+#  --enable-teuchos-gmp
 #
 
 
@@ -8036,6 +8041,189 @@ echo "${ECHO_T}no" >&6; }
 	     	 echo "-----"
 	     	 { { echo "$as_me:$LINENO: error: GNU MP test cannot link" >&5
 echo "$as_me: error: GNU MP test cannot link" >&2;}
+   { (exit 1); exit 1; }; }
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
+      conftest$ac_exeext conftest.$ac_ext
+     ac_ext=cpp
+ac_cpp='$CXXCPP $CPPFLAGS'
+ac_compile='$CXX -c $CXXFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CXX -o conftest$ac_exeext $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
+
+
+fi
+
+#
+#  --enable-teuchos-qd
+#
+
+
+# Check whether --enable-teuchos-qd was given.
+if test "${enable_teuchos_qd+set}" = set; then
+  enableval=$enable_teuchos_qd; ac_cv_use_teuchos_qd=$enableval
+else
+  ac_cv_use_teuchos_qd=no
+fi
+
+
+{ echo "$as_me:$LINENO: checking whether to use teuchos-qd" >&5
+echo $ECHO_N "checking whether to use teuchos-qd... $ECHO_C" >&6; }
+
+if test "X$ac_cv_use_teuchos_qd" != "Xno"; then
+  { echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6; }
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_TEUCHOS_QD
+_ACEOF
+
+else
+  { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+fi
+
+
+if test "X$ac_cv_use_teuchos_qd" != "Xno"; then
+
+
+# Check whether --enable-teuchos-double-to-dd was given.
+if test "${enable_teuchos_double_to_dd+set}" = set; then
+  enableval=$enable_teuchos_double_to_dd; ac_cv_use_teuchos_double-to-dd=$enableval
+else
+  ac_cv_use_teuchos_double-to-dd=no
+fi
+
+
+{ echo "$as_me:$LINENO: checking whether to use teuchos-double-to-dd" >&5
+echo $ECHO_N "checking whether to use teuchos-double-to-dd... $ECHO_C" >&6; }
+
+if test "X$ac_cv_use_teuchos_double-to-dd" != "Xno"; then
+  { echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6; }
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_TEUCHOS_DOUBLE_TO_DD
+_ACEOF
+
+else
+  { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+fi
+
+
+#  TAC_ARG_WITH( trilinos3pldir, [Set Trilinos3PL directory], trilinos3pldir_is_not_specified )
+#  if test "X${tac_with_teuchos_trilinos3pldir}" != "Xtrilinos3pldir_is_not_specified"; then
+#
+#  Check for QD headers.
+#
+     { echo "$as_me:$LINENO: checking for QD headers (qd/qd_real.h) " >&5
+echo $ECHO_N "checking for QD headers (qd/qd_real.h) ... $ECHO_C" >&6; }
+     cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include "qd/qd_real.h"
+_ACEOF
+if { (ac_try="$ac_cpp conftest.$ac_ext"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_cpp conftest.$ac_ext") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } >/dev/null && {
+	 test -z "$ac_cxx_preproc_warn_flag$ac_cxx_werror_flag" ||
+	 test ! -s conftest.err
+       }; then
+  { echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6; }
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+
+	 { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+	 echo "-----"
+     	 echo "Cannot find QD headers."
+     	 echo "Use --with-incdirs to specify QD include directory."
+     	 echo "-----"
+     	 { { echo "$as_me:$LINENO: error: QD headers cannot be found" >&5
+echo "$as_me: error: QD headers cannot be found" >&2;}
+   { (exit 1); exit 1; }; }
+
+fi
+
+rm -f conftest.err conftest.$ac_ext
+#
+#  Check for QD library.
+#
+     { echo "$as_me:$LINENO: checking for QD library (libqd.a) " >&5
+echo $ECHO_N "checking for QD library (libqd.a) ... $ECHO_C" >&6; }
+
+     ac_ext=cpp
+ac_cpp='$CXXCPP $CPPFLAGS'
+ac_compile='$CXX -c $CXXFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CXX -o conftest$ac_exeext $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
+
+     cat >conftest.$ac_ext <<_ACEOF
+ /* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include "qd/qd_real.h"
+int
+main ()
+{
+qd_real one(1.0); sqrt(one);
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_cxx_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest$ac_exeext &&
+       $as_test_x conftest$ac_exeext; then
+  { echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6; }
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	{ echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+		 echo "-----"
+	     	 echo "Cannot find QD library."
+     		 echo "Use --with-ldflags to specify QD library directory."
+	     	 echo "Use --with-libs to specify QD library (-lqd)."
+	     	 echo "-----"
+	     	 { { echo "$as_me:$LINENO: error: QD test cannot link" >&5
+echo "$as_me: error: QD test cannot link" >&2;}
    { (exit 1); exit 1; }; }
 fi
 
