Trying to fix bug #859 on AIX where the compiler (AIX 5.1) doesn't allow "template" as a qualifier.  Introduced new m4 macro to test the compiler for this capability, which will set a variable (HAVE_TEMPLATE_QUALIFIER). The ParameterList test/example, which uses this syntax, is now ifdef'd by HAVE_TEMPLATE_QUALIFIER.  The ParameterList class is not ifdef'd, just in case the compiler accepts the syntax:
double temp = My_List.get<double>( "Tol " );

Some compilers seem to accept this, others don't, and it's not supported
by the ANSI C++ standard (ambiguous "less-than" sign).

diff --git a/packages/teuchos/configure b/packages/teuchos/configure
--- a/packages/teuchos/configure
+++ b/packages/teuchos/configure
@@ -6746,6 +6746,93 @@ _ACEOF
 
 fi
 
+echo "$as_me:$LINENO: checking whether the compiler accepts the \"template\" qualifier" >&5
+echo $ECHO_N "checking whether the compiler accepts the \"template\" qualifier... $ECHO_C" >&6
+if test "${ac_cv_cxx_template_qualifier+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+
+
+ ac_ext=cc
+ac_cpp='$CXXCPP $CPPFLAGS'
+ac_compile='$CXX -c $CXXFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CXX -o conftest$ac_exeext $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
+
+ cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+int
+main ()
+{
+
+class DummyClass {
+  public:
+    DummyClass() : dummyint( 1 ) {};
+    ~DummyClass() {};
+    template<typename T>
+    T get() { return( (T) dummyint ); };
+  private:
+    int dummyint;
+};
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_cxx_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+    DummyClass my_dummy;
+   double temp = my_dummy.template get<double>();
+
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_cxx_template_qualifier=yes
+fi
+rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
+ ac_ext=cc
+ac_cpp='$CXXCPP $CPPFLAGS'
+ac_compile='$CXX -c $CXXFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CXX -o conftest$ac_exeext $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
+
+
+fi
+echo "$as_me:$LINENO: result: $ac_cv_cxx_template_qualifier" >&5
+echo "${ECHO_T}$ac_cv_cxx_template_qualifier" >&6
+if test "$ac_cv_cxx_template_qualifier" = yes; then
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_TEMPLATE_QUALIFIER
+_ACEOF
+
+fi
+
 
 # ------------------------------------------------------------------------
 # Checks if tests should be built
@@ -7421,7 +7508,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_verb"
-(eval echo $as_me:7424: \"$ac_link\") >&5
+(eval echo $as_me:7511: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
@@ -7499,7 +7586,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_cv_prog_f77_v"
-(eval echo $as_me:7502: \"$ac_link\") >&5
+(eval echo $as_me:7589: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
@@ -10029,7 +10116,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_verb"
-(eval echo $as_me:10032: \"$ac_link\") >&5
+(eval echo $as_me:10119: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
@@ -10107,7 +10194,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_cv_prog_f77_v"
-(eval echo $as_me:10110: \"$ac_link\") >&5
+(eval echo $as_me:10197: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
