SUMMARY:  Put in --disable-teuchos-blasfloat to optionally remove all code that           depends on the float implementation of the BLAS
BUGS:     2886

CHECKLIST:

1) Did you add any source files? No

2) Did you update or change the build system? Yes
2.a) Did you remember to do a bootstrap and do a 'cvs add' on the
     Makefile.am files and the Makefile.in files? Yes
2.b) [Optional but recommended] Did you blow away the libraries and
     executables and then rebuild the libraries? Yes

3) Did you rerun the test suite on at least the packages that you
   changed? [???]

COMMENTS:

Here I have added a configure option --disable-teuchos-blasfloat to remove all
of the code and tests that depend on the float implementation of the BLAS.
The float BLAS and LAPACK tests in Teuchos have been failing for months on my
machine (see bug 2886 filed back on 2006-11-10).  The BLAS/float adapters and
tests are enabled by default so the behavior of Trilinos is unchanged unless
you add --disable-teuchos-blasfloat at configure time.  I also had to ifdef
out several tests in thyra when this flag is set since the float tests are
failing and so I had put in
TAC_ARG_INFORM_SUBPACKAGE_USED(teuchos,blasfloat,...) macro to catch this in
thyra.  Now the BLAS and LAPACK tests pass (which does not mean much, see
below)..

Note, however, that the BLAS and LAPACK tests where written to do a simple
comparison of the float and double versions that I had to effectively disarm
to get this to compile.  These tests are very simplistic and do not really
test the BLAS and LAPACK wrappers (other than to make sure that you do not
segfault or something).  It is really up to the clients of these wrappers to
have their own tests.  This is an SQA issue that Trilinos needs to work out
and have a policy for.

diff --git a/packages/teuchos/configure b/packages/teuchos/configure
--- a/packages/teuchos/configure
+++ b/packages/teuchos/configure
@@ -740,6 +740,8 @@ HAVE_TEUCHOS_COMPLEX_TRUE
 HAVE_TEUCHOS_COMPLEX_FALSE
 HAVE_TEUCHOS_EXTENDED_TRUE
 HAVE_TEUCHOS_EXTENDED_FALSE
+HAVE_TEUCHOS_BLASFLOAT_TRUE
+HAVE_TEUCHOS_BLASFLOAT_FALSE
 HAVE_TEUCHOS_BOOST_TRUE
 HAVE_TEUCHOS_BOOST_FALSE
 FLIBS
@@ -1381,6 +1383,9 @@ Optional Features:
                           Enable Teuchos extended code (default is yes)
   --enable-teuchos-arprec Enable Teuchos interface support for the ARbitrary
                           PRECision Library (default is no)
+  --enable-teuchos-blasfloat
+                          Enable support for float BLAS wrappers code (default
+                          is yes)
   --enable-teuchos-gmp    Enable Teuchos interface support for the GNU MP
                           Library (default is no)
   --enable-teuchos-expat  Enable Teuchos interface support for the Expat XML
@@ -10253,6 +10258,44 @@ echo "${ECHO_T}no" >&6; }
 fi
 
 
+#
+#  --enable-teuchos-blasfloat
+#
+
+
+# Check whether --enable-teuchos-blasfloat was given.
+if test "${enable_teuchos_blasfloat+set}" = set; then
+  enableval=$enable_teuchos_blasfloat; ac_cv_use_teuchos_blasfloat=$enableval
+else
+  ac_cv_use_teuchos_blasfloat=yes
+fi
+
+
+{ echo "$as_me:$LINENO: checking whether to use teuchos-blasfloat" >&5
+echo $ECHO_N "checking whether to use teuchos-blasfloat... $ECHO_C" >&6; }
+
+if test "X$ac_cv_use_teuchos_blasfloat" != "Xno"; then
+  { echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6; }
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_TEUCHOS_BLASFLOAT
+_ACEOF
+
+else
+  { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+fi
+
+ if test "X$ac_cv_use_teuchos_blasfloat" != "Xno"; then
+  HAVE_TEUCHOS_BLASFLOAT_TRUE=
+  HAVE_TEUCHOS_BLASFLOAT_FALSE='#'
+else
+  HAVE_TEUCHOS_BLASFLOAT_TRUE='#'
+  HAVE_TEUCHOS_BLASFLOAT_FALSE=
+fi
+
+
 if test "X$ac_cv_use_teuchos_arprec" != "Xno"; then
 
 #  TAC_ARG_WITH( trilinos3pldir, [Set Trilinos3PL directory], trilinos3pldir_is_not_specified )
@@ -14649,6 +14692,13 @@ echo "$as_me: error: conditional \"HAVE_TEUCHOS_EXTENDED\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
+if test -z "${HAVE_TEUCHOS_BLASFLOAT_TRUE}" && test -z "${HAVE_TEUCHOS_BLASFLOAT_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"HAVE_TEUCHOS_BLASFLOAT\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"HAVE_TEUCHOS_BLASFLOAT\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
 if test -z "${HAVE_TEUCHOS_BOOST_TRUE}" && test -z "${HAVE_TEUCHOS_BOOST_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"HAVE_TEUCHOS_BOOST\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
@@ -15410,6 +15460,8 @@ HAVE_TEUCHOS_COMPLEX_TRUE!$HAVE_TEUCHOS_COMPLEX_TRUE$ac_delim
 HAVE_TEUCHOS_COMPLEX_FALSE!$HAVE_TEUCHOS_COMPLEX_FALSE$ac_delim
 HAVE_TEUCHOS_EXTENDED_TRUE!$HAVE_TEUCHOS_EXTENDED_TRUE$ac_delim
 HAVE_TEUCHOS_EXTENDED_FALSE!$HAVE_TEUCHOS_EXTENDED_FALSE$ac_delim
+HAVE_TEUCHOS_BLASFLOAT_TRUE!$HAVE_TEUCHOS_BLASFLOAT_TRUE$ac_delim
+HAVE_TEUCHOS_BLASFLOAT_FALSE!$HAVE_TEUCHOS_BLASFLOAT_FALSE$ac_delim
 HAVE_TEUCHOS_BOOST_TRUE!$HAVE_TEUCHOS_BOOST_TRUE$ac_delim
 HAVE_TEUCHOS_BOOST_FALSE!$HAVE_TEUCHOS_BOOST_FALSE$ac_delim
 FLIBS!$FLIBS$ac_delim
@@ -15431,7 +15483,7 @@ LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 47; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 49; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
diff --git a/packages/thyra/configure b/packages/thyra/configure
--- a/packages/thyra/configure
+++ b/packages/thyra/configure
@@ -702,6 +702,8 @@ ENABLE_THYRA_TPETRA_TRUE
 ENABLE_THYRA_TPETRA_FALSE
 ENABLE_THYRA_EPETRAEXT_TRUE
 ENABLE_THYRA_EPETRAEXT_FALSE
+ENABLE_THYRA_TEUCHOS_BLASFLOAT_TRUE
+ENABLE_THYRA_TEUCHOS_BLASFLOAT_FALSE
 USING_EXPORT_MAKEFILES_TRUE
 USING_EXPORT_MAKEFILES_FALSE
 PERL_EXE
@@ -1342,6 +1344,13 @@ Optional Features:
                           be overridden with --disable-thyra-epetraext.
   --enable-thyra-epetraext
                           Build the Thyra adapater support for EpetraExt.
+  --enable-teuchos        Determines if float support is enabled or not. See
+                          thyra/configure --help
+  --enable-blasfloat      Determines if float support is enabled or not. See
+                          thyra/configure --help
+  --enable-teuchos-blasfloat
+                          Determines if float support is enabled or not. See
+                          thyra/configure --help
   --enable-export-makefiles
                           Creates export makefiles in the install (prefix)
                           directory. This option requires perl to be set in
@@ -5621,6 +5630,69 @@ fi
 
 
 
+
+
+# Check whether --enable-teuchos was given.
+if test "${enable_teuchos+set}" = set; then
+  enableval=$enable_teuchos; ac_cv_implicit_use_teuchos=$enableval
+else
+  ac_cv_implicit_use_teuchos=no
+fi
+
+
+# Check whether --enable-blasfloat was given.
+if test "${enable_blasfloat+set}" = set; then
+  enableval=$enable_blasfloat; ac_cv_implicit_use_blasfloat=$enableval
+else
+  ac_cv_implicit_use_blasfloat=no
+fi
+
+
+if test "Xyes" != "Xno"; then
+  if test "X$ac_cv_implicit_use_teuchos" != "Xno"; then
+    ac_cv_teuchos_using_blasfloat_default=$ac_cv_implicit_use_blasfloat
+  else
+    ac_cv_teuchos_using_blasfloat_default=no
+  fi
+else
+  ac_cv_teuchos_using_blasfloat_default=no
+fi
+
+# Check whether --enable-teuchos-blasfloat was given.
+if test "${enable_teuchos_blasfloat+set}" = set; then
+  enableval=$enable_teuchos_blasfloat; ac_cv_use_blasfloat=$enableval
+else
+  ac_cv_use_blasfloat=$ac_cv_teuchos_using_blasfloat_default
+fi
+
+
+{ echo "$as_me:$LINENO: checking whether to build optional blasfloat dependent code in teuchos" >&5
+echo $ECHO_N "checking whether to build optional blasfloat dependent code in teuchos... $ECHO_C" >&6; }
+
+if test "X$ac_cv_use_blasfloat" != "Xno"; then
+  { echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6; }
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_THYRA_TEUCHOS_BLASFLOAT 1
+_ACEOF
+
+else
+  { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+fi
+
+ if test "X$ac_cv_use_blasfloat" = "Xyes"; then
+  ENABLE_THYRA_TEUCHOS_BLASFLOAT_TRUE=
+  ENABLE_THYRA_TEUCHOS_BLASFLOAT_FALSE='#'
+else
+  ENABLE_THYRA_TEUCHOS_BLASFLOAT_TRUE='#'
+  ENABLE_THYRA_TEUCHOS_BLASFLOAT_FALSE=
+fi
+
+
+
+
 # ------------------------------------------------------------------------
 # Specify other directories
 # ------------------------------------------------------------------------
@@ -6640,6 +6712,13 @@ echo "$as_me: error: conditional \"ENABLE_THYRA_EPETRAEXT\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
+if test -z "${ENABLE_THYRA_TEUCHOS_BLASFLOAT_TRUE}" && test -z "${ENABLE_THYRA_TEUCHOS_BLASFLOAT_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"ENABLE_THYRA_TEUCHOS_BLASFLOAT\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"ENABLE_THYRA_TEUCHOS_BLASFLOAT\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
 if test -z "${USING_EXPORT_MAKEFILES_TRUE}" && test -z "${USING_EXPORT_MAKEFILES_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"USING_EXPORT_MAKEFILES\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
@@ -7378,6 +7457,8 @@ ENABLE_THYRA_TPETRA_TRUE!$ENABLE_THYRA_TPETRA_TRUE$ac_delim
 ENABLE_THYRA_TPETRA_FALSE!$ENABLE_THYRA_TPETRA_FALSE$ac_delim
 ENABLE_THYRA_EPETRAEXT_TRUE!$ENABLE_THYRA_EPETRAEXT_TRUE$ac_delim
 ENABLE_THYRA_EPETRAEXT_FALSE!$ENABLE_THYRA_EPETRAEXT_FALSE$ac_delim
+ENABLE_THYRA_TEUCHOS_BLASFLOAT_TRUE!$ENABLE_THYRA_TEUCHOS_BLASFLOAT_TRUE$ac_delim
+ENABLE_THYRA_TEUCHOS_BLASFLOAT_FALSE!$ENABLE_THYRA_TEUCHOS_BLASFLOAT_FALSE$ac_delim
 USING_EXPORT_MAKEFILES_TRUE!$USING_EXPORT_MAKEFILES_TRUE$ac_delim
 USING_EXPORT_MAKEFILES_FALSE!$USING_EXPORT_MAKEFILES_FALSE$ac_delim
 PERL_EXE!$PERL_EXE$ac_delim
@@ -7393,7 +7474,7 @@ LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 39; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 41; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
