----------------------------------------------------------------------
 Committing in .

 Modified Files:
 	Makefile.in aclocal.m4 configure configure.ac src/Makefile.in
 	src/Teuchos_BLAS_wrappers.hpp src/Teuchos_ConfigDefs.hpp
 	src/Teuchos_LAPACK_wrappers.hpp src/Teuchos_ParameterList.hpp
 	src/Teuchos_ScalarTraits.hpp src/Teuchos_config.h.in
 	test/Makefile.in test/BLAS/Makefile.in
 	test/DenseMatrix/Makefile.in test/LAPACK/Makefile.in
 	test/ParameterList/Makefile.in
 ----------------------------------------------------------------------

 Added some common included header files to configure script and removed
 them from source files, then bootstrapped Teuchos.

diff --git a/packages/teuchos/configure b/packages/teuchos/configure
--- a/packages/teuchos/configure
+++ b/packages/teuchos/configure
@@ -1400,7 +1400,7 @@ ac_config_sub="$SHELL $ac_aux_dir/config.sub"
 ac_configure="$SHELL $ac_aux_dir/configure" # This should be Cygnus configure.
 
 #  #np# - Change file names in next line
-# Configure should create src/New_Package_config.h from src/New_Package_config.h.in
+# Configure should create src/Teuchos_config.h from src/Teuchos_config.h.in
 
 # Add the stamp file to the list of files AC keeps track of,
 # along with our hook.
@@ -4745,7 +4745,156 @@ done
 
 
 
-for ac_header in string string.h
+
+
+
+
+for ac_header in string string.h complex complex.h algorithm algorithm.h
+do
+as_ac_Header=`echo "ac_cv_header_$ac_header" | $as_tr_sh`
+if eval "test \"\${$as_ac_Header+set}\" = set"; then
+  echo "$as_me:$LINENO: checking for $ac_header" >&5
+echo $ECHO_N "checking for $ac_header... $ECHO_C" >&6
+if eval "test \"\${$as_ac_Header+set}\" = set"; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+fi
+echo "$as_me:$LINENO: result: `eval echo '${'$as_ac_Header'}'`" >&5
+echo "${ECHO_T}`eval echo '${'$as_ac_Header'}'`" >&6
+else
+  # Is the header compilable?
+echo "$as_me:$LINENO: checking $ac_header usability" >&5
+echo $ECHO_N "checking $ac_header usability... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+$ac_includes_default
+#include <$ac_header>
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_header_compiler=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_header_compiler=no
+fi
+rm -f conftest.$ac_objext conftest.$ac_ext
+echo "$as_me:$LINENO: result: $ac_header_compiler" >&5
+echo "${ECHO_T}$ac_header_compiler" >&6
+
+# Is the header present?
+echo "$as_me:$LINENO: checking $ac_header presence" >&5
+echo $ECHO_N "checking $ac_header presence... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <$ac_header>
+_ACEOF
+if { (eval echo "$as_me:$LINENO: \"$ac_cpp conftest.$ac_ext\"") >&5
+  (eval $ac_cpp conftest.$ac_ext) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } >/dev/null; then
+  if test -s conftest.err; then
+    ac_cpp_err=$ac_cxx_preproc_warn_flag
+  else
+    ac_cpp_err=
+  fi
+else
+  ac_cpp_err=yes
+fi
+if test -z "$ac_cpp_err"; then
+  ac_header_preproc=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+  ac_header_preproc=no
+fi
+rm -f conftest.err conftest.$ac_ext
+echo "$as_me:$LINENO: result: $ac_header_preproc" >&5
+echo "${ECHO_T}$ac_header_preproc" >&6
+
+# So?  What about this header?
+case $ac_header_compiler:$ac_header_preproc in
+  yes:no )
+    { echo "$as_me:$LINENO: WARNING: $ac_header: accepted by the compiler, rejected by the preprocessor!" >&5
+echo "$as_me: WARNING: $ac_header: accepted by the compiler, rejected by the preprocessor!" >&2;}
+    { echo "$as_me:$LINENO: WARNING: $ac_header: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: $ac_header: proceeding with the preprocessor's result" >&2;}
+    (
+      cat <<\_ASBOX
+## ------------------------------------ ##
+## Report this to bug-autoconf@gnu.org. ##
+## ------------------------------------ ##
+_ASBOX
+    ) |
+      sed "s/^/$as_me: WARNING:     /" >&2
+    ;;
+  no:yes )
+    { echo "$as_me:$LINENO: WARNING: $ac_header: present but cannot be compiled" >&5
+echo "$as_me: WARNING: $ac_header: present but cannot be compiled" >&2;}
+    { echo "$as_me:$LINENO: WARNING: $ac_header: check for missing prerequisite headers?" >&5
+echo "$as_me: WARNING: $ac_header: check for missing prerequisite headers?" >&2;}
+    { echo "$as_me:$LINENO: WARNING: $ac_header: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: $ac_header: proceeding with the preprocessor's result" >&2;}
+    (
+      cat <<\_ASBOX
+## ------------------------------------ ##
+## Report this to bug-autoconf@gnu.org. ##
+## ------------------------------------ ##
+_ASBOX
+    ) |
+      sed "s/^/$as_me: WARNING:     /" >&2
+    ;;
+esac
+echo "$as_me:$LINENO: checking for $ac_header" >&5
+echo $ECHO_N "checking for $ac_header... $ECHO_C" >&6
+if eval "test \"\${$as_ac_Header+set}\" = set"; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  eval "$as_ac_Header=$ac_header_preproc"
+fi
+echo "$as_me:$LINENO: result: `eval echo '${'$as_ac_Header'}'`" >&5
+echo "${ECHO_T}`eval echo '${'$as_ac_Header'}'`" >&6
+
+fi
+if test `eval echo '${'$as_ac_Header'}'` = yes; then
+  cat >>confdefs.h <<_ACEOF
+#define `echo "HAVE_$ac_header" | $as_tr_cpp` 1
+_ACEOF
+
+fi
+
+done
+
+
+
+
+
+for ac_header in map map.h vector vector.h
 do
 as_ac_Header=`echo "ac_cv_header_$ac_header" | $as_tr_sh`
 if eval "test \"\${$as_ac_Header+set}\" = set"; then
@@ -4888,46 +5037,70 @@ done
 
 
 if test "X$ac_cv_header_cstdlib" != "Xyes" && test "X$ac_cv_header_stdlib_h" != "Xyes"; then
-  { { echo "$as_me:$LINENO: error: Cannot find cstdlib or stdlib.h.  New_Package requires at least one or the other." >&5
-echo "$as_me: error: Cannot find cstdlib or stdlib.h.  New_Package requires at least one or the other." >&2;}
+  { { echo "$as_me:$LINENO: error: Cannot find cstdlib or stdlib.h.  Teuchos requires at least one or the other." >&5
+echo "$as_me: error: Cannot find cstdlib or stdlib.h.  Teuchos requires at least one or the other." >&2;}
    { (exit 1); exit 1; }; }
 fi
 
 if test "X$ac_cv_header_cstdio" != "Xyes" && test "X$ac_cv_header_stdio_h" != "Xyes"; then
-  { { echo "$as_me:$LINENO: error: Cannot find cstdio or stdio.h.  New_Package requires at least one or the other." >&5
-echo "$as_me: error: Cannot find cstdio or stdio.h.  New_Package requires at least one or the other." >&2;}
+  { { echo "$as_me:$LINENO: error: Cannot find cstdio or stdio.h.  Teuchos requires at least one or the other." >&5
+echo "$as_me: error: Cannot find cstdio or stdio.h.  Teuchos requires at least one or the other." >&2;}
    { (exit 1); exit 1; }; }
 fi
 
 if test "X$ac_cv_header_cassert" != "Xyes" && test "X$ac_cv_header_assert_h" != "Xyes"; then
-  { { echo "$as_me:$LINENO: error: Cannot find cassert or assert.h.  New_Package requires at least one or the other." >&5
-echo "$as_me: error: Cannot find cassert or assert.h.  New_Package requires at least one or the other." >&2;}
-   { (exit 1); exit 1; }; }
-fi
-
-if test "X$ac_cv_header_string" != "Xyes" && test "X$ac_cv_header_string_h" != "Xyes"; then
-  { { echo "$as_me:$LINENO: error: Cannot find string or string.h.  New_Package requires at least one or the other." >&5
-echo "$as_me: error: Cannot find string or string.h.  New_Package requires at least one or the other." >&2;}
+  { { echo "$as_me:$LINENO: error: Cannot find cassert or assert.h.  Teuchos requires at least one or the other." >&5
+echo "$as_me: error: Cannot find cassert or assert.h.  Teuchos requires at least one or the other." >&2;}
    { (exit 1); exit 1; }; }
 fi
 
 if test "X$ac_cv_header_iostream" != "Xyes" && test "X$ac_cv_header_iostream_h" != "Xyes"; then
-  { { echo "$as_me:$LINENO: error: Cannot find iostream or iostream.h.  New_Package requires at least one or the other." >&5
-echo "$as_me: error: Cannot find iostream or iostream.h.  New_Package requires at least one or the other." >&2;}
+  { { echo "$as_me:$LINENO: error: Cannot find iostream or iostream.h.  Teuchos requires at least one or the other." >&5
+echo "$as_me: error: Cannot find iostream or iostream.h.  Teuchos requires at least one or the other." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+
+if test "X$ac_cv_header_string" != "Xyes" && test "X$ac_cv_header_string_h" != "Xyes"; then
+  { { echo "$as_me:$LINENO: error: Cannot find string or string.h.  Teuchos requires at least one or the other." >&5
+echo "$as_me: error: Cannot find string or string.h.  Teuchos requires at least one or the other." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+
+if test "X$ac_cv_header_complex" != "Xyes" && test "X$ac_cv_header_complex_h" != "Xyes"; then
+  { { echo "$as_me:$LINENO: error: Cannot find complex or complex.h.  Teuchos requires at least one or the other." >&5
+echo "$as_me: error: Cannot find complex or complex.h.  Teuchos requires at least one or the other." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+
+if test "X$ac_cv_header_algorithm" != "Xyes" && test "X$ac_cv_header_algorithm_h" != "Xyes"; then
+  { { echo "$as_me:$LINENO: error: Cannot find algorithm or algorithm.h.  Teuchos requires at least one or the other." >&5
+echo "$as_me: error: Cannot find algorithm or algorithm.h.  Teuchos requires at least one or the other." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+
+if test "X$ac_cv_header_map" != "Xyes" && test "X$ac_cv_header_map_h" != "Xyes"; then
+  { { echo "$as_me:$LINENO: error: Cannot find map or map.h.  Teuchos requires at least one or the other." >&5
+echo "$as_me: error: Cannot find map or map.h.  Teuchos requires at least one or the other." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+
+if test "X$ac_cv_header_vector" != "Xyes" && test "X$ac_cv_header_vector_h" != "Xyes"; then
+  { { echo "$as_me:$LINENO: error: Cannot find vector or vector.h.  Teuchos requires at least one or the other." >&5
+echo "$as_me: error: Cannot find vector or vector.h.  Teuchos requires at least one or the other." >&2;}
    { (exit 1); exit 1; }; }
 fi
 
 if test "X${host}" != "Xtflop"; then
   if test "X$ac_cv_header_cmath" != "Xyes" && test "X$ac_cv_header_math_h" != "Xyes"; then
-    { { echo "$as_me:$LINENO: error: Cannot find cmath or math.h.  New_Package requires at least one or the other." >&5
-echo "$as_me: error: Cannot find cmath or math.h.  New_Package requires at least one or the other." >&2;}
+    { { echo "$as_me:$LINENO: error: Cannot find cmath or math.h.  Teuchos requires at least one or the other." >&5
+echo "$as_me: error: Cannot find cmath or math.h.  Teuchos requires at least one or the other." >&2;}
    { (exit 1); exit 1; }; }
   fi
 else
   # TFLOP
   if test "X$ac_cv_header_iomanip" != "Xyes" && test "X$ac_cv_header_iomanip_h" != "Xyes"; then
-    { { echo "$as_me:$LINENO: error: Cannot find iomanip or iomanip.h.  New_Package requires at least one or the other." >&5
-echo "$as_me: error: Cannot find iomanip or iomanip.h.  New_Package requires at least one or the other." >&2;}
+    { { echo "$as_me:$LINENO: error: Cannot find iomanip or iomanip.h.  Teuchos requires at least one or the other." >&5
+echo "$as_me: error: Cannot find iomanip or iomanip.h.  Teuchos requires at least one or the other." >&2;}
    { (exit 1); exit 1; }; }
   fi
 fi
@@ -5670,7 +5843,7 @@ fi;
 # a cpp #define command and one or more source or header files  - ie
 # conditional compilation which requires a change to the makefile.
 # If configure is called with "--enable-newp_swahili", it will place
-# a #define HAVE_NEWP_SWAHILI in New_Package_config.h and add source
+# a #define HAVE_NEWP_SWAHILI in Teuchos_config.h and add source
 # and header files as specified in Makefile.am
 #
 # To add an option to your package, you will need to modify this file
@@ -5680,7 +5853,7 @@ fi;
 # TAC_ARG_ENABLE_OPTION performs several tasks, including:
 #   1)  Setting a help string
 #   2)  Printing a message to standard out
-#   3)  Defining HAVE_NEWP_SWAHILI (For use in New_Package_config.h)
+#   3)  Defining HAVE_NEWP_SWAHILI (For use in Teuchos_config.h)
 #
 # AM_CONDITIONAL makes HAVE_NEWP_SWAHILI available for use in Makefile.am
 # ------------------------------------------------------------------------
@@ -6119,7 +6292,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_verb"
-(eval echo $as_me:6122: \"$ac_link\") >&5
+(eval echo $as_me:6295: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
@@ -6199,7 +6372,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_cv_prog_f77_v"
-(eval echo $as_me:6202: \"$ac_link\") >&5
+(eval echo $as_me:6375: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
@@ -8340,7 +8513,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_verb"
-(eval echo $as_me:8343: \"$ac_link\") >&5
+(eval echo $as_me:8516: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
@@ -8420,7 +8593,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_cv_prog_f77_v"
-(eval echo $as_me:8423: \"$ac_link\") >&5
+(eval echo $as_me:8596: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
