----------------------------------------------------------------------
 Committing in .

 Modified Files:
 	Makefile.in aclocal.m4 configure configure.ac src/Makefile.in
 	src/Teuchos_ConfigDefs.hpp src/Teuchos_PacketTraits.hpp
 	src/Teuchos_ParameterList.hpp src/Teuchos_ScalarTraits.hpp
 	src/Teuchos_config.h.in test/Makefile.in test/BLAS/Makefile.in
 	test/Containers/Makefile.in test/DenseMatrix/Makefile.in
 	test/LAPACK/Makefile.in test/ParameterList/Makefile.in
 	test/Random/Makefile.in test/RefCountPtr/Makefile.in
 	test/Time/Makefile.in test/XML/Makefile.in
 ----------------------------------------------------------------------

 The standard Teuchos package will configure and build with both RW and
 STLPort headers if complex code is turned off (bug #563).  Instead of
 keying this code off teuchos-experimental, it will be keyed off
 teuchos-complex.  This option will be disabled by default since no one is
 currently using the complex templates.

diff --git a/packages/teuchos/configure b/packages/teuchos/configure
--- a/packages/teuchos/configure
+++ b/packages/teuchos/configure
@@ -310,7 +310,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM AWK SET_MAKE CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE CXX CXXFLAGS ac_ct_CXX CXXDEPMODE F77 FFLAGS ac_ct_F77 RANLIB ac_ct_RANLIB MPI_CXX HAVE_MPI_TRUE HAVE_MPI_FALSE MPI_CXX_EXISTS MPI_CC_EXISTS MPI_F77_EXISTS USE_ALTERNATE_AR_TRUE USE_ALTERNATE_AR_FALSE ALTERNATE_AR CXXCPP EGREP BUILD_TESTS_TRUE BUILD_TESTS_FALSE HAVE_TEUCHOS_EXPERIMENTAL_TRUE HAVE_TEUCHOS_EXPERIMENTAL_FALSE FLIBS BLAS_LIBS LAPACK_LIBS TRILINOS_TEMPLATE_OBJS EXPAT_LIBS EXPAT_INC HAVE_EXPAT_TRUE HAVE_EXPAT_FALSE ac_aux_dir LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM AWK SET_MAKE CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE CXX CXXFLAGS ac_ct_CXX CXXDEPMODE F77 FFLAGS ac_ct_F77 RANLIB ac_ct_RANLIB MPI_CXX HAVE_MPI_TRUE HAVE_MPI_FALSE MPI_CXX_EXISTS MPI_CC_EXISTS MPI_F77_EXISTS USE_ALTERNATE_AR_TRUE USE_ALTERNATE_AR_FALSE ALTERNATE_AR CXXCPP EGREP BUILD_TESTS_TRUE BUILD_TESTS_FALSE HAVE_TEUCHOS_COMPLEX_TRUE HAVE_TEUCHOS_COMPLEX_FALSE HAVE_TEUCHOS_EXPERIMENTAL_TRUE HAVE_TEUCHOS_EXPERIMENTAL_FALSE FLIBS BLAS_LIBS LAPACK_LIBS TRILINOS_TEMPLATE_OBJS EXPAT_LIBS EXPAT_INC HAVE_EXPAT_TRUE HAVE_EXPAT_FALSE ac_aux_dir LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -878,6 +878,8 @@ Optional Features:
                           packages are sensitive to this option) (default is
                           yes)
   --enable-teuchos-abc    Enable array bounds checking (default is no)
+  --enable-teuchos-complex
+                          enable Teuchos complex code (default is no)
   --enable-teuchos-experimental
                           enable Teuchos experimental code (default is no)
   --enable-teuchos-arprec Enable Teuchos interface support for the ARbitrary
@@ -3179,7 +3181,7 @@ fi
 
 
 # Provide some information about the compiler.
-echo "$as_me:3182:" \
+echo "$as_me:3184:" \
      "checking for Fortran 77 compiler version" >&5
 ac_compiler=`set X $ac_compile; echo $2`
 { (eval echo "$as_me:$LINENO: \"$ac_compiler --version </dev/null >&5\"") >&5
@@ -6232,6 +6234,46 @@ fi
 # ------------------------------------------------------------------------
 
 #
+#  --enable-teuchos-complex
+#
+
+
+# Check whether --enable-teuchos-complex or --disable-teuchos-complex was given.
+if test "${enable_teuchos_complex+set}" = set; then
+  enableval="$enable_teuchos_complex"
+  ac_cv_use_teuchos_complex=$enableval
+else
+  ac_cv_use_teuchos_complex=no
+fi;
+
+echo "$as_me:$LINENO: checking whether to use teuchos-complex" >&5
+echo $ECHO_N "checking whether to use teuchos-complex... $ECHO_C" >&6
+
+if test "X$ac_cv_use_teuchos_complex" != "Xno"; then
+  echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_TEUCHOS_COMPLEX
+_ACEOF
+
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+
+
+if test "X$ac_cv_use_teuchos_complex" != "Xno"; then
+  HAVE_TEUCHOS_COMPLEX_TRUE=
+  HAVE_TEUCHOS_COMPLEX_FALSE='#'
+else
+  HAVE_TEUCHOS_COMPLEX_TRUE='#'
+  HAVE_TEUCHOS_COMPLEX_FALSE=
+fi
+
+
+#
 #  --enable-teuchos-experimental
 #
 
@@ -6649,7 +6691,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_verb"
-(eval echo $as_me:6652: \"$ac_link\") >&5
+(eval echo $as_me:6694: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
@@ -6729,7 +6771,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_cv_prog_f77_v"
-(eval echo $as_me:6732: \"$ac_link\") >&5
+(eval echo $as_me:6774: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
@@ -8870,7 +8912,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_verb"
-(eval echo $as_me:8873: \"$ac_link\") >&5
+(eval echo $as_me:8915: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
@@ -8950,7 +8992,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_cv_prog_f77_v"
-(eval echo $as_me:8953: \"$ac_link\") >&5
+(eval echo $as_me:8995: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
@@ -9415,6 +9457,13 @@ if test -z "${BUILD_TESTS_TRUE}" && test -z "${BUILD_TESTS_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"BUILD_TESTS\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"BUILD_TESTS\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${HAVE_TEUCHOS_COMPLEX_TRUE}" && test -z "${HAVE_TEUCHOS_COMPLEX_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"HAVE_TEUCHOS_COMPLEX\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"HAVE_TEUCHOS_COMPLEX\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -10042,6 +10091,8 @@ s,@CXXCPP@,$CXXCPP,;t t
 s,@EGREP@,$EGREP,;t t
 s,@BUILD_TESTS_TRUE@,$BUILD_TESTS_TRUE,;t t
 s,@BUILD_TESTS_FALSE@,$BUILD_TESTS_FALSE,;t t
+s,@HAVE_TEUCHOS_COMPLEX_TRUE@,$HAVE_TEUCHOS_COMPLEX_TRUE,;t t
+s,@HAVE_TEUCHOS_COMPLEX_FALSE@,$HAVE_TEUCHOS_COMPLEX_FALSE,;t t
 s,@HAVE_TEUCHOS_EXPERIMENTAL_TRUE@,$HAVE_TEUCHOS_EXPERIMENTAL_TRUE,;t t
 s,@HAVE_TEUCHOS_EXPERIMENTAL_FALSE@,$HAVE_TEUCHOS_EXPERIMENTAL_FALSE,;t t
 s,@FLIBS@,$FLIBS,;t t
