SUMMARY:  Partial port to cygwin/Intel C++ 8.0 for Windows XP           and update to doxygen documentation.
BUGS:     [???]

CHECKLIST:

1) Did you add any source files? No

2) Did you update or change the build system? Yes
2.a) Did you remember to do a bootstrap and do a 'cvs add' on the
     Makefile.am files and the Makefile.in files? Yes
2.b) [Optional but recommended] Did you blow away the libraries and
     executables and then rebuild the libraries? Yes

3) Did you rerun the test suite on at least the packages that you
   changed? No

COMMENTS:

Here I have ported the following library enables to cygwin/Intel C++ 8.0 for
Windows XP:

    --enable-teuchos --enable-teuchos-extended --enable-teuchos-debug --enable-teuchos-abc --disable-teuchos-complex \
    --enable-thyra \
    --enable-epetra --enable-epetra-abc \
    --enable-triutils --disable-triutils-tests --disable-triutils-examples \
    --enable-epetraext \
    --enable-amesos \
    --enable-ifpack \
    --enable-aztecoo \
    --enable-belos \
    --enable-stratimikos \
    --enable-rythmos \
    --enable-moocho --enable-moocho-ma28 \

All of the libraries built but not all of the tests and examples yet.  This
takes a long time on my poor little laptop that I run Outlook and losts of
other nasty APPs on at the same time.

I also partially updated the doxygen documentation after the move of many of
the Thyra adpaters into thyra and stratimikos.  There is still a good bit more
work to be done on the doxygen documentation before this is presentable.

diff --git a/packages/stratimikos/configure b/packages/stratimikos/configure
--- a/packages/stratimikos/configure
+++ b/packages/stratimikos/configure
@@ -710,6 +710,8 @@ ENABLE_STRATIMIKOS_THYRA_EPETRAEXT_TRUE
 ENABLE_STRATIMIKOS_THYRA_EPETRAEXT_FALSE
 ENABLE_STRATIMIKOS_ML_NOX_TRUE
 ENABLE_STRATIMIKOS_ML_NOX_FALSE
+BUILD_TEUCHOS_COMPLEX_TRUE
+BUILD_TEUCHOS_COMPLEX_FALSE
 BUILD_TESTS_TRUE
 BUILD_TESTS_FALSE
 BUILD_EXAMPLES_TRUE
@@ -1367,6 +1369,9 @@ Optional Features:
   --enable-ml             See ml/configure --help
   --enable-nox            See ml/configure --help
   --enable-ml-nox         See ml/configure --help
+  --enable-teuchos-complex
+                          Build examples/tests which use complex scalar type
+                          (default is yes)
   --enable-tests          Make tests for all Trilinos packages buildable with
                           'make tests' (default is yes)
 
@@ -5886,6 +5891,40 @@ fi
 
 
 
+
+# Check whether --enable-teuchos-complex was given.
+if test "${enable_teuchos_complex+set}" = set; then
+  enableval=$enable_teuchos_complex; ac_cv_use_teuchos_complex=$enableval
+else
+  ac_cv_use_teuchos_complex=yes
+fi
+
+
+{ echo "$as_me:$LINENO: checking whether to use teuchos-complex" >&5
+echo $ECHO_N "checking whether to use teuchos-complex... $ECHO_C" >&6; }
+
+if test "X$ac_cv_use_teuchos_complex" != "Xno"; then
+  { echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6; }
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_TEUCHOS_COMPLEX
+_ACEOF
+
+else
+  { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+fi
+
+ if test "X$ac_cv_use_teuchos_complex" != "Xno"; then
+  BUILD_TEUCHOS_COMPLEX_TRUE=
+  BUILD_TEUCHOS_COMPLEX_FALSE='#'
+else
+  BUILD_TEUCHOS_COMPLEX_TRUE='#'
+  BUILD_TEUCHOS_COMPLEX_FALSE=
+fi
+
+
 # ------------------------------------------------------------------------
 # Checks if examples should be built
 # ------------------------------------------------------------------------
@@ -7087,6 +7126,13 @@ echo "$as_me: error: conditional \"ENABLE_STRATIMIKOS_ML_NOX\" was never defined
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
+if test -z "${BUILD_TEUCHOS_COMPLEX_TRUE}" && test -z "${BUILD_TEUCHOS_COMPLEX_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"BUILD_TEUCHOS_COMPLEX\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"BUILD_TEUCHOS_COMPLEX\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
 if test -z "${BUILD_TESTS_TRUE}" && test -z "${BUILD_TESTS_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"BUILD_TESTS\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
@@ -7865,6 +7911,8 @@ ENABLE_STRATIMIKOS_THYRA_EPETRAEXT_TRUE!$ENABLE_STRATIMIKOS_THYRA_EPETRAEXT_TRUE
 ENABLE_STRATIMIKOS_THYRA_EPETRAEXT_FALSE!$ENABLE_STRATIMIKOS_THYRA_EPETRAEXT_FALSE$ac_delim
 ENABLE_STRATIMIKOS_ML_NOX_TRUE!$ENABLE_STRATIMIKOS_ML_NOX_TRUE$ac_delim
 ENABLE_STRATIMIKOS_ML_NOX_FALSE!$ENABLE_STRATIMIKOS_ML_NOX_FALSE$ac_delim
+BUILD_TEUCHOS_COMPLEX_TRUE!$BUILD_TEUCHOS_COMPLEX_TRUE$ac_delim
+BUILD_TEUCHOS_COMPLEX_FALSE!$BUILD_TEUCHOS_COMPLEX_FALSE$ac_delim
 BUILD_TESTS_TRUE!$BUILD_TESTS_TRUE$ac_delim
 BUILD_TESTS_FALSE!$BUILD_TESTS_FALSE$ac_delim
 BUILD_EXAMPLES_TRUE!$BUILD_EXAMPLES_TRUE$ac_delim
@@ -7888,7 +7936,7 @@ LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 55; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 57; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
