----------------------------------------------------------------------  Modified Files:  	Makefile.in aclocal.m4 configure configure.ac  	example/Makefile.in example/EpetraTpetraProfile/Makefile.in  	example/verySimple/Makefile.in src/Makefile.in  	src/Tpetra_config.h.in test/Makefile.in  	test/BasicPerfTest/Makefile.in  	test/BlockElementSpace/Makefile.in test/CisMatrix/Makefile.in  	test/Comm/Makefile.in test/Directory/Makefile.in  	test/Distributor/Makefile.in test/ElementSpace/Makefile.in  	test/ImportExport/Makefile.in test/Platform/Makefile.in  	test/Vector/Makefile.in test/VectorSpace/Makefile.in  	test/scripts/Makefile.in test/scripts/daily/Makefile.in  	test/scripts/daily/mpi/Makefile.in 	test/scripts/daily/serial/Makefile.in  Added Files:  	config/ac_cxx_std_new_count_syntax.m4  ----------------------------------------------------------------------
Added M4 macro for std::count algorithm and bootstrapped.

diff --git a/packages/tpetra/configure b/packages/tpetra/configure
--- a/packages/tpetra/configure
+++ b/packages/tpetra/configure
@@ -7245,6 +7245,96 @@ _ACEOF
 
 fi
 
+echo "$as_me:$LINENO: checking whether the compiler recognizes the new form of std::count" >&5
+echo $ECHO_N "checking whether the compiler recognizes the new form of std::count... $ECHO_C" >&6
+if test "${ac_cv_cxx_new_count+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+
+
+ ac_ext=cc
+ac_cpp='$CXXCPP $CPPFLAGS'
+ac_compile='$CXX -c $CXXFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CXX -o conftest$ac_exeext $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
+
+ cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+#ifdef HAVE_VECTOR
+#include <vector>
+#elif HAVE_VECTOR_H
+#include <vector.h>
+#endif
+#ifdef HAVE_ALGORITHM
+#include <algorithm>
+#elif HAVE_ALGO_H
+#include <algo.h>
+#endif
+void dummy() {
+	std::vector<int> foo;
+	std::count(foo.begin(), foo.end(), 0);
+};
+int
+main ()
+{
+ dummy();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_cxx_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_cxx_new_count=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_cxx_new_count=no
+fi
+rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
+ac_ext=cc
+ac_cpp='$CXXCPP $CPPFLAGS'
+ac_compile='$CXX -c $CXXFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CXX -o conftest$ac_exeext $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
+
+
+fi
+echo "$as_me:$LINENO: result: $ac_cv_cxx_new_count" >&5
+echo "${ECHO_T}$ac_cv_cxx_new_count" >&6
+if test "$ac_cv_cxx_new_count" = yes; then
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_STD_NEW_COUNT_SYNTAX
+_ACEOF
+
+fi
+
 
 # ------------------------------------------------------------------------
 # Checks if tests should be built
@@ -7850,7 +7940,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_verb"
-(eval echo $as_me:7853: \"$ac_link\") >&5
+(eval echo $as_me:7943: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
@@ -7928,7 +8018,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_cv_prog_f77_v"
-(eval echo $as_me:7931: \"$ac_link\") >&5
+(eval echo $as_me:8021: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
@@ -10461,7 +10551,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_verb"
-(eval echo $as_me:10464: \"$ac_link\") >&5
+(eval echo $as_me:10554: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
@@ -10539,7 +10629,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_cv_prog_f77_v"
-(eval echo $as_me:10542: \"$ac_link\") >&5
+(eval echo $as_me:10632: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
