Added configure option to detect AztecOO, thus all Makefile's got touched.
Initial committing of test for Block Davidson, not finished yet.

diff --git a/packages/anasazi/anasazi_new/configure b/packages/anasazi/anasazi_new/configure
--- a/packages/anasazi/anasazi_new/configure
+++ b/packages/anasazi/anasazi_new/configure
@@ -311,7 +311,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot MPI_TEMP_CXX MPI_CXX HAVE_MPI_TRUE HAVE_MPI_FALSE MPI_CXX_EXISTS MPI_CC_EXISTS MPI_F77_EXISTS CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE F77 FFLAGS ac_ct_F77 RANLIB ac_ct_RANLIB USE_ALTERNATE_AR_TRUE USE_ALTERNATE_AR_FALSE ALTERNATE_AR CXXCPP EGREP BUILD_EXAMPLES_TRUE BUILD_EXAMPLES_FALSE BUILD_TESTS_TRUE BUILD_TESTS_FALSE BUILD_TRIUTILS_TRUE BUILD_TRIUTILS_FALSE BUILD_BELOS_TRUE BUILD_BELOS_FALSE BUILD_IFPACK_TRUE BUILD_IFPACK_FALSE FLIBS BLAS_LIBS LAPACK_LIBS ac_aux_dir LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot MPI_TEMP_CXX MPI_CXX HAVE_MPI_TRUE HAVE_MPI_FALSE MPI_CXX_EXISTS MPI_CC_EXISTS MPI_F77_EXISTS CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE F77 FFLAGS ac_ct_F77 RANLIB ac_ct_RANLIB USE_ALTERNATE_AR_TRUE USE_ALTERNATE_AR_FALSE ALTERNATE_AR CXXCPP EGREP BUILD_EXAMPLES_TRUE BUILD_EXAMPLES_FALSE BUILD_TESTS_TRUE BUILD_TESTS_FALSE BUILD_TRIUTILS_TRUE BUILD_TRIUTILS_FALSE BUILD_BELOS_TRUE BUILD_BELOS_FALSE BUILD_AZTECOO_TRUE BUILD_AZTECOO_FALSE BUILD_IFPACK_TRUE BUILD_IFPACK_FALSE FLIBS BLAS_LIBS LAPACK_LIBS ac_aux_dir LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -892,6 +892,7 @@ Optional Features:
                           examples are also disabled.) (default is yes)
   --enable-triutils       Build examples which use Triutils
   --enable-belos          Build examples which use Belos
+  --enable-aztecoo        Build examples which use AztecOO
   --enable-ifpack         Build examples which use Ifpack
 
 Optional Packages:
@@ -3806,7 +3807,7 @@ fi
 
 
 # Provide some information about the compiler.
-echo "$as_me:3809:" \
+echo "$as_me:3810:" \
      "checking for Fortran 77 compiler version" >&5
 ac_compiler=`set X $ac_compile; echo $2`
 { (eval echo "$as_me:$LINENO: \"$ac_compiler --version </dev/null >&5\"") >&5
@@ -6929,6 +6930,42 @@ fi
 
 
 
+# Check whether --enable-aztecoo or --disable-aztecoo was given.
+if test "${enable_aztecoo+set}" = set; then
+  enableval="$enable_aztecoo"
+  ac_cv_use_aztecoo=$enableval
+else
+  ac_cv_use_aztecoo=no
+fi;
+
+echo "$as_me:$LINENO: checking whether to build optional aztecoo dependent code" >&5
+echo $ECHO_N "checking whether to build optional aztecoo dependent code... $ECHO_C" >&6
+
+if test "X$ac_cv_use_aztecoo" != "Xno"; then
+  echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_ANASAZI_AZTECOO 1
+_ACEOF
+
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+
+
+if test "X$ac_cv_use_aztecoo" != "Xno"; then
+  BUILD_AZTECOO_TRUE=
+  BUILD_AZTECOO_FALSE='#'
+else
+  BUILD_AZTECOO_TRUE='#'
+  BUILD_AZTECOO_FALSE=
+fi
+
+
+
 # Check whether --enable-ifpack or --disable-ifpack was given.
 if test "${enable_ifpack+set}" = set; then
   enableval="$enable_ifpack"
@@ -6962,7 +6999,6 @@ else
   BUILD_IFPACK_TRUE='#'
   BUILD_IFPACK_FALSE=
 fi
-
 
 
 # ------------------------------------------------------------------------
@@ -7063,7 +7099,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_verb"
-(eval echo $as_me:7066: \"$ac_link\") >&5
+(eval echo $as_me:7102: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
@@ -7141,7 +7177,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_cv_prog_f77_v"
-(eval echo $as_me:7144: \"$ac_link\") >&5
+(eval echo $as_me:7180: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
@@ -9980,7 +10016,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_verb"
-(eval echo $as_me:9983: \"$ac_link\") >&5
+(eval echo $as_me:10019: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
@@ -10058,7 +10094,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_cv_prog_f77_v"
-(eval echo $as_me:10061: \"$ac_link\") >&5
+(eval echo $as_me:10097: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
@@ -10281,7 +10317,7 @@ ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
 #  of tests.  New package comes only with src and example.
 #  You will need to change AC_CONFIG_FILES below and Makefile.am
 #  to add a new directory.
-                                                                      ac_config_files="$ac_config_files Makefile src/Makefile example/Makefile example/ModeLaplace/Makefile example/BlockKrylovSchur/Makefile test/Makefile test/ModalSolverUtils/Makefile"
+                                                                                ac_config_files="$ac_config_files Makefile src/Makefile example/Makefile example/ModeLaplace/Makefile example/BlockKrylovSchur/Makefile test/Makefile test/ModalSolverUtils/Makefile test/BlockDavidson/Makefile"
 
 
 cat >confcache <<\_ACEOF
@@ -10449,6 +10485,13 @@ if test -z "${BUILD_BELOS_TRUE}" && test -z "${BUILD_BELOS_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"BUILD_BELOS\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"BUILD_BELOS\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${BUILD_AZTECOO_TRUE}" && test -z "${BUILD_AZTECOO_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"BUILD_AZTECOO\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"BUILD_AZTECOO\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -10910,6 +10953,7 @@ do
   "example/BlockKrylovSchur/Makefile" ) CONFIG_FILES="$CONFIG_FILES example/BlockKrylovSchur/Makefile" ;;
   "test/Makefile" ) CONFIG_FILES="$CONFIG_FILES test/Makefile" ;;
   "test/ModalSolverUtils/Makefile" ) CONFIG_FILES="$CONFIG_FILES test/ModalSolverUtils/Makefile" ;;
+  "test/BlockDavidson/Makefile" ) CONFIG_FILES="$CONFIG_FILES test/BlockDavidson/Makefile" ;;
   "depfiles" ) CONFIG_COMMANDS="$CONFIG_COMMANDS depfiles" ;;
   "src/Anasazi_config.h" ) CONFIG_HEADERS="$CONFIG_HEADERS src/Anasazi_config.h:src/Anasazi_config.h.in" ;;
   *) { { echo "$as_me:$LINENO: error: invalid argument: $ac_config_target" >&5
@@ -11079,6 +11123,8 @@ s,@BUILD_TRIUTILS_TRUE@,$BUILD_TRIUTILS_TRUE,;t t
 s,@BUILD_TRIUTILS_FALSE@,$BUILD_TRIUTILS_FALSE,;t t
 s,@BUILD_BELOS_TRUE@,$BUILD_BELOS_TRUE,;t t
 s,@BUILD_BELOS_FALSE@,$BUILD_BELOS_FALSE,;t t
+s,@BUILD_AZTECOO_TRUE@,$BUILD_AZTECOO_TRUE,;t t
+s,@BUILD_AZTECOO_FALSE@,$BUILD_AZTECOO_FALSE,;t t
 s,@BUILD_IFPACK_TRUE@,$BUILD_IFPACK_TRUE,;t t
 s,@BUILD_IFPACK_FALSE@,$BUILD_IFPACK_FALSE,;t t
 s,@FLIBS@,$FLIBS,;t t
