Test script is almost done. Right now it only tests Chaco input files, but Nemesis problems will be added soon. Don't try running the script until I have committed the required input and output files.

diff --git a/packages/zoltan/test/run_tests b/packages/zoltan/test/run_tests
--- a/packages/zoltan/test/run_tests
+++ b/packages/zoltan/test/run_tests
@@ -1,11 +1,12 @@
-#!/bin/csh -x
+#!/bin/csh 
 #
 # This C-shell script runs all the test examples 
 # and compares the results against pre-computed results.
 #
-# Usage: run_tests <arch-type>
+# Usage: run_tests [-arch arch-type] [-cmd command]
 #
-# where arch-type is one of (sun, sunos, smos, tflop, cplant)
+# where arch-type is one of {sun, sunos, smos, tflop, cplant}.
+# Alternatively, give a command with the -cmd option.
 #
 # Initial version by Erik Boman, SNL 9226, 99/09/15.
 #
@@ -24,6 +25,8 @@ set nem_nproc = (5 6 9 36)
 @ no_parmetis = 0
 set outfile = tests.out
 set answers = answers
+set outdir = output
+unset run
 
 # Check for environment variables.
 if ($?NO_NEMESIS) then
@@ -33,31 +36,83 @@ if ($?NO_PARMETIS) then
    set no_parmetis = $NO_PARMETIS
 endif
 
-# Parse command-line options. These will override environment variables.
-# Not yet implemented, except for machine type.
+# Parse command-line options. 
+# These options will override the environment variables.
 
-# Determine what command to use to launch a parallel program
-if ( $#argv < 1 ) then
-  echo "Error: No machine-type argument"
+while ( $#argv )
+
+if ( $1 == "-no_parmetis" ) then
+   @ no_parmetis = 1
+else if ( $1 == "-no_nemesis" ) then
+   @ no_nemesis = 1
+else if ( $1 == "-arch" ) then
+
+  # Determine what command to use to launch a parallel program
+  if ( $#argv < 2 ) then
+    echo "Error: Missing argument for -arch"
+    goto usage
+  endif
+  
+  shift argv
+  set arch = $1
+  
+  switch ( $arch )
+  case sun:
+  case sunos:
+  case solaris:
+    set run = "mpirun -np"
+    breaksw
+  case smos:
+  case tflop:
+  case cplant:
+    set run = "yod -sz"
+    breaksw
+  default:
+    echo "Unknown arch-type. Please use -cmd to specify the run command."
+    exit -2
+    breaksw
+  endsw
+
+else if ( $1 == "-cmd" ) then
+  if ( $#argv < 2 ) then
+    echo "Error: Missing argument for -cmd"
+    goto usage
+  endif
+  
+  shift argv
+  set run = $1
+
+endif
+
+shift argv
+
+end # while ( $#argv )
+
+# Check if we have a run command
+if (! $?run ) then
+  echo "Error: No run command. Either -arch or -cmd must be used"
   goto usage
 endif
 
-switch ( $1 )
-case sun:
-case sunos:
-case solaris:
-  set run = "mpirun -np"
-  breaksw
-case smos:
-case tflop:
-case cplant:
-  set run = "yod -sz"
-  breaksw
-default:
-  echo "Unknown arch-type. You have to edit this script to make it work on your platform."
-  exit 2
-  breaksw
-endsw
+# Check if we have zdrive
+if ( $?arch ) then
+  set zdrive = zdrive.$arch
+else
+  set zdrive = zdrive
+endif
+if (! -x $zdrive ) then
+  echo "Error Cannot find executable $zdrive"
+  exit 3
+endif
+
+# Methods to try
+if ( $no_parmetis ) then
+  set ch_methods = ( rcb oct )
+  set nem_methods = ( rcb oct )
+else
+  set ch_methods = ( rcb oct partkway partkway-cyclic partgeom diffusion )
+  set nem_methods = ( rcb oct partkway partgeom diffusion )
+endif
 
 # Set up output file
 if ( -e $outfile ) mv $outfile ${outfile}.old
@@ -70,25 +125,56 @@ if (! $no_chaco ) then
   @ nprob = $#ch_name
   @ nfailed = 0
   while ( $#ch_name )
+
+    # Go to the next test directory, initialize
     cd ch_${ch_name[1]}
     @ fail = 0
     @ np = $ch_nproc[1]
-    # Run the driver
-    $run $np ../zdrive.$1
-    # Compare output files 
-    @ i = 0
-    while ( $i < $np )
-      diff -c ${ch_name[1]}.out.$np.$i ${answers}/${ch_name[1]}.out.$np.$i >> $outfile
-      if ( $status ) then 
-        @ fail = 1
+
+    # Check output directories 
+    if (! -d $outdir ) mkdir $outdir
+    if (! -d $answers ) then
+      echo "Warning: Answer directory missing in ch_${ch_name[1]}" | tee -a ../$outfile
+    endif
+
+    # Save input file 
+    if (-e zdrive.inp ) mv zdrive.inp zdrive.inp.bak
+
+    # Loop over all methods
+    foreach mtd ( $ch_methods )
+
+      # Check input file
+      if (-e zdrive.inp.${mtd} ) then
+        cp zdrive.inp.${mtd} zdrive.inp
+  
+        # Run the driver
+        $run $np ../$zdrive
+  
+        # Save and compare output files 
+        @ i = 0
+        while ( $i < $np )
+          mv ${ch_name[1]}.out.$np.$i  ${outdir}/${ch_name[1]}.$mtd.$np.$i
+          diff -c ${outdir}/${ch_name[1]}.$mtd.$np.$i ${answers}/${ch_name[1]}.$mtd.$np.$i >> ../$outfile
+          if ( $status ) then 
+            @ fail = 1
+          endif
+          @ i = $i + 1
+        end
+  
+      else
+        echo "Warning: Couldnt find input file ${ch_name[1]}/zdrive.inp.${mtd}, skipping..." | tee -a ../$outfile
       endif
-      @ i = $i + 1
-    end
+    end # foreach method
+
     # Add problem to failure list if it failed
     if ( $fail ) then
       @ nfailed = $nfailed + 1
-      echo "Test problem $ch_name failed."
+      echo "Test problem ${ch_name[1]} failed with method ${mtd}." | tee -a ../$outfile
     endif
+
+    # Restore zdrive.inp
+    if (-e zdrive.inp.bak ) mv zdrive.inp.bak zdrive.inp
+
     # Shift arguments and return to original directory
     shift ch_name
     shift ch_nproc
@@ -96,17 +182,20 @@ if (! $no_chaco ) then
   end
   
   # Print failure summary
-  echo " "
+  echo " " | tee -a $outfile
   if ( $nfailed == 0 ) then
-    echo "Success: all $nprob Chaco problems passed!"
+    echo "Success: all $nprob Chaco problems passed." | tee -a $outfile
   else
-    echo "Failure: $nfailed out of $nprob Chaco problems failed."
+    echo "Failure: $nfailed out of $nprob Chaco problems failed." | tee -a $outfile
   endif
-  echo " "
+  echo " " | tee -a $outfile
 
-endif # do_chaco
+endif # chaco
 
 # Loop over Nemesis problems
+if (! $no_nemesis ) then
+  echo "Script for Nemesis problems not finished yet."
+endif # nemesis
 
 
 # Exit successfully
@@ -114,7 +203,11 @@ exit 0
 
 # Print usage and exit with error
 usage:
-  echo "Usage: $0 <arch-type>"
-  echo "where arch-type is one of (sun, sunos, smos, tflop, cplant)"
+  echo "Usage: $0 [-arch arch-type] [-cmd command]"
+  echo "where arch-type is one of {sun, sunos, smos, tflop, cplant}."
+  echo "Either -arch or -cmd must be specified."
+  echo "Other options:"
+  echo "   -no_nemesis"
+  echo "   -no_parmetis"
   exit -1
 
