Address bug 3901. Fei wasn't responding to --disable-examples (in fact was producing a make error). I've now added changes to configure.ac and Makefile.am so that --disable-examples works as expected.

diff --git a/packages/fei/configure b/packages/fei/configure
--- a/packages/fei/configure
+++ b/packages/fei/configure
@@ -705,6 +705,8 @@ RUN_COMMAND_SPECIFIED_FALSE
 SPECIFIED_RUN_COMMAND
 BUILD_TESTS_TRUE
 BUILD_TESTS_FALSE
+BUILD_EXAMPLES_TRUE
+BUILD_EXAMPLES_FALSE
 ac_aux_dir
 LIBOBJS
 LTLIBOBJS'
@@ -1318,6 +1320,7 @@ Optional Features:
                           --disable-fei-ifpack.
   --enable-fei-ifpack     Enable Ifpack support.
   --enable-tests          Build tests for FEI package (default is yes)
+  --enable-examples       Build examples for FEI package (default is yes)
 
 Optional Packages:
   --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
@@ -5382,9 +5385,7 @@ fi
 # Checks if tests and examples should be built
 # ------------------------------------------------------------------------
 
-#  #np# - These options can disable the tests and examples of a package.
-#  #np# - Packages that do not have tests or examples should #-out the
-#  #np# - option(s) that does (do) not apply.
+#  These options can disable the tests and examples of a package.
 
 # Check whether --enable-tests was given.
 if test "${enable_tests+set}" = set; then
@@ -5411,12 +5412,45 @@ echo "${ECHO_T}no" >&6; }
 fi
 
 
+# Check whether --enable-examples was given.
+if test "${enable_examples+set}" = set; then
+  enableval=$enable_examples; ac_cv_use_examples=$enableval
+else
+  ac_cv_use_examples=yes
+fi
+
+
+{ echo "$as_me:$LINENO: checking whether to use examples" >&5
+echo $ECHO_N "checking whether to use examples... $ECHO_C" >&6; }
+
+if test "X$ac_cv_use_examples" != "Xno"; then
+  { echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6; }
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_EXAMPLES
+_ACEOF
+
+else
+  { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+fi
+
+
  if test "X$ac_cv_use_tests" != "Xno"; then
   BUILD_TESTS_TRUE=
   BUILD_TESTS_FALSE='#'
 else
   BUILD_TESTS_TRUE='#'
   BUILD_TESTS_FALSE=
+fi
+
+ if example "X$ac_cv_use_examples" != "Xno"; then
+  BUILD_EXAMPLES_TRUE=
+  BUILD_EXAMPLES_FALSE='#'
+else
+  BUILD_EXAMPLES_TRUE='#'
+  BUILD_EXAMPLES_FALSE=
 fi
 
 
@@ -5702,6 +5736,13 @@ if test -z "${BUILD_TESTS_TRUE}" && test -z "${BUILD_TESTS_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"BUILD_TESTS\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"BUILD_TESTS\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${BUILD_EXAMPLES_TRUE}" && test -z "${BUILD_EXAMPLES_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"BUILD_EXAMPLES\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"BUILD_EXAMPLES\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -6422,12 +6463,14 @@ RUN_COMMAND_SPECIFIED_FALSE!$RUN_COMMAND_SPECIFIED_FALSE$ac_delim
 SPECIFIED_RUN_COMMAND!$SPECIFIED_RUN_COMMAND$ac_delim
 BUILD_TESTS_TRUE!$BUILD_TESTS_TRUE$ac_delim
 BUILD_TESTS_FALSE!$BUILD_TESTS_FALSE$ac_delim
+BUILD_EXAMPLES_TRUE!$BUILD_EXAMPLES_TRUE$ac_delim
+BUILD_EXAMPLES_FALSE!$BUILD_EXAMPLES_FALSE$ac_delim
 ac_aux_dir!$ac_aux_dir$ac_delim
 LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 33; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 35; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
