----------------------------------------------------------------------
 Committing in .

 Modified Files:
 	Makefile.am Makefile.in aclocal.m4 configure configure.ac
 	example/Makefile.am example/Makefile.in
 	src/Anasazi_config.h.in src/Makefile.in utils/Makefile.in
 Added Files:
 	config/tac_arg_enable_feature_sub.m4
 ----------------------------------------------------------------------

 Added new --enable/disable-anasazi-examples option to allow the user to
 shut off just anasazi's examples.  The default is yes, so the examples will
 build if the user doesn't use this option.  The new m4 file was added to
 parse this new option.  Furthermore, the configure script now parses the
 configure line for ifpack and belos to determine which examples it can build
 safely.

diff --git a/packages/anasazi/configure b/packages/anasazi/configure
--- a/packages/anasazi/configure
+++ b/packages/anasazi/configure
@@ -310,7 +310,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM AWK SET_MAKE CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE CXX CXXFLAGS ac_ct_CXX CXXDEPMODE F77 FFLAGS ac_ct_F77 RANLIB ac_ct_RANLIB MPI_CXX HAVE_MPI_TRUE HAVE_MPI_FALSE MPI_CXX_EXISTS MPI_CC_EXISTS MPI_F77_EXISTS USE_ALTERNATE_AR_TRUE USE_ALTERNATE_AR_FALSE ALTERNATE_AR CXXCPP EGREP BUILD_EXAMPLES_TRUE BUILD_EXAMPLES_FALSE FLIBS BLAS_LIBS LAPACK_LIBS ac_aux_dir LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM AWK SET_MAKE CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE CXX CXXFLAGS ac_ct_CXX CXXDEPMODE F77 FFLAGS ac_ct_F77 RANLIB ac_ct_RANLIB MPI_CXX HAVE_MPI_TRUE HAVE_MPI_FALSE MPI_CXX_EXISTS MPI_CC_EXISTS MPI_F77_EXISTS USE_ALTERNATE_AR_TRUE USE_ALTERNATE_AR_FALSE ALTERNATE_AR CXXCPP EGREP BUILD_ANASAZI_EXAMPLES_TRUE BUILD_ANASAZI_EXAMPLES_FALSE BUILD_EXAMPLES_TRUE BUILD_EXAMPLES_FALSE BUILD_BELOS_TRUE BUILD_BELOS_FALSE BUILD_IFPACK_TRUE BUILD_IFPACK_FALSE FLIBS BLAS_LIBS LAPACK_LIBS ac_aux_dir LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -874,9 +874,12 @@ Optional Features:
   --disable-dependency-tracking Speeds up one-time builds
   --enable-dependency-tracking  Do not reject slow dependency extractors
   --enable-mpi            MPI support
-  --enable-examples       Build examples for all Trilinos packages (not all
-                          packages are sensitive to this option) (default is
+  --enable-anasazi-examples
+                          Build anasazi examples (default is yes)
+  --enable-examples       Build examples for all Trilinos packages (default is
                           yes)
+  --enable-belos          Build examples which use belos (default is no)
+  --enable-ifpack         Build examples which use ifpack (default is no)
 
 Optional Packages:
   --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
@@ -3160,7 +3163,7 @@ fi
 
 
 # Provide some information about the compiler.
-echo "$as_me:3163:" \
+echo "$as_me:3166:" \
      "checking for Fortran 77 compiler version" >&5
 ac_compiler=`set X $ac_compile; echo $2`
 { (eval echo "$as_me:$LINENO: \"$ac_compiler --version </dev/null >&5\"") >&5
@@ -5620,8 +5623,43 @@ fi
 # TAC_ARG_WITH_PACKAGE(rtop, [Enable RTOp interface support], RTOP, no)
 
 # ------------------------------------------------------------------------
-# Checks if examples should be built
+# Checks if examples should be built or which ones should be built
 # ------------------------------------------------------------------------
+
+
+# Check whether --enable-anasazi-examples or --disable-anasazi-examples was given.
+if test "${enable_anasazi_examples+set}" = set; then
+  enableval="$enable_anasazi_examples"
+  ac_cv_use_anasazi_examples=$enableval
+else
+  ac_cv_use_anasazi_examples=yes
+fi;
+
+echo "$as_me:$LINENO: checking whether to use anasazi-examples" >&5
+echo $ECHO_N "checking whether to use anasazi-examples... $ECHO_C" >&6
+
+if test "X$ac_cv_use_anasazi_examples" != "Xno"; then
+  echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_ANASAZI_EXAMPLES
+_ACEOF
+
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+
+
+if test "X$ac_cv_use_anasazi_examples" != "Xno"; then
+  BUILD_ANASAZI_EXAMPLES_TRUE=
+  BUILD_ANASAZI_EXAMPLES_FALSE='#'
+else
+  BUILD_ANASAZI_EXAMPLES_TRUE='#'
+  BUILD_ANASAZI_EXAMPLES_FALSE=
+fi
 
 
 # Check whether --enable-examples or --disable-examples was given.
@@ -5656,6 +5694,78 @@ if test "X$ac_cv_use_examples" != "Xno"; then
 else
   BUILD_EXAMPLES_TRUE='#'
   BUILD_EXAMPLES_FALSE=
+fi
+
+#TAC_ARG_ENABLE_FEATURE(triutils, [Build examples which use triutils], TRIUTILS, no)
+#AM_CONDITIONAL(BUILD_TRIUTILS, test "X$ac_cv_use_triutils" != "Xno")
+
+# Check whether --enable-belos or --disable-belos was given.
+if test "${enable_belos+set}" = set; then
+  enableval="$enable_belos"
+  ac_cv_use_belos=$enableval
+else
+  ac_cv_use_belos=no
+fi;
+
+echo "$as_me:$LINENO: checking whether to use belos" >&5
+echo $ECHO_N "checking whether to use belos... $ECHO_C" >&6
+
+if test "X$ac_cv_use_belos" != "Xno"; then
+  echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_BELOS
+_ACEOF
+
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+
+
+if test "X$ac_cv_use_belos" != "Xno"; then
+  BUILD_BELOS_TRUE=
+  BUILD_BELOS_FALSE='#'
+else
+  BUILD_BELOS_TRUE='#'
+  BUILD_BELOS_FALSE=
+fi
+
+
+# Check whether --enable-ifpack or --disable-ifpack was given.
+if test "${enable_ifpack+set}" = set; then
+  enableval="$enable_ifpack"
+  ac_cv_use_ifpack=$enableval
+else
+  ac_cv_use_ifpack=no
+fi;
+
+echo "$as_me:$LINENO: checking whether to use ifpack" >&5
+echo $ECHO_N "checking whether to use ifpack... $ECHO_C" >&6
+
+if test "X$ac_cv_use_ifpack" != "Xno"; then
+  echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_IFPACK
+_ACEOF
+
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+
+
+if test "X$ac_cv_use_ifpack" != "Xno"; then
+  BUILD_IFPACK_TRUE=
+  BUILD_IFPACK_FALSE='#'
+else
+  BUILD_IFPACK_TRUE='#'
+  BUILD_IFPACK_FALSE=
 fi
 
 
@@ -5753,7 +5863,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_verb"
-(eval echo $as_me:5756: \"$ac_link\") >&5
+(eval echo $as_me:5866: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
@@ -5833,7 +5943,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_cv_prog_f77_v"
-(eval echo $as_me:5836: \"$ac_link\") >&5
+(eval echo $as_me:5946: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
@@ -8227,7 +8337,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_verb"
-(eval echo $as_me:8230: \"$ac_link\") >&5
+(eval echo $as_me:8340: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
@@ -8307,7 +8417,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_cv_prog_f77_v"
-(eval echo $as_me:8310: \"$ac_link\") >&5
+(eval echo $as_me:8420: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
@@ -8655,10 +8765,31 @@ echo "$as_me: error: conditional \"USE_ALTERNATE_AR\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
+if test -z "${BUILD_ANASAZI_EXAMPLES_TRUE}" && test -z "${BUILD_ANASAZI_EXAMPLES_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"BUILD_ANASAZI_EXAMPLES\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"BUILD_ANASAZI_EXAMPLES\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
 if test -z "${BUILD_EXAMPLES_TRUE}" && test -z "${BUILD_EXAMPLES_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"BUILD_EXAMPLES\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"BUILD_EXAMPLES\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${BUILD_BELOS_TRUE}" && test -z "${BUILD_BELOS_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"BUILD_BELOS\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"BUILD_BELOS\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${BUILD_IFPACK_TRUE}" && test -z "${BUILD_IFPACK_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"BUILD_IFPACK\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"BUILD_IFPACK\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -9262,8 +9393,14 @@ s,@USE_ALTERNATE_AR_FALSE@,$USE_ALTERNATE_AR_FALSE,;t t
 s,@ALTERNATE_AR@,$ALTERNATE_AR,;t t
 s,@CXXCPP@,$CXXCPP,;t t
 s,@EGREP@,$EGREP,;t t
+s,@BUILD_ANASAZI_EXAMPLES_TRUE@,$BUILD_ANASAZI_EXAMPLES_TRUE,;t t
+s,@BUILD_ANASAZI_EXAMPLES_FALSE@,$BUILD_ANASAZI_EXAMPLES_FALSE,;t t
 s,@BUILD_EXAMPLES_TRUE@,$BUILD_EXAMPLES_TRUE,;t t
 s,@BUILD_EXAMPLES_FALSE@,$BUILD_EXAMPLES_FALSE,;t t
+s,@BUILD_BELOS_TRUE@,$BUILD_BELOS_TRUE,;t t
+s,@BUILD_BELOS_FALSE@,$BUILD_BELOS_FALSE,;t t
+s,@BUILD_IFPACK_TRUE@,$BUILD_IFPACK_TRUE,;t t
+s,@BUILD_IFPACK_FALSE@,$BUILD_IFPACK_FALSE,;t t
 s,@FLIBS@,$FLIBS,;t t
 s,@BLAS_LIBS@,$BLAS_LIBS,;t t
 s,@LAPACK_LIBS@,$LAPACK_LIBS,;t t
