----------------------------------------------------------------------
 Committing in .

 Modified Files:
 	Makefile.am Makefile.in aclocal.m4 configure configure.ac
 	src/Belos_config.h.in src/Makefile.in test/Makefile.am
 	test/Makefile.in test/BlockCG/Makefile.am
 	test/BlockCG/Makefile.in test/BlockGmres/Makefile.am
 	test/BlockGmres/Makefile.in
 Added Files:
 	config/tac_arg_enable_feature_sub.m4
 ----------------------------------------------------------------------

 Added new --enable/disable-belos-tests option to allow user to turn off the
 belos tests.  This option defaults to yes, i.e. builds the tests.  The new
 m4 file was added to parse this option from the configure line.  Furthermore,
 the configure line is not parsed to check for additional packages that were
 enabled (like ifpack).  This allows the makefile to safely build the tests
 that depend on those packages.

diff --git a/packages/belos/configure b/packages/belos/configure
--- a/packages/belos/configure
+++ b/packages/belos/configure
@@ -310,7 +310,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM AWK SET_MAKE CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE CXX CXXFLAGS ac_ct_CXX CXXDEPMODE F77 FFLAGS ac_ct_F77 RANLIB ac_ct_RANLIB MPI_CXX HAVE_MPI_TRUE HAVE_MPI_FALSE MPI_CXX_EXISTS MPI_CC_EXISTS MPI_F77_EXISTS USE_ALTERNATE_AR_TRUE USE_ALTERNATE_AR_FALSE ALTERNATE_AR CXXCPP EGREP BUILD_TESTS_TRUE BUILD_TESTS_FALSE FLIBS BLAS_LIBS LAPACK_LIBS ac_aux_dir LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM AWK SET_MAKE CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE CXX CXXFLAGS ac_ct_CXX CXXDEPMODE F77 FFLAGS ac_ct_F77 RANLIB ac_ct_RANLIB MPI_CXX HAVE_MPI_TRUE HAVE_MPI_FALSE MPI_CXX_EXISTS MPI_CC_EXISTS MPI_F77_EXISTS USE_ALTERNATE_AR_TRUE USE_ALTERNATE_AR_FALSE ALTERNATE_AR CXXCPP EGREP BUILD_BELOS_TESTS_TRUE BUILD_BELOS_TESTS_FALSE BUILD_TESTS_TRUE BUILD_TESTS_FALSE BUILD_IFPACK_TRUE BUILD_IFPACK_FALSE FLIBS BLAS_LIBS LAPACK_LIBS ac_aux_dir LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -874,9 +874,10 @@ Optional Features:
   --disable-dependency-tracking Speeds up one-time builds
   --enable-dependency-tracking  Do not reject slow dependency extractors
   --enable-mpi            MPI support
-  --enable-tests          Build tests for all Trilinos packages (not all
-                          packages are sensitive to this option) (default is
+  --enable-belos-tests    Build belos tests (default is yes)
+  --enable-tests          Build tests for all Trilinos packages (default is
                           yes)
+  --enable-ifpack         Build examples which use ifpack (default is no)
 
 Optional Packages:
   --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
@@ -3150,7 +3151,7 @@ fi
 
 
 # Provide some information about the compiler.
-echo "$as_me:3153:" \
+echo "$as_me:3154:" \
      "checking for Fortran 77 compiler version" >&5
 ac_compiler=`set X $ac_compile; echo $2`
 { (eval echo "$as_me:$LINENO: \"$ac_compiler --version </dev/null >&5\"") >&5
@@ -5406,8 +5407,43 @@ fi
 # ------------------------------------------------------------------------
 
 # ------------------------------------------------------------------------
-# Checks if tests should be built
+# Checks if tests should be built and which ones should be built
 # ------------------------------------------------------------------------
+
+
+# Check whether --enable-belos-tests or --disable-belos-tests was given.
+if test "${enable_belos_tests+set}" = set; then
+  enableval="$enable_belos_tests"
+  ac_cv_use_belos_tests=$enableval
+else
+  ac_cv_use_belos_tests=yes
+fi;
+
+echo "$as_me:$LINENO: checking whether to use belos-tests" >&5
+echo $ECHO_N "checking whether to use belos-tests... $ECHO_C" >&6
+
+if test "X$ac_cv_use_belos_tests" != "Xno"; then
+  echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_BELOS_TESTS
+_ACEOF
+
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+
+
+if test "X$ac_cv_use_belos_tests" != "Xno"; then
+  BUILD_BELOS_TESTS_TRUE=
+  BUILD_BELOS_TESTS_FALSE='#'
+else
+  BUILD_BELOS_TESTS_TRUE='#'
+  BUILD_BELOS_TESTS_FALSE=
+fi
 
 
 # Check whether --enable-tests or --disable-tests was given.
@@ -5442,6 +5478,41 @@ if test "X$ac_cv_use_tests" != "Xno"; then
 else
   BUILD_TESTS_TRUE='#'
   BUILD_TESTS_FALSE=
+fi
+
+
+# Check whether --enable-ifpack or --disable-ifpack was given.
+if test "${enable_ifpack+set}" = set; then
+  enableval="$enable_ifpack"
+  ac_cv_use_ifpack=$enableval
+else
+  ac_cv_use_ifpack=no
+fi;
+
+echo "$as_me:$LINENO: checking whether to use ifpack" >&5
+echo $ECHO_N "checking whether to use ifpack... $ECHO_C" >&6
+
+if test "X$ac_cv_use_ifpack" != "Xno"; then
+  echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_IFPACK
+_ACEOF
+
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+
+
+if test "X$ac_cv_use_ifpack" != "Xno"; then
+  BUILD_IFPACK_TRUE=
+  BUILD_IFPACK_FALSE='#'
+else
+  BUILD_IFPACK_TRUE='#'
+  BUILD_IFPACK_FALSE=
 fi
 
 
@@ -5536,7 +5607,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_verb"
-(eval echo $as_me:5539: \"$ac_link\") >&5
+(eval echo $as_me:5610: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
@@ -5616,7 +5687,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_cv_prog_f77_v"
-(eval echo $as_me:5619: \"$ac_link\") >&5
+(eval echo $as_me:5690: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
@@ -8003,7 +8074,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_verb"
-(eval echo $as_me:8006: \"$ac_link\") >&5
+(eval echo $as_me:8077: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
@@ -8083,7 +8154,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_cv_prog_f77_v"
-(eval echo $as_me:8086: \"$ac_link\") >&5
+(eval echo $as_me:8157: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
@@ -8428,10 +8499,24 @@ echo "$as_me: error: conditional \"USE_ALTERNATE_AR\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
+if test -z "${BUILD_BELOS_TESTS_TRUE}" && test -z "${BUILD_BELOS_TESTS_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"BUILD_BELOS_TESTS\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"BUILD_BELOS_TESTS\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
 if test -z "${BUILD_TESTS_TRUE}" && test -z "${BUILD_TESTS_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"BUILD_TESTS\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"BUILD_TESTS\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${BUILD_IFPACK_TRUE}" && test -z "${BUILD_IFPACK_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"BUILD_IFPACK\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"BUILD_IFPACK\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -9036,8 +9121,12 @@ s,@USE_ALTERNATE_AR_FALSE@,$USE_ALTERNATE_AR_FALSE,;t t
 s,@ALTERNATE_AR@,$ALTERNATE_AR,;t t
 s,@CXXCPP@,$CXXCPP,;t t
 s,@EGREP@,$EGREP,;t t
+s,@BUILD_BELOS_TESTS_TRUE@,$BUILD_BELOS_TESTS_TRUE,;t t
+s,@BUILD_BELOS_TESTS_FALSE@,$BUILD_BELOS_TESTS_FALSE,;t t
 s,@BUILD_TESTS_TRUE@,$BUILD_TESTS_TRUE,;t t
 s,@BUILD_TESTS_FALSE@,$BUILD_TESTS_FALSE,;t t
+s,@BUILD_IFPACK_TRUE@,$BUILD_IFPACK_TRUE,;t t
+s,@BUILD_IFPACK_FALSE@,$BUILD_IFPACK_FALSE,;t t
 s,@FLIBS@,$FLIBS,;t t
 s,@BLAS_LIBS@,$BLAS_LIBS,;t t
 s,@LAPACK_LIBS@,$LAPACK_LIBS,;t t
