Merged my changes from 9.x branch back to Dev.
Teuchos:
* removed private destructor from ArrayView
* added fix for complex BLAS Apple vecLib bug
* minor fixes for unused parameter warnings

Anasazi:
* Development/documentation of IRTR eigensolvers
* Tpetra adaptors and tests

Belos:
* Tpetra adaptors and tests

Tpetra:
* All of the work from the past three months. Work will now continue in dev branch.

Everything compiles, all tests pass.

diff --git a/packages/belos/configure b/packages/belos/configure
--- a/packages/belos/configure
+++ b/packages/belos/configure
@@ -751,6 +751,8 @@ BUILD_ML_TRUE
 BUILD_ML_FALSE
 BUILD_EPETRAEXT_TRUE
 BUILD_EPETRAEXT_FALSE
+BUILD_TPETRA_TRUE
+BUILD_TPETRA_FALSE
 ac_aux_dir
 LIBOBJS
 LTLIBOBJS'
@@ -1389,6 +1391,9 @@ Optional Features:
   --enable-belos-epetraext
                           Build tests that use EpetraExt. Can be overridden
                           with --disable-belos-epetraext.
+  --enable-tpetra         Build tests that use Tpetra.
+  --enable-belos-tpetra   Build tests that use Tpetra. Can be overridden with
+                          --disable-belos-tpetra.
 
 Optional Packages:
   --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
@@ -7889,7 +7894,7 @@ fi
 # ------------------------------------------------------------------------
 # Trilinos Package Dependencies
 # Required: Epetra, Teuchos, Triutils
-# Optional: Ifpack, TSFCore, ML
+# Optional: Ifpack, TSFCore, ML, Tpetra
 # ------------------------------------------------------------------------
 
 
@@ -8126,6 +8131,58 @@ else
   BUILD_EPETRAEXT_TRUE='#'
   BUILD_EPETRAEXT_FALSE=
 fi
+
+
+
+
+
+
+# Check whether --enable-tpetra was given.
+if test "${enable_tpetra+set}" = set; then
+  enableval=$enable_tpetra; ac_cv_implicit_use_tpetra=$enableval
+else
+  ac_cv_implicit_use_tpetra=no
+fi
+
+
+if test "Xno" != "Xno"; then
+  ac_cv_belos_using_tpetra_default=$ac_cv_implicit_use_tpetra
+else
+  ac_cv_belos_using_tpetra_default=no
+fi
+
+# Check whether --enable-belos-tpetra was given.
+if test "${enable_belos_tpetra+set}" = set; then
+  enableval=$enable_belos_tpetra; ac_cv_use_tpetra=$enableval
+else
+  ac_cv_use_tpetra=$ac_cv_belos_using_tpetra_default
+fi
+
+
+{ echo "$as_me:$LINENO: checking whether to build optional tpetra dependent code in belos" >&5
+echo $ECHO_N "checking whether to build optional tpetra dependent code in belos... $ECHO_C" >&6; }
+
+if test "X$ac_cv_use_tpetra" != "Xno"; then
+  { echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6; }
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_BELOS_TPETRA 1
+_ACEOF
+
+else
+  { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+fi
+
+ if test "X$ac_cv_use_tpetra" = "Xyes"; then
+  BUILD_TPETRA_TRUE=
+  BUILD_TPETRA_FALSE='#'
+else
+  BUILD_TPETRA_TRUE='#'
+  BUILD_TPETRA_FALSE=
+fi
+
 
 
 
@@ -8423,7 +8480,7 @@ fi
 # ------------------------------------------------------------------------
 ##
 
-ac_config_files="$ac_config_files Makefile Makefile.export.belos src/Makefile example/Makefile example/BlockGmres/Makefile example/BlockCG/Makefile example/GCRODR/Makefile example/PCPG/Makefile test/Makefile test/BlockCG/Makefile test/BlockGmres/Makefile test/GCRODR/Makefile test/PCPG/Makefile test/MVOPTester/Makefile"
+ac_config_files="$ac_config_files Makefile Makefile.export.belos src/Makefile example/Makefile example/BlockGmres/Makefile example/BlockCG/Makefile example/GCRODR/Makefile example/PCPG/Makefile test/Makefile test/BlockCG/Makefile test/BlockGmres/Makefile test/GCRODR/Makefile test/PCPG/Makefile test/MVOPTester/Makefile tpetra/Makefile tpetra/src/Makefile tpetra/test/Makefile tpetra/test/MVOPTester/Makefile tpetra/test/BlockCG/Makefile"
 
 
 cat >confcache <<\_ACEOF
@@ -8652,6 +8709,13 @@ if test -z "${BUILD_EPETRAEXT_TRUE}" && test -z "${BUILD_EPETRAEXT_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"BUILD_EPETRAEXT\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"BUILD_EPETRAEXT\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${BUILD_TPETRA_TRUE}" && test -z "${BUILD_TPETRA_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"BUILD_TPETRA\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"BUILD_TPETRA\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -9138,6 +9202,11 @@ do
     "test/GCRODR/Makefile") CONFIG_FILES="$CONFIG_FILES test/GCRODR/Makefile" ;;
     "test/PCPG/Makefile") CONFIG_FILES="$CONFIG_FILES test/PCPG/Makefile" ;;
     "test/MVOPTester/Makefile") CONFIG_FILES="$CONFIG_FILES test/MVOPTester/Makefile" ;;
+    "tpetra/Makefile") CONFIG_FILES="$CONFIG_FILES tpetra/Makefile" ;;
+    "tpetra/src/Makefile") CONFIG_FILES="$CONFIG_FILES tpetra/src/Makefile" ;;
+    "tpetra/test/Makefile") CONFIG_FILES="$CONFIG_FILES tpetra/test/Makefile" ;;
+    "tpetra/test/MVOPTester/Makefile") CONFIG_FILES="$CONFIG_FILES tpetra/test/MVOPTester/Makefile" ;;
+    "tpetra/test/BlockCG/Makefile") CONFIG_FILES="$CONFIG_FILES tpetra/test/BlockCG/Makefile" ;;
 
   *) { { echo "$as_me:$LINENO: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
@@ -9377,12 +9446,14 @@ BUILD_ML_TRUE!$BUILD_ML_TRUE$ac_delim
 BUILD_ML_FALSE!$BUILD_ML_FALSE$ac_delim
 BUILD_EPETRAEXT_TRUE!$BUILD_EPETRAEXT_TRUE$ac_delim
 BUILD_EPETRAEXT_FALSE!$BUILD_EPETRAEXT_FALSE$ac_delim
+BUILD_TPETRA_TRUE!$BUILD_TPETRA_TRUE$ac_delim
+BUILD_TPETRA_FALSE!$BUILD_TPETRA_FALSE$ac_delim
 ac_aux_dir!$ac_aux_dir$ac_delim
 LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 42; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 44; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
