Fixing MATLAB build problems.

diff --git a/packages/ml/configure b/packages/ml/configure
--- a/packages/ml/configure
+++ b/packages/ml/configure
@@ -12870,7 +12870,7 @@ if test "${with_matlab_exec+set}" = set; then
                 then
                     # "yes" was specified, but we don't have a path
                     # for the executable.
-                    # So, let's searth the PATH Environment Variable.
+		    # Check PATH +  if needed
                     echo "$as_me:$LINENO: result: yes" >&5
 echo "${ECHO_T}yes" >&6
                     # Extract the first word of "mex", so it can be a program name with args.
@@ -12886,7 +12886,8 @@ else
   ;;
   *)
   as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
-for as_dir in $PATH
+as_dummy=":$PATH"
+for as_dir in $as_dummy
 do
   IFS=$as_save_IFS
   test -z "$as_dir" && as_dir=.
@@ -12938,6 +12939,7 @@ do
 done
 done
 
+  test -z "$ac_cv_path_MATLAB" && ac_cv_path_MATLAB=":$PATH"
   ;;
 esac
 fi
@@ -12951,10 +12953,16 @@ else
 echo "${ECHO_T}no" >&6
 fi
 
-                    if test -z "$MATLAB_EXE"
+                    if test -z "$MATLAB"
                     then
-                        { { echo "$as_me:$LINENO: error: no path to matlab found" >&5
-echo "$as_me: error: no path to matlab found" >&2;}
+                        { { echo "$as_me:$LINENO: error: no path to matlab binary found" >&5
+echo "$as_me: error: no path to matlab binary found" >&2;}
+   { (exit 1); exit 1; }; }
+                    fi
+                    if test -z "$MEX"
+                    then
+                        { { echo "$as_me:$LINENO: error: no path to mex binary found" >&5
+echo "$as_me: error: no path to mex binary found" >&2;}
    { (exit 1); exit 1; }; }
                     fi
                     az_matlab_use=true
@@ -13067,6 +13075,18 @@ else
 echo "${ECHO_T}no" >&6
 fi
 
+                    if test -z "$MATLAB"
+                    then
+                        { { echo "$as_me:$LINENO: error: no path to matlab binary found" >&5
+echo "$as_me: error: no path to matlab binary found" >&2;}
+   { (exit 1); exit 1; }; }
+                    fi
+                    if test -z "$MEX"
+                    then
+                        { { echo "$as_me:$LINENO: error: no path to mex binary found" >&5
+echo "$as_me: error: no path to mex binary found" >&2;}
+   { (exit 1); exit 1; }; }
+                    fi
                     az_matlab_use=true
 
 
@@ -13294,7 +13314,7 @@ fi;
 
 echo "$as_me:$LINENO: checking whether we should build the matlab wrappers" >&5
 echo $ECHO_N "checking whether we should build the matlab wrappers... $ECHO_C" >&6
-if test -n "$MATLAB_EXE"; then
+if test -n "$MATLAB_EXE" -a -n "$MATLAB_ROOT_USE" -a -n "MATLAB_USE"; then
   BUILD_MATLAB=yes
   echo "$as_me:$LINENO: result: yes" >&5
 echo "${ECHO_T}yes" >&6
@@ -13315,9 +13335,8 @@ fi
     echo "Setting MATLAB_INCLUDES to: $MATLAB_INCLUDES" #debug line
   else
     MATLAB_INCLUDES=
-
   fi
-    ML_MATLAB_INCLUDES=$MATLAB_INCLUDES
+  ML_MATLAB_INCLUDES=$MATLAB_INCLUDES
 
 
   # Cache the old CPPFLAGS, add $MATLAB_INCLUDE
@@ -13472,7 +13491,7 @@ echo "${ECHO_T}no" >&6
 	 echo "-----"
      	 echo "Cannot find Matlab libeng header file engine.h."
 	 echo "Use --with-matlab-root=<DIR> to add the matlab root directory"
-         echo "(such that <DIR>/extern/include constains engine.h)"
+         echo "(such that <DIR>/extern/include contains engine.h)"
      	 echo "-----"
      	 { { echo "$as_me:$LINENO: error: Matlab header file engine.h not found" >&5
 echo "$as_me: error: Matlab header file engine.h not found" >&2;}
@@ -13629,7 +13648,7 @@ echo "${ECHO_T}no" >&6
 	 echo "-----"
      	 echo "Cannot find Matlab libmx header file mex.h."
 	 echo "Use --with-matlab-root=<DIR> to add the matlab root directory "
-         echo "(such that <DIR>/extern/include constains mex.h)"
+         echo "(such that <DIR>/extern/include contains mex.h)"
      	 echo "-----"
      	 { { echo "$as_me:$LINENO: error: Matlab header file mex.h not found" >&5
 echo "$as_me: error: Matlab header file mex.h not found" >&2;}
@@ -13640,11 +13659,9 @@ fi
 
   # Restore CPPFLAGS
   CPPFLAGS=$save_CPPFLAGS
-
-  # Since there's no reliable way to figure out the location of the mex libraries, let's just not check form them.
-  # If you've managed to get maltab and mex installed and specified the matlab root so we can find mexext and the
+  # Since there's no reliable way to figure out the location of the mex libraries, let's just not check for them.
+  # If you've managed to get matlab and mex installed and specified the matlab root so we can find mexext and the
   # mex headers, I'm going to presume that mex can link ok.
-
 else
   echo "$as_me:$LINENO: result: no" >&5
 echo "${ECHO_T}no" >&6
@@ -13801,7 +13818,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_verb"
-(eval echo $as_me:13804: \"$ac_link\") >&5
+(eval echo $as_me:13821: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
@@ -13879,7 +13896,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_cv_prog_f77_v"
-(eval echo $as_me:13882: \"$ac_link\") >&5
+(eval echo $as_me:13899: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
