SUMMARY:   Fixing compile error in Alegra TPL
     BUGS:      4038

     CHECKLIST:

     1)   Did you add any source files?  no

     2)   Did you update or change the build system?  yes
     2.a) Did you remember to do a bootstrap and do a 'cvs add' on the
          Makefile.am files and the Makefile.in files?  yes & n/a
     2.b) [Optional but recommended] Did you blow away the libraries and
          executables and then rebuild?  yes

     3) Did you rerun the test suite on at least the packages that you
        changed?  yes

     COMMENTS:

Rich Drake reported problems in 9.0 builds on all platforms.  It turns out that
F77_BLAS_MANGLE wasn't defined if the configure option --disable-libcheck is
used.  (--enable-libcheck is the default.)  And of course this is an option
that Alegra uses.

My patch is based on what is done in AztecOO.  My Alegra Trilinos TPL compile,
which was failing before, now passes with this patch.  Also, all tests pass.

(checklist version 2007-06-20)

diff --git a/packages/ml/configure b/packages/ml/configure
--- a/packages/ml/configure
+++ b/packages/ml/configure
@@ -4016,7 +4016,7 @@ else
 fi
 
 
-if test "X$ac_cv_use_epetra" == "Xno" && test "X$ac_cv_use_ml_multiple_rhs"; then
+if test "X$ac_cv_use_epetra" == "Xno" && test "X$ac_cv_use_ml_multiple_rhs" != "Xno"; then
  { { echo "$as_me:$LINENO: error: The use of --enable-ml_multiple_rhs in ML requires Epetra." >&5
 echo "$as_me: error: The use of --enable-ml_multiple_rhs in ML requires Epetra." >&2;}
    { (exit 1); exit 1; }; }
@@ -10438,12 +10438,12 @@ ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
 # for these libraries.
 if test "X$ac_cv_use_ml_tests" != "Xno" || test "X$ac_cv_use_ml_examples" != "Xno" || test "X$ac_cv_use_libcheck" != "Xno"; then
 
-# #np# -
-# To add any libraries that you want to check for, replace pow below
-# with the name of an entry point in that library.
-# checks for libraries now
-#  #np# These lines can be removed if the math lib is not needed.
-{ echo "$as_me:$LINENO: checking for library containing pow" >&5
+  # #np# -
+  # To add any libraries that you want to check for, replace pow below
+  # with the name of an entry point in that library.
+  # checks for libraries now
+    #  #np# These lines can be removed if the math lib is not needed.
+  { echo "$as_me:$LINENO: checking for library containing pow" >&5
 echo $ECHO_N "checking for library containing pow... $ECHO_C" >&6; }
 if test "${ac_cv_search_pow+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -10538,7 +10538,7 @@ echo "$as_me: error: Cannot find math library" >&2;}
    { (exit 1); exit 1; }; }
 fi
 
-{ echo "$as_me:$LINENO: checking for library containing sqrt" >&5
+  { echo "$as_me:$LINENO: checking for library containing sqrt" >&5
 echo $ECHO_N "checking for library containing sqrt... $ECHO_C" >&6; }
 if test "${ac_cv_search_sqrt+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -10634,7 +10634,7 @@ echo "$as_me: error: Cannot find math library" >&2;}
 fi
 
 
-# find or choose to supply valid blas and lapack libraries
+  # find or choose to supply valid blas and lapack libraries
 
 
 
@@ -16912,6 +16912,66 @@ echo "$as_me: error: Cannot find lapack library, specify a path using --with-ldf
    { (exit 1); exit 1; }; }
 fi
 
+
+else
+
+  # If we don't check for BLAS above, we will use F77_FUNC as the name mangling
+  # for the BLAS and LAPACK.  This is what we used before we allowed the BLAS
+  # and LAPACK to use different name mangling than the compiler.
+  ac_ext=f
+ac_compile='$F77 -c $FFLAGS conftest.$ac_ext >&5'
+ac_link='$F77 -o conftest$ac_exeext $FFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_f77_compiler_gnu
+case $ac_cv_f77_mangling in
+  upper*) ac_val="DGEMM" ;;
+  lower*) ac_val="dgemm" ;;
+  *)      ac_val="unknown" ;;
+esac
+case $ac_cv_f77_mangling in *," underscore"*) ac_val="$ac_val"_ ;; esac
+
+dgemm="$ac_val"
+
+ac_ext=cpp
+ac_cpp='$CXXCPP $CPPFLAGS'
+ac_compile='$CXX -c $CXXFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CXX -o conftest$ac_exeext $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
+
+  if test "X$dgemm" = "Xdgemm_"; then
+
+cat >>confdefs.h <<\_ACEOF
+#define F77_BLAS_MANGLE(name,NAME) name ## _
+_ACEOF
+
+  else
+    if test "X$dgemm" = "Xdgemm"; then
+
+cat >>confdefs.h <<\_ACEOF
+#define F77_BLAS_MANGLE(name,NAME) name
+_ACEOF
+
+    else
+      if test "X$dgemm" = "XDGEMM"; then
+
+cat >>confdefs.h <<\_ACEOF
+#define F77_BLAS_MANGLE(name,NAME) NAME
+_ACEOF
+
+      else
+        if test "X$dgemm" = "XDGEMM_"; then
+
+cat >>confdefs.h <<\_ACEOF
+#define F77_BLAS_MANGLE(name,NAME) NAME ## _
+_ACEOF
+
+        else
+          { { echo "$as_me:$LINENO: error: Cannot determine BLAS and LAPACK name mangling using the value of F77_FUNC.  Please try configuring Trilinos without the --disable-libcheck option." >&5
+echo "$as_me: error: Cannot determine BLAS and LAPACK name mangling using the value of F77_FUNC.  Please try configuring Trilinos without the --disable-libcheck option." >&2;}
+   { (exit 1); exit 1; }; }
+        fi
+      fi
+    fi
+  fi
 
 fi
 # end of the list of libraries that don't need to be checked for if
