SUMMARY:   Merging in changes from dev
     BUGS:      4125

     CHECKLIST:

     1)   Did you add any source files?  no

     2)   Did you update or change the build system?  yes
     2.a) Did you remember to do a bootstrap and do a 'cvs add' on the
          Makefile.am files and the Makefile.in files?  yes & n/a
     2.b) [Optional but recommended] Did you blow away the libraries and
          executables and then rebuild?  yes

     3) Did you rerun the test suite on at least the packages that you
        changed?  yes

     COMMENTS:

     Merging in changes from trunk.  Slight change to PETSc option name, adding
     check that epetraext is enabled if petsc option is enabled, now validating
     "used" parameters.

     Compiles fine and all ML tests pass w/ and w/o --with-petsc option.

(checklist version 2007-06-20)

diff --git a/packages/ml/configure b/packages/ml/configure
--- a/packages/ml/configure
+++ b/packages/ml/configure
@@ -8934,7 +8934,6 @@ else
 echo "${ECHO_T}no" >&6; }
 fi
 
-#
 
 #
 # ------------------------------------------------------------------------
@@ -9260,6 +9259,15 @@ fi
 
 
 
+#
+# if user wants PETSc, EpetraExt must be enabled.
+if test "X$ac_cv_use_epetraext" != "Xyes"; then
+   if test "X$ac_cv_use_petsc" = "Xyes"; then
+     { { echo "$as_me:$LINENO: error: --with-petsc requires --enable-epetraext." >&5
+echo "$as_me: error: --with-petsc requires --enable-epetraext." >&2;}
+   { (exit 1); exit 1; }; }
+   fi
+fi
 #
 
 
