Making same changes to --with-ml_zoltan option as in release branch.

diff --git a/packages/ml/configure b/packages/ml/configure
--- a/packages/ml/configure
+++ b/packages/ml/configure
@@ -1031,8 +1031,9 @@ Optional Packages:
                           --with-ml_metis. (default is no)
   --with-ml_parasails     Enable Parasails support. See notes for
                           --with-ml_metis. (default is no)
-  --with-ml_zoltan        Enable Zoltan support. See notes for
-                          --with-ml_metis. (default is no)
+  --with-ml_zoltan        Enable Zoltan support. This option requires that MPI
+                          be enabled. See notes for --with-ml_metis. (default
+                          is no)
   --with-libdirs          OBSOLETE use --with-ldflags instead. (ex.
                           --with-ldflags="-L<DIR> -L<DIR2>")
   --with-incdirs          additional directories containing include files:
@@ -3932,7 +3933,7 @@ fi
 
 
 # Provide some information about the compiler.
-echo "$as_me:3935:" \
+echo "$as_me:3936:" \
      "checking for Fortran 77 compiler version" >&5
 ac_compiler=`set X $ac_compile; echo $2`
 { (eval echo "$as_me:$LINENO: \"$ac_compiler --version </dev/null >&5\"") >&5
@@ -7864,6 +7865,17 @@ else
 echo "${ECHO_T}no" >&6
 fi
 
+#this works
+if test "X${HAVE_PKG_MPI}" != "Xyes"; then
+#if test "X${HAVE_MPI}" != "Xyes"; then
+   #issue an error message and abort if the user has configured with
+   #the zoltan interface enabled but without mpi enabled
+   if test "X$ac_cv_use_ml_zoltan" = "Xyes"; then
+     { { echo "$as_me:$LINENO: error: Zoltan support in ML requires enabling MPI." >&5
+echo "$as_me: error: Zoltan support in ML requires enabling MPI." >&2;}
+   { (exit 1); exit 1; }; }
+   fi
+fi
 #
 # ------------------------------------------------------------------------
 # Interfaces to other Trilinos packages
@@ -8425,7 +8437,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_verb"
-(eval echo $as_me:8428: \"$ac_link\") >&5
+(eval echo $as_me:8440: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
@@ -8503,7 +8515,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_cv_prog_f77_v"
-(eval echo $as_me:8506: \"$ac_link\") >&5
+(eval echo $as_me:8518: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
@@ -11456,7 +11468,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_verb"
-(eval echo $as_me:11459: \"$ac_link\") >&5
+(eval echo $as_me:11471: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
@@ -11534,7 +11546,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_cv_prog_f77_v"
-(eval echo $as_me:11537: \"$ac_link\") >&5
+(eval echo $as_me:11549: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
