Changed configure so that only one of --enable-ml_amesos and --enable-ml_superlu* can be specified.  This avoids namespace collisions between Amesos and ML's old SuperLU interfaces.

diff --git a/packages/ml/configure b/packages/ml/configure
--- a/packages/ml/configure
+++ b/packages/ml/configure
@@ -916,10 +916,10 @@ Optional Features:
   --enable-ml-epetra      Enable Epetra support.
   --enable-amesos         Enable AMESOS support. Amesos, a Trilinos package,
                           can be used to interface ML with various direct
-                          solvers, such as SuperLU, MUMPS, UMFPACK, KLU, and
-                          other. Amesos requires --enable-epetra. See notes
-                          for --enable-ml_metis. Can be overridden with
-                          --disable-ml-amesos.
+                          solvers, such as SuperLU, SuperLUdist, MUMPS,
+                          UMFPACK, KLU, and other. Amesos requires
+                          --enable-epetra. See notes for --enable-ml_metis.
+                          Can be overridden with --disable-ml-amesos.
   --enable-ml-amesos      Enable AMESOS support. Amesos, a Trilinos package,
                           can be used to interface ML with various direct
                           solvers, such as SuperLU, MUMPS, UMFPACK, KLU, and
@@ -1042,7 +1042,9 @@ Optional Packages:
                           --with-ml-64bit-integer="long long" for LINUX,
                           TFLOP, IRIXN32"; --with-ml-64bit-integer="long" for
                           IRIX64, ALPHA (Cplant)
-  --with-ml_superlu       Enable serial SuperLU (version 1.0) support. Note 1:
+  --with-ml_superlu       (Deprecated in favor of --enable-ml-amesos. Cannot
+                          be used at the same time as --enable-ml-amesos.)
+                          Enable serial SuperLU (version 1.0) support. Note 1:
                           SuperLU is a third party library. As such, configure
                           assumes that it has already been built. Note 2: You
                           must also specify the location and name of the
@@ -1051,7 +1053,9 @@ Optional Packages:
                           --with-ldflags="-L<SuperLU-library-path>"
                           --with-incdirs="<SuperLU-include-path>". (default is
                           no)
-  --with-ml_superlu2      Enable serial SuperLU (version 2.0) support. Note 1:
+  --with-ml_superlu2      (Deprecated in favor of --enable-ml-amesos. Cannot
+                          be used at the same time as --enable-ml-amesos.)
+                          Enable serial SuperLU (version 2.0) support. Note 1:
                           SuperLU is a third party library. As such, configure
                           assumes that it has already been built. Note 2: You
                           must also specify the location and name of the
@@ -1060,7 +1064,9 @@ Optional Packages:
                           --with-ldflags="-L<SuperLU-library-path>"
                           --with-incdirs="<SuperLU-include-path>". (default is
                           no)
-  --with-ml_superlu_dist  Enable SuperLU_DIST support. Note 1: SuperLU_DIST is
+  --with-ml_superlu_dist  (Deprecated in favor of --enable-ml-amesos. Cannot
+                          be used at the same time as --enable-ml-amesos.)
+                          Enable SuperLU_DIST support. Note 1: SuperLU_DIST is
                           a third party library. As such, configure assumes
                           that it has already been built. Note 2: You must
                           also specify the location and name of the
@@ -4003,7 +4009,7 @@ fi
 
 
 # Provide some information about the compiler.
-echo "$as_me:4006:" \
+echo "$as_me:4012:" \
      "checking for Fortran 77 compiler version" >&5
 ac_compiler=`set X $ac_compile; echo $2`
 { (eval echo "$as_me:$LINENO: \"$ac_compiler --version </dev/null >&5\"") >&5
@@ -8306,6 +8312,17 @@ fi
 
 
 #
+if test "X${ac_cv_use_amesos}" = "Xyes"; then
+   #Issue an error message and abort if the user has configured with
+   #both the Amesos interface and ML's internal SuperLU interface enabled.
+   #Amesos wants SuperLU version 3.0, whereas ML uses SuperLU versions 1.0/2.0.
+   if test "X$ac_cv_use_ml_superlu" = "Xyes" || test "X${ac_cv_use_ml_superlu2}" = "Xyes" || test "X${ac_cv_use_ml_superlu_dist}" = "Xyes"; then
+     { { echo "$as_me:$LINENO: error: You cannot use Amesos and ML's internal interface to SuperLU/SuperLU-dist at the same time." >&5
+echo "$as_me: error: You cannot use Amesos and ML's internal interface to SuperLU/SuperLU-dist at the same time." >&2;}
+   { (exit 1); exit 1; }; }
+   fi
+fi
+#
 
 
 # Check whether --enable-ifpack or --disable-ifpack was given.
@@ -9819,7 +9836,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_verb"
-(eval echo $as_me:9822: \"$ac_link\") >&5
+(eval echo $as_me:9839: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
@@ -9897,7 +9914,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_cv_prog_f77_v"
-(eval echo $as_me:9900: \"$ac_link\") >&5
+(eval echo $as_me:9917: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
@@ -12850,7 +12867,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_verb"
-(eval echo $as_me:12853: \"$ac_link\") >&5
+(eval echo $as_me:12870: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
@@ -12928,7 +12945,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_cv_prog_f77_v"
-(eval echo $as_me:12931: \"$ac_link\") >&5
+(eval echo $as_me:12948: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
