Changing the way we build Trilinos so that "make" simply builds the libraries. Tests and examples will be built with "make tests" and "make examples", respectively.  I will send a note with more details to the developer list after I am done making these changes.

diff --git a/packages/ml/configure b/packages/ml/configure
--- a/packages/ml/configure
+++ b/packages/ml/configure
@@ -764,6 +764,10 @@ ML_BUILD_EXAMPLES_TRUE
 ML_BUILD_EXAMPLES_FALSE
 BUILD_TESTS_TRUE
 BUILD_TESTS_FALSE
+SUB_TEST_TRUE
+SUB_TEST_FALSE
+SUB_EXAMPLE_TRUE
+SUB_EXAMPLE_FALSE
 FLIBS
 BLAS_LIBS
 LAPACK_LIBS
@@ -1473,19 +1477,18 @@ Optional Features:
   --enable-ml-galeri      Enable Galeri support. Galeri, a Trilinos package,
                           is used in some ML examples to construct the linear
                           system and can optionally be used by the MLAPI.
-  --enable-examples       Build examples for all Trilinos packages (not all
-                          packages are sensitive to this option) (default is
-                          yes)
-  --enable-ml_examples    Build ML examples (deprecated, use
-                          --enable-ml-examples)
-  --enable-ml-examples    Build ML examples (default is yes if
-                          --disable-examples is not specified)
-  --enable-tests          Build tests for all Trilinos packages (not all
-                          packages are sensitive to this option) (default is
-                          yes)
+  --enable-examples       Make examples for all Trilinos packages buildable
+                          with 'make examples' (default is yes)
+  --enable-ml_examples    Make ML examples buildable with 'make examples'
+                          (deprecated, use --enable-ml-examples)
+  --enable-ml-examples    Make ML examples buildable with 'make examples'
+                          (default is yes if --disable-examples is not
+                          specified)
+  --enable-tests          Make tests for all Trilinos packages buildable with
+                          'make tests' (default is yes)
 
-  --enable-ml-tests       Build ML tests (default is yes if --disable-tests is
-                          not specified)
+  --enable-ml-tests       Make ML tests buildable with 'make tests' (default
+                          is yes if --disable-tests is not specified)
   --enable-libcheck       Check for some third-party libraries including BLAS
                           and LAPACK. (Cannot be disabled unless tests and
                           examples are also disabled.) (default is yes)
@@ -9403,6 +9406,28 @@ else
 fi
 
 
+#We now build tests and examples through separate make targets, rather than
+#during "make".  We still need to conditionally include the test and example
+#in SUBDIRS, even though SUB_TEST and SUB_EXAMPLE will never be
+#defined, so that the tests and examples are included in the distribution
+#tarball.
+ if test "X$ac_cv_use_sub_test" = "Xyes"; then
+  SUB_TEST_TRUE=
+  SUB_TEST_FALSE='#'
+else
+  SUB_TEST_TRUE='#'
+  SUB_TEST_FALSE=
+fi
+
+ if test "X$ac_cv_use_sub_example" = "Xyes"; then
+  SUB_EXAMPLE_TRUE=
+  SUB_EXAMPLE_FALSE='#'
+else
+  SUB_EXAMPLE_TRUE='#'
+  SUB_EXAMPLE_FALSE=
+fi
+
+
 
 # Check whether --enable-libcheck was given.
 if test "${enable_libcheck+set}" = set; then
@@ -13884,6 +13909,20 @@ echo "$as_me: error: conditional \"BUILD_TESTS\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
+if test -z "${SUB_TEST_TRUE}" && test -z "${SUB_TEST_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"SUB_TEST\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"SUB_TEST\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${SUB_EXAMPLE_TRUE}" && test -z "${SUB_EXAMPLE_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"SUB_EXAMPLE\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"SUB_EXAMPLE\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
 if test -z "${BUILD_ML_MATLAB_TRUE}" && test -z "${BUILD_ML_MATLAB_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"BUILD_ML_MATLAB\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
@@ -14738,6 +14777,10 @@ ML_BUILD_EXAMPLES_TRUE!$ML_BUILD_EXAMPLES_TRUE$ac_delim
 ML_BUILD_EXAMPLES_FALSE!$ML_BUILD_EXAMPLES_FALSE$ac_delim
 BUILD_TESTS_TRUE!$BUILD_TESTS_TRUE$ac_delim
 BUILD_TESTS_FALSE!$BUILD_TESTS_FALSE$ac_delim
+SUB_TEST_TRUE!$SUB_TEST_TRUE$ac_delim
+SUB_TEST_FALSE!$SUB_TEST_FALSE$ac_delim
+SUB_EXAMPLE_TRUE!$SUB_EXAMPLE_TRUE$ac_delim
+SUB_EXAMPLE_FALSE!$SUB_EXAMPLE_FALSE$ac_delim
 FLIBS!$FLIBS$ac_delim
 BLAS_LIBS!$BLAS_LIBS$ac_delim
 LAPACK_LIBS!$LAPACK_LIBS$ac_delim
@@ -14761,7 +14804,7 @@ ac_aux_dir!$ac_aux_dir$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 73; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 77; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
diff --git a/packages/nox/configure b/packages/nox/configure
--- a/packages/nox/configure
+++ b/packages/nox/configure
@@ -756,6 +756,10 @@ BUILD_LIBLOCALAPACK_TRUE
 BUILD_LIBLOCALAPACK_FALSE
 BUILD_LIBLOCAEPETRA_TRUE
 BUILD_LIBLOCAEPETRA_FALSE
+SUB_TEST_TRUE
+SUB_TEST_FALSE
+SUB_EXAMPLE_TRUE
+SUB_EXAMPLE_FALSE
 BUILD_NOX_TESTS_TRUE
 BUILD_NOX_TESTS_FALSE
 BUILD_LOCA_TESTS_TRUE
@@ -786,6 +790,8 @@ BUILD_THYRA_TESTS_FALSE
 ADDON_thyra_TESTS
 BUILD_TESTUTILS_TRUE
 BUILD_TESTUTILS_FALSE
+BUILD_NOX_EXAMPLES_TRUE
+BUILD_NOX_EXAMPLES_FALSE
 BUILD_LAPACK_EXAMPLES_TRUE
 BUILD_LAPACK_EXAMPLES_FALSE
 BUILD_LOCA_LAPACK_EXAMPLES_TRUE
@@ -1458,17 +1464,18 @@ Optional Features:
   --enable-nox-petsc      compile nox-petsc interface libraries
   --enable-nox-belos      compile nox-belos interface libraries
   --enable-nox-thyra      compile nox-thyra interface libraries
-  --enable-nox-tests      compile regression tests, over-rides the trilinos
-                          flag "--enable-tests" so that nox tests can be built
-                          separately from other trilinos package tests
-  --enable-tests          compile regression tests, will be ignored if
-                          "--enable-nox-tests" is specified
-  --enable-nox-examples   compile examples, over-rides the trilinos flag
-                          "--enable-examples" so that nox examples can be
-                          built separately from other trilinos package
-                          examples
-  --enable-examples       compile examples, will be ignored if
-                          "--enable-nox-examples" is specified
+  --enable-nox-tests      compile regression tests with "make tests",
+                          over-rides the trilinos flag "--enable-tests" so
+                          that nox tests can be built separately from other
+                          trilinos package tests
+  --enable-tests          compile regression tests with "make tests", will be
+                          ignored if "--enable-nox-tests" is specified
+  --enable-nox-examples   compile examples with "make examples", over-rides
+                          the trilinos flag "--enable-examples" so that nox
+                          examples can be built separately from other trilinos
+                          package examples
+  --enable-examples       compile examples with "make examples", will be
+                          ignored if "--enable-nox-examples" is specified
   --enable-anasazi        Implicitly build anasazi support into the loca
                           library. Can be overridden with
                           --<en|dis>able-loca-anasazi.
@@ -8885,6 +8892,28 @@ REQUIRE_LIB_CHECK=no
 # Checks for Regression Testing
 # ------------------------------------------------------------------------
 
+#We now build tests and examples through separate make targets, rather than
+#during "make".  We still need to conditionally include the test and example
+#in SUBDIRS, even though SUB_TEST and SUB_EXAMPLE will never be
+#defined, so that the tests and examples are included in the distribution
+#tarball.
+ if test "X$ac_cv_use_sub_test" = "Xyes"; then
+  SUB_TEST_TRUE=
+  SUB_TEST_FALSE='#'
+else
+  SUB_TEST_TRUE='#'
+  SUB_TEST_FALSE=
+fi
+
+ if test "X$ac_cv_use_sub_example" = "Xyes"; then
+  SUB_EXAMPLE_TRUE=
+  SUB_EXAMPLE_FALSE='#'
+else
+  SUB_EXAMPLE_TRUE='#'
+  SUB_EXAMPLE_FALSE=
+fi
+
+
 
 
   # See if testing is enabled
@@ -9232,6 +9261,14 @@ fi
 
   { echo "$as_me:$LINENO: result: ${ADDON_EXAMPLES}" >&5
 echo "${ECHO_T}${ADDON_EXAMPLES}" >&6; }
+
+   if test X${ADDON_EXAMPLES} = Xyes; then
+  BUILD_NOX_EXAMPLES_TRUE=
+  BUILD_NOX_EXAMPLES_FALSE='#'
+else
+  BUILD_NOX_EXAMPLES_TRUE='#'
+  BUILD_NOX_EXAMPLES_FALSE=
+fi
 
   # lapack
 
@@ -16773,6 +16810,20 @@ echo "$as_me: error: conditional \"BUILD_LIBLOCAEPETRA\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
+if test -z "${SUB_TEST_TRUE}" && test -z "${SUB_TEST_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"SUB_TEST\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"SUB_TEST\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${SUB_EXAMPLE_TRUE}" && test -z "${SUB_EXAMPLE_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"SUB_EXAMPLE\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"SUB_EXAMPLE\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
 if test -z "${BUILD_NOX_TESTS_TRUE}" && test -z "${BUILD_NOX_TESTS_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"BUILD_NOX_TESTS\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
@@ -16847,6 +16898,13 @@ if test -z "${BUILD_TESTUTILS_TRUE}" && test -z "${BUILD_TESTUTILS_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"BUILD_TESTUTILS\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"BUILD_TESTUTILS\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${BUILD_NOX_EXAMPLES_TRUE}" && test -z "${BUILD_NOX_EXAMPLES_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"BUILD_NOX_EXAMPLES\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"BUILD_NOX_EXAMPLES\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -17722,6 +17780,10 @@ BUILD_LIBLOCALAPACK_TRUE!$BUILD_LIBLOCALAPACK_TRUE$ac_delim
 BUILD_LIBLOCALAPACK_FALSE!$BUILD_LIBLOCALAPACK_FALSE$ac_delim
 BUILD_LIBLOCAEPETRA_TRUE!$BUILD_LIBLOCAEPETRA_TRUE$ac_delim
 BUILD_LIBLOCAEPETRA_FALSE!$BUILD_LIBLOCAEPETRA_FALSE$ac_delim
+SUB_TEST_TRUE!$SUB_TEST_TRUE$ac_delim
+SUB_TEST_FALSE!$SUB_TEST_FALSE$ac_delim
+SUB_EXAMPLE_TRUE!$SUB_EXAMPLE_TRUE$ac_delim
+SUB_EXAMPLE_FALSE!$SUB_EXAMPLE_FALSE$ac_delim
 BUILD_NOX_TESTS_TRUE!$BUILD_NOX_TESTS_TRUE$ac_delim
 BUILD_NOX_TESTS_FALSE!$BUILD_NOX_TESTS_FALSE$ac_delim
 BUILD_LOCA_TESTS_TRUE!$BUILD_LOCA_TESTS_TRUE$ac_delim
@@ -17752,6 +17814,8 @@ BUILD_THYRA_TESTS_FALSE!$BUILD_THYRA_TESTS_FALSE$ac_delim
 ADDON_thyra_TESTS!$ADDON_thyra_TESTS$ac_delim
 BUILD_TESTUTILS_TRUE!$BUILD_TESTUTILS_TRUE$ac_delim
 BUILD_TESTUTILS_FALSE!$BUILD_TESTUTILS_FALSE$ac_delim
+BUILD_NOX_EXAMPLES_TRUE!$BUILD_NOX_EXAMPLES_TRUE$ac_delim
+BUILD_NOX_EXAMPLES_FALSE!$BUILD_NOX_EXAMPLES_FALSE$ac_delim
 BUILD_LAPACK_EXAMPLES_TRUE!$BUILD_LAPACK_EXAMPLES_TRUE$ac_delim
 BUILD_LAPACK_EXAMPLES_FALSE!$BUILD_LAPACK_EXAMPLES_FALSE$ac_delim
 BUILD_LOCA_LAPACK_EXAMPLES_TRUE!$BUILD_LOCA_LAPACK_EXAMPLES_TRUE$ac_delim
@@ -17769,12 +17833,6 @@ BUILD_PETSC_EXAMPLES_FALSE!$BUILD_PETSC_EXAMPLES_FALSE$ac_delim
 ADDON_petsc_EXAMPLES!$ADDON_petsc_EXAMPLES$ac_delim
 BUILD_BELOS_EXAMPLES_TRUE!$BUILD_BELOS_EXAMPLES_TRUE$ac_delim
 BUILD_BELOS_EXAMPLES_FALSE!$BUILD_BELOS_EXAMPLES_FALSE$ac_delim
-ADDON_belos_EXAMPLES!$ADDON_belos_EXAMPLES$ac_delim
-BUILD_LOCAANASAZI_TRUE!$BUILD_LOCAANASAZI_TRUE$ac_delim
-BUILD_LOCAANASAZI_FALSE!$BUILD_LOCAANASAZI_FALSE$ac_delim
-BUILD_LIBLOCAMF_TRUE!$BUILD_LIBLOCAMF_TRUE$ac_delim
-BUILD_LIBLOCAMF_FALSE!$BUILD_LIBLOCAMF_FALSE$ac_delim
-MF_INCDIR!$MF_INCDIR$ac_delim
 _ACEOF
 
   if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 97; then
@@ -17816,6 +17874,12 @@ _ACEOF
 ac_delim='%!_!# '
 for ac_last_try in false false false false false :; do
   cat >conf$$subs.sed <<_ACEOF
+ADDON_belos_EXAMPLES!$ADDON_belos_EXAMPLES$ac_delim
+BUILD_LOCAANASAZI_TRUE!$BUILD_LOCAANASAZI_TRUE$ac_delim
+BUILD_LOCAANASAZI_FALSE!$BUILD_LOCAANASAZI_FALSE$ac_delim
+BUILD_LIBLOCAMF_TRUE!$BUILD_LIBLOCAMF_TRUE$ac_delim
+BUILD_LIBLOCAMF_FALSE!$BUILD_LIBLOCAMF_FALSE$ac_delim
+MF_INCDIR!$MF_INCDIR$ac_delim
 MF_LIBDIR!$MF_LIBDIR$ac_delim
 MF_LIBS!$MF_LIBS$ac_delim
 BUILD_NOX_EPETRAEXT_SUPPORT_TRUE!$BUILD_NOX_EPETRAEXT_SUPPORT_TRUE$ac_delim
@@ -17844,7 +17908,7 @@ LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 26; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 32; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
diff --git a/packages/rythmos/configure b/packages/rythmos/configure
--- a/packages/rythmos/configure
+++ b/packages/rythmos/configure
@@ -766,6 +766,10 @@ BUILD_EXAMPLES_TRUE
 BUILD_EXAMPLES_FALSE
 BUILD_TESTS_TRUE
 BUILD_TESTS_FALSE
+SUB_TEST_TRUE
+SUB_TEST_FALSE
+SUB_EXAMPLE_TRUE
+SUB_EXAMPLE_FALSE
 PYTHON_USE_TRUE
 PYTHON_USE_FALSE
 PYTHON
@@ -1440,16 +1444,17 @@ Optional Features:
   --enable-nox-epetra     See nox/configure --help
 
   --enable-rythmos-examples
-                          Build Rythmos Examples (default is yes if
-                          --disable-examples is not specified), note: the
-                          examples will not be built unless the following
-                          packages are also enabled: epetraext, amesos,
-                          aztecoo, stratimikos, and epetraext-thyra
-  --enable-rythmos-tests  Build Rythmos Tests (default is yes if
-                          --disable-tests is not specified), note: all of the
-                          tests come from the examples, so if tests are
-                          enabled, the examples will be built (assuming all
-                          the dependencies are enabled)
+                          Make Rythmos examples buildable with 'make examples'
+                          (default is yes if --disable-examples is not
+                          specified), note: the examples will not be built
+                          unless the following packages are also enabled:
+                          epetraext, amesos, aztecoo, stratimikos, and
+                          epetraext-thyra
+  --enable-rythmos-tests  Make Rythmos tests buildable with 'make tests'
+                          (default is yes if --disable-tests is not
+                          specified), note: all of the tests come from the
+                          examples, so if tests are enabled, the examples will
+                          be built (assuming all the dependencies are enabled)
   --enable-libcheck       Check for some third-party libraries including BLAS
                           and LAPACK. (Cannot be disabled unless tests and
                           examples are also disabled.) (default is yes)
@@ -8719,6 +8724,28 @@ fi
 
 fi
 
+#We now build tests and examples through separate make targets, rather than
+#during "make".  We still need to conditionally include the test and example
+#in SUBDIRS, even though SUB_TEST and SUB_EXAMPLE will never be
+#defined, so that the tests and examples are included in the distribution
+#tarball.
+ if test "X$ac_cv_use_sub_test" = "Xyes"; then
+  SUB_TEST_TRUE=
+  SUB_TEST_FALSE='#'
+else
+  SUB_TEST_TRUE='#'
+  SUB_TEST_FALSE=
+fi
+
+ if test "X$ac_cv_use_sub_example" = "Xyes"; then
+  SUB_EXAMPLE_TRUE=
+  SUB_EXAMPLE_FALSE='#'
+else
+  SUB_EXAMPLE_TRUE='#'
+  SUB_EXAMPLE_FALSE=
+fi
+
+
 
 # Check whether --enable-libcheck was given.
 if test "${enable_libcheck+set}" = set; then
@@ -12819,6 +12846,20 @@ echo "$as_me: error: conditional \"BUILD_TESTS\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
+if test -z "${SUB_TEST_TRUE}" && test -z "${SUB_TEST_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"SUB_TEST\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"SUB_TEST\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${SUB_EXAMPLE_TRUE}" && test -z "${SUB_EXAMPLE_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"SUB_EXAMPLE\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"SUB_EXAMPLE\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
 if test -z "${PYTHON_USE_TRUE}" && test -z "${PYTHON_USE_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"PYTHON_USE\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
@@ -13637,6 +13678,10 @@ BUILD_EXAMPLES_TRUE!$BUILD_EXAMPLES_TRUE$ac_delim
 BUILD_EXAMPLES_FALSE!$BUILD_EXAMPLES_FALSE$ac_delim
 BUILD_TESTS_TRUE!$BUILD_TESTS_TRUE$ac_delim
 BUILD_TESTS_FALSE!$BUILD_TESTS_FALSE$ac_delim
+SUB_TEST_TRUE!$SUB_TEST_TRUE$ac_delim
+SUB_TEST_FALSE!$SUB_TEST_FALSE$ac_delim
+SUB_EXAMPLE_TRUE!$SUB_EXAMPLE_TRUE$ac_delim
+SUB_EXAMPLE_FALSE!$SUB_EXAMPLE_FALSE$ac_delim
 PYTHON_USE_TRUE!$PYTHON_USE_TRUE$ac_delim
 PYTHON_USE_FALSE!$PYTHON_USE_FALSE$ac_delim
 PYTHON!$PYTHON$ac_delim
@@ -13661,7 +13706,7 @@ LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 76; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 80; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
diff --git a/packages/sacado/configure b/packages/sacado/configure
--- a/packages/sacado/configure
+++ b/packages/sacado/configure
@@ -742,6 +742,10 @@ BUILD_TESTS_TRUE
 BUILD_TESTS_FALSE
 BUILD_EXAMPLES_TRUE
 BUILD_EXAMPLES_FALSE
+SUB_TEST_TRUE
+SUB_TEST_FALSE
+SUB_EXAMPLE_TRUE
+SUB_EXAMPLE_FALSE
 execincludedir
 CPPUNIT_CONFIG
 CPPUNIT_CFLAGS
@@ -1370,14 +1374,17 @@ Optional Features:
   --enable-teuchos        Build in Teuchos support in Sacado. Can be
                           overridden with --disable-sacado-teuchos.
   --enable-sacado-teuchos Build in Teuchos support in Sacado.
-  --enable-tests          Build Sacado tests (default is no)
+  --enable-tests          Make tests for all Trilinos packages buildable with
+                          'make tests' (default is yes)
 
-  --enable-sacado-tests   Build Sacado tests (default is yes if
-                          --disable-tests is not specified)
-  --enable-examples       Build Sacado examples (default is yes)
+  --enable-sacado-tests   Make Sacado tests buildable with 'make tests'
+                          (default is yes if --disable-tests is not specified)
+  --enable-examples       Make examples for all Trilinos packages buildable
+                          with 'make examples' (default is yes)
   --enable-sacado-examples
-                          Build Sacado examples (default is yes if
-                          --disable-examples is not specified)
+                          Make Sacado examples buildable with 'make examples'
+                          (default is yes if --disable-examples is not
+                          specified)
   --enable-libcheck       Check for some third-party libraries including BLAS
                           and LAPACK. (Cannot be disabled unless tests and
                           examples are also disabled.) (default is yes)
@@ -8222,7 +8229,7 @@ fi
 if test "${enable_tests+set}" = set; then
   enableval=$enable_tests; ac_cv_use_tests=$enableval
 else
-  ac_cv_use_tests=no
+  ac_cv_use_tests=yes
 fi
 
 
@@ -8348,6 +8355,28 @@ fi
 else
   BUILD_EXAMPLES_TRUE='#'
   BUILD_EXAMPLES_FALSE=
+fi
+
+
+#We now build tests and examples through separate make targets, rather than
+#during "make".  We still need to conditionally include the test and example
+#in SUBDIRS, even though SUB_TEST and SUB_EXAMPLE will never be
+#defined, so that the tests and examples are included in the distribution
+#tarball.
+ if test "X$ac_cv_use_sub_test" = "Xyes"; then
+  SUB_TEST_TRUE=
+  SUB_TEST_FALSE='#'
+else
+  SUB_TEST_TRUE='#'
+  SUB_TEST_FALSE=
+fi
+
+ if test "X$ac_cv_use_sub_example" = "Xyes"; then
+  SUB_EXAMPLE_TRUE=
+  SUB_EXAMPLE_FALSE='#'
+else
+  SUB_EXAMPLE_TRUE='#'
+  SUB_EXAMPLE_FALSE=
 fi
 
 
@@ -9204,6 +9233,20 @@ echo "$as_me: error: conditional \"BUILD_EXAMPLES\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
+if test -z "${SUB_TEST_TRUE}" && test -z "${SUB_TEST_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"SUB_TEST\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"SUB_TEST\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${SUB_EXAMPLE_TRUE}" && test -z "${SUB_EXAMPLE_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"SUB_EXAMPLE\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"SUB_EXAMPLE\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
 if test -z "${HAVE_CPPUNIT_TRUE}" && test -z "${HAVE_CPPUNIT_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"HAVE_CPPUNIT\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
@@ -9928,6 +9971,10 @@ BUILD_TESTS_TRUE!$BUILD_TESTS_TRUE$ac_delim
 BUILD_TESTS_FALSE!$BUILD_TESTS_FALSE$ac_delim
 BUILD_EXAMPLES_TRUE!$BUILD_EXAMPLES_TRUE$ac_delim
 BUILD_EXAMPLES_FALSE!$BUILD_EXAMPLES_FALSE$ac_delim
+SUB_TEST_TRUE!$SUB_TEST_TRUE$ac_delim
+SUB_TEST_FALSE!$SUB_TEST_FALSE$ac_delim
+SUB_EXAMPLE_TRUE!$SUB_EXAMPLE_TRUE$ac_delim
+SUB_EXAMPLE_FALSE!$SUB_EXAMPLE_FALSE$ac_delim
 execincludedir!$execincludedir$ac_delim
 CPPUNIT_CONFIG!$CPPUNIT_CONFIG$ac_delim
 CPPUNIT_CFLAGS!$CPPUNIT_CFLAGS$ac_delim
@@ -9945,7 +9992,7 @@ LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 45; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 49; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
diff --git a/packages/stratimikos/configure b/packages/stratimikos/configure
--- a/packages/stratimikos/configure
+++ b/packages/stratimikos/configure
@@ -714,6 +714,10 @@ BUILD_TESTS_TRUE
 BUILD_TESTS_FALSE
 BUILD_EXAMPLES_TRUE
 BUILD_EXAMPLES_FALSE
+SUB_TEST_TRUE
+SUB_TEST_FALSE
+SUB_EXAMPLE_TRUE
+SUB_EXAMPLE_FALSE
 USING_EXPORT_MAKEFILES_TRUE
 USING_EXPORT_MAKEFILES_FALSE
 PERL_EXE
@@ -1363,19 +1367,18 @@ Optional Features:
   --enable-ml             See ml/configure --help
   --enable-nox            See ml/configure --help
   --enable-ml-nox         See ml/configure --help
-  --enable-tests          Build tests for all Trilinos packages (not all
-                          packages are sensitive to this option) (default is
-                          yes)
+  --enable-tests          Make tests for all Trilinos packages buildable with
+                          'make tests' (default is yes)
 
   --enable-stratimikos-tests
-                          Build Stratimikos tests (default is yes if
-                          --disable-tests is not specified)
-  --enable-examples       Build examples for all Trilinos packages (not all
-                          packages are sensitive to this option) (default is
-                          yes)
+                          Make Stratimikos tests buildable with 'make tests'
+                          (default is yes if --disable-tests is not specified)
+  --enable-examples       Make examples for all Trilinos packages buildable
+                          with 'make examples' (default is yes)
   --enable-stratimikos-examples
-                          Build Stratimikos examples (default is yes if
-                          --disable-examples is not specified)
+                          Make Stratimikos examples buildable with 'make
+                          examples' (default is yes if --disable-examples is
+                          not specified)
   --enable-export-makefiles
                           Creates export makefiles in the install (prefix)
                           directory. This option requires perl to be set in
@@ -6021,6 +6024,28 @@ else
 fi
 
 
+#We now build tests and examples through separate make targets, rather than
+#during "make".  We still need to conditionally include the test and example
+#in SUBDIRS, even though SUB_TEST and SUB_EXAMPLE will never be
+#defined, so that the tests and examples are included in the distribution
+#tarball.
+ if test "X$ac_cv_use_sub_test" = "Xyes"; then
+  SUB_TEST_TRUE=
+  SUB_TEST_FALSE='#'
+else
+  SUB_TEST_TRUE='#'
+  SUB_TEST_FALSE=
+fi
+
+ if test "X$ac_cv_use_sub_example" = "Xyes"; then
+  SUB_EXAMPLE_TRUE=
+  SUB_EXAMPLE_FALSE='#'
+else
+  SUB_EXAMPLE_TRUE='#'
+  SUB_EXAMPLE_FALSE=
+fi
+
+
 # ------------------------------------------------------------------------
 # Specify other directories
 # ------------------------------------------------------------------------
@@ -7076,6 +7101,20 @@ echo "$as_me: error: conditional \"BUILD_EXAMPLES\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
+if test -z "${SUB_TEST_TRUE}" && test -z "${SUB_TEST_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"SUB_TEST\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"SUB_TEST\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${SUB_EXAMPLE_TRUE}" && test -z "${SUB_EXAMPLE_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"SUB_EXAMPLE\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"SUB_EXAMPLE\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
 if test -z "${USING_EXPORT_MAKEFILES_TRUE}" && test -z "${USING_EXPORT_MAKEFILES_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"USING_EXPORT_MAKEFILES\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
@@ -7830,6 +7869,10 @@ BUILD_TESTS_TRUE!$BUILD_TESTS_TRUE$ac_delim
 BUILD_TESTS_FALSE!$BUILD_TESTS_FALSE$ac_delim
 BUILD_EXAMPLES_TRUE!$BUILD_EXAMPLES_TRUE$ac_delim
 BUILD_EXAMPLES_FALSE!$BUILD_EXAMPLES_FALSE$ac_delim
+SUB_TEST_TRUE!$SUB_TEST_TRUE$ac_delim
+SUB_TEST_FALSE!$SUB_TEST_FALSE$ac_delim
+SUB_EXAMPLE_TRUE!$SUB_EXAMPLE_TRUE$ac_delim
+SUB_EXAMPLE_FALSE!$SUB_EXAMPLE_FALSE$ac_delim
 USING_EXPORT_MAKEFILES_TRUE!$USING_EXPORT_MAKEFILES_TRUE$ac_delim
 USING_EXPORT_MAKEFILES_FALSE!$USING_EXPORT_MAKEFILES_FALSE$ac_delim
 PERL_EXE!$PERL_EXE$ac_delim
@@ -7845,7 +7888,7 @@ LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 51; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 55; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
diff --git a/packages/thyra/configure b/packages/thyra/configure
--- a/packages/thyra/configure
+++ b/packages/thyra/configure
@@ -696,6 +696,10 @@ BUILD_TESTS_TRUE
 BUILD_TESTS_FALSE
 BUILD_EXAMPLES_TRUE
 BUILD_EXAMPLES_FALSE
+SUB_TEST_TRUE
+SUB_TEST_FALSE
+SUB_EXAMPLE_TRUE
+SUB_EXAMPLE_FALSE
 ENABLE_THYRA_EPETRA_TRUE
 ENABLE_THYRA_EPETRA_FALSE
 ENABLE_THYRA_TPETRA_TRUE
@@ -1319,17 +1323,16 @@ Optional Features:
   --enable-dependency-tracking   do not reject slow dependency extractors
   --enable-teuchos-complex
                           Enable Teuchos complex code (default is yes)
-  --enable-tests          Build tests for all Trilinos packages (not all
-                          packages are sensitive to this option) (default is
-                          yes)
+  --enable-tests          Make tests for all Trilinos packages buildable with
+                          'make tests' (default is yes)
 
-  --enable-thyra-tests    Build Thyra tests (default is yes if --disable-tests
-                          is not specified)
-  --enable-examples       Build examples for all Trilinos packages (not all
-                          packages are sensitive to this option) (default is
-                          yes)
-  --enable-thyra-examples Build Thyra examples (default is yes if
-                          --disable-examples is not specified)
+  --enable-thyra-tests    Make Thyra tests buildable with 'make tests'
+                          (default is yes if --disable-tests is not specified)
+  --enable-examples       Make examples for all Trilinos packages buildable
+                          with 'make examples' (default is yes)
+  --enable-thyra-examples Make Thyra examples buildable with 'make examples'
+                          (default is yes if --disable-examples is not
+                          specified)
   --enable-epetra         Build the Thyra operator/vector adapater support for
                           Epetra. Can be overridden with
                           --disable-thyra-epetra.
@@ -5473,6 +5476,28 @@ else
 fi
 
 
+#We now build tests and examples through separate make targets, rather than
+#during "make".  We still need to conditionally include the test and example
+#in SUBDIRS, even though SUB_TEST and SUB_EXAMPLE will never be
+#defined, so that the tests and examples are included in the distribution
+#tarball.
+ if test "X$ac_cv_use_sub_test" = "Xyes"; then
+  SUB_TEST_TRUE=
+  SUB_TEST_FALSE='#'
+else
+  SUB_TEST_TRUE='#'
+  SUB_TEST_FALSE=
+fi
+
+ if test "X$ac_cv_use_sub_example" = "Xyes"; then
+  SUB_EXAMPLE_TRUE=
+  SUB_EXAMPLE_FALSE='#'
+else
+  SUB_EXAMPLE_TRUE='#'
+  SUB_EXAMPLE_FALSE=
+fi
+
+
 # ------------------------------------------------------------------------
 # Checks if adapters should be built
 # ------------------------------------------------------------------------
@@ -6691,6 +6716,20 @@ echo "$as_me: error: conditional \"BUILD_EXAMPLES\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
+if test -z "${SUB_TEST_TRUE}" && test -z "${SUB_TEST_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"SUB_TEST\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"SUB_TEST\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${SUB_EXAMPLE_TRUE}" && test -z "${SUB_EXAMPLE_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"SUB_EXAMPLE\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"SUB_EXAMPLE\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
 if test -z "${ENABLE_THYRA_EPETRA_TRUE}" && test -z "${ENABLE_THYRA_EPETRA_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"ENABLE_THYRA_EPETRA\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
@@ -7451,6 +7490,10 @@ BUILD_TESTS_TRUE!$BUILD_TESTS_TRUE$ac_delim
 BUILD_TESTS_FALSE!$BUILD_TESTS_FALSE$ac_delim
 BUILD_EXAMPLES_TRUE!$BUILD_EXAMPLES_TRUE$ac_delim
 BUILD_EXAMPLES_FALSE!$BUILD_EXAMPLES_FALSE$ac_delim
+SUB_TEST_TRUE!$SUB_TEST_TRUE$ac_delim
+SUB_TEST_FALSE!$SUB_TEST_FALSE$ac_delim
+SUB_EXAMPLE_TRUE!$SUB_EXAMPLE_TRUE$ac_delim
+SUB_EXAMPLE_FALSE!$SUB_EXAMPLE_FALSE$ac_delim
 ENABLE_THYRA_EPETRA_TRUE!$ENABLE_THYRA_EPETRA_TRUE$ac_delim
 ENABLE_THYRA_EPETRA_FALSE!$ENABLE_THYRA_EPETRA_FALSE$ac_delim
 ENABLE_THYRA_TPETRA_TRUE!$ENABLE_THYRA_TPETRA_TRUE$ac_delim
@@ -7474,7 +7517,7 @@ LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 41; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 45; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
