Fixing matlab compilation bugs

diff --git a/packages/ml/configure b/packages/ml/configure
--- a/packages/ml/configure
+++ b/packages/ml/configure
@@ -311,7 +311,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot MPI_TEMP_CXX MPI_CXX HAVE_MPI_TRUE HAVE_MPI_FALSE MPI_CXX_EXISTS MPI_CC_EXISTS MPI_F77_EXISTS CXX CXXFLAGS LDFLAGS CPPFLAGS ac_ct_CXX EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE CC CFLAGS ac_ct_CC CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE F77 FFLAGS ac_ct_F77 RANLIB ac_ct_RANLIB ML_BUILD_DIRECTORY USE_ALTERNATE_AR_TRUE USE_ALTERNATE_AR_FALSE ALTERNATE_AR CXXCPP USING_EXPORT_MAKEFILES_TRUE USING_EXPORT_MAKEFILES_FALSE PERL_EXE HAVE_PERL USING_PERL_TRUE USING_PERL_FALSE USING_GNUMAKE_TRUE USING_GNUMAKE_FALSE EGREP LIBOBJS ML_CFUNC_TRUE ML_CFUNC_FALSE ML_BENCHMARKING_TRUE ML_BENCHMARKING_FALSE ML_USING_NOX_TRUE ML_USING_NOX_FALSE ML_USING_EPETRA_TRUE ML_USING_EPETRA_FALSE ML_USING_AMESOS_TRUE ML_USING_AMESOS_FALSE ML_USING_IFPACK_TRUE ML_USING_IFPACK_FALSE ML_USING_TEUCHOS_TRUE ML_USING_TEUCHOS_FALSE ML_USING_AZTECOO_TRUE ML_USING_AZTECOO_FALSE ML_USING_EPETRAEXT_TRUE ML_USING_EPETRAEXT_FALSE ML_USING_GALERI_TRUE ML_USING_GALERI_FALSE ENABLE_ML_THYRA_TRUE ENABLE_ML_THYRA_FALSE ML_STANDALONE_MODE_TRUE ML_STANDALONE_MODE_FALSE ML_BUILD_EXAMPLES_TRUE ML_BUILD_EXAMPLES_FALSE BUILD_TESTS_TRUE BUILD_TESTS_FALSE BUILD_ML_PYTHON_TRUE BUILD_ML_PYTHON_FALSE PYTHON_USE_TRUE PYTHON_USE_FALSE PYTHON PYTHON_PREFIX PYTHON_EXECPREFIX BUILD_PYTHON_TRUE BUILD_PYTHON_FALSE PYTHON_CSPEC PYTHON_LSPEC WITH_SWIG SWIG SWIG_LIB SWIG_PYTHON_OPT SWIG_PYTHON_CPPFLAGS HAVE_SWIG_TRUE HAVE_SWIG_FALSE GNU_HAVE_SWIG FLIBS BLAS_LIBS LAPACK_LIBS BUILD_ML_MATLAB_TRUE BUILD_ML_MATLAB_FALSE MATLAB_USE_TRUE MATLAB_USE_FALSE MATLAB_ROOT_USE_TRUE MATLAB_ROOT_USE_FALSE MATLAB_EXE MEX MATLAB MATLAB_ROOT MEXEXT MEXEXT_VALUE BUILD_MATLAB_TRUE BUILD_MATLAB_FALSE ML_MATLAB_INCLUDES TRILINOS_TEMPLATE_OBJS ac_aux_dir LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot MPI_TEMP_CXX MPI_CXX HAVE_MPI_TRUE HAVE_MPI_FALSE MPI_CXX_EXISTS MPI_CC_EXISTS MPI_F77_EXISTS CXX CXXFLAGS LDFLAGS CPPFLAGS ac_ct_CXX EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE CC CFLAGS ac_ct_CC CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE F77 FFLAGS ac_ct_F77 RANLIB ac_ct_RANLIB ML_BUILD_DIRECTORY USE_ALTERNATE_AR_TRUE USE_ALTERNATE_AR_FALSE ALTERNATE_AR CXXCPP USING_EXPORT_MAKEFILES_TRUE USING_EXPORT_MAKEFILES_FALSE PERL_EXE HAVE_PERL USING_PERL_TRUE USING_PERL_FALSE USING_GNUMAKE_TRUE USING_GNUMAKE_FALSE EGREP LIBOBJS ML_CFUNC_TRUE ML_CFUNC_FALSE ML_BENCHMARKING_TRUE ML_BENCHMARKING_FALSE ML_USING_NOX_TRUE ML_USING_NOX_FALSE ML_USING_EPETRA_TRUE ML_USING_EPETRA_FALSE ML_USING_AMESOS_TRUE ML_USING_AMESOS_FALSE ML_USING_IFPACK_TRUE ML_USING_IFPACK_FALSE ML_USING_TEUCHOS_TRUE ML_USING_TEUCHOS_FALSE ML_USING_AZTECOO_TRUE ML_USING_AZTECOO_FALSE ML_USING_EPETRAEXT_TRUE ML_USING_EPETRAEXT_FALSE ML_USING_GALERI_TRUE ML_USING_GALERI_FALSE ENABLE_ML_THYRA_TRUE ENABLE_ML_THYRA_FALSE ML_STANDALONE_MODE_TRUE ML_STANDALONE_MODE_FALSE ML_BUILD_EXAMPLES_TRUE ML_BUILD_EXAMPLES_FALSE BUILD_TESTS_TRUE BUILD_TESTS_FALSE BUILD_ML_PYTHON_TRUE BUILD_ML_PYTHON_FALSE PYTHON_USE_TRUE PYTHON_USE_FALSE PYTHON PYTHON_PREFIX PYTHON_EXECPREFIX BUILD_PYTHON_TRUE BUILD_PYTHON_FALSE PYTHON_CSPEC PYTHON_LSPEC WITH_SWIG SWIG SWIG_LIB SWIG_PYTHON_OPT SWIG_PYTHON_CPPFLAGS HAVE_SWIG_TRUE HAVE_SWIG_FALSE GNU_HAVE_SWIG FLIBS BLAS_LIBS LAPACK_LIBS BUILD_ML_MATLAB_TRUE BUILD_ML_MATLAB_FALSE MATLAB_USE_TRUE MATLAB_USE_FALSE MATLAB_ROOT_USE_TRUE MATLAB_ROOT_USE_FALSE MATLAB_EXE MEX MATLAB_BIN MATLAB_ROOT MEXEXT MEXEXT_VALUE BUILD_MATLAB_TRUE BUILD_MATLAB_FALSE ML_MATLAB_INCLUDES TRILINOS_TEMPLATE_OBJS ac_aux_dir LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -12855,7 +12855,7 @@ fi
 
 
 
-    # unless MATLAB was supplied to us (as a precious variable),
+    # unless MATLAB_EXE was supplied to us (as a precious variable),
     # see if --with-matlab[=MatlabExecutablePath], --with-matlab,
     # --without-matlab or --with-matlab=no was given.
     if test -z "$MATLAB_EXE"
@@ -12871,7 +12871,7 @@ if test "${with_matlab_exec+set}" = set; then
                 then
                     # "yes" was specified, but we don't have a path
                     # for the executable.
-		    # Check PATH +  if needed
+                    # So, let's searth the PATH Environment Variable.
                     echo "$as_me:$LINENO: result: yes" >&5
 echo "${ECHO_T}yes" >&6
                     # Extract the first word of "mex", so it can be a program name with args.
@@ -12887,8 +12887,7 @@ else
   ;;
   *)
   as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
-as_dummy=":$PATH"
-for as_dir in $as_dummy
+for as_dir in $PATH
 do
   IFS=$as_save_IFS
   test -z "$as_dir" && as_dir=.
@@ -12918,12 +12917,12 @@ fi
 set dummy matlab; ac_word=$2
 echo "$as_me:$LINENO: checking for $ac_word" >&5
 echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
-if test "${ac_cv_path_MATLAB+set}" = set; then
+if test "${ac_cv_path_MATLAB_BIN+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
-  case $MATLAB in
+  case $MATLAB_BIN in
   [\\/]* | ?:[\\/]*)
-  ac_cv_path_MATLAB="$MATLAB" # Let the user override the test with a path.
+  ac_cv_path_MATLAB_BIN="$MATLAB_BIN" # Let the user override the test with a path.
   ;;
   *)
   as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
@@ -12933,37 +12932,30 @@ do
   test -z "$as_dir" && as_dir=.
   for ac_exec_ext in '' $ac_executable_extensions; do
   if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
-    ac_cv_path_MATLAB="$as_dir/$ac_word$ac_exec_ext"
+    ac_cv_path_MATLAB_BIN="$as_dir/$ac_word$ac_exec_ext"
     echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
     break 2
   fi
 done
 done
 
-  test -z "$ac_cv_path_MATLAB" && ac_cv_path_MATLAB=":$PATH"
   ;;
 esac
 fi
-MATLAB=$ac_cv_path_MATLAB
+MATLAB_BIN=$ac_cv_path_MATLAB_BIN
 
-if test -n "$MATLAB"; then
-  echo "$as_me:$LINENO: result: $MATLAB" >&5
-echo "${ECHO_T}$MATLAB" >&6
+if test -n "$MATLAB_BIN"; then
+  echo "$as_me:$LINENO: result: $MATLAB_BIN" >&5
+echo "${ECHO_T}$MATLAB_BIN" >&6
 else
   echo "$as_me:$LINENO: result: no" >&5
 echo "${ECHO_T}no" >&6
 fi
 
-                    if test -z "$MATLAB"
+                    if test -z "$MATLAB_EXE"
                     then
-                        { { echo "$as_me:$LINENO: error: no path to matlab binary found" >&5
-echo "$as_me: error: no path to matlab binary found" >&2;}
-   { (exit 1); exit 1; }; }
-                    fi
-                    if test -z "$MEX"
-                    then
-                        { { echo "$as_me:$LINENO: error: no path to mex binary found" >&5
-echo "$as_me: error: no path to mex binary found" >&2;}
+                        { { echo "$as_me:$LINENO: error: no path to matlab found" >&5
+echo "$as_me: error: no path to matlab found" >&2;}
    { (exit 1); exit 1; }; }
                     fi
                     az_matlab_use=true
@@ -13041,12 +13033,12 @@ fi
 set dummy matlab; ac_word=$2
 echo "$as_me:$LINENO: checking for $ac_word" >&5
 echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
-if test "${ac_cv_path_MATLAB+set}" = set; then
+if test "${ac_cv_path_MATLAB_BIN+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
-  case $MATLAB in
+  case $MATLAB_BIN in
   [\\/]* | ?:[\\/]*)
-  ac_cv_path_MATLAB="$MATLAB" # Let the user override the test with a path.
+  ac_cv_path_MATLAB_BIN="$MATLAB_BIN" # Let the user override the test with a path.
   ;;
   *)
   as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
@@ -13056,7 +13048,7 @@ do
   test -z "$as_dir" && as_dir=.
   for ac_exec_ext in '' $ac_executable_extensions; do
   if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
-    ac_cv_path_MATLAB="$as_dir/$ac_word$ac_exec_ext"
+    ac_cv_path_MATLAB_BIN="$as_dir/$ac_word$ac_exec_ext"
     echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
     break 2
   fi
@@ -13066,28 +13058,16 @@ done
   ;;
 esac
 fi
-MATLAB=$ac_cv_path_MATLAB
+MATLAB_BIN=$ac_cv_path_MATLAB_BIN
 
-if test -n "$MATLAB"; then
-  echo "$as_me:$LINENO: result: $MATLAB" >&5
-echo "${ECHO_T}$MATLAB" >&6
+if test -n "$MATLAB_BIN"; then
+  echo "$as_me:$LINENO: result: $MATLAB_BIN" >&5
+echo "${ECHO_T}$MATLAB_BIN" >&6
 else
   echo "$as_me:$LINENO: result: no" >&5
 echo "${ECHO_T}no" >&6
 fi
 
-                    if test -z "$MATLAB"
-                    then
-                        { { echo "$as_me:$LINENO: error: no path to matlab binary found" >&5
-echo "$as_me: error: no path to matlab binary found" >&2;}
-   { (exit 1); exit 1; }; }
-                    fi
-                    if test -z "$MEX"
-                    then
-                        { { echo "$as_me:$LINENO: error: no path to mex binary found" >&5
-echo "$as_me: error: no path to mex binary found" >&2;}
-   { (exit 1); exit 1; }; }
-                    fi
                     az_matlab_use=true
 
 
@@ -13819,7 +13799,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_verb"
-(eval echo $as_me:13822: \"$ac_link\") >&5
+(eval echo $as_me:13802: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
@@ -13897,7 +13877,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_cv_prog_f77_v"
-(eval echo $as_me:13900: \"$ac_link\") >&5
+(eval echo $as_me:13880: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
@@ -15312,7 +15292,7 @@ s,@MATLAB_ROOT_USE_TRUE@,$MATLAB_ROOT_USE_TRUE,;t t
 s,@MATLAB_ROOT_USE_FALSE@,$MATLAB_ROOT_USE_FALSE,;t t
 s,@MATLAB_EXE@,$MATLAB_EXE,;t t
 s,@MEX@,$MEX,;t t
-s,@MATLAB@,$MATLAB,;t t
+s,@MATLAB_BIN@,$MATLAB_BIN,;t t
 s,@MATLAB_ROOT@,$MATLAB_ROOT,;t t
 s,@MEXEXT@,$MEXEXT,;t t
 s,@MEXEXT_VALUE@,$MEXEXT_VALUE,;t t
