Added --with-ml_superlu_dist flag to configure.ac to support SuperLU_DIST
Added --with-ml_element_number64 flag to configure.ac to support
64-bit global element numbers (right now this is required only when
the ML library is to be used with MPSalsa)

If the --with-ml_element_number64 flag is specified with configure,
then must also specify CPPFLAGS=-D<platform> where
platform is LINUX, TFLOP, IRIX, IRIXN32, IRIX64, ALPHA

diff --git a/packages/ml/configure b/packages/ml/configure
--- a/packages/ml/configure
+++ b/packages/ml/configure
@@ -310,7 +310,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM AWK SET_MAKE MPI_CXX HAVE_MPI_TRUE HAVE_MPI_FALSE MPI_CXX_EXISTS MPI_CC_EXISTS MPI_F77_EXISTS CXX CXXFLAGS LDFLAGS CPPFLAGS ac_ct_CXX EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CXXDEPMODE CC CFLAGS ac_ct_CC CCDEPMODE F77 FFLAGS ac_ct_F77 RANLIB ac_ct_RANLIB USE_ALTERNATE_AR_TRUE USE_ALTERNATE_AR_FALSE ALTERNATE_AR CXXCPP EGREP ML_STANDALONE_MODE_TRUE ML_STANDALONE_MODE_FALSE BUILD_EXAMPLES_TRUE BUILD_EXAMPLES_FALSE FLIBS BLAS_LIBS LAPACK_LIBS ac_aux_dir LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM AWK SET_MAKE MPI_CXX HAVE_MPI_TRUE HAVE_MPI_FALSE MPI_CXX_EXISTS MPI_CC_EXISTS MPI_F77_EXISTS CXX CXXFLAGS LDFLAGS CPPFLAGS ac_ct_CXX EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CXXDEPMODE CC CFLAGS ac_ct_CC CCDEPMODE F77 FFLAGS ac_ct_F77 RANLIB ac_ct_RANLIB USE_ALTERNATE_AR_TRUE USE_ALTERNATE_AR_FALSE ALTERNATE_AR CXXCPP EGREP ML_STANDALONE_MODE_TRUE ML_STANDALONE_MODE_FALSE ML_BENCHMARKING_TRUE ML_BENCHMARKING_FALSE BUILD_EXAMPLES_TRUE BUILD_EXAMPLES_FALSE FLIBS BLAS_LIBS LAPACK_LIBS ac_aux_dir LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -925,6 +925,19 @@ Optional Packages:
                           libraries via the configure options
                           --with-ldflags=<SuperLU-library-path/library-name>
                           and --with-incdirs=SuperLU-include-directory.
+                          (default is no)
+  --with-ml_superlu_dist  Enable SuperLU_DIST support. Note 1: SuperLU_DIST is
+                          a third party library. As such, configure assumes
+                          that it has already been built. Note 2: You must
+                          also specify the location of the SuperLU_DIST
+                          headers and libraries via the configure options
+                          --with-ldflags=<SuperLU_DIST-library-path/library-name>
+                          and --with-incdirs=SuperLU_DIST-include-directory.
+                          (default is no)
+  --with-ml_element_number64
+                          Enable 64-bit global element numbers. This is
+                          required if ML is intended to be used with MPSalsa
+                          because MPSalsa uses 64-bit global element numbers.
                           (default is no)
   --with-ml_metis         Enable METIS support. Note 1: METIS is a third party
                           library. As such, configure assumes that it has
@@ -3578,7 +3591,7 @@ fi
 
 
 # Provide some information about the compiler.
-echo "$as_me:3581:" \
+echo "$as_me:3594:" \
      "checking for Fortran 77 compiler version" >&5
 ac_compiler=`set X $ac_compile; echo $2`
 { (eval echo "$as_me:$LINENO: \"$ac_compiler --version </dev/null >&5\"") >&5
@@ -5890,6 +5903,60 @@ else
 echo "${ECHO_T}no" >&6
 fi
 
+#
+
+
+# Check whether --with-ml_superlu_dist or --without-ml_superlu_dist was given.
+if test "${with_ml_superlu_dist+set}" = set; then
+  withval="$with_ml_superlu_dist"
+  ac_cv_use_ml_superlu_dist=$withval
+else
+  ac_cv_use_ml_superlu_dist=no
+fi;
+
+echo "$as_me:$LINENO: checking whether to use ml_superlu_dist" >&5
+echo $ECHO_N "checking whether to use ml_superlu_dist... $ECHO_C" >&6
+
+if test "X$ac_cv_use_ml_superlu_dist" != "Xno"; then
+  echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_ML_SUPERLU_DIST
+_ACEOF
+
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+#
+
+
+# Check whether --with-ml_element_number64 or --without-ml_element_number64 was given.
+if test "${with_ml_element_number64+set}" = set; then
+  withval="$with_ml_element_number64"
+  ac_cv_use_ml_element_number64=$withval
+else
+  ac_cv_use_ml_element_number64=no
+fi;
+
+echo "$as_me:$LINENO: checking whether to use ml_element_number64" >&5
+echo $ECHO_N "checking whether to use ml_element_number64... $ECHO_C" >&6
+
+if test "X$ac_cv_use_ml_element_number64" != "Xno"; then
+  echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_ML_ELEMENT_NUM64
+_ACEOF
+
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
  #
 
 # Check whether --enable-ml_complex_maxwell or --disable-ml_complex_maxwell was given.
@@ -5993,6 +6060,16 @@ _ACEOF
 else
   echo "$as_me:$LINENO: result: no" >&5
 echo "${ECHO_T}no" >&6
+fi
+
+
+
+if test "X$ac_cv_use_ml_benchmarking" != "Xno"; then
+  ML_BENCHMARKING_TRUE=
+  ML_BENCHMARKING_FALSE='#'
+else
+  ML_BENCHMARKING_TRUE='#'
+  ML_BENCHMARKING_FALSE=
 fi
 
 
@@ -6219,7 +6296,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_verb"
-(eval echo $as_me:6222: \"$ac_link\") >&5
+(eval echo $as_me:6299: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
@@ -6299,7 +6376,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_cv_prog_f77_v"
-(eval echo $as_me:6302: \"$ac_link\") >&5
+(eval echo $as_me:6379: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
@@ -8730,7 +8807,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_verb"
-(eval echo $as_me:8733: \"$ac_link\") >&5
+(eval echo $as_me:8810: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
@@ -8810,7 +8887,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_cv_prog_f77_v"
-(eval echo $as_me:8813: \"$ac_link\") >&5
+(eval echo $as_me:8890: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
@@ -9162,6 +9239,13 @@ if test -z "${ML_STANDALONE_MODE_TRUE}" && test -z "${ML_STANDALONE_MODE_FALSE}"
   { { echo "$as_me:$LINENO: error: conditional \"ML_STANDALONE_MODE\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"ML_STANDALONE_MODE\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${ML_BENCHMARKING_TRUE}" && test -z "${ML_BENCHMARKING_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"ML_BENCHMARKING\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"ML_BENCHMARKING\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -9773,6 +9857,8 @@ s,@CXXCPP@,$CXXCPP,;t t
 s,@EGREP@,$EGREP,;t t
 s,@ML_STANDALONE_MODE_TRUE@,$ML_STANDALONE_MODE_TRUE,;t t
 s,@ML_STANDALONE_MODE_FALSE@,$ML_STANDALONE_MODE_FALSE,;t t
+s,@ML_BENCHMARKING_TRUE@,$ML_BENCHMARKING_TRUE,;t t
+s,@ML_BENCHMARKING_FALSE@,$ML_BENCHMARKING_FALSE,;t t
 s,@BUILD_EXAMPLES_TRUE@,$BUILD_EXAMPLES_TRUE,;t t
 s,@BUILD_EXAMPLES_FALSE@,$BUILD_EXAMPLES_FALSE,;t t
 s,@FLIBS@,$FLIBS,;t t
