SUMMARY:   HAVE_ML_ZOLTAN_THREE now implies HAVE_ML_ZOLTAN
     BUGS:      4087

     CHECKLIST:

     1)   Did you add any source files?  no

     2)   Did you update or change the build system?  yes
     2.a) Did you remember to do a bootstrap and do a 'cvs add' on the
          Makefile.am files and the Makefile.in files?  yes & n/a
     2.b) [Optional but recommended] Did you blow away the libraries and
          executables and then rebuild?  yes

     3) Did you rerun the test suite on at least the packages that you
        changed?  yes

     COMMENTS:

     --enable-ml_zoltan3 now turns on *all* Zoltan code, including that
     implied by --enable-ml_zoltan

     Configured with and without --enable-ml_zoltan3, all tests compile &
     pass.

     Configure also now checks for MPI when either zoltan option is on,
     and dies if MPI is not enabled.

(checklist version 2007-06-20)

diff --git a/packages/ml/configure b/packages/ml/configure
--- a/packages/ml/configure
+++ b/packages/ml/configure
@@ -8861,17 +8861,6 @@ else
 echo "${ECHO_T}no" >&6; }
 fi
 
-#this works
-if test "X${HAVE_PKG_MPI}" != "Xyes"; then
-#if test "X${HAVE_MPI}" != "Xyes"; then
-   #issue an error message and abort if the user has configured with
-   #the zoltan interface enabled but without mpi enabled
-   if test "X$ac_cv_use_ml_zoltan" = "Xyes"; then
-     { { echo "$as_me:$LINENO: error: Zoltan support in ML requires enabling MPI." >&5
-echo "$as_me: error: Zoltan support in ML requires enabling MPI." >&2;}
-   { (exit 1); exit 1; }; }
-   fi
-fi
  if test "X$ac_cv_use_ml_zoltan" = "Xyes"; then
   ML_USING_ZOLTAN_TRUE=
   ML_USING_ZOLTAN_FALSE='#'
@@ -8880,7 +8869,7 @@ else
   ML_USING_ZOLTAN_FALSE=
 fi
 
-
+#
 
 
 # Check whether --with-ml_zoltan3 was given.
@@ -8907,6 +8896,16 @@ else
 echo "${ECHO_T}no" >&6; }
 fi
 
+#
+if test "X${HAVE_PKG_MPI}" != "Xyes"; then
+   #issue an error message and abort if the user has configured with
+   #the zoltan interface enabled but without mpi enabled
+   if test "X$ac_cv_use_ml_zoltan" = "Xyes" || test "X$ac_cv_use_ml_zoltan3" = "Xyes"; then
+     { { echo "$as_me:$LINENO: error: Zoltan support in ML requires enabling MPI." >&5
+echo "$as_me: error: Zoltan support in ML requires enabling MPI." >&2;}
+   { (exit 1); exit 1; }; }
+   fi
+fi
 #
 
 
