Bugs 3771, 3740
Removing the requirement of a Fortran compiler when building AztecOO.  There
are now C equivalents of the two Fortran source files in AzteOO.  After
consulting with Mike H, we decided to leave the Fortran files as the default
for now.

In addition, I cleaned up the problem that we saw with Teuchos and the new
BLAS/LAPACK detection when libcheck is disabled.

I also cleaned up a few obsolete parts of configure.ac and src/Makefile.am and
removed az_fortran_wrap.c.  The Fortran wrappers are obsolete, per Mike H.
This allowed me to remove some obsolete code in other files too.

I recompiled on my machine with fortran enabled and disabled and ran the
runtests make target for both builds as well.

I still need to clean up the two new C files, but I want to get this checked
in because everything is compiling with and without Fortran.

diff --git a/packages/aztecoo/configure b/packages/aztecoo/configure
--- a/packages/aztecoo/configure
+++ b/packages/aztecoo/configure
@@ -689,6 +689,8 @@ am__leading_dot
 AMTAR
 am__tar
 am__untar
+FORTRAN_DISABLED_TRUE
+FORTRAN_DISABLED_FALSE
 MPI_TEMP_CXX
 MPI_CXX
 HAVE_MPI_TRUE
@@ -1354,6 +1356,7 @@ Optional Features:
   --enable-FEATURE[=ARG]  include FEATURE [ARG=yes]
   --enable-maintainer-mode  enable make rules and dependencies not useful
 			  (and sometimes confusing) to the casual installer
+  --enable-fortran        enable Fortran support (default is yes)
   --enable-mpi            MPI support
   --disable-dependency-tracking  speeds up one-time build
   --enable-dependency-tracking   do not reject slow dependency extractors
@@ -2657,6 +2660,44 @@ echo "${ECHO_T}$am_cv_prog_tar_ustar" >&6; }
 
 
 # ------------------------------------------------------------------------
+# Check if Fortran is enabled or not
+# ------------------------------------------------------------------------
+
+
+# Check whether --enable-fortran was given.
+if test "${enable_fortran+set}" = set; then
+  enableval=$enable_fortran; ac_cv_use_fortran=$enableval
+else
+  ac_cv_use_fortran=yes
+fi
+
+
+{ echo "$as_me:$LINENO: checking whether to use fortran" >&5
+echo $ECHO_N "checking whether to use fortran... $ECHO_C" >&6; }
+
+if test "X$ac_cv_use_fortran" != "Xno"; then
+  { echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6; }
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_FORTRAN_SUPPORT 1
+_ACEOF
+
+else
+  { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+fi
+
+ if test "X$ac_cv_use_fortran" != "Xyes"; then
+  FORTRAN_DISABLED_TRUE=
+  FORTRAN_DISABLED_FALSE='#'
+else
+  FORTRAN_DISABLED_TRUE='#'
+  FORTRAN_DISABLED_FALSE=
+fi
+
+
+# ------------------------------------------------------------------------
 # Check to see if MPI enabled and if any special configuration done
 # ------------------------------------------------------------------------
 
@@ -2984,6 +3025,8 @@ echo "$as_me: error: MPI C compiler (${MPI_CC}) not found." >&2;}
   fi
 fi
 
+if test "X$ac_cv_use_fortran" = "Xyes"; then
+
 if test -n "${MPI_F77}"; then
   if test -f ${MPI_F77}; then
     MPI_F77_EXISTS=yes
@@ -3043,6 +3086,7 @@ echo "$as_me: error: MPI Fortran 77 compiler (${MPI_F77}) not found." >&2;}
   fi
 fi
 
+fi
 
 # ------------------------------------------------------------------------
 # Checks for programs.
@@ -4413,7 +4457,7 @@ else
 fi
 
 
-BASE_CXX=${CXX}
+if test "X$ac_cv_use_fortran" != "Xno"; then
 ac_ext=f
 ac_compile='$F77 -c $FFLAGS conftest.$ac_ext >&5'
 ac_link='$F77 -o conftest$ac_exeext $FFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
@@ -4674,6 +4718,7 @@ ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
 ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
 ac_compiler_gnu=$ac_cv_c_compiler_gnu
 
+fi
 if test -n "$ac_tool_prefix"; then
   # Extract the first word of "${ac_tool_prefix}ranlib", so it can be a program name with args.
 set dummy ${ac_tool_prefix}ranlib; ac_word=$2
@@ -4772,71 +4817,6 @@ fi
 
 
 # ------------------------------------------------------------------------
-# Checks for --enable-debug, --enable-optimize, --enable-profile, --enable-purify
-# Changes flags and compiler names accordingly
-# ------------------------------------------------------------------------
-
-
-#------------------------------------------------------------------------
-# Check for --enable-debug, --enable-opt, --enable-profile, and --enable-purify
-#------------------------------------------------------------------------
-
-#TAC_ARG_ENABLE_OPTION(debug, [enable debugging], DEBUG, no)
-
-#TAC_ARG_ENABLE_OPTION(opt,[enable optimization],OPTIMIZE,no)
-
-#TAC_ARG_ENABLE_OPTION(profile,[enable profiling],PROFILE,no)
-
-#TAC_ARG_ENABLE_OPTION(purify,[enable purify],PURIFY,no)
-
-#------------------------------------------------------------------------
-# Check if any user overrides were defined in the above section
-#------------------------------------------------------------------------
-# Likely will permanently remove the concept of a custom platform when
-# another way to turn on debug, opt, profile, and purify is found.
-#AC_ARG_WITH(platform,
-#AC_HELP_STRING([--with-platform],[Utilize a custom platform] (must specify)),
-#ac_cv_use_platform=$withval, ac_cv_use_platform=no)
-
-#AC_MSG_CHECKING(whether to use a custom platform)
-
-#if test "X$ac_cv_use_platform" != "Xno"; then
-#  AC_MSG_RESULT(yes)
-      # case $ac_cv_use_platform in
-          # foo*) TAC_SET_COMPILE_OPTIONS_FOO;;
-  # esac
-#else
-#  AC_MSG_RESULT(no)
-#  if test "X$ac_cv_use_debug" != "Xno" || test "X$ac_cv_use_opt" != "Xno" ||
-#     test "X$ac_cv_use_profile" != "Xno"|| test "X$ac_cv_use_purify" != "Xno"; then
-#    if test "X${CXX}" != "XmpiCC"; then
-#      BASE_CXX=${CXX}
-#    fi
-  # Check if user defined a custom platform name
-  #otherwise parse info gathered
-#  case $target in
-#    *linux*)
-#      case $BASE_CXX in
-# 	 *g++*) TAC_SET_COMPILE_OPTIONS_LINUX_GCC;;
-#    esac
-#    ;;
-
-#    *solaris*)
-#      case $BASE_CXX in
-#	*cc* | *CC*) TAC_SET_COMPILE_OPTIONS_SOLARIS_CC;;
-#    esac
-#    ;;
-    # need to add case for cplant
-
-    # need to add case for sgi - and sub-cases for 32 and 64
-
-#  esac
-
-#  fi
-#fi
-
-
-# ------------------------------------------------------------------------
 # Checks for extra flags
 # ------------------------------------------------------------------------
 # Check if --with-flags present, prepend any specs to FLAGS
@@ -4895,6 +4875,7 @@ echo "${ECHO_T}no" >&6; }
 fi
 
 
+if test "X$ac_cv_use_fortran" != "Xno"; then
 
 { echo "$as_me:$LINENO: checking whether additional FFLAGS flags should be added" >&5
 echo $ECHO_N "checking whether additional FFLAGS flags should be added... $ECHO_C" >&6; }
@@ -4913,6 +4894,7 @@ echo "${ECHO_T}no" >&6; }
 fi
 
 
+fi
 
 { echo "$as_me:$LINENO: checking whether additional libraries are needed" >&5
 echo $ECHO_N "checking whether additional libraries are needed... $ECHO_C" >&6; }
@@ -8626,7 +8608,9 @@ fi
 
 
 
-# Define F77_FUNC that will be used to link with Fortran subroutines.
+# Define F77_FUNC that will be used to link with Fortran subroutines found in
+# Trilinos source code
+if test "X$ac_cv_use_fortran" != "Xno"; then
 
 ac_ext=f
 ac_compile='$F77 -c $FFLAGS conftest.$ac_ext >&5'
@@ -9454,6 +9438,7 @@ ac_compile='$CXX -c $CXXFLAGS $CPPFLAGS conftest.$ac_ext >&5'
 ac_link='$CXX -o conftest$ac_exeext $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
 ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
 
+fi
 
 # For now we will consider AztecOO to be dependent on Triutils,
 # even though it is really only the examples.
@@ -16038,6 +16023,69 @@ echo "$as_me: error: Cannot find lapack library, specify a path using --with-ldf
    { (exit 1); exit 1; }; }
 fi
 
+
+else
+
+  if test "X$ac_cv_use_fortran" != "Xno"; then
+  # If we don't check for BLAS above, we will use F77_FUNC as the name mangling
+  # for the BLAS and LAPACK.  This is what we used before we allowed the BLAS
+  # and LAPACK to use different name mangling than the compiler.
+  ac_ext=f
+ac_compile='$F77 -c $FFLAGS conftest.$ac_ext >&5'
+ac_link='$F77 -o conftest$ac_exeext $FFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_f77_compiler_gnu
+case $ac_cv_f77_mangling in
+  upper*) ac_val="DGEMM" ;;
+  lower*) ac_val="dgemm" ;;
+  *)      ac_val="unknown" ;;
+esac
+case $ac_cv_f77_mangling in *," underscore"*) ac_val="$ac_val"_ ;; esac
+
+dgemm="$ac_val"
+
+ac_ext=cpp
+ac_cpp='$CXXCPP $CPPFLAGS'
+ac_compile='$CXX -c $CXXFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CXX -o conftest$ac_exeext $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
+
+    if test "X$dgemm" = "Xdgemm_"; then
+
+cat >>confdefs.h <<\_ACEOF
+#define F77_BLAS_MANGLE(name,NAME) name ## _
+_ACEOF
+
+    else
+      if test "X$dgemm" = "Xdgemm"; then
+
+cat >>confdefs.h <<\_ACEOF
+#define F77_BLAS_MANGLE(name,NAME) name
+_ACEOF
+
+      else
+        if test "X$dgemm" = "XDGEMM"; then
+
+cat >>confdefs.h <<\_ACEOF
+#define F77_BLAS_MANGLE(name,NAME) NAME
+_ACEOF
+
+        else
+          if test "X$dgemm" = "XDGEMM_"; then
+
+cat >>confdefs.h <<\_ACEOF
+#define F77_BLAS_MANGLE(name,NAME) NAME ## _
+_ACEOF
+
+          else
+            { { echo "$as_me:$LINENO: error: Cannot determine BLAS and LAPACK name mangling using the value of F77_FUNC.  Please try configuring Trilinos without the --disable-libcheck option." >&5
+echo "$as_me: error: Cannot determine BLAS and LAPACK name mangling using the value of F77_FUNC.  Please try configuring Trilinos without the --disable-libcheck option." >&2;}
+   { (exit 1); exit 1; }; }
+          fi
+        fi
+      fi
+    fi
+  fi
+
 fi
 # end of the list of libraries that don't need to be checked for if
 # tests and examples are disabled.
@@ -16518,6 +16566,13 @@ if test -z "${MAINTAINER_MODE_TRUE}" && test -z "${MAINTAINER_MODE_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"MAINTAINER_MODE\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"MAINTAINER_MODE\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${FORTRAN_DISABLED_TRUE}" && test -z "${FORTRAN_DISABLED_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"FORTRAN_DISABLED\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"FORTRAN_DISABLED\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -17265,6 +17320,8 @@ am__leading_dot!$am__leading_dot$ac_delim
 AMTAR!$AMTAR$ac_delim
 am__tar!$am__tar$ac_delim
 am__untar!$am__untar$ac_delim
+FORTRAN_DISABLED_TRUE!$FORTRAN_DISABLED_TRUE$ac_delim
+FORTRAN_DISABLED_FALSE!$FORTRAN_DISABLED_FALSE$ac_delim
 MPI_TEMP_CXX!$MPI_TEMP_CXX$ac_delim
 MPI_CXX!$MPI_CXX$ac_delim
 HAVE_MPI_TRUE!$HAVE_MPI_TRUE$ac_delim
@@ -17286,8 +17343,6 @@ AMDEP_TRUE!$AMDEP_TRUE$ac_delim
 AMDEP_FALSE!$AMDEP_FALSE$ac_delim
 AMDEPBACKSLASH!$AMDEPBACKSLASH$ac_delim
 CCDEPMODE!$CCDEPMODE$ac_delim
-am__fastdepCC_TRUE!$am__fastdepCC_TRUE$ac_delim
-am__fastdepCC_FALSE!$am__fastdepCC_FALSE$ac_delim
 _ACEOF
 
   if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 97; then
@@ -17329,6 +17384,8 @@ _ACEOF
 ac_delim='%!_!# '
 for ac_last_try in false false false false false :; do
   cat >conf$$subs.sed <<_ACEOF
+am__fastdepCC_TRUE!$am__fastdepCC_TRUE$ac_delim
+am__fastdepCC_FALSE!$am__fastdepCC_FALSE$ac_delim
 CXX!$CXX$ac_delim
 CXXFLAGS!$CXXFLAGS$ac_delim
 ac_ct_CXX!$ac_ct_CXX$ac_delim
@@ -17376,7 +17433,7 @@ ac_aux_dir!$ac_aux_dir$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 45; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 47; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
