---------------------------------------------------------------------- Committing in .
Modified Files:
Makefile.am Makefile.in Trilinos_config.h.in configure
configure.ac packages/aztecoo/aclocal.m4
packages/aztecoo/configure packages/aztecoo/configure.ac
packages/aztecoo/example/AztecOO/Makefile.am
packages/aztecoo/example/AztecOO/Makefile.in
packages/aztecoo/example/AztecOO_UserOpUserMat/Makefile.am
packages/aztecoo/example/AztecOO_UserOpUserMat/Makefile.in
packages/aztecoo/example/simple_epetra_aztecoo/Makefile.am
packages/aztecoo/example/simple_epetra_aztecoo/Makefile.in
packages/aztecoo/src/AztecOO_config.h.in
----------------------------------------------------------------------
Partially addresses bug 444.

Removes the referencey12m option from all packages except NOX.

Tammy and Roger have requested that I not do this for them.

diff --git a/packages/aztecoo/configure b/packages/aztecoo/configure
--- a/packages/aztecoo/configure
+++ b/packages/aztecoo/configure
@@ -310,7 +310,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM AWK SET_MAKE MPI_CXX HAVE_MPI_TRUE HAVE_MPI_FALSE MPI_CXX_EXISTS MPI_CC_EXISTS MPI_F77_EXISTS CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE CXX CXXFLAGS ac_ct_CXX CXXDEPMODE F77 FFLAGS ac_ct_F77 RANLIB ac_ct_RANLIB USE_ALTERNATE_AR_TRUE USE_ALTERNATE_AR_FALSE ALTERNATE_AR CXXCPP EGREP LIBOBJS BUILD_TRIUTILS_TRUE BUILD_TRIUTILS_FALSE BUILD_Y12M_TRUE BUILD_Y12M_FALSE FLIBS BLAS_LIBS LAPACK_LIBS TRILINOS_TEMPLATE_OBJS ac_aux_dir LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM AWK SET_MAKE MPI_CXX HAVE_MPI_TRUE HAVE_MPI_FALSE MPI_CXX_EXISTS MPI_CC_EXISTS MPI_F77_EXISTS CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE CXX CXXFLAGS ac_ct_CXX CXXDEPMODE F77 FFLAGS ac_ct_F77 RANLIB ac_ct_RANLIB USE_ALTERNATE_AR_TRUE USE_ALTERNATE_AR_FALSE ALTERNATE_AR CXXCPP EGREP LIBOBJS BUILD_TRIUTILS_TRUE BUILD_TRIUTILS_FALSE FLIBS BLAS_LIBS LAPACK_LIBS TRILINOS_TEMPLATE_OBJS ac_aux_dir LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -877,8 +877,6 @@ Optional Features:
   --enable-aztecoo-azlu   Enable az-lu preconditioner. Default is no. Requires
                           y12m.
   --enable-triutils       Build triutils (default is yes)
-  --enable-referencey12m  Build y12m lib included in the distribution (default
-                          is no)
 
 Optional Packages:
   --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
@@ -3497,7 +3495,7 @@ fi
 
 
 # Provide some information about the compiler.
-echo "$as_me:3500:" \
+echo "$as_me:3498:" \
      "checking for Fortran 77 compiler version" >&5
 ac_compiler=`set X $ac_compile; echo $2`
 { (eval echo "$as_me:$LINENO: \"$ac_compiler --version </dev/null >&5\"") >&5
@@ -5955,47 +5953,9 @@ else
 fi
 
 
-# We need to perform this check even if azlu is not enabled.  Otherwise
-# the macros associated with referencey12m are undefined
-
-# Check whether --enable-referencey12m or --disable-referencey12m was given.
-if test "${enable_referencey12m+set}" = set; then
-  enableval="$enable_referencey12m"
-  ac_cv_use_referencey12m=$enableval
-else
-  ac_cv_use_referencey12m=no
-fi;
-
-echo "$as_me:$LINENO: checking whether to use referencey12m" >&5
-echo $ECHO_N "checking whether to use referencey12m... $ECHO_C" >&6
-
-if test "X$ac_cv_use_referencey12m" != "Xno"; then
-  echo "$as_me:$LINENO: result: yes" >&5
-echo "${ECHO_T}yes" >&6
-
-cat >>confdefs.h <<\_ACEOF
-#define HAVE_Y12M
-_ACEOF
-
-else
-  echo "$as_me:$LINENO: result: no" >&5
-echo "${ECHO_T}no" >&6
-fi
-
-
-
-if test "X$ac_cv_use_referencey12m" != "Xno"; then
-  BUILD_Y12M_TRUE=
-  BUILD_Y12M_FALSE='#'
-else
-  BUILD_Y12M_TRUE='#'
-  BUILD_Y12M_FALSE=
-fi
-
 # y12m is needed only when AZ_lu is enabled
 if test "X$ac_cv_use_aztecoo_azlu" != "Xno"; then
 # y12m library needed
-  if test "X$ac_cv_use_referencey12m" = "Xno"; then
     # Find a valid y12m
 
 
@@ -6074,8 +6034,8 @@ if test "$ac_cv_search_y12mae" != no; then
   test "$ac_cv_search_y12mae" = "none required" || LIBS="$ac_cv_search_y12mae $LIBS"
 
 else
-  { { echo "$as_me:$LINENO: error: Cannot find y12m library, specify a location using --with-ldflags-L<DIR> (ex. --with-ldflags=-L/usr/path/lib) or type --enable-referencey12m on the configure line in the Trilinos level directory to use the y12m library included with the distribution" >&5
-echo "$as_me: error: Cannot find y12m library, specify a location using --with-ldflags-L<DIR> (ex. --with-ldflags=-L/usr/path/lib) or type --enable-referencey12m on the configure line in the Trilinos level directory to use the y12m library included with the distribution" >&2;}
+  { { echo "$as_me:$LINENO: error: Cannot find y12m library, specify a location using --with-ldflags-L<DIR> (ex. --with-ldflags=-L/usr/path/lib)." >&5
+echo "$as_me: error: Cannot find y12m library, specify a location using --with-ldflags-L<DIR> (ex. --with-ldflags=-L/usr/path/lib)." >&2;}
    { (exit 1); exit 1; }; }
 fi
 
@@ -6085,7 +6045,6 @@ ac_compile='$CXX -c $CXXFLAGS $CPPFLAGS conftest.$ac_ext >&5'
 ac_link='$CXX -o conftest$ac_exeext $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
 ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
 
-  fi
 fi
 # Checks for library functions.
 echo "$as_me:$LINENO: checking for library containing pow" >&5
@@ -6381,7 +6340,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_verb"
-(eval echo $as_me:6384: \"$ac_link\") >&5
+(eval echo $as_me:6343: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
@@ -6461,7 +6420,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_cv_prog_f77_v"
-(eval echo $as_me:6464: \"$ac_link\") >&5
+(eval echo $as_me:6423: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
@@ -8601,7 +8560,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_verb"
-(eval echo $as_me:8604: \"$ac_link\") >&5
+(eval echo $as_me:8563: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
@@ -8681,7 +8640,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_cv_prog_f77_v"
-(eval echo $as_me:8684: \"$ac_link\") >&5
+(eval echo $as_me:8643: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
@@ -9027,13 +8986,6 @@ if test -z "${BUILD_TRIUTILS_TRUE}" && test -z "${BUILD_TRIUTILS_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"BUILD_TRIUTILS\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"BUILD_TRIUTILS\" was never defined.
-Usually this means the macro was only invoked conditionally." >&2;}
-   { (exit 1); exit 1; }; }
-fi
-if test -z "${BUILD_Y12M_TRUE}" && test -z "${BUILD_Y12M_FALSE}"; then
-  { { echo "$as_me:$LINENO: error: conditional \"BUILD_Y12M\" was never defined.
-Usually this means the macro was only invoked conditionally." >&5
-echo "$as_me: error: conditional \"BUILD_Y12M\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -9647,8 +9599,6 @@ s,@EGREP@,$EGREP,;t t
 s,@LIBOBJS@,$LIBOBJS,;t t
 s,@BUILD_TRIUTILS_TRUE@,$BUILD_TRIUTILS_TRUE,;t t
 s,@BUILD_TRIUTILS_FALSE@,$BUILD_TRIUTILS_FALSE,;t t
-s,@BUILD_Y12M_TRUE@,$BUILD_Y12M_TRUE,;t t
-s,@BUILD_Y12M_FALSE@,$BUILD_Y12M_FALSE,;t t
 s,@FLIBS@,$FLIBS,;t t
 s,@BLAS_LIBS@,$BLAS_LIBS,;t t
 s,@LAPACK_LIBS@,$LAPACK_LIBS,;t t
