----------------------------------------------------------------------
 Committing in .

 Modified Files:
 	packages/aztecoo/aclocal.m4 packages/aztecoo/configure
 	packages/aztecoo/configure.ac packages/epetra/Makefile.in
 	packages/epetra/aclocal.m4 packages/epetra/configure
 	packages/epetra/configure.ac
 	packages/epetra/example/Makefile.in
 	packages/epetra/example/petra_power_method/Makefile.in
 	packages/epetra/example/verySimple/Makefile.in
 	packages/epetra/src/Makefile.am
 	packages/epetra/src/Makefile.in
 	packages/epetra/test/Makefile.in
 	packages/epetra/test/BlockMap/Makefile.in
 	packages/epetra/test/Comm/Makefile.in
 	packages/epetra/test/CrsGraph/Makefile.in
 	packages/epetra/test/CrsMatrix/Makefile.in
 	packages/epetra/test/CrsRectMatrix/Makefile.in
 	packages/epetra/test/FECrsMatrix/Makefile.in
 	packages/epetra/test/FEVbrMatrix/Makefile.in
 	packages/epetra/test/FEVector/Makefile.in
 	packages/epetra/test/ImportExport/Makefile.in
 	packages/epetra/test/Map/Makefile.in
 	packages/epetra/test/MapColoring/Makefile.in
 	packages/epetra/test/MultiVector/Makefile.in
 	packages/epetra/test/Object/Makefile.in
 	packages/epetra/test/SerialDense/Makefile.in
 	packages/epetra/test/SerialSpdDense/Makefile.in
 	packages/epetra/test/VbrMatrix/Makefile.in
 	packages/epetra/test/Vector/Makefile.in
 	packages/epetra/test/scripts/Makefile.in
 	packages/epetra/test/scripts/daily/Makefile.in
 	packages/epetra/test/scripts/daily/mpi/Makefile.in
 	packages/epetra/test/scripts/daily/serial/Makefile.in
 	packages/epetra/test/scripts/weekly/Makefile.in
 	packages/epetra/test/scripts/weekly/mpi/Makefile.in
 	packages/epetra/test/scripts/weekly/serial/Makefile.in
 ----------------------------------------------------------------------
Fixes bug 252 for AztecOO and Epetra.

Introduces TRILINOS_TEMPLATE_OBJS for Epetra, replacing EPETRA_TEMPLATE_OBJS

Also provides more output in AztecOO as far as printing the value of
TRILNOS_TEMPLATE_OBJS during the configure stage and providing documentation
for configure --help.

diff --git a/packages/epetra/configure b/packages/epetra/configure
--- a/packages/epetra/configure
+++ b/packages/epetra/configure
@@ -8216,7 +8216,25 @@ ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
 # -- DEC CXX --
 
 
+  TRILINOS_TEMPLATE_OBJS  template object file location - often needed on DEC
+                          - try 'cxx_repository/*.o'
+echo "$as_me:$LINENO: checking for template-specific object files to be linked" >&5
+echo $ECHO_N "checking for template-specific object files to be linked... $ECHO_C" >&6
+if test "X$TRILINOS_TEMPLATE_OBJS" = "X"; then
+ echo "$as_me:$LINENO: result: none" >&5
+echo "${ECHO_T}none" >&6
+else
+ echo "$as_me:$LINENO: result: $TRILINOS_TEMPLATE_OBJS" >&5
+echo "${ECHO_T}$TRILINOS_TEMPLATE_OBJS" >&6
+fi
 
+
+
+if test "X$EPETRA_TEMPLATE_OBJS" != "X"; then
+ { { echo "$as_me:$LINENO: error: EPETRA_TEMPLATE_OBJS is obsolete, use TRILINOS_TEMPLATE_OBJS" >&5
+echo "$as_me: error: EPETRA_TEMPLATE_OBJS is obsolete, use TRILINOS_TEMPLATE_OBJS" >&2;}
+   { (exit 1); exit 1; }; }
+fi
 
 # ------------------------------------------------------------------------
 # Checks for library functions
@@ -8903,7 +8921,7 @@ s,@HAVE_THREADS_FALSE@,$HAVE_THREADS_FALSE,;t t
 s,@FLIBS@,$FLIBS,;t t
 s,@BLAS_LIBS@,$BLAS_LIBS,;t t
 s,@LAPACK_LIBS@,$LAPACK_LIBS,;t t
-s,@EPETRA_TEMPLATE_OBJS@,$EPETRA_TEMPLATE_OBJS,;t t
+s,@TRILINOS_TEMPLATE_OBJS@,$TRILINOS_TEMPLATE_OBJS,;t t
 s,@XTRALDADD@,$XTRALDADD,;t t
 s,@ac_aux_dir@,$ac_aux_dir,;t t
 CEOF
