SUMMARY:  The name mangling for BLAS and LAPACK will now default to the value of F77_FUNC when libcheck is disabled
     BUGS:     3771

     CHECKLIST:

     1)   Did you add any source files?  no

     2)   Did you update or change the build system? yes
     2.a) Did you remember to do a bootstrap and do a 'cvs add' on the
          Makefile.am files and the Makefile.in files?  yes
     2.b) [Optional but recommended] Did you blow away the libraries and
          executables and then rebuild?  yes

     3) Did you rerun the test suite on at least the packages that you
        changed?  yes

     COMMENTS:



(checklist version 2007-06-20)

diff --git a/packages/epetra/configure b/packages/epetra/configure
--- a/packages/epetra/configure
+++ b/packages/epetra/configure
@@ -1393,8 +1393,9 @@ Optional Features:
                           (default is yes if --disable-examples is not
                           specified)
   --enable-libcheck       Check for some third-party libraries including BLAS
-                          and LAPACK. (Cannot be disabled unless tests and
-                          examples are also disabled.) (default is yes)
+                          and LAPACK. Cannot be disabled unless tests and
+                          examples are also disabled. Cannot be disabled when
+                          fortran is disabled. (default is yes)
 
 Optional Packages:
   --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
@@ -7734,39 +7735,6 @@ echo "${ECHO_T}no" >&6; }
 fi
 
 
-
-
-# Check whether --enable-fortran was given.
-if test "${enable_fortran+set}" = set; then
-  enableval=$enable_fortran; ac_cv_use_fortran=$enableval
-else
-  ac_cv_use_fortran=yes
-fi
-
-
-{ echo "$as_me:$LINENO: checking whether to use fortran" >&5
-echo $ECHO_N "checking whether to use fortran... $ECHO_C" >&6; }
-
-if test "X$ac_cv_use_fortran" != "Xno"; then
-  { echo "$as_me:$LINENO: result: yes" >&5
-echo "${ECHO_T}yes" >&6; }
-
-cat >>confdefs.h <<\_ACEOF
-#define HAVE_FORTRAN_SUPPORT 1
-_ACEOF
-
-else
-  { echo "$as_me:$LINENO: result: no" >&5
-echo "${ECHO_T}no" >&6; }
-fi
-
- if test "X$ac_cv_use_fortran" != "Xyes"; then
-  FORTRAN_DISABLED_TRUE=
-  FORTRAN_DISABLED_FALSE='#'
-else
-  FORTRAN_DISABLED_TRUE='#'
-  FORTRAN_DISABLED_FALSE=
-fi
 
 # Define F77_FUNC that will be used to link with Fortran subroutines found in
 # Trilinos source code
@@ -15080,6 +15048,68 @@ echo "$as_me: error: Cannot find lapack library, specify a path using --with-ldf
 fi
 
 
+else
+
+  if test "X$ac_cv_use_fortran" != "Xno"; then
+  # If we don't check for BLAS above, we will use F77_FUNC as the name mangling
+  # for the BLAS and LAPACK.  This is what we used before we allowed the BLAS
+  # and LAPACK to use different name mangling than the compiler.
+  ac_ext=f
+ac_compile='$F77 -c $FFLAGS conftest.$ac_ext >&5'
+ac_link='$F77 -o conftest$ac_exeext $FFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_f77_compiler_gnu
+case $ac_cv_f77_mangling in
+  upper*) ac_val="DGEMM" ;;
+  lower*) ac_val="dgemm" ;;
+  *)      ac_val="unknown" ;;
+esac
+case $ac_cv_f77_mangling in *," underscore"*) ac_val="$ac_val"_ ;; esac
+
+dgemm="$ac_val"
+
+ac_ext=cpp
+ac_cpp='$CXXCPP $CPPFLAGS'
+ac_compile='$CXX -c $CXXFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CXX -o conftest$ac_exeext $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
+
+    if test "X$dgemm" = "Xdgemm_"; then
+
+cat >>confdefs.h <<\_ACEOF
+#define F77_BLAS_MANGLE(name,NAME) name ## _
+_ACEOF
+
+    else
+      if test "X$dgemm" = "Xdgemm"; then
+
+cat >>confdefs.h <<\_ACEOF
+#define F77_BLAS_MANGLE(name,NAME) name
+_ACEOF
+
+      else
+        if test "X$dgemm" = "XDGEMM"; then
+
+cat >>confdefs.h <<\_ACEOF
+#define F77_BLAS_MANGLE(name,NAME) NAME
+_ACEOF
+
+        else
+          if test "X$dgemm" = "XDGEMM_"; then
+
+cat >>confdefs.h <<\_ACEOF
+#define F77_BLAS_MANGLE(name,NAME) NAME ## _
+_ACEOF
+
+          else
+            { { echo "$as_me:$LINENO: error: Cannot determine BLAS and LAPACK name mangling using the value of F77_FUNC.  Please try configuring Trilinos without the --disable-libcheck option." >&5
+echo "$as_me: error: Cannot determine BLAS and LAPACK name mangling using the value of F77_FUNC.  Please try configuring Trilinos without the --disable-libcheck option." >&2;}
+   { (exit 1); exit 1; }; }
+          fi
+        fi
+      fi
+    fi
+  fi
+
 fi
 # end of the list of libraries that don't need to be checked for if
 # tests and examples are disabled.
@@ -15663,13 +15693,6 @@ if test -z "${SUB_EXAMPLE_TRUE}" && test -z "${SUB_EXAMPLE_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"SUB_EXAMPLE\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"SUB_EXAMPLE\" was never defined.
-Usually this means the macro was only invoked conditionally." >&2;}
-   { (exit 1); exit 1; }; }
-fi
-if test -z "${FORTRAN_DISABLED_TRUE}" && test -z "${FORTRAN_DISABLED_FALSE}"; then
-  { { echo "$as_me:$LINENO: error: conditional \"FORTRAN_DISABLED\" was never defined.
-Usually this means the macro was only invoked conditionally." >&5
-echo "$as_me: error: conditional \"FORTRAN_DISABLED\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
