Cleaned up configure process for python and swig prior to using as template for other packages

diff --git a/packages/epetra/configure b/packages/epetra/configure
--- a/packages/epetra/configure
+++ b/packages/epetra/configure
@@ -311,7 +311,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot MPI_TEMP_CXX MPI_CXX HAVE_MPI_TRUE HAVE_MPI_FALSE MPI_CXX_EXISTS MPI_CC_EXISTS MPI_F77_EXISTS CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE F77 FFLAGS ac_ct_F77 RANLIB ac_ct_RANLIB USE_ALTERNATE_AR_TRUE USE_ALTERNATE_AR_FALSE ALTERNATE_AR CXXCPP EGREP HAVE_THREADS_TRUE HAVE_THREADS_FALSE BUILD_TESTS_TRUE BUILD_TESTS_FALSE BUILD_EXAMPLES_TRUE BUILD_EXAMPLES_FALSE PYTHON_USE_TRUE PYTHON_USE_FALSE PYTHON PYTHON_PREFIX PYTHON_EXECPREFIX PYTHON_CSPEC PYTHON_LSPEC BUILD_PYTHON_TRUE BUILD_PYTHON_FALSE WITH_SWIG HAVE_SWIG_TRUE HAVE_SWIG_FALSE GNU_HAVE_SWIG SWIG SWIG_LIB SWIG_PYTHON_OPT SWIG_PYTHON_CPPFLAGS FLIBS BLAS_LIBS LAPACK_LIBS TRILINOS_TEMPLATE_OBJS ac_aux_dir EPETRA_BUILD_DIRECTORY LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot MPI_TEMP_CXX MPI_CXX HAVE_MPI_TRUE HAVE_MPI_FALSE MPI_CXX_EXISTS MPI_CC_EXISTS MPI_F77_EXISTS CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE F77 FFLAGS ac_ct_F77 RANLIB ac_ct_RANLIB USE_ALTERNATE_AR_TRUE USE_ALTERNATE_AR_FALSE ALTERNATE_AR CXXCPP EGREP HAVE_THREADS_TRUE HAVE_THREADS_FALSE BUILD_TESTS_TRUE BUILD_TESTS_FALSE BUILD_EXAMPLES_TRUE BUILD_EXAMPLES_FALSE PYTHON_USE_TRUE PYTHON_USE_FALSE PYTHON PYTHON_PREFIX PYTHON_EXECPREFIX BUILD_PYTHON_TRUE BUILD_PYTHON_FALSE PYTHON_CSPEC PYTHON_LSPEC WITH_SWIG HAVE_SWIG_TRUE HAVE_SWIG_FALSE GNU_HAVE_SWIG SWIG SWIG_LIB SWIG_PYTHON_OPT SWIG_PYTHON_CPPFLAGS FLIBS BLAS_LIBS LAPACK_LIBS TRILINOS_TEMPLATE_OBJS ac_aux_dir EPETRA_BUILD_DIRECTORY LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -7119,7 +7119,7 @@ fi
 
 
 # ------------------------------------------------------------------------
-# Check if python interface should be created
+# Check if python wrappers should be created
 # ------------------------------------------------------------------------
 
     az_python_use=false
@@ -7457,7 +7457,25 @@ fi;
     fi
 
      # Check for --with-python, --without-python
-# if $PYTHON is not defined, then the following do nothing.
+
+echo "$as_me:$LINENO: checking whether we should build the python wrappers" >&5
+echo $ECHO_N "checking whether we should build the python wrappers... $ECHO_C" >&6
+if test -n "$PYTHON"; then
+  BUILD_PYTHON=yes
+  echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+
+
+if true; then
+  BUILD_PYTHON_TRUE=
+  BUILD_PYTHON_FALSE='#'
+else
+  BUILD_PYTHON_TRUE='#'
+  BUILD_PYTHON_FALSE=
+fi
+
+
+  # Ensure that we have python version 2.2 or greater (for distutils)
 
 
 
@@ -7510,6 +7528,8 @@ echo "$as_me: error: too old" >&2;}
     fi
 
 
+
+  # Python compiler and linker flags
 
 
     if test -n "$PYTHON"
@@ -7600,23 +7620,6 @@ _ACEOF
         { echo "$as_me:$LINENO: PYTHON_LSPEC=${az_python_output}" >&5
 echo "$as_me: PYTHON_LSPEC=${az_python_output}" >&6;}
     fi
-
-
-echo "$as_me:$LINENO: checking whether we should build the python support" >&5
-echo $ECHO_N "checking whether we should build the python support... $ECHO_C" >&6
-if test -n "$PYTHON"; then
-  BUILD_PYTHON=yes
-  echo "$as_me:$LINENO: result: yes" >&5
-echo "${ECHO_T}yes" >&6
-
-
-if true; then
-  BUILD_PYTHON_TRUE=
-  BUILD_PYTHON_FALSE='#'
-else
-  BUILD_PYTHON_TRUE='#'
-  BUILD_PYTHON_FALSE=
-fi
 
 
   # Check that Python.h is available
@@ -7826,23 +7829,29 @@ fi
 fi
 
 # ------------------------------------------------------------------------
-# Configure swig
+# If the python wrappers are to be built, then SWIG (Simple Wrapper
+# Interface Generator) is required
 # ------------------------------------------------------------------------
 
-# Check for --with-swig[=path]
+if test -n "$PYTHON"; then
+
+  # Check for --with-swig[=path]
+  echo "$as_me:$LINENO: checking for --with-swig" >&5
+echo $ECHO_N "checking for --with-swig... $ECHO_C" >&6
 
 # Check whether --with-swig or --without-swig was given.
 if test "${with_swig+set}" = set; then
   withval="$with_swig"
-  WITH_SWIG=yes
-	     if test X${withval} != Xyes ; then
-	     	SWIG=$withval
-	     fi
-fi;
-
-# If --with-swig not present, check for swig in standard path
-if test X${WITH_SWIG} != Xyes; then
-  # Extract the first word of "swig", so it can be a program name with args.
+  echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+	       WITH_SWIG=yes
+	       if test X${withval} != Xyes ; then
+	     	 SWIG=$withval
+	       fi
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+	       # Extract the first word of "swig", so it can be a program name with args.
 set dummy swig; ac_word=$2
 echo "$as_me:$LINENO: checking for $ac_word" >&5
 echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
@@ -7878,12 +7887,16 @@ else
 echo "${ECHO_T}no" >&6
 fi
 
-fi
+fi;
 
-echo "$as_me:$LINENO: checking whether we should enable swig support" >&5
-echo $ECHO_N "checking whether we should enable swig support... $ECHO_C" >&6
-echo "$as_me:$LINENO: result: ${WITH_SWIG}" >&5
-echo "${ECHO_T}${WITH_SWIG}" >&6
+  # Report error if no swig found
+  if test ${WITH_SWIG} = no; then
+     { { echo "$as_me:$LINENO: error: Python wrappers require swig (Simple Wrapper Interface Generator).
+      See http://www.swig.org" >&5
+echo "$as_me: error: Python wrappers require swig (Simple Wrapper Interface Generator).
+      See http://www.swig.org" >&2;}
+   { (exit 1); exit 1; }; }
+  fi
 
 
 if test X${WITH_SWIG} = Xyes; then
@@ -7894,10 +7907,10 @@ else
   HAVE_SWIG_FALSE=
 fi
 
-GNU_HAVE_SWIG=${WITH_SWIG}
+  GNU_HAVE_SWIG=${WITH_SWIG}
 
 
-if test -n "$PYTHON" && test X${WITH_SWIG} = Xyes; then
+  # SWIG configuration
 
 	if test -z "$SWIG"; then
         	# Extract the first word of "swig", so it can be a program name with args.
@@ -8125,7 +8138,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_verb"
-(eval echo $as_me:8128: \"$ac_link\") >&5
+(eval echo $as_me:8141: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
@@ -8203,7 +8216,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_cv_prog_f77_v"
-(eval echo $as_me:8206: \"$ac_link\") >&5
+(eval echo $as_me:8219: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
@@ -11078,7 +11091,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_verb"
-(eval echo $as_me:11081: \"$ac_link\") >&5
+(eval echo $as_me:11094: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
@@ -11156,7 +11169,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_cv_prog_f77_v"
-(eval echo $as_me:11159: \"$ac_link\") >&5
+(eval echo $as_me:11172: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
@@ -12299,10 +12312,10 @@ s,@PYTHON_USE_FALSE@,$PYTHON_USE_FALSE,;t t
 s,@PYTHON@,$PYTHON,;t t
 s,@PYTHON_PREFIX@,$PYTHON_PREFIX,;t t
 s,@PYTHON_EXECPREFIX@,$PYTHON_EXECPREFIX,;t t
-s,@PYTHON_CSPEC@,$PYTHON_CSPEC,;t t
-s,@PYTHON_LSPEC@,$PYTHON_LSPEC,;t t
 s,@BUILD_PYTHON_TRUE@,$BUILD_PYTHON_TRUE,;t t
 s,@BUILD_PYTHON_FALSE@,$BUILD_PYTHON_FALSE,;t t
+s,@PYTHON_CSPEC@,$PYTHON_CSPEC,;t t
+s,@PYTHON_LSPEC@,$PYTHON_LSPEC,;t t
 s,@WITH_SWIG@,$WITH_SWIG,;t t
 s,@HAVE_SWIG_TRUE@,$HAVE_SWIG_TRUE,;t t
 s,@HAVE_SWIG_FALSE@,$HAVE_SWIG_FALSE,;t t
