SUMMARY:   Switching the ordering of two configure checks
     BUGS:

     CHECKLIST:

     1)   Did you add any source files?  no

     2)   Did you update or change the build system?  yes
     2.a) Did you remember to do a bootstrap and do a 'cvs add' on the
          Makefile.am files and the Makefile.in files?  yes
     2.b) [Optional but recommended] Did you blow away the libraries and
          executables and then rebuild?  yes

     3) Did you rerun the test suite on at least the packages that you
        changed?  yes

     COMMENTS:

     After modifying the mpi config macro, the check for fortran needs to
     occur before the call to the new version of the macro.

(checklist version 2007-06-20)

diff --git a/packages/epetra/configure b/packages/epetra/configure
--- a/packages/epetra/configure
+++ b/packages/epetra/configure
@@ -689,6 +689,8 @@ am__leading_dot
 AMTAR
 am__tar
 am__untar
+FORTRAN_DISABLED_TRUE
+FORTRAN_DISABLED_FALSE
 MPI_TEMP_CXX
 MPI_CXX
 HAVE_MPI_TRUE
@@ -696,8 +698,6 @@ HAVE_MPI_FALSE
 MPI_CXX_EXISTS
 MPI_CC_EXISTS
 MPI_F77_EXISTS
-FORTRAN_DISABLED_TRUE
-FORTRAN_DISABLED_FALSE
 CC
 CFLAGS
 LDFLAGS
@@ -1355,8 +1355,8 @@ Optional Features:
   --enable-FEATURE[=ARG]  include FEATURE [ARG=yes]
   --enable-maintainer-mode  enable make rules and dependencies not useful
 			  (and sometimes confusing) to the casual installer
-  --enable-mpi            MPI support
   --enable-fortran        enable Fortran support (default is yes)
+  --enable-mpi            MPI support
   --disable-dependency-tracking  speeds up one-time build
   --enable-dependency-tracking   do not reject slow dependency extractors
   --enable-export-makefiles
@@ -2653,6 +2653,44 @@ echo "${ECHO_T}$am_cv_prog_tar_ustar" >&6; }
 
 
 # ------------------------------------------------------------------------
+# Check if Fortran is enabled or not
+# ------------------------------------------------------------------------
+
+
+# Check whether --enable-fortran was given.
+if test "${enable_fortran+set}" = set; then
+  enableval=$enable_fortran; ac_cv_use_fortran=$enableval
+else
+  ac_cv_use_fortran=yes
+fi
+
+
+{ echo "$as_me:$LINENO: checking whether to use fortran" >&5
+echo $ECHO_N "checking whether to use fortran... $ECHO_C" >&6; }
+
+if test "X$ac_cv_use_fortran" != "Xno"; then
+  { echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6; }
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_FORTRAN_SUPPORT 1
+_ACEOF
+
+else
+  { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+fi
+
+ if test "X$ac_cv_use_fortran" != "Xyes"; then
+  FORTRAN_DISABLED_TRUE=
+  FORTRAN_DISABLED_FALSE='#'
+else
+  FORTRAN_DISABLED_TRUE='#'
+  FORTRAN_DISABLED_FALSE=
+fi
+
+
+# ------------------------------------------------------------------------
 # Check to see if MPI enabled and if any special configuration done
 # ------------------------------------------------------------------------
 
@@ -3042,44 +3080,6 @@ echo "$as_me: error: MPI Fortran 77 compiler (${MPI_F77}) not found." >&2;}
 fi
 
 fi
-
-# ------------------------------------------------------------------------
-# Check if Fortran is enabled or not
-# ------------------------------------------------------------------------
-
-
-# Check whether --enable-fortran was given.
-if test "${enable_fortran+set}" = set; then
-  enableval=$enable_fortran; ac_cv_use_fortran=$enableval
-else
-  ac_cv_use_fortran=yes
-fi
-
-
-{ echo "$as_me:$LINENO: checking whether to use fortran" >&5
-echo $ECHO_N "checking whether to use fortran... $ECHO_C" >&6; }
-
-if test "X$ac_cv_use_fortran" != "Xno"; then
-  { echo "$as_me:$LINENO: result: yes" >&5
-echo "${ECHO_T}yes" >&6; }
-
-cat >>confdefs.h <<\_ACEOF
-#define HAVE_FORTRAN_SUPPORT 1
-_ACEOF
-
-else
-  { echo "$as_me:$LINENO: result: no" >&5
-echo "${ECHO_T}no" >&6; }
-fi
-
- if test "X$ac_cv_use_fortran" != "Xyes"; then
-  FORTRAN_DISABLED_TRUE=
-  FORTRAN_DISABLED_FALSE='#'
-else
-  FORTRAN_DISABLED_TRUE='#'
-  FORTRAN_DISABLED_FALSE=
-fi
-
 
 # ------------------------------------------------------------------------
 # Checks for programs
@@ -15554,17 +15554,17 @@ echo "$as_me: error: conditional \"MAINTAINER_MODE\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
-if test -z "${HAVE_MPI_TRUE}" && test -z "${HAVE_MPI_FALSE}"; then
-  { { echo "$as_me:$LINENO: error: conditional \"HAVE_MPI\" was never defined.
-Usually this means the macro was only invoked conditionally." >&5
-echo "$as_me: error: conditional \"HAVE_MPI\" was never defined.
-Usually this means the macro was only invoked conditionally." >&2;}
-   { (exit 1); exit 1; }; }
-fi
 if test -z "${FORTRAN_DISABLED_TRUE}" && test -z "${FORTRAN_DISABLED_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"FORTRAN_DISABLED\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"FORTRAN_DISABLED\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${HAVE_MPI_TRUE}" && test -z "${HAVE_MPI_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"HAVE_MPI\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"HAVE_MPI\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -16336,6 +16336,8 @@ am__leading_dot!$am__leading_dot$ac_delim
 AMTAR!$AMTAR$ac_delim
 am__tar!$am__tar$ac_delim
 am__untar!$am__untar$ac_delim
+FORTRAN_DISABLED_TRUE!$FORTRAN_DISABLED_TRUE$ac_delim
+FORTRAN_DISABLED_FALSE!$FORTRAN_DISABLED_FALSE$ac_delim
 MPI_TEMP_CXX!$MPI_TEMP_CXX$ac_delim
 MPI_CXX!$MPI_CXX$ac_delim
 HAVE_MPI_TRUE!$HAVE_MPI_TRUE$ac_delim
@@ -16343,8 +16345,6 @@ HAVE_MPI_FALSE!$HAVE_MPI_FALSE$ac_delim
 MPI_CXX_EXISTS!$MPI_CXX_EXISTS$ac_delim
 MPI_CC_EXISTS!$MPI_CC_EXISTS$ac_delim
 MPI_F77_EXISTS!$MPI_F77_EXISTS$ac_delim
-FORTRAN_DISABLED_TRUE!$FORTRAN_DISABLED_TRUE$ac_delim
-FORTRAN_DISABLED_FALSE!$FORTRAN_DISABLED_FALSE$ac_delim
 CC!$CC$ac_delim
 CFLAGS!$CFLAGS$ac_delim
 LDFLAGS!$LDFLAGS$ac_delim
