Upgraded all Trilinos packages that have python wrappers to interface with python module numpy rather than Numeric.  The numpy module homepage is
  http://numeric.scipy.org/

and can be downloaded from

  http://sourceforge.net/project/showfiles.php?group_id=1369&package_id=175103

Numeric is now obsolete and all new development in the scientific
python community for multidimensional, homogeneous, contiguous
arrays is done in numpy.  All python interfaces to Trilinos
packages are now numpy-compatible and no longer Numeric-
compatible.

Only the PyTrilinos and Epetra packages directly interface to
numpy, although all other packages with python interfaces depend
on these two packages.  Therefore, the configuration check for
Numeric has been removed from all packages and new configuration
checks for numpy have been aded to PyTrilinos and Epetra only.

The Epetra python wrappers make use of numpy.lib.UserArray, which
first became available in numpy version 0.9.6, first available 14
Mar 2006.  The configure script for epetra specifically checks
for this module.

All test and example python scripts that used to import from
Numeric now import from numpy.

diff --git a/packages/epetra/configure b/packages/epetra/configure
--- a/packages/epetra/configure
+++ b/packages/epetra/configure
@@ -1775,7 +1775,7 @@ else
 echo "$as_me: WARNING: \`missing' script is too old or missing" >&2;}
 fi
 
-if mkdir -p -- . 2>/dev/null; then
+if mkdir -p --version . >/dev/null 2>&1 && test ! -d ./--version; then
   # Keeping the `.' argument allows $(mkdir_p) to be used without
   # argument.  Indeed, we sometimes output rules like
   #   $(mkdir_p) $(somedir)
@@ -1788,7 +1788,7 @@ else
   # recognize any option.  It will interpret all options as
   # directories to create, and then abort because `.' already
   # exists.
-  for d in ./-p ./--;
+  for d in ./-p ./--version;
   do
     test -d $d && rmdir $d
   done
@@ -3236,7 +3236,9 @@ else
     : > sub/conftest.c
     for i in 1 2 3 4 5 6; do
       echo '#include "conftst'$i'.h"' >> sub/conftest.c
-      : > sub/conftst$i.h
+      # Using `: > sub/conftst$i.h' creates only sub/conftst1.h with
+      # Solaris 8's {/usr,}/bin/sh.
+      touch sub/conftst$i.h
     done
     echo "${am__include} ${am__quote}sub/conftest.Po${am__quote}" > confmf
 
@@ -3264,9 +3266,14 @@ else
        grep sub/conftest.${OBJEXT-o} sub/conftest.Po > /dev/null 2>&1 &&
        ${MAKE-make} -s -f confmf > /dev/null 2>&1; then
       # icc doesn't choke on unknown options, it will just issue warnings
-      # (even with -Werror).  So we grep stderr for any message
-      # that says an option was ignored.
-      if grep 'ignoring option' conftest.err >/dev/null 2>&1; then :; else
+      # or remarks (even with -Werror).  So we grep stderr for any message
+      # that says an option was ignored or not supported.
+      # When given -MP, icc 7.0 and 7.1 complain thusly:
+      #   icc: Command line warning: ignoring option '-M'; no argument required
+      # The diagnosis changed in icc 8.0:
+      #   icc: Command line remark: option '-MP' not supported
+      if (grep 'ignoring option' conftest.err ||
+          grep 'not supported' conftest.err) >/dev/null 2>&1; then :; else
         am_cv_CC_dependencies_compiler_type=$depmode
         break
       fi
@@ -3693,7 +3700,9 @@ else
     : > sub/conftest.c
     for i in 1 2 3 4 5 6; do
       echo '#include "conftst'$i'.h"' >> sub/conftest.c
-      : > sub/conftst$i.h
+      # Using `: > sub/conftst$i.h' creates only sub/conftst1.h with
+      # Solaris 8's {/usr,}/bin/sh.
+      touch sub/conftst$i.h
     done
     echo "${am__include} ${am__quote}sub/conftest.Po${am__quote}" > confmf
 
@@ -3721,9 +3730,14 @@ else
        grep sub/conftest.${OBJEXT-o} sub/conftest.Po > /dev/null 2>&1 &&
        ${MAKE-make} -s -f confmf > /dev/null 2>&1; then
       # icc doesn't choke on unknown options, it will just issue warnings
-      # (even with -Werror).  So we grep stderr for any message
-      # that says an option was ignored.
-      if grep 'ignoring option' conftest.err >/dev/null 2>&1; then :; else
+      # or remarks (even with -Werror).  So we grep stderr for any message
+      # that says an option was ignored or not supported.
+      # When given -MP, icc 7.0 and 7.1 complain thusly:
+      #   icc: Command line warning: ignoring option '-M'; no argument required
+      # The diagnosis changed in icc 8.0:
+      #   icc: Command line remark: option '-MP' not supported
+      if (grep 'ignoring option' conftest.err ||
+          grep 'not supported' conftest.err) >/dev/null 2>&1; then :; else
         am_cv_CXX_dependencies_compiler_type=$depmode
         break
       fi
@@ -3846,7 +3860,7 @@ fi
 
 
 # Provide some information about the compiler.
-echo "$as_me:3849:" \
+echo "$as_me:3863:" \
      "checking for Fortran 77 compiler version" >&5
 ac_compiler=`set X $ac_compile; echo $2`
 { (eval echo "$as_me:$LINENO: \"$ac_compiler --version </dev/null >&5\"") >&5
@@ -8058,30 +8072,121 @@ fi
 
   CPPFLAGS="$save_CPPFLAGS"
 
-  # Check for Numeric
+  # Check for numpy python module
 
-	echo "$as_me:$LINENO: checking python module: Numeric" >&5
-echo $ECHO_N "checking python module: Numeric... $ECHO_C" >&6
-	python -c "import Numeric" 2>/dev/null
+	echo "$as_me:$LINENO: checking python module: numpy" >&5
+echo $ECHO_N "checking python module: numpy... $ECHO_C" >&6
+	python -c "import numpy" 2>/dev/null
 	if test $? -eq 0;
 	then
 		echo "$as_me:$LINENO: result: yes" >&5
 echo "${ECHO_T}yes" >&6
-		eval HAVE_PYMOD_NUMERIC=yes
+		eval HAVE_PYMOD_NUMPY=yes
 	else
 		echo "$as_me:$LINENO: result: no" >&5
 echo "${ECHO_T}no" >&6
-		eval HAVE_PYMOD_NUMERIC=no
+		eval HAVE_PYMOD_NUMPY=no
 		#
 		if test -n "yes"
 		then
-			{ { echo "$as_me:$LINENO: error: failed to find required module Numeric" >&5
-echo "$as_me: error: failed to find required module Numeric" >&2;}
+			{ { echo "$as_me:$LINENO: error: failed to find required module numpy" >&5
+echo "$as_me: error: failed to find required module numpy" >&2;}
    { (exit 1); exit 1; }; }
 			exit 1
 		fi
 	fi
 
+
+	echo "$as_me:$LINENO: checking python module: numpy.lib.UserArray" >&5
+echo $ECHO_N "checking python module: numpy.lib.UserArray... $ECHO_C" >&6
+	python -c "import numpy.lib.UserArray" 2>/dev/null
+	if test $? -eq 0;
+	then
+		echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+		eval HAVE_PYMOD_NUMPY_LIB_USERARRAY=yes
+	else
+		echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+		eval HAVE_PYMOD_NUMPY_LIB_USERARRAY=no
+		#
+		if test -n "yes"
+		then
+			{ { echo "$as_me:$LINENO: error: failed to find required module numpy.lib.UserArray" >&5
+echo "$as_me: error: failed to find required module numpy.lib.UserArray" >&2;}
+   { (exit 1); exit 1; }; }
+			exit 1
+		fi
+	fi
+
+
+  # Check that numpy/arrayobject.h is available
+  save_CPPFLAGS=$CPPFLAGS
+  CPPFLAGS="$save_CPPFLAGS $PYTHON_CSPEC"
+  ac_ext=cc
+ac_cpp='$CXXCPP $CPPFLAGS'
+ac_compile='$CXX -c $CXXFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CXX -o conftest$ac_exeext $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
+
+  echo "$as_me:$LINENO: checking for numpy/arrayobject.h" >&5
+echo $ECHO_N "checking for numpy/arrayobject.h... $ECHO_C" >&6
+if test "${ac_cv_header_numpy_arrayobject_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <Python.h>
+
+#include <numpy/arrayobject.h>
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_cxx_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_header_numpy_arrayobject_h=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_header_numpy_arrayobject_h=no
+fi
+rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
+fi
+echo "$as_me:$LINENO: result: $ac_cv_header_numpy_arrayobject_h" >&5
+echo "${ECHO_T}$ac_cv_header_numpy_arrayobject_h" >&6
+if test $ac_cv_header_numpy_arrayobject_h = yes; then
+  break
+else
+  { { echo "$as_me:$LINENO: error: numpy/arrayobject.h not found" >&5
+echo "$as_me: error: numpy/arrayobject.h not found" >&2;}
+   { (exit 1); exit 1; }; }
+fi
+
+
+  CPPFLAGS="$save_CPPFLAGS"
 
   # If user specifies prefix, use it for the PYTHON_PREFIX
   if test "$prefix" != "$ac_default_prefix"; then
@@ -8419,7 +8524,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_verb"
-(eval echo $as_me:8422: \"$ac_link\") >&5
+(eval echo $as_me:8527: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
@@ -8497,7 +8602,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_cv_prog_f77_v"
-(eval echo $as_me:8500: \"$ac_link\") >&5
+(eval echo $as_me:8605: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
@@ -11391,7 +11496,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_verb"
-(eval echo $as_me:11394: \"$ac_link\") >&5
+(eval echo $as_me:11499: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
@@ -11469,7 +11574,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_cv_prog_f77_v"
-(eval echo $as_me:11472: \"$ac_link\") >&5
+(eval echo $as_me:11577: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
@@ -13317,14 +13422,14 @@ echo X"$mf" |
   grep '^DEP_FILES *= *[^ #]' < "$mf" > /dev/null || continue
   # Extract the definition of DEP_FILES from the Makefile without
   # running `make'.
-  DEPDIR=`sed -n -e '/^DEPDIR = / s///p' < "$mf"`
+  DEPDIR=`sed -n 's/^DEPDIR = //p' < "$mf"`
   test -z "$DEPDIR" && continue
   # When using ansi2knr, U may be empty or an underscore; expand it
-  U=`sed -n -e '/^U = / s///p' < "$mf"`
+  U=`sed -n 's/^U = //p' < "$mf"`
   test -d "$dirpart/$DEPDIR" || mkdir "$dirpart/$DEPDIR"
   # We invoke sed twice because it is the simplest approach to
   # changing $(DEPDIR) to its actual value in the expansion.
-  for file in `sed -n -e '
+  for file in `sed -n '
     /^DEP_FILES = .*\\\\$/ {
       s/^DEP_FILES = //
       :loop
