----------------------------------------------------------------------
Committing in .

Modified Files:
	packages/triutils/Makefile.in packages/triutils/aclocal.m4
	packages/triutils/configure packages/triutils/configure.ac
	packages/triutils/src/Makefile.am
	packages/triutils/src/Makefile.in
	packages/triutils/src/Trilinos_Util.h
	packages/triutils/src/Triutils_config.h.in
	testharness/checkin-test-harness
Added Files:
	packages/triutils/src/Trilinos_Util_ShellOptions.cpp
----------------------------------------------------------------------
Bug 493

Adding Marzio's ShellOptions class to Triutils.

I still have to test the portablity of the code.

diff --git a/packages/triutils/configure b/packages/triutils/configure
--- a/packages/triutils/configure
+++ b/packages/triutils/configure
@@ -4494,7 +4494,9 @@ done
 
 
 
-for ac_header in cstdlib stdlib.h cstdio stdio.h
+
+
+for ac_header in cstdlib stdlib.h cstdio stdio.h iostream iostream.h
 do
 as_ac_Header=`echo "ac_cv_header_$ac_header" | $as_tr_sh`
 if eval "test \"\${$as_ac_Header+set}\" = set"; then
@@ -4639,7 +4641,9 @@ done
 
 
 
-for ac_header in cmath math.h string string.h
+
+
+for ac_header in cmath math.h string string.h map map.h
 do
 as_ac_Header=`echo "ac_cv_header_$ac_header" | $as_tr_sh`
 if eval "test \"\${$as_ac_Header+set}\" = set"; then
@@ -4938,6 +4942,18 @@ fi
 if test "X$ac_cv_header_string" != "Xyes" && test "X$ac_cv_header_string_h" != "Xyes"; then
   { { echo "$as_me:$LINENO: error: Cannot find string or string.h.  Triutils requires at least one or the other." >&5
 echo "$as_me: error: Cannot find string or string.h.  Triutils requires at least one or the other." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+
+if test "X$ac_cv_header_iostream" != "Xyes" && test "X$ac_cv_header_iostream_h" != "Xyes"; then
+  { { echo "$as_me:$LINENO: error: Cannot find iostream or iostream.h.  Triutils requires at least one or the other." >&5
+echo "$as_me: error: Cannot find iostream or iostream.h.  Triutils requires at least one or the other." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+
+if test "X$ac_cv_header_map" != "Xyes" && test "X$ac_cv_header_map_h" != "Xyes"; then
+  { { echo "$as_me:$LINENO: error: Cannot find map or map.h.  Triutils requires at least one or the other." >&5
+echo "$as_me: error: Cannot find map or map.h.  Triutils requires at least one or the other." >&2;}
    { (exit 1); exit 1; }; }
 fi
 
@@ -5682,7 +5698,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_verb"
-(eval echo $as_me:5685: \"$ac_link\") >&5
+(eval echo $as_me:5701: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
@@ -5762,7 +5778,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_cv_prog_f77_v"
-(eval echo $as_me:5765: \"$ac_link\") >&5
+(eval echo $as_me:5781: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
@@ -8126,7 +8142,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_verb"
-(eval echo $as_me:8129: \"$ac_link\") >&5
+(eval echo $as_me:8145: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
@@ -8206,7 +8222,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_cv_prog_f77_v"
-(eval echo $as_me:8209: \"$ac_link\") >&5
+(eval echo $as_me:8225: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
