----------------------------------------------------------------------
 Committing in .

 Modified Files:
 	configure configure.ac src/Kokkos_BaseSparseMultiply.hpp
 	src/Kokkos_BaseSparseSolve.hpp src/Kokkos_CisMatrix.hpp
 	src/Kokkos_CompObject.hpp src/Kokkos_ConfigDefs.hpp
 	src/Kokkos_DenseMultiVector.hpp src/Kokkos_DenseVector.hpp
 	src/Kokkos_Flops.hpp src/Kokkos_HbMatrix.hpp
 	src/Kokkos_MultiVector.hpp src/Kokkos_PackedSparseMultiply.hpp
 	src/Kokkos_Permutation.hpp src/Kokkos_SparseOperation.hpp
 	src/Kokkos_Time.hpp src/Kokkos_Vector.hpp
 	src/Kokkos_Version.cpp src/Kokkos_config.h.in
 	test/BaseSparseMultiply/GenerateHbProblem.hpp
 	test/BaseSparseMultiply/cxx_main.cpp
 	test/BaseSparseSolve/cxx_main.cpp
 	test/DenseMultiVector/cxx_main.cpp
 	test/HbMatrix/GenerateHbProblem.hpp test/HbMatrix/cxx_main.cpp
 	test/Permutation/cxx_main.cpp
 ----------------------------------------------------------------------

Cleaned up/added copyright notices (I thought I was done with that).

I removed a lot of #includes and added more header checks to the configure
process and used the centralized #include method.

This problem was brought to my attention by a failure on Atlantis.

Everything configures and builds cleanly on Linux.

diff --git a/packages/kokkos/configure b/packages/kokkos/configure
--- a/packages/kokkos/configure
+++ b/packages/kokkos/configure
@@ -4893,7 +4893,11 @@ done
 
 
 
-for ac_header in string string.h
+
+
+
+
+for ac_header in string string.h cassert assert.h iostream iostream.h
 do
 as_ac_Header=`echo "ac_cv_header_$ac_header" | $as_tr_sh`
 if eval "test \"\${$as_ac_Header+set}\" = set"; then
@@ -5052,6 +5056,18 @@ fi
 if test "X$ac_cv_header_string" != "Xyes" && test "X$ac_cv_header_string_h" != "Xyes"; then
   { { echo "$as_me:$LINENO: error: Cannot find string or string.h.  Kokkos requires at least one or the other." >&5
 echo "$as_me: error: Cannot find string or string.h.  Kokkos requires at least one or the other." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+
+if test "X$ac_cv_header_cassert" != "Xyes" && test "X$ac_cv_header_assert_h" != "Xyes"; then
+  { { echo "$as_me:$LINENO: error: Cannot find cassert or assert.h.  Kokkos requires at least one or the other." >&5
+echo "$as_me: error: Cannot find cassert or assert.h.  Kokkos requires at least one or the other." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+
+if test "X$ac_cv_header_iostream" != "Xyes" && test "X$ac_cv_header_iostream_h" != "Xyes"; then
+  { { echo "$as_me:$LINENO: error: Cannot find iostream or iostream.h.  Kokkos requires at least one or the other." >&5
+echo "$as_me: error: Cannot find iostream or iostream.h.  Kokkos requires at least one or the other." >&2;}
    { (exit 1); exit 1; }; }
 fi
 
@@ -5965,7 +5981,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_verb"
-(eval echo $as_me:5968: \"$ac_link\") >&5
+(eval echo $as_me:5984: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
@@ -6043,7 +6059,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_cv_prog_f77_v"
-(eval echo $as_me:6046: \"$ac_link\") >&5
+(eval echo $as_me:6062: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
@@ -8416,7 +8432,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_verb"
-(eval echo $as_me:8419: \"$ac_link\") >&5
+(eval echo $as_me:8435: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
@@ -8494,7 +8510,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_cv_prog_f77_v"
-(eval echo $as_me:8497: \"$ac_link\") >&5
+(eval echo $as_me:8513: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
