Fixed bug 2791: check for numpy module uses proper python

diff --git a/packages/PyTrilinos/configure b/packages/PyTrilinos/configure
--- a/packages/PyTrilinos/configure
+++ b/packages/PyTrilinos/configure
@@ -934,6 +934,8 @@ Optional Features:
                           yes)
   --enable-pytrilinos-examples
                           Enable PyTrilinos examples (default is )
+  --enable-python[=PYTHON]
+                          absolute path name of Python executable
 
 Optional Packages:
   --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
@@ -4415,6 +4417,167 @@ fi;
 
 
     # unless PYTHON was supplied to us (as a precious variable),
+    # see if --enable-python[=PythonExecutablePath], --enable-python,
+    # --disable-python or --enable-python=no was given.
+    if test -z "$PYTHON"
+    then
+        echo "$as_me:$LINENO: checking for --enable-python" >&5
+echo $ECHO_N "checking for --enable-python... $ECHO_C" >&6
+        # Check whether --enable-python or --disable-python was given.
+if test "${enable_python+set}" = set; then
+  enableval="$enable_python"
+
+                if test "$enableval" = "yes"
+                then
+                    # "yes" was specified, but we don't have a path
+                    # for the executable.
+                    # So, let's searth the PATH Environment Variable.
+                    echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+                    # Extract the first word of "python", so it can be a program name with args.
+set dummy python; ac_word=$2
+echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_path_PYTHON+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  case $PYTHON in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_PYTHON="$PYTHON" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_path_PYTHON="$as_dir/$ac_word$ac_exec_ext"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+
+  ;;
+esac
+fi
+PYTHON=$ac_cv_path_PYTHON
+
+if test -n "$PYTHON"; then
+  echo "$as_me:$LINENO: result: $PYTHON" >&5
+echo "${ECHO_T}$PYTHON" >&6
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+                    if test -z "$PYTHON"
+                    then
+                        { { echo "$as_me:$LINENO: error: no path to python found" >&5
+echo "$as_me: error: no path to python found" >&2;}
+   { (exit 1); exit 1; }; }
+                    fi
+                    az_python_use=true
+
+
+if test x"$az_python_use" = x"true"; then
+  PYTHON_USE_TRUE=
+  PYTHON_USE_FALSE='#'
+else
+  PYTHON_USE_TRUE='#'
+  PYTHON_USE_FALSE=
+fi
+
+
+    if test -z "$PYTHON"
+    then
+        { { echo "$as_me:$LINENO: error: Python Executable Path is not known" >&5
+echo "$as_me: error: Python Executable Path is not known" >&2;}
+   { (exit 1); exit 1; }; }
+    fi
+    ax_python_prefix=`${PYTHON} -c "import sys; print sys.prefix"`
+    ax_python_execprefix=`${PYTHON} -c "import sys; print sys.exec_prefix"`
+    PYTHON_PREFIX="${ax_python_prefix}"
+
+    PYTHON_EXECPREFIX="${ax_python_execprefix}"
+
+
+                elif test "$enableval" = "no"
+                then
+                    echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+                    az_python_use=false
+
+
+if test x"$az_python_use" = x"true"; then
+  PYTHON_USE_TRUE=
+  PYTHON_USE_FALSE='#'
+else
+  PYTHON_USE_TRUE='#'
+  PYTHON_USE_FALSE=
+fi
+
+                else
+                    # $enableval must be the executable path then.
+                    PYTHON="${enableval}"
+
+                    echo "$as_me:$LINENO: result: $withval" >&5
+echo "${ECHO_T}$withval" >&6
+                    az_python_use=true
+
+
+if test x"$az_python_use" = x"true"; then
+  PYTHON_USE_TRUE=
+  PYTHON_USE_FALSE='#'
+else
+  PYTHON_USE_TRUE='#'
+  PYTHON_USE_FALSE=
+fi
+
+
+    if test -z "$PYTHON"
+    then
+        { { echo "$as_me:$LINENO: error: Python Executable Path is not known" >&5
+echo "$as_me: error: Python Executable Path is not known" >&2;}
+   { (exit 1); exit 1; }; }
+    fi
+    ax_python_prefix=`${PYTHON} -c "import sys; print sys.prefix"`
+    ax_python_execprefix=`${PYTHON} -c "import sys; print sys.exec_prefix"`
+    PYTHON_PREFIX="${ax_python_prefix}"
+
+    PYTHON_EXECPREFIX="${ax_python_execprefix}"
+
+
+                fi
+
+else
+
+                # --with-python was not specified.
+                echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+                az_python_use=false
+
+
+if test x"$az_python_use" = x"true"; then
+  PYTHON_USE_TRUE=
+  PYTHON_USE_FALSE='#'
+else
+  PYTHON_USE_TRUE='#'
+  PYTHON_USE_FALSE=
+fi
+
+
+
+fi;
+    fi
+
+   # Check for --enable-python, --disable-python
+
+
+
+    # unless PYTHON was supplied to us (as a precious variable),
     # see if --with-python[=PythonExecutablePath], --with-python,
     # --without-python or --with-python=no was given.
     if test -z "$PYTHON"
@@ -4573,19 +4736,9 @@ fi;
     fi
 
      # Check for --with-python, --without-python
-az_python_use=true
 
 
-if test x"$az_python_use" = x"true"; then
-  PYTHON_USE_TRUE=
-  PYTHON_USE_FALSE='#'
-else
-  PYTHON_USE_TRUE='#'
-  PYTHON_USE_FALSE=
-fi
-
-
-# Extract the first word of "python", so it can be a program name with args.
+    # Extract the first word of "python", so it can be a program name with args.
 set dummy python; ac_word=$2
 echo "$as_me:$LINENO: checking for $ac_word" >&5
 echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
@@ -4624,6 +4777,25 @@ else
 echo "${ECHO_T}no" >&6
 fi
 
+    if test -z "$PYTHON"
+    then
+        { { echo "$as_me:$LINENO: error: Python Executable not found" >&5
+echo "$as_me: error: Python Executable not found" >&2;}
+   { (exit 1); exit 1; }; }
+    else
+        az_python_use=true
+    fi
+
+
+if test "$az_python_use" = "true"; then
+  PYTHON_USE_TRUE=
+  PYTHON_USE_FALSE='#'
+else
+  PYTHON_USE_TRUE='#'
+  PYTHON_USE_FALSE=
+fi
+
+     # Look for python assuming none has been previously found
 
 if test -z "$PYTHON"; then
    { { echo "$as_me:$LINENO: error: no path to python found" >&5
@@ -5206,7 +5378,7 @@ CPPFLAGS="$save_CPPFLAGS"
 
 	echo "$as_me:$LINENO: checking python module: numpy" >&5
 echo $ECHO_N "checking python module: numpy... $ECHO_C" >&6
-	python -c "import numpy" 2>/dev/null
+	$PYTHON -c "import numpy" 2>/dev/null
 	if test $? -eq 0;
 	then
 		echo "$as_me:$LINENO: result: yes" >&5
@@ -5229,7 +5401,7 @@ echo "$as_me: error: failed to find required module numpy" >&2;}
 
 	echo "$as_me:$LINENO: checking python module: numpy.lib.user_array" >&5
 echo $ECHO_N "checking python module: numpy.lib.user_array... $ECHO_C" >&6
-	python -c "import numpy.lib.user_array" 2>/dev/null
+	$PYTHON -c "import numpy.lib.user_array" 2>/dev/null
 	if test $? -eq 0;
 	then
 		echo "$as_me:$LINENO: result: yes" >&5
@@ -5253,7 +5425,7 @@ if test "X$HAVE_PYMOD_NUMPY_LIB_USER_ARRAY" == "Xno"; then
 
 	echo "$as_me:$LINENO: checking python module: numpy.lib.UserArray" >&5
 echo $ECHO_N "checking python module: numpy.lib.UserArray... $ECHO_C" >&6
-	python -c "import numpy.lib.UserArray" 2>/dev/null
+	$PYTHON -c "import numpy.lib.UserArray" 2>/dev/null
 	if test $? -eq 0;
 	then
 		echo "$as_me:$LINENO: result: yes" >&5
@@ -5739,6 +5911,34 @@ if test -z "${BUILD_EXAMPLES_TRUE}" && test -z "${BUILD_EXAMPLES_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"BUILD_EXAMPLES\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"BUILD_EXAMPLES\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${PYTHON_USE_TRUE}" && test -z "${PYTHON_USE_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"PYTHON_USE\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"PYTHON_USE\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${PYTHON_USE_TRUE}" && test -z "${PYTHON_USE_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"PYTHON_USE\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"PYTHON_USE\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${PYTHON_USE_TRUE}" && test -z "${PYTHON_USE_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"PYTHON_USE\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"PYTHON_USE\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${PYTHON_USE_TRUE}" && test -z "${PYTHON_USE_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"PYTHON_USE\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"PYTHON_USE\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
