----------------------------------------------------------------------
 Committing in .

 Modified Files:
 	Makefile.am Makefile.in configure configure.ac doc/Makefile.in
 	example/Makefile.include.in src/Ifpack_config.h.in
 	src/Makefile.include.am src/Makefile.include.in
 	test/Makefile.am test/Makefile.in
 	test/CompareWithAztecOO/Makefile.include.in
 	test/Container/Makefile.include.in
 	test/CrsRiluk/Makefile.include.in test/IC/Makefile.include.in
 	test/ILU/Makefile.include.in
 	test/IlukGraph/Makefile.include.in
 	test/OverlappingRowMatrix/Makefile.include.in
 	test/PreconditionerFactory/Makefile.include.in
 	test/Relaxation/Makefile.include.in
 	test/SetParameters/Makefile.include.in
 	test/TestAll/Makefile.include.in test/scripts/Makefile.in
 	test/scripts/daily/Makefile.in
 	test/scripts/daily/mpi/Makefile.in
 	test/scripts/daily/serial/Makefile.in
 	test/scripts/weekly/Makefile.in
 	test/scripts/weekly/mpi/Makefile.in
 	test/scripts/weekly/serial/Makefile.in
 ----------------------------------------------------------------------
Merging tarball changes back from the 5.0 release branch.

diff --git a/packages/ifpack/configure b/packages/ifpack/configure
--- a/packages/ifpack/configure
+++ b/packages/ifpack/configure
@@ -311,7 +311,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot MPI_TEMP_CXX MPI_CXX HAVE_MPI_TRUE HAVE_MPI_FALSE MPI_CXX_EXISTS MPI_CC_EXISTS MPI_F77_EXISTS CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE F77 FFLAGS ac_ct_F77 RANLIB ac_ct_RANLIB USE_ALTERNATE_AR_TRUE USE_ALTERNATE_AR_FALSE ALTERNATE_AR CXXCPP EGREP HAVE_IFPACK_AZTECOO_TRUE HAVE_IFPACK_AZTECOO_FALSE HAVE_IFPACK_TRIUTILS_TRUE HAVE_IFPACK_TRIUTILS_FALSE HAVE_IFPACK_TEUCHOS_TRUE HAVE_IFPACK_TEUCHOS_FALSE HAVE_IFPACK_AMESOS_TRUE HAVE_IFPACK_AMESOS_FALSE HAVE_IFPACK_EPETRAEXT_TRUE HAVE_IFPACK_EPETRAEXT_FALSE HAVE_IFPACK_METIS_TRUE HAVE_IFPACK_METIS_FALSE BUILD_TESTS_TRUE BUILD_TESTS_FALSE FLIBS BLAS_LIBS LAPACK_LIBS TRILINOS_TEMPLATE_OBJS ac_aux_dir LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot MPI_TEMP_CXX MPI_CXX HAVE_MPI_TRUE HAVE_MPI_FALSE MPI_CXX_EXISTS MPI_CC_EXISTS MPI_F77_EXISTS CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE F77 FFLAGS ac_ct_F77 RANLIB ac_ct_RANLIB USE_ALTERNATE_AR_TRUE USE_ALTERNATE_AR_FALSE ALTERNATE_AR CXXCPP EGREP HAVE_IFPACK_AZTECOO_TRUE HAVE_IFPACK_AZTECOO_FALSE HAVE_IFPACK_TRIUTILS_TRUE HAVE_IFPACK_TRIUTILS_FALSE HAVE_IFPACK_TEUCHOS_TRUE HAVE_IFPACK_TEUCHOS_FALSE HAVE_IFPACK_AMESOS_TRUE HAVE_IFPACK_AMESOS_FALSE HAVE_IFPACK_EPETRAEXT_TRUE HAVE_IFPACK_EPETRAEXT_FALSE HAVE_IFPACK_METIS_TRUE HAVE_IFPACK_METIS_FALSE BUILD_TESTS_TRUE BUILD_TESTS_FALSE BUILD_EXAMPLES_TRUE BUILD_EXAMPLES_FALSE FLIBS BLAS_LIBS LAPACK_LIBS TRILINOS_TEMPLATE_OBJS ac_aux_dir LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -905,6 +905,12 @@ Optional Features:
 
   --enable-ifpack-tests   Build Ifpack tests (default is yes if
                           --disable-tests is not specified)
+  --enable-examples       Build examples for all Trilinos packages (not all
+                          packages are sensitive to this option) (default is
+                          yes)
+  --enable-ifpack-examples
+                          Build Ifpack examples (default is yes if
+                          --disable-examples is not specified)
   --enable-libcheck       Check for some third-party libraries including BLAS
                           and LAPACK. (Cannot be disabled unless tests and
                           examples are also disabled.) (default is yes)
@@ -3818,7 +3824,7 @@ fi
 
 
 # Provide some information about the compiler.
-echo "$as_me:3821:" \
+echo "$as_me:3827:" \
      "checking for Fortran 77 compiler version" >&5
 ac_compiler=`set X $ac_compile; echo $2`
 { (eval echo "$as_me:$LINENO: \"$ac_compiler --version </dev/null >&5\"") >&5
@@ -7127,7 +7133,7 @@ fi
 #AM_CONDITIONAL(HAVE_IFPACK_TEUCHOS, [test "X$ac_cv_use_ifpack_teuchos" != "Xno"])
 
 # ------------------------------------------------------------------------
-# Checks if tests should be built
+# Checks if tests and examples should be built
 # ------------------------------------------------------------------------
 
 
@@ -7196,6 +7202,75 @@ if test "X$ac_cv_use_ifpack_tests" != "Xno"; then
 else
   BUILD_TESTS_TRUE='#'
   BUILD_TESTS_FALSE=
+fi
+
+
+
+# Check whether --enable-examples or --disable-examples was given.
+if test "${enable_examples+set}" = set; then
+  enableval="$enable_examples"
+  ac_cv_use_examples=$enableval
+else
+  ac_cv_use_examples=yes
+fi;
+
+echo "$as_me:$LINENO: checking whether to use examples" >&5
+echo $ECHO_N "checking whether to use examples... $ECHO_C" >&6
+
+if test "X$ac_cv_use_examples" != "Xno"; then
+  echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_EXAMPLES
+_ACEOF
+
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+
+# Check whether --enable-examples or --disable-examples was given.
+if test "${enable_examples+set}" = set; then
+  enableval="$enable_examples"
+  ac_cv_use_examples=$enableval
+else
+  ac_cv_use_examples=yes
+fi;
+
+# Check whether --enable-ifpack-examples or --disable-ifpack-examples was given.
+if test "${enable_ifpack_examples+set}" = set; then
+  enableval="$enable_ifpack_examples"
+  ac_cv_use_ifpack_examples=$enableval
+else
+  ac_cv_use_ifpack_examples=${ac_cv_use_examples}
+fi;
+
+echo "$as_me:$LINENO: checking whether to use ifpack-examples" >&5
+echo $ECHO_N "checking whether to use ifpack-examples... $ECHO_C" >&6
+
+if test "X$ac_cv_use_ifpack_examples" != "Xno"; then
+  echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_IFPACK_EXAMPLES
+_ACEOF
+
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+
+
+if test "X$ac_cv_use_ifpack_examples" != "Xno"; then
+  BUILD_EXAMPLES_TRUE=
+  BUILD_EXAMPLES_FALSE='#'
+else
+  BUILD_EXAMPLES_TRUE='#'
+  BUILD_EXAMPLES_FALSE=
 fi
 
 
@@ -7321,7 +7396,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_verb"
-(eval echo $as_me:7324: \"$ac_link\") >&5
+(eval echo $as_me:7399: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
@@ -7399,7 +7474,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_cv_prog_f77_v"
-(eval echo $as_me:7402: \"$ac_link\") >&5
+(eval echo $as_me:7477: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
@@ -8093,8 +8168,7 @@ ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
 
 # If tests, examples and libcheck are disabled, we don't have to check
 # for these libraries.
-#if test "X$ac_cv_use_ifpack_tests" != "Xno" || test "X$ac_cv_use_ifpack_examples" != "Xno" || test "X$ac_cv_use_libcheck" != "Xno"; then
-if test "X$ac_cv_use_ifpack_tests" != "Xno" || test "X$ac_cv_use_libcheck" != "Xno"; then
+if test "X$ac_cv_use_ifpack_tests" != "Xno" || test "X$ac_cv_use_ifpack_examples" != "Xno" || test "X$ac_cv_use_libcheck" != "Xno"; then
 
 # checks for libraries now
 echo "$as_me:$LINENO: checking for library containing sqrt" >&5
@@ -8285,10 +8359,6 @@ fi
 
 
 # find or choose to supply valid blas and lapack libraries
-#TAC_ARG_ENABLE_FEATURE(referenceblasandlapack, [Build blas and lapack libs included in the distribution], BLASANDLAPACK, no)
-#AM_CONDITIONAL(BUILD_BLAS, test "X$ac_cv_use_referenceblasandlapack" != "Xno")
-#if test "X$ac_cv_use_referenceblasandlapack" = "Xno"; then
-#  ACX_BLAS([], [AC_MSG_ERROR([[Cannot find blas library, please specify additional locations using --with-ldflags, additional lib names using --with-blas or type --with-referenceblasandlapack on the configure line in the Trilinos level directory to use the blas and lapack libraries included in the distribution]])])
 
 
 
@@ -9737,11 +9807,6 @@ echo "$as_me: error: Cannot find blas library, specify a path using --with-ldfla
    { (exit 1); exit 1; }; }
 fi
 
-#fi
-#TAC_ARG_ENABLE_FEATURE(referencelapack, [Build lapack lib included in the distribution], LAPACK, no)
-#AM_CONDITIONAL(BUILD_LAPACK, test "X$ac_cv_use_referencelapack" != "Xno" || test "X$ac_cv_use_referenceblasandlapack" != "Xno")
-#if test "X$ac_cv_use_referencelapack" = "Xno" && test "X$ac_cv_use_referenceblasandlapack" = "Xno"; then
-#  ACX_LAPACK([], [AC_MSG_ERROR([[Cannot find lapack library, please specify additional locations using --with-ldflags, additional lib names using --with-lapacklib or type --with-referencelapack on the configure line in the Trilinos level directory to use the lapack library included in the distribution]])])
 
 
 acx_lapack_ok=no
@@ -10135,7 +10200,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_verb"
-(eval echo $as_me:10138: \"$ac_link\") >&5
+(eval echo $as_me:10203: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
@@ -10213,7 +10278,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_cv_prog_f77_v"
-(eval echo $as_me:10216: \"$ac_link\") >&5
+(eval echo $as_me:10281: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
@@ -10439,7 +10504,7 @@ fi
 #		example/Makefile
 #		example/ifpack_hb/Makefile
 
-                                                                                                                                                                                                                                                                                                                                                                                  ac_config_files="$ac_config_files Makefile Makefile.export src/Makefile src/Makefile.include doc/Makefile example/Makefile example/Makefile.include test/Makefile test/PreconditionerFactory/Makefile test/PreconditionerFactory/Makefile.include test/TestAll/Makefile test/TestAll/Makefile.include test/CrsRiluk/Makefile test/CrsRiluk/Makefile.include test/IlukGraph/Makefile test/IlukGraph/Makefile.include test/SetParameters/Makefile test/SetParameters/Makefile.include test/Relaxation/Makefile test/Relaxation/Makefile.include test/Container/Makefile test/Container/Makefile.include test/OverlappingRowMatrix/Makefile test/OverlappingRowMatrix/Makefile.include test/CompareWithAztecOO/Makefile test/CompareWithAztecOO/Makefile.include test/ILU/Makefile test/ILU/Makefile.include test/IC/Makefile test/IC/Makefile.include test/scripts/Makefile test/scripts/daily/Makefile test/scripts/daily/mpi/Makefile test/scripts/daily/serial/Makefile test/scripts/weekly/Makefile test/scripts/weekly/mpi/Makefile test/scripts/weekly/serial/Makefile"
+                                                                                                                                                                                                                                                                                                                                                                                  ac_config_files="$ac_config_files Makefile Makefile.export src/Makefile src/Makefile.include example/Makefile example/Makefile.include doc/Makefile test/Makefile test/PreconditionerFactory/Makefile test/PreconditionerFactory/Makefile.include test/TestAll/Makefile test/TestAll/Makefile.include test/CrsRiluk/Makefile test/CrsRiluk/Makefile.include test/IlukGraph/Makefile test/IlukGraph/Makefile.include test/SetParameters/Makefile test/SetParameters/Makefile.include test/Relaxation/Makefile test/Relaxation/Makefile.include test/Container/Makefile test/Container/Makefile.include test/OverlappingRowMatrix/Makefile test/OverlappingRowMatrix/Makefile.include test/CompareWithAztecOO/Makefile test/CompareWithAztecOO/Makefile.include test/ILU/Makefile test/ILU/Makefile.include test/IC/Makefile test/IC/Makefile.include test/scripts/Makefile test/scripts/daily/Makefile test/scripts/daily/mpi/Makefile test/scripts/daily/serial/Makefile test/scripts/weekly/Makefile test/scripts/weekly/mpi/Makefile test/scripts/weekly/serial/Makefile"
 
 
 cat >confcache <<\_ACEOF
@@ -10628,6 +10693,13 @@ if test -z "${BUILD_TESTS_TRUE}" && test -z "${BUILD_TESTS_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"BUILD_TESTS\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"BUILD_TESTS\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${BUILD_EXAMPLES_TRUE}" && test -z "${BUILD_EXAMPLES_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"BUILD_EXAMPLES\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"BUILD_EXAMPLES\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -11079,9 +11151,9 @@ do
   "Makefile.export" ) CONFIG_FILES="$CONFIG_FILES Makefile.export" ;;
   "src/Makefile" ) CONFIG_FILES="$CONFIG_FILES src/Makefile" ;;
   "src/Makefile.include" ) CONFIG_FILES="$CONFIG_FILES src/Makefile.include" ;;
-  "doc/Makefile" ) CONFIG_FILES="$CONFIG_FILES doc/Makefile" ;;
   "example/Makefile" ) CONFIG_FILES="$CONFIG_FILES example/Makefile" ;;
   "example/Makefile.include" ) CONFIG_FILES="$CONFIG_FILES example/Makefile.include" ;;
+  "doc/Makefile" ) CONFIG_FILES="$CONFIG_FILES doc/Makefile" ;;
   "test/Makefile" ) CONFIG_FILES="$CONFIG_FILES test/Makefile" ;;
   "test/PreconditionerFactory/Makefile" ) CONFIG_FILES="$CONFIG_FILES test/PreconditionerFactory/Makefile" ;;
   "test/PreconditionerFactory/Makefile.include" ) CONFIG_FILES="$CONFIG_FILES test/PreconditionerFactory/Makefile.include" ;;
@@ -11287,6 +11359,8 @@ s,@HAVE_IFPACK_METIS_TRUE@,$HAVE_IFPACK_METIS_TRUE,;t t
 s,@HAVE_IFPACK_METIS_FALSE@,$HAVE_IFPACK_METIS_FALSE,;t t
 s,@BUILD_TESTS_TRUE@,$BUILD_TESTS_TRUE,;t t
 s,@BUILD_TESTS_FALSE@,$BUILD_TESTS_FALSE,;t t
+s,@BUILD_EXAMPLES_TRUE@,$BUILD_EXAMPLES_TRUE,;t t
+s,@BUILD_EXAMPLES_FALSE@,$BUILD_EXAMPLES_FALSE,;t t
 s,@FLIBS@,$FLIBS,;t t
 s,@BLAS_LIBS@,$BLAS_LIBS,;t t
 s,@LAPACK_LIBS@,$LAPACK_LIBS,;t t
