SUMMARY:   Addition of GAASP TPL source to Rythmos and minor unit testing updates.
     BUGS:      3984

     CHECKLIST:

     1)   Did you add any source files?  Yes
     1.a) Did you do a 'cvs add'?  YES
     1.b) Did you add them to a Makefile.am file in some way?  YES
     1.c) Did you do a new bootstrap?  YES

     2)   Did you update or change the build system?  YES
     2.a) Did you remember to do a bootstrap and do a 'cvs add' on the
          Makefile.am files and the Makefile.in files?  YES
     2.b) [Optional but recommended] Did you blow away the libraries and
          executables and then rebuild?  YES

     3) Did you rerun the test suite on at least the packages that you
        changed?  YES


(checklist version 2007-06-20)

diff --git a/packages/rythmos/configure b/packages/rythmos/configure
--- a/packages/rythmos/configure
+++ b/packages/rythmos/configure
@@ -745,8 +745,8 @@ ENABLE_RYTHMOS_EPETRAEXT_TRUE
 ENABLE_RYTHMOS_EPETRAEXT_FALSE
 ENABLE_RYTHMOS_SACADO_TRUE
 ENABLE_RYTHMOS_SACADO_FALSE
-ENABLE_RYTHMOS_GAASP_TRUE
-ENABLE_RYTHMOS_GAASP_FALSE
+ENABLE_RYTHMOS_TEUCHOS_BOOST_TRUE
+ENABLE_RYTHMOS_TEUCHOS_BOOST_FALSE
 ENABLE_RYTHMOS_STRATIMIKOS_AMESOS_TRUE
 ENABLE_RYTHMOS_STRATIMIKOS_AMESOS_FALSE
 ENABLE_RYTHMOS_STRATIMIKOS_AZTECOO_TRUE
@@ -761,6 +761,10 @@ ENABLE_RYTHMOS_THYRA_EPETRAEXT_TRUE
 ENABLE_RYTHMOS_THYRA_EPETRAEXT_FALSE
 ENABLE_RYTHMOS_NOX_EPETRA_TRUE
 ENABLE_RYTHMOS_NOX_EPETRA_FALSE
+ENABLE_RYTHMOS_GAASP_TRUE
+ENABLE_RYTHMOS_GAASP_FALSE
+ENABLE_RYTHMOS_GAASP_INTERNAL_TRUE
+ENABLE_RYTHMOS_GAASP_INTERNAL_FALSE
 BUILD_EXAMPLES_TRUE
 BUILD_EXAMPLES_FALSE
 BUILD_TESTS_TRUE
@@ -1397,9 +1401,9 @@ Optional Features:
   --enable-sacado         Build the Sacado adapter support in Rythmos. Can be
                           overridden with --disable-rythmos-sacado.
   --enable-rythmos-sacado Build the Sacado adapter support in Rythmos.
-  --enable-gaasp          Build the GAASP adapter support in Rythmos. Can be
-                          overridden with --disable-rythmos-gasp.
-  --enable-rythmos-gaasp  Build the GAASP adapter support in Rythmos.
+  --enable-teuchos        See teuchos/configure --help
+  --enable-boost          See teuchos/configure --help
+  --enable-teuchos-boost  See teuchos/configure --help
   --enable-stratimikos    See stratimikos/configure --help
   --enable-amesos         See stratimikos/configure --help
   --enable-stratimikos-amesos
@@ -1422,6 +1426,9 @@ Optional Features:
   --enable-nox            See nox/configure --help
   --enable-epetra         See nox/configure --help
   --enable-nox-epetra     See nox/configure --help
+  --enable-rythmos-gaasp  Enable GAASP adapter support (default is yes)
+  --enable-rythmos-gaaspinternal
+                          Build internal GAASP TPL library (default is yes)
 
   --enable-rythmos-examples
                           Make Rythmos examples buildable with 'make examples'
@@ -7812,38 +7819,49 @@ fi
 
 
 
-# Check whether --enable-gaasp was given.
-if test "${enable_gaasp+set}" = set; then
-  enableval=$enable_gaasp; ac_cv_implicit_use_gaasp=$enableval
+# Check whether --enable-teuchos was given.
+if test "${enable_teuchos+set}" = set; then
+  enableval=$enable_teuchos; ac_cv_implicit_use_teuchos=$enableval
 else
-  ac_cv_implicit_use_gaasp=no
+  ac_cv_implicit_use_teuchos=no
 fi
 
 
-if test "Xno
-    " != "Xno"; then
-  ac_cv_rythmos_using_gaasp_default=$ac_cv_implicit_use_gaasp
+# Check whether --enable-boost was given.
+if test "${enable_boost+set}" = set; then
+  enableval=$enable_boost; ac_cv_implicit_use_boost=$enableval
 else
-  ac_cv_rythmos_using_gaasp_default=no
-fi
-
-# Check whether --enable-rythmos-gaasp was given.
-if test "${enable_rythmos_gaasp+set}" = set; then
-  enableval=$enable_rythmos_gaasp; ac_cv_use_gaasp=$enableval
-else
-  ac_cv_use_gaasp=$ac_cv_rythmos_using_gaasp_default
+  ac_cv_implicit_use_boost=no
 fi
 
 
-{ echo "$as_me:$LINENO: checking whether to build optional gaasp dependent code in rythmos" >&5
-echo $ECHO_N "checking whether to build optional gaasp dependent code in rythmos... $ECHO_C" >&6; }
+if test "Xyes" != "Xno"; then
+  if test "X$ac_cv_implicit_use_teuchos" != "Xno"; then
+    ac_cv_teuchos_using_boost_default=$ac_cv_implicit_use_boost
+  else
+    ac_cv_teuchos_using_boost_default=no
+  fi
+else
+  ac_cv_teuchos_using_boost_default=no
+fi
 
-if test "X$ac_cv_use_gaasp" != "Xno"; then
+# Check whether --enable-teuchos-boost was given.
+if test "${enable_teuchos_boost+set}" = set; then
+  enableval=$enable_teuchos_boost; ac_cv_use_boost=$enableval
+else
+  ac_cv_use_boost=$ac_cv_teuchos_using_boost_default
+fi
+
+
+{ echo "$as_me:$LINENO: checking whether to build optional boost dependent code in teuchos" >&5
+echo $ECHO_N "checking whether to build optional boost dependent code in teuchos... $ECHO_C" >&6; }
+
+if test "X$ac_cv_use_boost" != "Xno"; then
   { echo "$as_me:$LINENO: result: yes" >&5
 echo "${ECHO_T}yes" >&6; }
 
 cat >>confdefs.h <<\_ACEOF
-#define HAVE_RYTHMOS_GAASP 1
+#define HAVE_RYTHMOS_TEUCHOS_BOOST 1
 _ACEOF
 
 else
@@ -7851,12 +7869,12 @@ else
 echo "${ECHO_T}no" >&6; }
 fi
 
- if test "X$ac_cv_use_gaasp" = "Xyes"; then
-  ENABLE_RYTHMOS_GAASP_TRUE=
-  ENABLE_RYTHMOS_GAASP_FALSE='#'
+ if test "X$ac_cv_use_boost" = "Xyes"; then
+  ENABLE_RYTHMOS_TEUCHOS_BOOST_TRUE=
+  ENABLE_RYTHMOS_TEUCHOS_BOOST_FALSE='#'
 else
-  ENABLE_RYTHMOS_GAASP_TRUE='#'
-  ENABLE_RYTHMOS_GAASP_FALSE=
+  ENABLE_RYTHMOS_TEUCHOS_BOOST_TRUE='#'
+  ENABLE_RYTHMOS_TEUCHOS_BOOST_FALSE=
 fi
 
 
@@ -8302,6 +8320,78 @@ else
 fi
 
 
+
+
+# ------------------------------------------------------------------------
+# Check for GAASP support
+# ------------------------------------------------------------------------
+
+
+# Check whether --enable-rythmos-gaasp was given.
+if test "${enable_rythmos_gaasp+set}" = set; then
+  enableval=$enable_rythmos_gaasp; ac_cv_use_rythmos_gaasp=$enableval
+else
+  ac_cv_use_rythmos_gaasp=yes
+fi
+
+
+{ echo "$as_me:$LINENO: checking whether to use rythmos-gaasp" >&5
+echo $ECHO_N "checking whether to use rythmos-gaasp... $ECHO_C" >&6; }
+
+if test "X$ac_cv_use_rythmos_gaasp" != "Xno"; then
+  { echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6; }
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_RYTHMOS_GAASP
+_ACEOF
+
+else
+  { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+fi
+
+ if test "X$ac_cv_use_rythmos_gaasp" != "Xno"; then
+  ENABLE_RYTHMOS_GAASP_TRUE=
+  ENABLE_RYTHMOS_GAASP_FALSE='#'
+else
+  ENABLE_RYTHMOS_GAASP_TRUE='#'
+  ENABLE_RYTHMOS_GAASP_FALSE=
+fi
+
+
+
+# Check whether --enable-rythmos-gaaspinternal was given.
+if test "${enable_rythmos_gaaspinternal+set}" = set; then
+  enableval=$enable_rythmos_gaaspinternal; ac_cv_use_rythmos_gaaspinternal=$enableval
+else
+  ac_cv_use_rythmos_gaaspinternal=yes
+fi
+
+
+{ echo "$as_me:$LINENO: checking whether to use rythmos-gaaspinternal" >&5
+echo $ECHO_N "checking whether to use rythmos-gaaspinternal... $ECHO_C" >&6; }
+
+if test "X$ac_cv_use_rythmos_gaaspinternal" != "Xno"; then
+  { echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6; }
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_RYTHMOS_GAASP_INTERNAL
+_ACEOF
+
+else
+  { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+fi
+
+ if test "X$ac_cv_use_rythmos_gaaspinternal" != "Xno"; then
+  ENABLE_RYTHMOS_GAASP_INTERNAL_TRUE=
+  ENABLE_RYTHMOS_GAASP_INTERNAL_FALSE='#'
+else
+  ENABLE_RYTHMOS_GAASP_INTERNAL_TRUE='#'
+  ENABLE_RYTHMOS_GAASP_INTERNAL_FALSE=
+fi
 
 
 # ------------------------------------------------------------------------
@@ -8799,7 +8889,7 @@ fi
 # Output files
 # ------------------------------------------------------------------------
 
-ac_config_files="$ac_config_files Makefile Makefile.export.rythmos example/Makefile example/diagonalTransient/Makefile example/epetra/1Dfem/Makefile example/epetra/Makefile example/timeDiscretizedBackwardEuler/Makefile src/Makefile adapters/Makefile adapters/gaasp/Makefile adapters/gaasp/src/Makefile adapters/gaasp/test/Makefile adapters/gaasp/example/Makefile test/ExplicitTaylorPolynomialStepper/Makefile test/ExplicitTaylorPolynomialStepper/VanDerPolOscillator/Makefile test/Makefile test/UnitTest/Makefile test/complicatedExample/Makefile test/simpleAdjoint/Makefile"
+ac_config_files="$ac_config_files Makefile Makefile.export.rythmos example/Makefile example/diagonalTransient/Makefile example/epetra/1Dfem/Makefile example/epetra/Makefile example/timeDiscretizedBackwardEuler/Makefile src/Makefile adapters/Makefile adapters/gaasp/Makefile adapters/gaasp/src/Makefile adapters/gaasp/test/Makefile adapters/gaasp/example/Makefile adapters/gaasp/tpl_src/Makefile test/ExplicitTaylorPolynomialStepper/Makefile test/ExplicitTaylorPolynomialStepper/VanDerPolOscillator/Makefile test/Makefile test/UnitTest/Makefile test/complicatedExample/Makefile test/simpleAdjoint/Makefile"
 
 
 cat >confcache <<\_ACEOF
@@ -9031,10 +9121,10 @@ echo "$as_me: error: conditional \"ENABLE_RYTHMOS_SACADO\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
-if test -z "${ENABLE_RYTHMOS_GAASP_TRUE}" && test -z "${ENABLE_RYTHMOS_GAASP_FALSE}"; then
-  { { echo "$as_me:$LINENO: error: conditional \"ENABLE_RYTHMOS_GAASP\" was never defined.
+if test -z "${ENABLE_RYTHMOS_TEUCHOS_BOOST_TRUE}" && test -z "${ENABLE_RYTHMOS_TEUCHOS_BOOST_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"ENABLE_RYTHMOS_TEUCHOS_BOOST\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
-echo "$as_me: error: conditional \"ENABLE_RYTHMOS_GAASP\" was never defined.
+echo "$as_me: error: conditional \"ENABLE_RYTHMOS_TEUCHOS_BOOST\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -9084,6 +9174,20 @@ if test -z "${ENABLE_RYTHMOS_NOX_EPETRA_TRUE}" && test -z "${ENABLE_RYTHMOS_NOX_
   { { echo "$as_me:$LINENO: error: conditional \"ENABLE_RYTHMOS_NOX_EPETRA\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"ENABLE_RYTHMOS_NOX_EPETRA\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${ENABLE_RYTHMOS_GAASP_TRUE}" && test -z "${ENABLE_RYTHMOS_GAASP_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"ENABLE_RYTHMOS_GAASP\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"ENABLE_RYTHMOS_GAASP\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${ENABLE_RYTHMOS_GAASP_INTERNAL_TRUE}" && test -z "${ENABLE_RYTHMOS_GAASP_INTERNAL_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"ENABLE_RYTHMOS_GAASP_INTERNAL\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"ENABLE_RYTHMOS_GAASP_INTERNAL\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -9618,6 +9722,7 @@ do
     "adapters/gaasp/src/Makefile") CONFIG_FILES="$CONFIG_FILES adapters/gaasp/src/Makefile" ;;
     "adapters/gaasp/test/Makefile") CONFIG_FILES="$CONFIG_FILES adapters/gaasp/test/Makefile" ;;
     "adapters/gaasp/example/Makefile") CONFIG_FILES="$CONFIG_FILES adapters/gaasp/example/Makefile" ;;
+    "adapters/gaasp/tpl_src/Makefile") CONFIG_FILES="$CONFIG_FILES adapters/gaasp/tpl_src/Makefile" ;;
     "test/ExplicitTaylorPolynomialStepper/Makefile") CONFIG_FILES="$CONFIG_FILES test/ExplicitTaylorPolynomialStepper/Makefile" ;;
     "test/ExplicitTaylorPolynomialStepper/VanDerPolOscillator/Makefile") CONFIG_FILES="$CONFIG_FILES test/ExplicitTaylorPolynomialStepper/VanDerPolOscillator/Makefile" ;;
     "test/Makefile") CONFIG_FILES="$CONFIG_FILES test/Makefile" ;;
@@ -9857,8 +9962,8 @@ ENABLE_RYTHMOS_EPETRAEXT_TRUE!$ENABLE_RYTHMOS_EPETRAEXT_TRUE$ac_delim
 ENABLE_RYTHMOS_EPETRAEXT_FALSE!$ENABLE_RYTHMOS_EPETRAEXT_FALSE$ac_delim
 ENABLE_RYTHMOS_SACADO_TRUE!$ENABLE_RYTHMOS_SACADO_TRUE$ac_delim
 ENABLE_RYTHMOS_SACADO_FALSE!$ENABLE_RYTHMOS_SACADO_FALSE$ac_delim
-ENABLE_RYTHMOS_GAASP_TRUE!$ENABLE_RYTHMOS_GAASP_TRUE$ac_delim
-ENABLE_RYTHMOS_GAASP_FALSE!$ENABLE_RYTHMOS_GAASP_FALSE$ac_delim
+ENABLE_RYTHMOS_TEUCHOS_BOOST_TRUE!$ENABLE_RYTHMOS_TEUCHOS_BOOST_TRUE$ac_delim
+ENABLE_RYTHMOS_TEUCHOS_BOOST_FALSE!$ENABLE_RYTHMOS_TEUCHOS_BOOST_FALSE$ac_delim
 ENABLE_RYTHMOS_STRATIMIKOS_AMESOS_TRUE!$ENABLE_RYTHMOS_STRATIMIKOS_AMESOS_TRUE$ac_delim
 ENABLE_RYTHMOS_STRATIMIKOS_AMESOS_FALSE!$ENABLE_RYTHMOS_STRATIMIKOS_AMESOS_FALSE$ac_delim
 ENABLE_RYTHMOS_STRATIMIKOS_AZTECOO_TRUE!$ENABLE_RYTHMOS_STRATIMIKOS_AZTECOO_TRUE$ac_delim
@@ -9873,6 +9978,10 @@ ENABLE_RYTHMOS_THYRA_EPETRAEXT_TRUE!$ENABLE_RYTHMOS_THYRA_EPETRAEXT_TRUE$ac_deli
 ENABLE_RYTHMOS_THYRA_EPETRAEXT_FALSE!$ENABLE_RYTHMOS_THYRA_EPETRAEXT_FALSE$ac_delim
 ENABLE_RYTHMOS_NOX_EPETRA_TRUE!$ENABLE_RYTHMOS_NOX_EPETRA_TRUE$ac_delim
 ENABLE_RYTHMOS_NOX_EPETRA_FALSE!$ENABLE_RYTHMOS_NOX_EPETRA_FALSE$ac_delim
+ENABLE_RYTHMOS_GAASP_TRUE!$ENABLE_RYTHMOS_GAASP_TRUE$ac_delim
+ENABLE_RYTHMOS_GAASP_FALSE!$ENABLE_RYTHMOS_GAASP_FALSE$ac_delim
+ENABLE_RYTHMOS_GAASP_INTERNAL_TRUE!$ENABLE_RYTHMOS_GAASP_INTERNAL_TRUE$ac_delim
+ENABLE_RYTHMOS_GAASP_INTERNAL_FALSE!$ENABLE_RYTHMOS_GAASP_INTERNAL_FALSE$ac_delim
 BUILD_EXAMPLES_TRUE!$BUILD_EXAMPLES_TRUE$ac_delim
 BUILD_EXAMPLES_FALSE!$BUILD_EXAMPLES_FALSE$ac_delim
 BUILD_TESTS_TRUE!$BUILD_TESTS_TRUE$ac_delim
@@ -9886,7 +9995,7 @@ LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 60; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 64; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
