I did a few things here:
1) I updated rythmos to use Stratimikos instead of Amesos and AztecOO directly.  However, I did not update the NOX-based example and NOX is disabled in my build.

2) I set x=0 before calling solve in the implicit time steppers.  This is needed for iterative linear solvers so you should just always do it.

3) I fixed the behavior of reading parameters and building solver and preconditioner factories.  This was wrong after my last update but not it is correct.  I also added a destructor to help check that the parameters have been used and accessed correctly.

This checkin breaks rythmos in two ways.  First, the NOX-based example will not build.  Also, I added a test using AztecOO that fails.  I am not sure what is happening here but I will let Todd decide what to do.

diff --git a/packages/rythmos/configure b/packages/rythmos/configure
--- a/packages/rythmos/configure
+++ b/packages/rythmos/configure
@@ -311,7 +311,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot MPI_TEMP_CXX MPI_CXX HAVE_MPI_TRUE HAVE_MPI_FALSE MPI_CXX_EXISTS MPI_CC_EXISTS MPI_F77_EXISTS CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE F77 FFLAGS ac_ct_F77 RANLIB ac_ct_RANLIB USE_ALTERNATE_AR_TRUE USE_ALTERNATE_AR_FALSE ALTERNATE_AR CXXCPP EGREP USING_EXPORT_MAKEFILES_TRUE USING_EXPORT_MAKEFILES_FALSE PERL_EXE HAVE_PERL USING_PERL_TRUE USING_PERL_FALSE USING_GNUMAKE_TRUE USING_GNUMAKE_FALSE ENABLE_RYTHMOS_AMESOS_TRUE ENABLE_RYTHMOS_AMESOS_FALSE ENABLE_RYTHMOS_AZTECOO_TRUE ENABLE_RYTHMOS_AZTECOO_FALSE ENABLE_RYTHMOS_NOX_TRUE ENABLE_RYTHMOS_NOX_FALSE HAVE_NEWP_SWAHILI_TRUE HAVE_NEWP_SWAHILI_FALSE BUILD_TESTS_TRUE BUILD_TESTS_FALSE BUILD_EXAMPLES_TRUE BUILD_EXAMPLES_FALSE PYTHON_USE_TRUE PYTHON_USE_FALSE PYTHON PYTHON_PREFIX PYTHON_EXECPREFIX BUILD_PYTHON_TRUE BUILD_PYTHON_FALSE PYTHON_CSPEC PYTHON_LSPEC WITH_SWIG SWIG SWIG_LIB SWIG_PYTHON_OPT SWIG_PYTHON_CPPFLAGS HAVE_SWIG_TRUE HAVE_SWIG_FALSE GNU_HAVE_SWIG FLIBS BLAS_LIBS ac_aux_dir LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot MPI_TEMP_CXX MPI_CXX HAVE_MPI_TRUE HAVE_MPI_FALSE MPI_CXX_EXISTS MPI_CC_EXISTS MPI_F77_EXISTS CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE F77 FFLAGS ac_ct_F77 RANLIB ac_ct_RANLIB USE_ALTERNATE_AR_TRUE USE_ALTERNATE_AR_FALSE ALTERNATE_AR CXXCPP EGREP USING_EXPORT_MAKEFILES_TRUE USING_EXPORT_MAKEFILES_FALSE PERL_EXE HAVE_PERL USING_PERL_TRUE USING_PERL_FALSE USING_GNUMAKE_TRUE USING_GNUMAKE_FALSE ENABLE_RYTHMOS_NOX_TRUE ENABLE_RYTHMOS_NOX_FALSE ENABLE_RYTHMOS_STRATIMIKOS_TRUE ENABLE_RYTHMOS_STRATIMIKOS_FALSE ENABLE_EPETRAEXT_THYRA_TRUE ENABLE_EPETRAEXT_THYRA_FALSE HAVE_NEWP_SWAHILI_TRUE HAVE_NEWP_SWAHILI_FALSE BUILD_TESTS_TRUE BUILD_TESTS_FALSE BUILD_EXAMPLES_TRUE BUILD_EXAMPLES_FALSE PYTHON_USE_TRUE PYTHON_USE_FALSE PYTHON PYTHON_PREFIX PYTHON_EXECPREFIX BUILD_PYTHON_TRUE BUILD_PYTHON_FALSE PYTHON_CSPEC PYTHON_LSPEC WITH_SWIG SWIG SWIG_LIB SWIG_PYTHON_OPT SWIG_PYTHON_CPPFLAGS HAVE_SWIG_TRUE HAVE_SWIG_FALSE GNU_HAVE_SWIG FLIBS BLAS_LIBS ac_aux_dir LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -721,13 +721,13 @@ echo X"$0" |
   	  /^X\(\/\).*/{ s//\1/; q; }
   	  s/.*/./; q'`
   srcdir=$ac_confdir
-  if test ! -r "$srcdir/$ac_unique_file"; then
+  if test ! -r $srcdir/$ac_unique_file; then
     srcdir=..
   fi
 else
   ac_srcdir_defaulted=no
 fi
-if test ! -r "$srcdir/$ac_unique_file"; then
+if test ! -r $srcdir/$ac_unique_file; then
   if test "$ac_srcdir_defaulted" = yes; then
     { echo "$as_me: error: cannot find sources ($ac_unique_file) in $ac_confdir or .." >&2
    { (exit 1); exit 1; }; }
@@ -736,7 +736,7 @@ if test ! -r "$srcdir/$ac_unique_file"; then
    { (exit 1); exit 1; }; }
   fi
 fi
-(cd $srcdir && test -r "./$ac_unique_file") 2>/dev/null ||
+(cd $srcdir && test -r ./$ac_unique_file) 2>/dev/null ||
   { echo "$as_me: error: sources are in $srcdir, but \`cd $srcdir' does not work" >&2
    { (exit 1); exit 1; }; }
 srcdir=`echo "$srcdir" | sed 's%\([^\\/]\)[\\/]*$%\1%'`
@@ -884,20 +884,18 @@ Optional Features:
                           directory. This option requires perl to be set in
                           your path or defined with --with-perl=<perl
                           executable>(default is no)
-  --enable-amesos         Build the Amesos operator/vector adapater support in
-                          Rythmos. Can be overridden with
-                          --disable-rythmos-amesos.
-  --enable-rythmos-amesos Build the Amesos operator/vector adapater support in
-                          Rythmos.
-  --enable-aztecoo        Build the AztecOO operator/vector adapater support
-                          in Rythmos. Can be overridden with
-                          --disable-rythmos-aztecoo.
-  --enable-rythmos-aztecoo
-                          Build the AztecOO operator/vector adapater support
-                          in Rythmos.
   --enable-nox            Build in NOX support in Rythmos. Can be overridden
                           with --disable-rythmos-nox.
   --enable-rythmos-nox    Build in NOX support in Rythmos.
+  --enable-stratimikos    Build the Stratimikos adapater support in Rythmos.
+                          Can be overridden with
+                          --disable-rythmos-stratimikos.
+  --enable-rythmos-stratimikos
+                          Build the Stratimikos adapater support in Rythmos.
+  --enable-epetraext      See epetraext/configure --help
+  --enable-thyra          See epetraext/configure --help
+  --enable-epetraext-thyra
+                          See epetraext/configure --help
   --enable-newp_swahili   enable swahili support (default is no)
   --enable-tests          Build tests for all Trilinos packages (not all
                           packages are sensitive to this option) (default is
@@ -3849,7 +3847,7 @@ fi
 
 
 # Provide some information about the compiler.
-echo "$as_me:3852:" \
+echo "$as_me:3850:" \
      "checking for Fortran 77 compiler version" >&5
 ac_compiler=`set X $ac_compile; echo $2`
 { (eval echo "$as_me:$LINENO: \"$ac_compiler --version </dev/null >&5\"") >&5
@@ -6895,112 +6893,6 @@ fi
 
 
 
-# Check whether --enable-amesos or --disable-amesos was given.
-if test "${enable_amesos+set}" = set; then
-  enableval="$enable_amesos"
-  ac_cv_implicit_use_amesos=$enableval
-else
-  ac_cv_implicit_use_amesos=no
-fi;
-
-if test "Xyes" != "Xno"; then
-  ac_cv_rythmos_using_amesos_default=$ac_cv_implicit_use_amesos
-else
-  ac_cv_rythmos_using_amesos_default=no
-fi
-
-# Check whether --enable-rythmos-amesos or --disable-rythmos-amesos was given.
-if test "${enable_rythmos_amesos+set}" = set; then
-  enableval="$enable_rythmos_amesos"
-  ac_cv_use_amesos=$enableval
-else
-  ac_cv_use_amesos=$ac_cv_rythmos_using_amesos_default
-fi;
-
-echo "$as_me:$LINENO: checking whether to build optional amesos dependent code in rythmos" >&5
-echo $ECHO_N "checking whether to build optional amesos dependent code in rythmos... $ECHO_C" >&6
-
-if test "X$ac_cv_use_amesos" != "Xno"; then
-  echo "$as_me:$LINENO: result: yes" >&5
-echo "${ECHO_T}yes" >&6
-
-cat >>confdefs.h <<\_ACEOF
-#define HAVE_RYTHMOS_AMESOS 1
-_ACEOF
-
-else
-  echo "$as_me:$LINENO: result: no" >&5
-echo "${ECHO_T}no" >&6
-fi
-
-
-
-if test "X$ac_cv_use_amesos" = "Xyes"; then
-  ENABLE_RYTHMOS_AMESOS_TRUE=
-  ENABLE_RYTHMOS_AMESOS_FALSE='#'
-else
-  ENABLE_RYTHMOS_AMESOS_TRUE='#'
-  ENABLE_RYTHMOS_AMESOS_FALSE=
-fi
-
-
-
-
-
-
-# Check whether --enable-aztecoo or --disable-aztecoo was given.
-if test "${enable_aztecoo+set}" = set; then
-  enableval="$enable_aztecoo"
-  ac_cv_implicit_use_aztecoo=$enableval
-else
-  ac_cv_implicit_use_aztecoo=no
-fi;
-
-if test "Xyes" != "Xno"; then
-  ac_cv_rythmos_using_aztecoo_default=$ac_cv_implicit_use_aztecoo
-else
-  ac_cv_rythmos_using_aztecoo_default=no
-fi
-
-# Check whether --enable-rythmos-aztecoo or --disable-rythmos-aztecoo was given.
-if test "${enable_rythmos_aztecoo+set}" = set; then
-  enableval="$enable_rythmos_aztecoo"
-  ac_cv_use_aztecoo=$enableval
-else
-  ac_cv_use_aztecoo=$ac_cv_rythmos_using_aztecoo_default
-fi;
-
-echo "$as_me:$LINENO: checking whether to build optional aztecoo dependent code in rythmos" >&5
-echo $ECHO_N "checking whether to build optional aztecoo dependent code in rythmos... $ECHO_C" >&6
-
-if test "X$ac_cv_use_aztecoo" != "Xno"; then
-  echo "$as_me:$LINENO: result: yes" >&5
-echo "${ECHO_T}yes" >&6
-
-cat >>confdefs.h <<\_ACEOF
-#define HAVE_RYTHMOS_AZTECOO 1
-_ACEOF
-
-else
-  echo "$as_me:$LINENO: result: no" >&5
-echo "${ECHO_T}no" >&6
-fi
-
-
-
-if test "X$ac_cv_use_aztecoo" = "Xyes"; then
-  ENABLE_RYTHMOS_AZTECOO_TRUE=
-  ENABLE_RYTHMOS_AZTECOO_FALSE='#'
-else
-  ENABLE_RYTHMOS_AZTECOO_TRUE='#'
-  ENABLE_RYTHMOS_AZTECOO_FALSE=
-fi
-
-
-
-
-
-
 # Check whether --enable-nox or --disable-nox was given.
 if test "${enable_nox+set}" = set; then
   enableval="$enable_nox"
@@ -7047,6 +6939,126 @@ if test "X$ac_cv_use_nox" = "Xyes"; then
 else
   ENABLE_RYTHMOS_NOX_TRUE='#'
   ENABLE_RYTHMOS_NOX_FALSE=
+fi
+
+
+
+
+
+
+# Check whether --enable-stratimikos or --disable-stratimikos was given.
+if test "${enable_stratimikos+set}" = set; then
+  enableval="$enable_stratimikos"
+  ac_cv_implicit_use_stratimikos=$enableval
+else
+  ac_cv_implicit_use_stratimikos=no
+fi;
+
+if test "Xyes
+  " != "Xno"; then
+  ac_cv_rythmos_using_stratimikos_default=$ac_cv_implicit_use_stratimikos
+else
+  ac_cv_rythmos_using_stratimikos_default=no
+fi
+
+# Check whether --enable-rythmos-stratimikos or --disable-rythmos-stratimikos was given.
+if test "${enable_rythmos_stratimikos+set}" = set; then
+  enableval="$enable_rythmos_stratimikos"
+  ac_cv_use_stratimikos=$enableval
+else
+  ac_cv_use_stratimikos=$ac_cv_rythmos_using_stratimikos_default
+fi;
+
+echo "$as_me:$LINENO: checking whether to build optional stratimikos dependent code in rythmos" >&5
+echo $ECHO_N "checking whether to build optional stratimikos dependent code in rythmos... $ECHO_C" >&6
+
+if test "X$ac_cv_use_stratimikos" != "Xno"; then
+  echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_RYTHMOS_STRATIMIKOS 1
+_ACEOF
+
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+
+
+if test "X$ac_cv_use_stratimikos" = "Xyes"; then
+  ENABLE_RYTHMOS_STRATIMIKOS_TRUE=
+  ENABLE_RYTHMOS_STRATIMIKOS_FALSE='#'
+else
+  ENABLE_RYTHMOS_STRATIMIKOS_TRUE='#'
+  ENABLE_RYTHMOS_STRATIMIKOS_FALSE=
+fi
+
+
+
+
+
+
+# Check whether --enable-epetraext or --disable-epetraext was given.
+if test "${enable_epetraext+set}" = set; then
+  enableval="$enable_epetraext"
+  ac_cv_implicit_use_epetraext=$enableval
+else
+  ac_cv_implicit_use_epetraext=no
+fi;
+
+# Check whether --enable-thyra or --disable-thyra was given.
+if test "${enable_thyra+set}" = set; then
+  enableval="$enable_thyra"
+  ac_cv_implicit_use_thyra=$enableval
+else
+  ac_cv_implicit_use_thyra=no
+fi;
+
+if test "Xyes
+  " != "Xno"; then
+  if test "X$ac_cv_implicit_use_epetraext" != "Xno"; then
+    ac_cv_epetraext_using_thyra_default=$ac_cv_implicit_use_thyra
+  else
+    ac_cv_epetraext_using_thyra_default=no
+  fi
+else
+  ac_cv_epetraext_using_thyra_default=no
+fi
+
+# Check whether --enable-epetraext-thyra or --disable-epetraext-thyra was given.
+if test "${enable_epetraext_thyra+set}" = set; then
+  enableval="$enable_epetraext_thyra"
+  ac_cv_use_thyra=$enableval
+else
+  ac_cv_use_thyra=$ac_cv_epetraext_using_thyra_default
+fi;
+
+echo "$as_me:$LINENO: checking whether to build optional thyra dependent code in epetraext" >&5
+echo $ECHO_N "checking whether to build optional thyra dependent code in epetraext... $ECHO_C" >&6
+
+if test "X$ac_cv_use_thyra" != "Xno"; then
+  echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_EPETRAEXT_THYRA 1
+_ACEOF
+
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+
+
+if test "X$ac_cv_use_thyra" = "Xyes"; then
+  ENABLE_EPETRAEXT_THYRA_TRUE=
+  ENABLE_EPETRAEXT_THYRA_FALSE='#'
+else
+  ENABLE_EPETRAEXT_THYRA_TRUE='#'
+  ENABLE_EPETRAEXT_THYRA_FALSE=
 fi
 
 
@@ -8304,7 +8316,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_verb"
-(eval echo $as_me:8307: \"$ac_link\") >&5
+(eval echo $as_me:8319: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
@@ -8382,7 +8394,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_cv_prog_f77_v"
-(eval echo $as_me:8385: \"$ac_link\") >&5
+(eval echo $as_me:8397: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
@@ -10928,7 +10940,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_verb"
-(eval echo $as_me:10931: \"$ac_link\") >&5
+(eval echo $as_me:10943: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
@@ -11006,7 +11018,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_cv_prog_f77_v"
-(eval echo $as_me:11009: \"$ac_link\") >&5
+(eval echo $as_me:11021: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
@@ -11394,24 +11406,24 @@ echo "$as_me: error: conditional \"USING_GNUMAKE\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
-if test -z "${ENABLE_RYTHMOS_AMESOS_TRUE}" && test -z "${ENABLE_RYTHMOS_AMESOS_FALSE}"; then
-  { { echo "$as_me:$LINENO: error: conditional \"ENABLE_RYTHMOS_AMESOS\" was never defined.
-Usually this means the macro was only invoked conditionally." >&5
-echo "$as_me: error: conditional \"ENABLE_RYTHMOS_AMESOS\" was never defined.
-Usually this means the macro was only invoked conditionally." >&2;}
-   { (exit 1); exit 1; }; }
-fi
-if test -z "${ENABLE_RYTHMOS_AZTECOO_TRUE}" && test -z "${ENABLE_RYTHMOS_AZTECOO_FALSE}"; then
-  { { echo "$as_me:$LINENO: error: conditional \"ENABLE_RYTHMOS_AZTECOO\" was never defined.
-Usually this means the macro was only invoked conditionally." >&5
-echo "$as_me: error: conditional \"ENABLE_RYTHMOS_AZTECOO\" was never defined.
-Usually this means the macro was only invoked conditionally." >&2;}
-   { (exit 1); exit 1; }; }
-fi
 if test -z "${ENABLE_RYTHMOS_NOX_TRUE}" && test -z "${ENABLE_RYTHMOS_NOX_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"ENABLE_RYTHMOS_NOX\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"ENABLE_RYTHMOS_NOX\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${ENABLE_RYTHMOS_STRATIMIKOS_TRUE}" && test -z "${ENABLE_RYTHMOS_STRATIMIKOS_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"ENABLE_RYTHMOS_STRATIMIKOS\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"ENABLE_RYTHMOS_STRATIMIKOS\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${ENABLE_EPETRAEXT_THYRA_TRUE}" && test -z "${ENABLE_EPETRAEXT_THYRA_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"ENABLE_EPETRAEXT_THYRA\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"ENABLE_EPETRAEXT_THYRA\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -12147,12 +12159,12 @@ s,@USING_PERL_TRUE@,$USING_PERL_TRUE,;t t
 s,@USING_PERL_FALSE@,$USING_PERL_FALSE,;t t
 s,@USING_GNUMAKE_TRUE@,$USING_GNUMAKE_TRUE,;t t
 s,@USING_GNUMAKE_FALSE@,$USING_GNUMAKE_FALSE,;t t
-s,@ENABLE_RYTHMOS_AMESOS_TRUE@,$ENABLE_RYTHMOS_AMESOS_TRUE,;t t
-s,@ENABLE_RYTHMOS_AMESOS_FALSE@,$ENABLE_RYTHMOS_AMESOS_FALSE,;t t
-s,@ENABLE_RYTHMOS_AZTECOO_TRUE@,$ENABLE_RYTHMOS_AZTECOO_TRUE,;t t
-s,@ENABLE_RYTHMOS_AZTECOO_FALSE@,$ENABLE_RYTHMOS_AZTECOO_FALSE,;t t
 s,@ENABLE_RYTHMOS_NOX_TRUE@,$ENABLE_RYTHMOS_NOX_TRUE,;t t
 s,@ENABLE_RYTHMOS_NOX_FALSE@,$ENABLE_RYTHMOS_NOX_FALSE,;t t
+s,@ENABLE_RYTHMOS_STRATIMIKOS_TRUE@,$ENABLE_RYTHMOS_STRATIMIKOS_TRUE,;t t
+s,@ENABLE_RYTHMOS_STRATIMIKOS_FALSE@,$ENABLE_RYTHMOS_STRATIMIKOS_FALSE,;t t
+s,@ENABLE_EPETRAEXT_THYRA_TRUE@,$ENABLE_EPETRAEXT_THYRA_TRUE,;t t
+s,@ENABLE_EPETRAEXT_THYRA_FALSE@,$ENABLE_EPETRAEXT_THYRA_FALSE,;t t
 s,@HAVE_NEWP_SWAHILI_TRUE@,$HAVE_NEWP_SWAHILI_TRUE,;t t
 s,@HAVE_NEWP_SWAHILI_FALSE@,$HAVE_NEWP_SWAHILI_FALSE,;t t
 s,@BUILD_TESTS_TRUE@,$BUILD_TESTS_TRUE,;t t
