Added a NOX Random class to encapsulate the calculation of random numbers. The algorithm used to compute random numbers is the same as that used by Epetra and relies on the POSIX rand() system call to compute a seed number.
Added methods to the NOX::Abstract::Vector class to fill a vector with random
values and set the random number seed.  These methods have default
implementations that print an error message and throw an error.

Added an autoconf test to check for cstdlib and stdlib.h and include them in
NOX_Common.H

diff --git a/packages/nox/configure b/packages/nox/configure
--- a/packages/nox/configure
+++ b/packages/nox/configure
@@ -3452,6 +3452,114 @@ rm -f conftest.err conftest.$ac_ext
 fi
 rm -f conftest.$ac_objext conftest.$ac_ext
 
+#cstdlib
+
+# Note that the check for cmath had to be changed from AC_TRY_CPP to
+# AC_TRY_COMPILE to accomodate the TFLOPS cross-compilation.
+
+ac_ext=cc
+ac_cpp='$CXXCPP $CPPFLAGS'
+ac_compile='$CXX -c $CXXFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CXX -o conftest$ac_exeext $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
+
+echo "$as_me:$LINENO: checking for cstdlib" >&5
+echo $ECHO_N "checking for cstdlib... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+#include "confdefs.h"
+#include <cstdlib>
+#ifdef F77_DUMMY_MAIN
+#  ifdef __cplusplus
+     extern "C"
+#  endif
+   int F77_DUMMY_MAIN() { return 1; }
+#endif
+int
+main ()
+{
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+
+  echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_CSTDLIB
+_ACEOF
+
+
+else
+  echo "$as_me: failed program was:" >&5
+cat conftest.$ac_ext >&5
+
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+  echo "$as_me:$LINENO: checking for stdlib.h" >&5
+echo $ECHO_N "checking for stdlib.h... $ECHO_C" >&6
+  cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+#include "confdefs.h"
+#include "stdlib.h"
+_ACEOF
+if { (eval echo "$as_me:$LINENO: \"$ac_cpp conftest.$ac_ext\"") >&5
+  (eval $ac_cpp conftest.$ac_ext) 2>conftest.er1
+  ac_status=$?
+  egrep -v '^ *\+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } >/dev/null; then
+  if test -s conftest.err; then
+    ac_cpp_err=$ac_cxx_preproc_warn_flag
+  else
+    ac_cpp_err=
+  fi
+else
+  ac_cpp_err=yes
+fi
+if test -z "$ac_cpp_err"; then
+
+    echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_STDLIB_H
+_ACEOF
+
+
+else
+  echo "$as_me: failed program was:" >&5
+  cat conftest.$ac_ext >&5
+
+    echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+    { echo "$as_me:$LINENO: You do not appear to have cstdlib nor stdlib.h!!" >&5
+echo "$as_me: You do not appear to have cstdlib nor stdlib.h!!" >&6;}
+
+
+fi
+rm -f conftest.err conftest.$ac_ext
+
+
+fi
+rm -f conftest.$ac_objext conftest.$ac_ext
+
 # can we say using std::ostream?
 ac_ext=cc
 ac_cpp='$CXXCPP $CPPFLAGS'
@@ -4263,7 +4371,7 @@ fi
 
 
 # Provide some information about the compiler.
-echo "$as_me:4266:" \
+echo "$as_me:4374:" \
      "checking for Fortran 77 compiler version" >&5
 ac_compiler=`set X $ac_compile; echo $2`
 { (eval echo "$as_me:$LINENO: \"$ac_compiler --version </dev/null >&5\"") >&5
@@ -4430,7 +4538,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_verb"
-(eval echo $as_me:4433: \"$ac_link\") >&5
+(eval echo $as_me:4541: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
@@ -4509,7 +4617,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FFLAGS
 FFLAGS="$FFLAGS $ac_cv_prog_f77_v"
-(eval echo $as_me:4512: \"$ac_link\") >&5
+(eval echo $as_me:4620: \"$ac_link\") >&5
 ac_f77_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f77_v_output" >&5
 FFLAGS=$ac_save_FFLAGS
