A few more minor changed to configure.ac.

diff --git a/packages/nox/configure b/packages/nox/configure
--- a/packages/nox/configure
+++ b/packages/nox/configure
@@ -4111,7 +4111,7 @@ if test ${USE_TRILINOS} = yes; then
 
    LDFLAGS="-L${TRILINOS_LIB_DIR} $LDFLAGS"
    TRILINOS_CXXFLAGS="-DEPETRA_${TRILINOS_COMM} -I${TRILINOS_EPETRA_INC} -I${TRILINOS_AZTECOO_INC}"
-   TRILINOS_LDADD="-lepetra -laztecoo -lifpack -ly12m"
+   TRILINOS_LDADD="-lepetra -laztecoo"
 
   ac_ext=f
 ac_compile='$F77 -c $FFLAGS conftest.$ac_ext >&5'
@@ -4595,6 +4595,78 @@ ac_compile='$CXX -c $CXXFLAGS $CPPFLAGS conftest.$ac_ext >&5'
 ac_link='$CXX -o conftest$ac_exeext $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
 ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
 
+echo "$as_me:$LINENO: checking for az2ifp_blockmatrix in -lifpack" >&5
+echo $ECHO_N "checking for az2ifp_blockmatrix in -lifpack... $ECHO_C" >&6
+if test "${ac_cv_lib_ifpack_az2ifp_blockmatrix+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lifpack  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+#include "confdefs.h"
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char az2ifp_blockmatrix ();
+#ifdef F77_DUMMY_MAIN
+#  ifdef __cplusplus
+     extern "C"
+#  endif
+   int F77_DUMMY_MAIN() { return 1; }
+#endif
+int
+main ()
+{
+az2ifp_blockmatrix ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_ifpack_az2ifp_blockmatrix=yes
+else
+  echo "$as_me: failed program was:" >&5
+cat conftest.$ac_ext >&5
+ac_cv_lib_ifpack_az2ifp_blockmatrix=no
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib_ifpack_az2ifp_blockmatrix" >&5
+echo "${ECHO_T}$ac_cv_lib_ifpack_az2ifp_blockmatrix" >&6
+if test $ac_cv_lib_ifpack_az2ifp_blockmatrix = yes; then
+  cat >>confdefs.h <<_ACEOF
+#define HAVE_LIBIFPACK 1
+_ACEOF
+
+  LIBS="-lifpack $LIBS"
+
+fi
+
+#  AC_CHECK_LIB(aztecoo,[AztecOO::Iterate(int a, double b)])
+#  AC_CHECK_LIB(epetra,)
+  ac_ext=cc
+ac_cpp='$CXXCPP $CPPFLAGS'
+ac_compile='$CXX -c $CXXFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CXX -o conftest$ac_exeext $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
+
 fi
 
 # ------------------------------------------------------------------------
@@ -4609,6 +4681,7 @@ fi
 # Checks for libraries
 # ------------------------------------------------------------------------
 
+# THIS TEST ISN'T WORKING - WILL COME BACK TO IT LATER.
 # Check that all libraries will link with C++
 
 # ------------------------------------------------------------------------
