Added the Thyra group and a serial test that uses stratimikos underneath.  This test is not passing yet.  I have to talk to Ross about some things tomorrow.
Eventually, you can enable the build with --enable-nox-thyra.  This also requres --enable-thyra and --enable-stratimikos.

I'm committing this in it's current state so that Eric can start on the LOCA/Thyra group for the release.

diff --git a/packages/nox/configure b/packages/nox/configure
--- a/packages/nox/configure
+++ b/packages/nox/configure
@@ -781,6 +781,9 @@ ADDON_loca_petsc_TESTS
 BUILD_BELOS_TESTS_TRUE
 BUILD_BELOS_TESTS_FALSE
 ADDON_belos_TESTS
+BUILD_THYRA_TESTS_TRUE
+BUILD_THYRA_TESTS_FALSE
+ADDON_thyra_TESTS
 BUILD_TESTUTILS_TRUE
 BUILD_TESTUTILS_FALSE
 BUILD_LAPACK_EXAMPLES_TRUE
@@ -9144,6 +9147,53 @@ fi
 
 
 
+  # thyra testing
+
+    { echo "$as_me:$LINENO: checking whether we should build the nox thyra regression tests" >&5
+echo $ECHO_N "checking whether we should build the nox thyra regression tests... $ECHO_C" >&6; }
+    if test X${ADDON_TESTS} = Xyes && test X${ADDON_thyra} = Xyes; then
+      { echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6; }
+      ADDON_thyra_TESTS=yes
+
+      { echo "$as_me:$LINENO: checking whether we should build the loca thyra regression tests" >&5
+echo $ECHO_N "checking whether we should build the loca thyra regression tests... $ECHO_C" >&6; }
+      if test X${BUILD_LIBLOCA} = Xyes; then
+	ADDON_loca_thyra_TESTS=yes
+        { echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6; }
+      else
+	ADDON_loca_thyra_TESTS=no
+        { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+      fi
+
+    else
+      { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+      ADDON_thyra_TESTS=no
+      { echo "$as_me:$LINENO: checking whether we should build the loca thyra regression tests" >&5
+echo $ECHO_N "checking whether we should build the loca thyra regression tests... $ECHO_C" >&6; }
+      { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+      ADDON_loca_thyra_TESTS=no
+    fi
+
+    if test X${ADDON_thyra_TESTS} = Xyes; then
+      REQUIRE_LIB_CHECK=yes
+    fi
+
+
+   if test X${ADDON_thyra_TESTS} = Xyes; then
+  BUILD_THYRA_TESTS_TRUE=
+  BUILD_THYRA_TESTS_FALSE='#'
+else
+  BUILD_THYRA_TESTS_TRUE='#'
+  BUILD_THYRA_TESTS_FALSE=
+fi
+
+
+
   # Determine whether to build the new test utils library
    if test X${REQUIRE_LIB_CHECK} = Xyes; then
   BUILD_TESTUTILS_TRUE=
@@ -15696,6 +15746,168 @@ echo "$as_me: error: Cannot find thyra include directory containing Thyra_Versio
   fi
 
 
+  save_CPPFLAGS=$CPPFLAGS
+  done=no
+
+  # First try the directories we already have
+  CPPFLAGS="$save_CPPFLAGS $ABS_TRILINOS_CPPFLAGS"
+  cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+#undef PACKAGE
+#undef PACKAGE_NAME
+#undef PACKAGE_BUGREPORT
+#undef PACKAGE_STRING
+#undef PACKAGE_TARNAME
+#undef PACKAGE_VERSION
+#undef VERSION
+#include "Stratimikos_Config.h"
+
+_ACEOF
+if { (ac_try="$ac_cpp conftest.$ac_ext"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_cpp conftest.$ac_ext") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } >/dev/null && {
+	 test -z "$ac_cxx_preproc_warn_flag$ac_cxx_werror_flag" ||
+	 test ! -s conftest.err
+       }; then
+  done=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+
+fi
+
+rm -f conftest.err conftest.$ac_ext
+  CPPFLAGS=$save_CPPFLAGS
+
+  # Next try the Trilinos build dir
+  if test $done = no; then
+    CPPFLAGS="-I../stratimikos/src $save_CPPFLAGS $ABS_TRILINOS_CPPFLAGS"
+    cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+#undef PACKAGE
+#undef PACKAGE_NAME
+#undef PACKAGE_BUGREPORT
+#undef PACKAGE_STRING
+#undef PACKAGE_TARNAME
+#undef PACKAGE_VERSION
+#undef VERSION
+#include "Stratimikos_Config.h"
+
+_ACEOF
+if { (ac_try="$ac_cpp conftest.$ac_ext"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_cpp conftest.$ac_ext") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } >/dev/null && {
+	 test -z "$ac_cxx_preproc_warn_flag$ac_cxx_werror_flag" ||
+	 test ! -s conftest.err
+       }; then
+   done=yes
+      REL_TRILINOS_CPPFLAGS="-I\$(top_builddir)/../stratimikos/src ${REL_TRILINOS_CPPFLAGS}"
+      ABS_TRILINOS_CPPFLAGS="-I../stratimikos/src ${ABS_TRILINOS_CPPFLAGS}"
+
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+
+fi
+
+rm -f conftest.err conftest.$ac_ext
+    CPPFLAGS=$save_CPPFLAGS
+  fi
+
+  # Next try the Trilinos source dir
+  if test $done = no && test -n "$srcdir"; then
+    CPPFLAGS="-I$srcdir/../stratimikos/src $save_CPPFLAGS $ABS_TRILINOS_CPPFLAGS"
+    cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+#undef PACKAGE
+#undef PACKAGE_NAME
+#undef PACKAGE_BUGREPORT
+#undef PACKAGE_STRING
+#undef PACKAGE_TARNAME
+#undef PACKAGE_VERSION
+#undef VERSION
+#include "Stratimikos_Config.h"
+
+_ACEOF
+if { (ac_try="$ac_cpp conftest.$ac_ext"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_cpp conftest.$ac_ext") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } >/dev/null && {
+	 test -z "$ac_cxx_preproc_warn_flag$ac_cxx_werror_flag" ||
+	 test ! -s conftest.err
+       }; then
+   done=yes
+      REL_TRILINOS_CPPFLAGS="-I\$(top_srcdir)/../stratimikos/src ${REL_TRILINOS_CPPFLAGS}"
+      ABS_TRILINOS_CPPFLAGS="-I$srcdir/../stratimikos/src ${ABS_TRILINOS_CPPFLAGS}"
+
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+
+fi
+
+rm -f conftest.err conftest.$ac_ext
+    CPPFLAGS=$save_CPPFLAGS
+  fi
+
+  if test $done = no; then
+    echo "------"
+    echo "Cannot preprocess the include file Stratimikos_Config.h, part of the stratimikos package."
+    echo "Try --with-incdir=\"-I<dir1> -I<dir2>\""
+    echo "------"
+    { { echo "$as_me:$LINENO: error: Cannot find stratimikos include directory containing Stratimikos_Config.h" >&5
+echo "$as_me: error: Cannot find stratimikos include directory containing Stratimikos_Config.h" >&2;}
+   { (exit 1); exit 1; }; }
+  fi
+
+
 cat >>confdefs.h <<\_ACEOF
 #define HAVE_NOX_THYRA 1
 _ACEOF
@@ -16329,7 +16541,7 @@ echo "${ECHO_T}$WITH_PRERELEASE" >&6; }
 # Output files
 # ------------------------------------------------------------------------
 
-ac_config_files="$ac_config_files Makefile Makefile.export.nox doc/Makefile doc/Doxyfile src/Makefile src-lapack/Makefile src-epetra/Makefile src-petsc/Makefile src-belos/Makefile src-thyra/Makefile src-loca/Makefile src-loca/doc/Makefile src-loca/src/Makefile src-loca/src-epetra/Makefile src-loca/src-lapack/Makefile src-loca/src-mf/Makefile examples/Makefile examples/lapack/Makefile examples/lapack/NOX_SimpleExamples/Makefile examples/lapack/LOCA_Chan/Makefile examples/lapack/LOCA_Brusselator/Makefile examples/lapack/LOCA_1DFDPitchfork/Makefile examples/epetra/Makefile examples/epetra/NOX_1DFEMNonlinear/Makefile examples/epetra/NOX_Sacado_FEApp/Makefile examples/epetra/LOCA_Tcubed/Makefile examples/epetra/LOCA_Brusselator_xyzt/Makefile examples/epetra/LOCA_Sacado_FEApp/Makefile examples/petsc/Makefile examples/petsc/DS6.5.1/Makefile examples/petsc/1DFiniteDifference/Makefile test/Makefile test/basic/Makefile test/utils/Makefile test/lapack/Makefile test/lapack/NOX/Makefile test/lapack/NOX_NewTest/Makefile test/lapack/NOX_Group/Makefile test/lapack/LOCA_TestProblems/Makefile test/lapack/LOCA_UnitTests/Makefile test/lapack/LOCA_ChanProblem/Makefile test/epetra/Makefile test/epetra/NOX_NewTest/Makefile test/epetra/NOX_Vector/Makefile test/epetra/NOX_Operators/Makefile test/epetra/NOX_Group/Makefile test/epetra/LOCA_TestProblems/Makefile test/epetra/LOCA_UnitTests/Makefile test/epetra/LOCA_Tcubed/Makefile test/epetra/LOCA_Pitchfork/Makefile test/epetra/LOCA_Brusselator/Makefile test/epetra/LOCA_Brusselator_xyzt/Makefile test/epetra/LOCA_MultiPoint_Tcubed/Makefile test/epetra/1Dfem/Makefile test/epetra/MultiPhysics/Makefile test/epetra/DS6.5.1/Makefile test/epetra/Brusselator/Makefile test/epetra/PelletTransport/Makefile test/epetra/FiniteDifferenceColoring/Makefile test/petsc/Makefile"
+ac_config_files="$ac_config_files Makefile Makefile.export.nox doc/Makefile doc/Doxyfile src/Makefile src-lapack/Makefile src-epetra/Makefile src-petsc/Makefile src-belos/Makefile src-thyra/Makefile src-loca/Makefile src-loca/doc/Makefile src-loca/src/Makefile src-loca/src-epetra/Makefile src-loca/src-lapack/Makefile src-loca/src-mf/Makefile examples/Makefile examples/lapack/Makefile examples/lapack/NOX_SimpleExamples/Makefile examples/lapack/LOCA_Chan/Makefile examples/lapack/LOCA_Brusselator/Makefile examples/lapack/LOCA_1DFDPitchfork/Makefile examples/epetra/Makefile examples/epetra/NOX_1DFEMNonlinear/Makefile examples/epetra/NOX_Sacado_FEApp/Makefile examples/epetra/LOCA_Tcubed/Makefile examples/epetra/LOCA_Brusselator_xyzt/Makefile examples/epetra/LOCA_Sacado_FEApp/Makefile examples/petsc/Makefile examples/petsc/DS6.5.1/Makefile examples/petsc/1DFiniteDifference/Makefile test/Makefile test/basic/Makefile test/utils/Makefile test/lapack/Makefile test/lapack/NOX/Makefile test/lapack/NOX_NewTest/Makefile test/lapack/NOX_Group/Makefile test/lapack/LOCA_TestProblems/Makefile test/lapack/LOCA_UnitTests/Makefile test/lapack/LOCA_ChanProblem/Makefile test/epetra/Makefile test/epetra/NOX_NewTest/Makefile test/epetra/NOX_Vector/Makefile test/epetra/NOX_Operators/Makefile test/epetra/NOX_Group/Makefile test/epetra/LOCA_TestProblems/Makefile test/epetra/LOCA_UnitTests/Makefile test/epetra/LOCA_Tcubed/Makefile test/epetra/LOCA_Pitchfork/Makefile test/epetra/LOCA_Brusselator/Makefile test/epetra/LOCA_Brusselator_xyzt/Makefile test/epetra/LOCA_MultiPoint_Tcubed/Makefile test/epetra/1Dfem/Makefile test/epetra/MultiPhysics/Makefile test/epetra/DS6.5.1/Makefile test/epetra/Brusselator/Makefile test/epetra/PelletTransport/Makefile test/epetra/FiniteDifferenceColoring/Makefile test/epetra/Thyra_2Dsim/Makefile test/petsc/Makefile"
 
 
 cat >confcache <<\_ACEOF
@@ -16621,6 +16833,13 @@ if test -z "${BUILD_BELOS_TESTS_TRUE}" && test -z "${BUILD_BELOS_TESTS_FALSE}"; 
   { { echo "$as_me:$LINENO: error: conditional \"BUILD_BELOS_TESTS\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"BUILD_BELOS_TESTS\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${BUILD_THYRA_TESTS_TRUE}" && test -z "${BUILD_THYRA_TESTS_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"BUILD_THYRA_TESTS\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"BUILD_THYRA_TESTS\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -17257,6 +17476,7 @@ do
     "test/epetra/Brusselator/Makefile") CONFIG_FILES="$CONFIG_FILES test/epetra/Brusselator/Makefile" ;;
     "test/epetra/PelletTransport/Makefile") CONFIG_FILES="$CONFIG_FILES test/epetra/PelletTransport/Makefile" ;;
     "test/epetra/FiniteDifferenceColoring/Makefile") CONFIG_FILES="$CONFIG_FILES test/epetra/FiniteDifferenceColoring/Makefile" ;;
+    "test/epetra/Thyra_2Dsim/Makefile") CONFIG_FILES="$CONFIG_FILES test/epetra/Thyra_2Dsim/Makefile" ;;
     "test/petsc/Makefile") CONFIG_FILES="$CONFIG_FILES test/petsc/Makefile" ;;
 
   *) { { echo "$as_me:$LINENO: error: invalid argument: $ac_config_target" >&5
@@ -17527,6 +17747,9 @@ ADDON_loca_petsc_TESTS!$ADDON_loca_petsc_TESTS$ac_delim
 BUILD_BELOS_TESTS_TRUE!$BUILD_BELOS_TESTS_TRUE$ac_delim
 BUILD_BELOS_TESTS_FALSE!$BUILD_BELOS_TESTS_FALSE$ac_delim
 ADDON_belos_TESTS!$ADDON_belos_TESTS$ac_delim
+BUILD_THYRA_TESTS_TRUE!$BUILD_THYRA_TESTS_TRUE$ac_delim
+BUILD_THYRA_TESTS_FALSE!$BUILD_THYRA_TESTS_FALSE$ac_delim
+ADDON_thyra_TESTS!$ADDON_thyra_TESTS$ac_delim
 BUILD_TESTUTILS_TRUE!$BUILD_TESTUTILS_TRUE$ac_delim
 BUILD_TESTUTILS_FALSE!$BUILD_TESTUTILS_FALSE$ac_delim
 BUILD_LAPACK_EXAMPLES_TRUE!$BUILD_LAPACK_EXAMPLES_TRUE$ac_delim
@@ -17552,9 +17775,6 @@ BUILD_LOCAANASAZI_FALSE!$BUILD_LOCAANASAZI_FALSE$ac_delim
 BUILD_LIBLOCAMF_TRUE!$BUILD_LIBLOCAMF_TRUE$ac_delim
 BUILD_LIBLOCAMF_FALSE!$BUILD_LIBLOCAMF_FALSE$ac_delim
 MF_INCDIR!$MF_INCDIR$ac_delim
-MF_LIBDIR!$MF_LIBDIR$ac_delim
-MF_LIBS!$MF_LIBS$ac_delim
-BUILD_NOX_EPETRAEXT_SUPPORT_TRUE!$BUILD_NOX_EPETRAEXT_SUPPORT_TRUE$ac_delim
 _ACEOF
 
   if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 97; then
@@ -17596,6 +17816,9 @@ _ACEOF
 ac_delim='%!_!# '
 for ac_last_try in false false false false false :; do
   cat >conf$$subs.sed <<_ACEOF
+MF_LIBDIR!$MF_LIBDIR$ac_delim
+MF_LIBS!$MF_LIBS$ac_delim
+BUILD_NOX_EPETRAEXT_SUPPORT_TRUE!$BUILD_NOX_EPETRAEXT_SUPPORT_TRUE$ac_delim
 BUILD_NOX_EPETRAEXT_SUPPORT_FALSE!$BUILD_NOX_EPETRAEXT_SUPPORT_FALSE$ac_delim
 BUILD_EPETRA_MULTIPHYSICS_TRUE!$BUILD_EPETRA_MULTIPHYSICS_TRUE$ac_delim
 BUILD_EPETRA_MULTIPHYSICS_FALSE!$BUILD_EPETRA_MULTIPHYSICS_FALSE$ac_delim
@@ -17621,7 +17844,7 @@ LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 23; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 26; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
