Added an example that uses the LOCA interface to EpetraExt::ModelEvaluator that is based on the Sacado FEApp.

diff --git a/packages/nox/configure b/packages/nox/configure
--- a/packages/nox/configure
+++ b/packages/nox/configure
@@ -816,6 +816,8 @@ BUILD_NOX_EPETRA_ML_SUPPORT_TRUE
 BUILD_NOX_EPETRA_ML_SUPPORT_FALSE
 ENABLE_NOX_SACADO_TRUE
 ENABLE_NOX_SACADO_FALSE
+ENABLE_LOCA_SACADO_TRUE
+ENABLE_LOCA_SACADO_FALSE
 FLIBS
 BLAS_LIBS
 LAPACK_LIBS
@@ -1477,7 +1479,7 @@ Optional Features:
                           --<en|dis>able-nox-ml.
   --enable-nox-ml         Build ml support into the noxepetra library.
   --enable-sacado         Build the Sacado adapater support in NOX. Can be
-                          overridden with --disable-epetraext-sacado.
+                          overridden with --disable-nox-sacado.
   --enable-nox-sacado     Build the Sacado adapater support in NOX.
   --enable-prerelease     Enable compilation and documentation of prerelease
                           code. Prerelease code is code under development that
@@ -9698,6 +9700,14 @@ fi
 
 
 
+ if test "X$BUILD_LIBLOCA" = "Xyes" && test "X$ac_cv_use_sacado" = "Xyes"; then
+  ENABLE_LOCA_SACADO_TRUE=
+  ENABLE_LOCA_SACADO_FALSE='#'
+else
+  ENABLE_LOCA_SACADO_TRUE='#'
+  ENABLE_LOCA_SACADO_FALSE=
+fi
+
 
 # ------------------------------------------------------------------------
 # User defined directories
@@ -16319,7 +16329,7 @@ echo "${ECHO_T}$WITH_PRERELEASE" >&6; }
 # Output files
 # ------------------------------------------------------------------------
 
-ac_config_files="$ac_config_files Makefile Makefile.export.nox doc/Makefile doc/Doxyfile src/Makefile src-lapack/Makefile src-epetra/Makefile src-petsc/Makefile src-belos/Makefile src-thyra/Makefile src-loca/Makefile src-loca/doc/Makefile src-loca/src/Makefile src-loca/src-epetra/Makefile src-loca/src-lapack/Makefile src-loca/src-mf/Makefile examples/Makefile examples/lapack/Makefile examples/lapack/NOX_SimpleExamples/Makefile examples/lapack/LOCA_Chan/Makefile examples/lapack/LOCA_Brusselator/Makefile examples/lapack/LOCA_1DFDPitchfork/Makefile examples/epetra/Makefile examples/epetra/NOX_1DFEMNonlinear/Makefile examples/epetra/NOX_Sacado_FEApp/Makefile examples/epetra/LOCA_Tcubed/Makefile examples/epetra/LOCA_Brusselator_xyzt/Makefile examples/petsc/Makefile examples/petsc/DS6.5.1/Makefile examples/petsc/1DFiniteDifference/Makefile test/Makefile test/basic/Makefile test/utils/Makefile test/lapack/Makefile test/lapack/NOX/Makefile test/lapack/NOX_NewTest/Makefile test/lapack/NOX_Group/Makefile test/lapack/LOCA_TestProblems/Makefile test/lapack/LOCA_UnitTests/Makefile test/lapack/LOCA_ChanProblem/Makefile test/epetra/Makefile test/epetra/NOX_NewTest/Makefile test/epetra/NOX_Vector/Makefile test/epetra/NOX_Operators/Makefile test/epetra/NOX_Group/Makefile test/epetra/LOCA_TestProblems/Makefile test/epetra/LOCA_UnitTests/Makefile test/epetra/LOCA_Tcubed/Makefile test/epetra/LOCA_Pitchfork/Makefile test/epetra/LOCA_Brusselator/Makefile test/epetra/LOCA_Brusselator_xyzt/Makefile test/epetra/LOCA_MultiPoint_Tcubed/Makefile test/epetra/1Dfem/Makefile test/epetra/MultiPhysics/Makefile test/epetra/DS6.5.1/Makefile test/epetra/Brusselator/Makefile test/epetra/FiniteDifferenceColoring/Makefile test/petsc/Makefile"
+ac_config_files="$ac_config_files Makefile Makefile.export.nox doc/Makefile doc/Doxyfile src/Makefile src-lapack/Makefile src-epetra/Makefile src-petsc/Makefile src-belos/Makefile src-thyra/Makefile src-loca/Makefile src-loca/doc/Makefile src-loca/src/Makefile src-loca/src-epetra/Makefile src-loca/src-lapack/Makefile src-loca/src-mf/Makefile examples/Makefile examples/lapack/Makefile examples/lapack/NOX_SimpleExamples/Makefile examples/lapack/LOCA_Chan/Makefile examples/lapack/LOCA_Brusselator/Makefile examples/lapack/LOCA_1DFDPitchfork/Makefile examples/epetra/Makefile examples/epetra/NOX_1DFEMNonlinear/Makefile examples/epetra/NOX_Sacado_FEApp/Makefile examples/epetra/LOCA_Tcubed/Makefile examples/epetra/LOCA_Brusselator_xyzt/Makefile examples/epetra/LOCA_Sacado_FEApp/Makefile examples/petsc/Makefile examples/petsc/DS6.5.1/Makefile examples/petsc/1DFiniteDifference/Makefile test/Makefile test/basic/Makefile test/utils/Makefile test/lapack/Makefile test/lapack/NOX/Makefile test/lapack/NOX_NewTest/Makefile test/lapack/NOX_Group/Makefile test/lapack/LOCA_TestProblems/Makefile test/lapack/LOCA_UnitTests/Makefile test/lapack/LOCA_ChanProblem/Makefile test/epetra/Makefile test/epetra/NOX_NewTest/Makefile test/epetra/NOX_Vector/Makefile test/epetra/NOX_Operators/Makefile test/epetra/NOX_Group/Makefile test/epetra/LOCA_TestProblems/Makefile test/epetra/LOCA_UnitTests/Makefile test/epetra/LOCA_Tcubed/Makefile test/epetra/LOCA_Pitchfork/Makefile test/epetra/LOCA_Brusselator/Makefile test/epetra/LOCA_Brusselator_xyzt/Makefile test/epetra/LOCA_MultiPoint_Tcubed/Makefile test/epetra/1Dfem/Makefile test/epetra/MultiPhysics/Makefile test/epetra/DS6.5.1/Makefile test/epetra/Brusselator/Makefile test/epetra/FiniteDifferenceColoring/Makefile test/petsc/Makefile"
 
 
 cat >confcache <<\_ACEOF
@@ -16702,6 +16712,13 @@ if test -z "${ENABLE_NOX_SACADO_TRUE}" && test -z "${ENABLE_NOX_SACADO_FALSE}"; 
   { { echo "$as_me:$LINENO: error: conditional \"ENABLE_NOX_SACADO\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"ENABLE_NOX_SACADO\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${ENABLE_LOCA_SACADO_TRUE}" && test -z "${ENABLE_LOCA_SACADO_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"ENABLE_LOCA_SACADO\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"ENABLE_LOCA_SACADO\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -17208,6 +17225,7 @@ do
     "examples/epetra/NOX_Sacado_FEApp/Makefile") CONFIG_FILES="$CONFIG_FILES examples/epetra/NOX_Sacado_FEApp/Makefile" ;;
     "examples/epetra/LOCA_Tcubed/Makefile") CONFIG_FILES="$CONFIG_FILES examples/epetra/LOCA_Tcubed/Makefile" ;;
     "examples/epetra/LOCA_Brusselator_xyzt/Makefile") CONFIG_FILES="$CONFIG_FILES examples/epetra/LOCA_Brusselator_xyzt/Makefile" ;;
+    "examples/epetra/LOCA_Sacado_FEApp/Makefile") CONFIG_FILES="$CONFIG_FILES examples/epetra/LOCA_Sacado_FEApp/Makefile" ;;
     "examples/petsc/Makefile") CONFIG_FILES="$CONFIG_FILES examples/petsc/Makefile" ;;
     "examples/petsc/DS6.5.1/Makefile") CONFIG_FILES="$CONFIG_FILES examples/petsc/DS6.5.1/Makefile" ;;
     "examples/petsc/1DFiniteDifference/Makefile") CONFIG_FILES="$CONFIG_FILES examples/petsc/1DFiniteDifference/Makefile" ;;
@@ -17584,6 +17602,8 @@ BUILD_NOX_EPETRA_ML_SUPPORT_TRUE!$BUILD_NOX_EPETRA_ML_SUPPORT_TRUE$ac_delim
 BUILD_NOX_EPETRA_ML_SUPPORT_FALSE!$BUILD_NOX_EPETRA_ML_SUPPORT_FALSE$ac_delim
 ENABLE_NOX_SACADO_TRUE!$ENABLE_NOX_SACADO_TRUE$ac_delim
 ENABLE_NOX_SACADO_FALSE!$ENABLE_NOX_SACADO_FALSE$ac_delim
+ENABLE_LOCA_SACADO_TRUE!$ENABLE_LOCA_SACADO_TRUE$ac_delim
+ENABLE_LOCA_SACADO_FALSE!$ENABLE_LOCA_SACADO_FALSE$ac_delim
 FLIBS!$FLIBS$ac_delim
 BLAS_LIBS!$BLAS_LIBS$ac_delim
 LAPACK_LIBS!$LAPACK_LIBS$ac_delim
@@ -17600,7 +17620,7 @@ LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 21; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 23; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
