Significant overhaul to improve configure checks and fix thread bug on Mac OS X

diff --git a/packages/PyTrilinos/src/Makefile.in b/packages/PyTrilinos/src/Makefile.in
--- a/packages/PyTrilinos/src/Makefile.in
+++ b/packages/PyTrilinos/src/Makefile.in
@@ -41,6 +41,68 @@
 # 
 # ************************************************************************
 # @HEADER
+
+#AUTOMAKE_OPTIONS = foreign
+
+#ACLOCAL	= aclocal -I config
+
+#
+#       I believe that by switching to AUX_DIR(../../config) one 
+#       could get rid of these.
+#
+# We will list some source files here because we don't compile them in the
+# usual way.
+#EXTRA_DIST = \
+#	Epetra_VectorHelper.h  NumPyArray.cxx \
+#	__init__.py            NumPyArray.h \
+#	EpetraExt.i            NumPyWrapper.cxx \
+#	Epetra_NumPyVector.cxx NumPyWrapper.h \
+#	Epetra_NumPyVector.h \
+#	Epetra.py              PyTrilinos.h \
+#	Epetra_VectorHelper.cxx \
+#	numeric_include.h      RawEpetra.i
+
+#AUX_DIST = config/install-sh config/missing config/mkinstalldirs 
+#
+#  Again, I hope that AUX_DIR(../../config) eliminates these
+#  config/install-sh config/missing config/mkinstalldirs 
+
+#MAINTAINERCLEANFILES = Makefile.in \
+#	$(AUX_DIST) 
+
+# @HEADER
+# ************************************************************************
+# 
+#               Epetra: Linear Algebra Services Package 
+#                 Copyright (2002) Sandia Corporation
+# 
+# Under terms of Contract DE-AC04-94AL85000, there is a non-exclusive
+# license for use of this work by or on behalf of the U.S. Government.
+# 
+# This library is free software; you can redistribute it and/or modify
+# it under the terms of the GNU Lesser General Public License as
+# published by the Free Software Foundation; either version 2.1 of the
+# License, or (at your option) any later version.
+#  
+# This library is distributed in the hope that it will be useful, but
+# WITHOUT ANY WARRANTY; without even the implied warranty of
+# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
+# Lesser General Public License for more details.
+#                                                                                 
+# You should have received a copy of the GNU Lesser General Public
+# License along with this library; if not, write to the Free Software
+# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307
+# USA                                                                                
+# Questions? Contact Tammy Kolda (tgkolda@sandia.gov) or Roger Pawlowski
+# (rppawlo@sandia.gov), Sandia National Laboratories.
+# 
+# ************************************************************************
+# @HEADER
+
+# ------------------------------------------------------------------------
+# Rules for building python interface files using swig.  Automatic 
+# dependency tracking for swig interface files is implemented.
+# ------------------------------------------------------------------------
 srcdir = @srcdir@
 top_srcdir = @top_srcdir@
 VPATH = @srcdir@
@@ -62,9 +124,10 @@ NORMAL_UNINSTALL = :
 PRE_UNINSTALL = :
 POST_UNINSTALL = :
 host_triplet = @host@
-subdir = src
 DIST_COMMON = $(srcdir)/Makefile.am $(srcdir)/Makefile.in \
-	$(srcdir)/PyTrilinos_config.h.in
+	$(srcdir)/PyTrilinos_config.h.in $(srcdir)/__init__.py.in \
+	$(top_srcdir)/config/swig.am
+subdir = src
 ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
 am__aclocal_m4_deps = $(top_srcdir)/config/ac_cxx_bool.m4 \
 	$(top_srcdir)/config/ac_cxx_have_stl.m4 \
@@ -91,20 +154,11 @@ am__configure_deps = $(am__aclocal_m4_deps) $(CONFIGURE_DEPENDENCIES) \
 	$(ACLOCAL_M4)
 mkinstalldirs = $(SHELL) $(top_srcdir)/config/mkinstalldirs
 CONFIG_HEADER = PyTrilinos_config.h
-CONFIG_CLEAN_FILES =
+CONFIG_CLEAN_FILES = __init__.py
 SOURCES =
 DIST_SOURCES =
-RECURSIVE_TARGETS = all-recursive check-recursive dvi-recursive \
-	html-recursive info-recursive install-data-recursive \
-	install-exec-recursive install-info-recursive \
-	install-recursive installcheck-recursive installdirs-recursive \
-	pdf-recursive ps-recursive uninstall-info-recursive \
-	uninstall-recursive
-ETAGS = etags
-CTAGS = ctags
-DIST_SUBDIRS = $(SUBDIRS)
 DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)
-ACLOCAL = aclocal -I config
+ACLOCAL = @ACLOCAL@
 ALTERNATE_AR = @ALTERNATE_AR@
 AMDEP_FALSE = @AMDEP_FALSE@
 AMDEP_TRUE = @AMDEP_TRUE@
@@ -178,7 +232,7 @@ RANLIB = @RANLIB@
 SET_MAKE = @SET_MAKE@
 SHELL = @SHELL@
 STRIP = @STRIP@
-SWIG = swig
+SWIG = @SWIG@
 SWIG_LIB = @SWIG_LIB@
 SWIG_PYTHON_CPPFLAGS = @SWIG_PYTHON_CPPFLAGS@
 SWIG_PYTHON_OPT = @SWIG_PYTHON_OPT@
@@ -231,46 +285,41 @@ target_alias = @target_alias@
 target_cpu = @target_cpu@
 target_os = @target_os@
 target_vendor = @target_vendor@
-AUTOMAKE_OPTIONS = foreign
 
-#
-#       I believe that by switching to AUX_DIR(../../config) one 
-#       could get rid of these.
-#
-# We will list some source files here because we don't compile them in the
-# usual way.
-EXTRA_DIST = \
-	Epetra_VectorHelper.h  NumPyArray.cxx \
-	__init__.py            NumPyArray.h \
-	EpetraExt.i            NumPyWrapper.cxx \
-	Epetra_NumPyVector.cxx NumPyWrapper.h \
-	Epetra_NumPyVector.h \
-	Epetra.py              PyTrilinos.h \
-	Epetra_VectorHelper.cxx \
-	numeric_include.h      RawEpetra.i
-
-AUX_DIST = config/install-sh config/missing config/mkinstalldirs 
-#
-#  Again, I hope that AUX_DIR(../../config) eliminates these
-#  config/install-sh config/missing config/mkinstalldirs 
-MAINTAINERCLEANFILES = Makefile.in \
-	$(AUX_DIST) 
-
-NOX_SUBDIR = NOX
-SUBDIRS = $(NOX_SUBDIR)
-SWIG_FLAGS = -I$(top_srcdir)/src -Wall -python -c++
+# Include paths
 EPETRA_INC = -I$(top_srcdir)/../epetra/src
 EPETRAEXT_INC = -I$(top_srcdir)/../epetraext/src/transform \
                 -I$(top_srcdir)/../epetraext/src/coloring
 
-INTERFACES = RawEpetra.i EpetraExt.i
-WRAPPERS = $(patsubst %.i, %_wrap.cxx, $(INTERFACES))
-TARGET = $(WRAPPERS) NOX_Wrappers
+NOX_INC = -I$(top_srcdir)/../nox/src
+NOXEPETRA_INC = -I$(top_srcdir)/../nox/src-epetra
+CLEANFILES = $(DEPDIR)/*.Pi setup.txt $(WRAPPERS) $(PROXIES)
+@HAVE_SWIG_TRUE@SWIGCOMPILE = $(SWIG) $(SWIG_PYTHON_OPT) $(SWIG_CXXFLAGS)
+
+# Include swig rules
+SWIG_CXXFLAGS = \
+	$(EPETRA_INC)    \
+	$(EPETRAEXT_INC) \
+	$(NOX_INC)       \
+	$(NOXEPETRA_INC) \
+	-I$(srcdir)
+
+
+# Currently, this temporary directory is required to be present for the
+# setup.py script to work correctly
+tempdir = $(shell $(PYTHON) $(top_srcdir)/pyLocate --temp)
+
+# Define the SWIG interface files and the resulting wrapper files
+INTERFACES = Epetra.i EpetraExt.i NOX/Abstract.i NOX/Epetra.i NOX/Parameter.i \
+	     NOX/Solver.i NOX/StatusTest.i
+
+WRAPPERS = $(INTERFACES:.i=_wrap.cxx)
+PROXIES = $(INTERFACES:.i=.py      )
 all: PyTrilinos_config.h
-	$(MAKE) $(AM_MAKEFLAGS) all-recursive
+	$(MAKE) $(AM_MAKEFLAGS) all-am
 
 .SUFFIXES:
-$(srcdir)/Makefile.in: @MAINTAINER_MODE_TRUE@ $(srcdir)/Makefile.am  $(am__configure_deps)
+$(srcdir)/Makefile.in: @MAINTAINER_MODE_TRUE@ $(srcdir)/Makefile.am $(top_srcdir)/config/swig.am $(am__configure_deps)
 	@for dep in $?; do \
 	  case '$(am__configure_deps)' in \
 	    *$$dep*) \
@@ -316,129 +365,18 @@ $(srcdir)/PyTrilinos_config.h.in: @MAINTAINER_MODE_TRUE@ $(am__configure_deps)
 
 distclean-hdr:
 	-rm -f PyTrilinos_config.h stamp-h1
+__init__.py: $(top_builddir)/config.status $(srcdir)/__init__.py.in
+	cd $(top_builddir) && $(SHELL) ./config.status $(subdir)/$@
 uninstall-info-am:
-
-# This directory's subdirectories are mostly independent; you can cd
-# into them and run `make' without going through this Makefile.
-# To change the values of `make' variables: instead of editing Makefiles,
-# (1) if the variable is set in `config.status', edit `config.status'
-#     (which will cause the Makefiles to be regenerated when you run `make');
-# (2) otherwise, pass the desired values on the `make' command line.
-$(RECURSIVE_TARGETS):
-	@set fnord $$MAKEFLAGS; amf=$$2; \
-	dot_seen=no; \
-	target=`echo $@ | sed s/-recursive//`; \
-	list='$(SUBDIRS)'; for subdir in $$list; do \
-	  echo "Making $$target in $$subdir"; \
-	  if test "$$subdir" = "."; then \
-	    dot_seen=yes; \
-	    local_target="$$target-am"; \
-	  else \
-	    local_target="$$target"; \
-	  fi; \
-	  (cd $$subdir && $(MAKE) $(AM_MAKEFLAGS) $$local_target) \
-	   || case "$$amf" in *=*) exit 1;; *k*) fail=yes;; *) exit 1;; esac; \
-	done; \
-	if test "$$dot_seen" = "no"; then \
-	  $(MAKE) $(AM_MAKEFLAGS) "$$target-am" || exit 1; \
-	fi; test -z "$$fail"
-
-mostlyclean-recursive clean-recursive distclean-recursive \
-maintainer-clean-recursive:
-	@set fnord $$MAKEFLAGS; amf=$$2; \
-	dot_seen=no; \
-	case "$@" in \
-	  distclean-* | maintainer-clean-*) list='$(DIST_SUBDIRS)' ;; \
-	  *) list='$(SUBDIRS)' ;; \
-	esac; \
-	rev=''; for subdir in $$list; do \
-	  if test "$$subdir" = "."; then :; else \
-	    rev="$$subdir $$rev"; \
-	  fi; \
-	done; \
-	rev="$$rev ."; \
-	target=`echo $@ | sed s/-recursive//`; \
-	for subdir in $$rev; do \
-	  echo "Making $$target in $$subdir"; \
-	  if test "$$subdir" = "."; then \
-	    local_target="$$target-am"; \
-	  else \
-	    local_target="$$target"; \
-	  fi; \
-	  (cd $$subdir && $(MAKE) $(AM_MAKEFLAGS) $$local_target) \
-	   || case "$$amf" in *=*) exit 1;; *k*) fail=yes;; *) exit 1;; esac; \
-	done && test -z "$$fail"
-tags-recursive:
-	list='$(SUBDIRS)'; for subdir in $$list; do \
-	  test "$$subdir" = . || (cd $$subdir && $(MAKE) $(AM_MAKEFLAGS) tags); \
-	done
-ctags-recursive:
-	list='$(SUBDIRS)'; for subdir in $$list; do \
-	  test "$$subdir" = . || (cd $$subdir && $(MAKE) $(AM_MAKEFLAGS) ctags); \
-	done
-
-ID: $(HEADERS) $(SOURCES) $(LISP) $(TAGS_FILES)
-	list='$(SOURCES) $(HEADERS) $(LISP) $(TAGS_FILES)'; \
-	unique=`for i in $$list; do \
-	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
-	  done | \
-	  $(AWK) '    { files[$$0] = 1; } \
-	       END { for (i in files) print i; }'`; \
-	mkid -fID $$unique
 tags: TAGS
+TAGS:
 
-TAGS: tags-recursive $(HEADERS) $(SOURCES) PyTrilinos_config.h.in $(TAGS_DEPENDENCIES) \
-		$(TAGS_FILES) $(LISP)
-	tags=; \
-	here=`pwd`; \
-	if ($(ETAGS) --etags-include --version) >/dev/null 2>&1; then \
-	  include_option=--etags-include; \
-	  empty_fix=.; \
-	else \
-	  include_option=--include; \
-	  empty_fix=; \
-	fi; \
-	list='$(SUBDIRS)'; for subdir in $$list; do \
-	  if test "$$subdir" = .; then :; else \
-	    test ! -f $$subdir/TAGS || \
-	      tags="$$tags $$include_option=$$here/$$subdir/TAGS"; \
-	  fi; \
-	done; \
-	list='$(SOURCES) $(HEADERS) PyTrilinos_config.h.in $(LISP) $(TAGS_FILES)'; \
-	unique=`for i in $$list; do \
-	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
-	  done | \
-	  $(AWK) '    { files[$$0] = 1; } \
-	       END { for (i in files) print i; }'`; \
-	if test -z "$(ETAGS_ARGS)$$tags$$unique"; then :; else \
-	  test -n "$$unique" || unique=$$empty_fix; \
-	  $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
-	    $$tags $$unique; \
-	fi
 ctags: CTAGS
-CTAGS: ctags-recursive $(HEADERS) $(SOURCES) PyTrilinos_config.h.in $(TAGS_DEPENDENCIES) \
-		$(TAGS_FILES) $(LISP)
-	tags=; \
-	here=`pwd`; \
-	list='$(SOURCES) $(HEADERS) PyTrilinos_config.h.in $(LISP) $(TAGS_FILES)'; \
-	unique=`for i in $$list; do \
-	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
-	  done | \
-	  $(AWK) '    { files[$$0] = 1; } \
-	       END { for (i in files) print i; }'`; \
-	test -z "$(CTAGS_ARGS)$$tags$$unique" \
-	  || $(CTAGS) $(CTAGSFLAGS) $(AM_CTAGSFLAGS) $(CTAGS_ARGS) \
-	     $$tags $$unique
+CTAGS:
 
-GTAGS:
-	here=`$(am__cd) $(top_builddir) && pwd` \
-	  && cd $(top_srcdir) \
-	  && gtags -i $(GTAGS_ARGS) $$here
-
-distclean-tags:
-	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags
 
 distdir: $(DISTFILES)
+	$(mkdir_p) $(distdir)/../config
 	@srcdirstrip=`echo "$(srcdir)" | sed 's|.|.|g'`; \
 	topsrcdirstrip=`echo "$(top_srcdir)" | sed 's|.|.|g'`; \
 	list='$(DISTFILES)'; for file in $$list; do \
@@ -465,33 +403,18 @@ distdir: $(DISTFILES)
 	    || exit 1; \
 	  fi; \
 	done
-	list='$(SUBDIRS)'; for subdir in $$list; do \
-	  if test "$$subdir" = .; then :; else \
-	    test -d "$(distdir)/$$subdir" \
-	    || mkdir "$(distdir)/$$subdir" \
-	    || exit 1; \
-	    (cd $$subdir && \
-	      $(MAKE) $(AM_MAKEFLAGS) \
-	        top_distdir="../$(top_distdir)" \
-	        distdir="../$(distdir)/$$subdir" \
-	        distdir) \
-	      || exit 1; \
-	  fi; \
-	done
 check-am: all-am
-check: check-recursive
+check: check-am
 all-am: Makefile PyTrilinos_config.h
-installdirs: installdirs-recursive
-installdirs-am:
-install: install-recursive
-install-exec: install-exec-recursive
-install-data: install-data-recursive
-uninstall: uninstall-recursive
+installdirs:
+install-exec: install-exec-am
+install-data: install-data-am
+uninstall: uninstall-am
 
 install-am: all-am
 	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am
 
-installcheck: installcheck-recursive
+installcheck: installcheck-am
 install-strip:
 	$(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
 	  install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
@@ -500,6 +423,7 @@ install-strip:
 mostlyclean-generic:
 
 clean-generic:
+	-test -z "$(CLEANFILES)" || rm -f $(CLEANFILES)
 
 distclean-generic:
 	-rm -f $(CONFIG_CLEAN_FILES)
@@ -507,22 +431,21 @@ distclean-generic:
 maintainer-clean-generic:
 	@echo "This command is intended for maintainers to use"
 	@echo "it deletes files that may require special tools to rebuild."
-	-test -z "$(MAINTAINERCLEANFILES)" || rm -f $(MAINTAINERCLEANFILES)
-clean: clean-recursive
+clean: clean-am
 
-clean-am: clean-generic mostlyclean-am
+clean-am: clean-generic clean-local mostlyclean-am
 
-distclean: distclean-recursive
+distclean: distclean-am
 	-rm -f Makefile
-distclean-am: clean-am distclean-generic distclean-hdr distclean-tags
+distclean-am: clean-am distclean-generic distclean-hdr
 
-dvi: dvi-recursive
+dvi: dvi-am
 
 dvi-am:
 
-html: html-recursive
+html: html-am
 
-info: info-recursive
+info: info-am
 
 info-am:
 
@@ -530,57 +453,95 @@ install-data-am:
 
 install-exec-am:
 
-install-info: install-info-recursive
+install-info: install-info-am
 
 install-man:
 
 installcheck-am:
 
-maintainer-clean: maintainer-clean-recursive
+maintainer-clean: maintainer-clean-am
 	-rm -f Makefile
 maintainer-clean-am: distclean-am maintainer-clean-generic
 
-mostlyclean: mostlyclean-recursive
+mostlyclean: mostlyclean-am
 
 mostlyclean-am: mostlyclean-generic
 
-pdf: pdf-recursive
+pdf: pdf-am
 
 pdf-am:
 
-ps: ps-recursive
+ps: ps-am
 
 ps-am:
 
 uninstall-am: uninstall-info-am
 
-uninstall-info: uninstall-info-recursive
-
-.PHONY: $(RECURSIVE_TARGETS) CTAGS GTAGS all all-am check check-am \
-	clean clean-generic clean-recursive ctags ctags-recursive \
-	distclean distclean-generic distclean-hdr distclean-recursive \
-	distclean-tags distdir dvi dvi-am html html-am info info-am \
-	install install-am install-data install-data-am install-exec \
-	install-exec-am install-info install-info-am install-man \
-	install-strip installcheck installcheck-am installdirs \
-	installdirs-am maintainer-clean maintainer-clean-generic \
-	maintainer-clean-recursive mostlyclean mostlyclean-generic \
-	mostlyclean-recursive pdf pdf-am ps ps-am tags tags-recursive \
-	uninstall uninstall-am uninstall-info-am
+.PHONY: all all-am check check-am clean clean-generic clean-local \
+	distclean distclean-generic distclean-hdr distdir dvi dvi-am \
+	html html-am info info-am install install-am install-data \
+	install-data-am install-exec install-exec-am install-info \
+	install-info-am install-man install-strip installcheck \
+	installcheck-am installdirs maintainer-clean \
+	maintainer-clean-generic mostlyclean mostlyclean-generic pdf \
+	pdf-am ps ps-am uninstall uninstall-am uninstall-info-am
 
 
-all-recursive: $(TARGET)
+%.py: %_wrap.cxx
+NOX/%.py: NOX/%_wrap.cxx
 
-NOX_Wrappers:
-	cd NOX && make
+@HAVE_SWIG_TRUE@$(DEPDIR):
+@HAVE_SWIG_TRUE@	mkdir -p $@ $@/NOX
 
-# Generate the RawEpetra C++ wrapper and proxy file from the RawEpetra SWIG interface
-RawEpetra_wrap.cxx RawEpetra.py: RawEpetra.i
-	$(SWIG) $(EPETRA_INC) $(SWIG_FLAGS) $<
+@HAVE_SWIG_TRUE@NOX/%_wrap.cxx: $(srcdir)/NOX/%.i $(DEPDIR)
+@HAVE_SWIG_TRUE@	if $(SWIGCOMPILE) -MMD -MF "$(DEPDIR)/NOX/$*.Tpi" -o $@ $<; \
+@HAVE_SWIG_TRUE@	then mv -f "$(DEPDIR)/NOX/$*.Tpi" "$(DEPDIR)/NOX/$*.Pi";    \
+@HAVE_SWIG_TRUE@	else rm -f "$(DEPDIR)/NOX/$*.Tpi"; exit 1; fi
 
-# Generate the EpetraExt C++ wrapper and proxy file from the EpetraExt SWIG interface
-EpetraExt_wrap.cxx EpetraExt.py: EpetraExt.i
-	$(SWIG) $(EPETRA_INC) $(EPETRAEXT_INC) $(SWIG_FLAGS) $<
+@HAVE_SWIG_TRUE@%_wrap.cxx: $(srcdir)/%.i $(DEPDIR)
+@HAVE_SWIG_TRUE@	if $(SWIGCOMPILE) -MMD -MF "$(DEPDIR)/$*.Tpi" -o $@ $<; \
+@HAVE_SWIG_TRUE@	then mv -f "$(DEPDIR)/$*.Tpi" "$(DEPDIR)/$*.Pi"; else rm -f "$(DEPDIR)/$*.Tpi"; exit 1; fi
+
+@HAVE_SWIG_FALSE@%_wrap.cxx: $(srcdir)/%.i 
+@HAVE_SWIG_FALSE@	@echo 'Error swig is not enabled and'
+@HAVE_SWIG_FALSE@	@echo '$@ is out-of-date with respect to $<.'
+@HAVE_SWIG_FALSE@	@echo 'Rerun configure with --with-swig=[path-to-swig].'
+@HAVE_SWIG_FALSE@	@exit 1
+
+swigclean:
+	rm -f $(srcdir)/src/wrap_* $(WRAPPERS) 
+
+# Default make target
+all-am: build
+
+$(tempdir):
+	@echo "Creating directory $@"
+	mkdir -p $@
+
+# File setup.txt is a way to transfer make variables to the setup.py
+# python script
+setup.txt: $(srcdir)/Makefile.am
+	@echo "creating $@"
+	@echo "{"                                   >  $@
+	@echo "  'top_srcdir'  : '$(top_srcdir)',"  >> $@
+	@echo "  'srcdir'      : '$(srcdir)',"      >> $@
+	@echo "  'LDFLAGS'     : '$(LDFLAGS)',"     >> $@
+	@echo "  'LAPACK_LIBS' : '$(LAPACK_LIBS)'," >> $@
+	@echo "  'BLAS_LIBS'   : '$(BLAS_LIBS)',"   >> $@
+	@echo "  'FLIBS'       : '$(FLIBS)',"       >> $@
+	@echo "  'LIBS'        : '$(LIBS)',"        >> $@
+	@echo "  'PYTHON'      : '$(PYTHON)'"       >> $@
+	@echo "}"                                   >> $@
+
+build: $(WRAPPERS) setup.txt $(tempdir)
+	$(PYTHON) $(srcdir)/setup.py build
+
+install: build
+	$(PYTHON) $(srcdir)/setup.py install --prefix=$(PYTHON_PREFIX)
+
+clean-local:
+	$(PYTHON) $(srcdir)/setup.py clean
+	$(RM) -r ../../packages
 # Tell versions [3.59,3.63) of GNU make to not export all variables.
 # Otherwise a system limit (for SysV at least) may be exceeded.
 .NOEXPORT:
